# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffraction_filter_setup.ui'
#
# Created: Mon Mar 18 10:14:00 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1026, 1273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Plain)
        Frame.setLineWidth(8)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1026, 1273))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.instr_name_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instr_name_label.sizePolicy().hasHeightForWidth())
        self.instr_name_label.setSizePolicy(sizePolicy)
        self.instr_name_label.setMinimumSize(QtCore.QSize(160, 30))
        self.instr_name_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instr_name_label.setFont(font)
        self.instr_name_label.setObjectName(_fromUtf8("instr_name_label"))
        self.horizontalLayout_13.addWidget(self.instr_name_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.help_button = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(73, 30))
        self.help_button.setMaximumSize(QtCore.QSize(73, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.help_button.setFont(font)
        self.help_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.help_button.setIconSize(QtCore.QSize(15, 15))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.horizontalLayout_13.addWidget(self.help_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.reduction_options_group = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduction_options_group.sizePolicy().hasHeightForWidth())
        self.reduction_options_group.setSizePolicy(sizePolicy)
        self.reduction_options_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reduction_options_group.setObjectName(_fromUtf8("reduction_options_group"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.reduction_options_group)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.att_scale_factor_label = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.att_scale_factor_label.sizePolicy().hasHeightForWidth())
        self.att_scale_factor_label.setSizePolicy(sizePolicy)
        self.att_scale_factor_label.setMinimumSize(QtCore.QSize(100, 0))
        self.att_scale_factor_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.att_scale_factor_label.setObjectName(_fromUtf8("att_scale_factor_label"))
        self.horizontalLayout_4.addWidget(self.att_scale_factor_label)
        self.title_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.title_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.title_edit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.title_edit.setObjectName(_fromUtf8("title_edit"))
        self.horizontalLayout_4.addWidget(self.title_edit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.monitor_layout = QtGui.QHBoxLayout()
        self.monitor_layout.setObjectName(_fromUtf8("monitor_layout"))
        self.label_3 = QtGui.QLabel(self.reduction_options_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.monitor_layout.addWidget(self.label_3)
        self.starttime_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.starttime_edit.setObjectName(_fromUtf8("starttime_edit"))
        self.monitor_layout.addWidget(self.starttime_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.monitor_layout.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.reduction_options_group)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.monitor_layout.addWidget(self.label_5)
        self.stoptime_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.stoptime_edit.setObjectName(_fromUtf8("stoptime_edit"))
        self.monitor_layout.addWidget(self.stoptime_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.monitor_layout.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.monitor_layout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_14 = QtGui.QLabel(self.reduction_options_group)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.abs_scale_direct_beam_layout = QtGui.QHBoxLayout()
        self.abs_scale_direct_beam_layout.setObjectName(_fromUtf8("abs_scale_direct_beam_layout"))
        self.direct_beam_label = QtGui.QLabel(self.reduction_options_group)
        self.direct_beam_label.setMinimumSize(QtCore.QSize(60, 0))
        self.direct_beam_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.direct_beam_label.setObjectName(_fromUtf8("direct_beam_label"))
        self.abs_scale_direct_beam_layout.addWidget(self.direct_beam_label)
        self.run_number_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.run_number_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.run_number_edit.setObjectName(_fromUtf8("run_number_edit"))
        self.abs_scale_direct_beam_layout.addWidget(self.run_number_edit)
        self.load_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.abs_scale_direct_beam_layout.addWidget(self.load_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_direct_beam_layout.addItem(spacerItem6)
        self.log_name_combo = QtGui.QComboBox(self.reduction_options_group)
        self.log_name_combo.setMinimumSize(QtCore.QSize(160, 0))
        self.log_name_combo.setObjectName(_fromUtf8("log_name_combo"))
        self.abs_scale_direct_beam_layout.addWidget(self.log_name_combo)
        self.plot_log_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_log_button.sizePolicy().hasHeightForWidth())
        self.plot_log_button.setSizePolicy(sizePolicy)
        self.plot_log_button.setObjectName(_fromUtf8("plot_log_button"))
        self.abs_scale_direct_beam_layout.addWidget(self.plot_log_button)
        self.syn_logname_button = QtGui.QPushButton(self.reduction_options_group)
        self.syn_logname_button.setObjectName(_fromUtf8("syn_logname_button"))
        self.abs_scale_direct_beam_layout.addWidget(self.syn_logname_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_direct_beam_layout.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.abs_scale_direct_beam_layout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.info_text_browser = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_text_browser.sizePolicy().hasHeightForWidth())
        self.info_text_browser.setSizePolicy(sizePolicy)
        self.info_text_browser.setMinimumSize(QtCore.QSize(300, 0))
        self.info_text_browser.setBaseSize(QtCore.QSize(0, 0))
        self.info_text_browser.setObjectName(_fromUtf8("info_text_browser"))
        self.horizontalLayout_7.addWidget(self.info_text_browser)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.reduction_options_group)
        self.geometry_options_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometry_options_groupbox.sizePolicy().hasHeightForWidth())
        self.geometry_options_groupbox.setSizePolicy(sizePolicy)
        self.geometry_options_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.geometry_options_groupbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.geometry_options_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.geometry_options_groupbox.setObjectName(_fromUtf8("geometry_options_groupbox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.geometry_options_groupbox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.mask_template_horiz_layout = QtGui.QHBoxLayout()
        self.mask_template_horiz_layout.setSpacing(0)
        self.mask_template_horiz_layout.setObjectName(_fromUtf8("mask_template_horiz_layout"))
        self.timefilter_checkBox = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.timefilter_checkBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.timefilter_checkBox.setWhatsThis(_fromUtf8(""))
        self.timefilter_checkBox.setText(_fromUtf8(""))
        self.timefilter_checkBox.setObjectName(_fromUtf8("timefilter_checkBox"))
        self.mask_template_horiz_layout.addWidget(self.timefilter_checkBox)
        self.experiment_parameter_help = QtGui.QLabel(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experiment_parameter_help.sizePolicy().hasHeightForWidth())
        self.experiment_parameter_help.setSizePolicy(sizePolicy)
        self.experiment_parameter_help.setMinimumSize(QtCore.QSize(150, 0))
        self.experiment_parameter_help.setStyleSheet(_fromUtf8("font: italic 10pt \"Bitstream Charter\";"))
        self.experiment_parameter_help.setObjectName(_fromUtf8("experiment_parameter_help"))
        self.mask_template_horiz_layout.addWidget(self.experiment_parameter_help)
        self.verticalLayout_5.addLayout(self.mask_template_horiz_layout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.timintervallength_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timintervallength_edit.sizePolicy().hasHeightForWidth())
        self.timintervallength_edit.setSizePolicy(sizePolicy)
        self.timintervallength_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.timintervallength_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.timintervallength_edit.setObjectName(_fromUtf8("timintervallength_edit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.timintervallength_edit)
        self.label = QtGui.QLabel(self.geometry_options_groupbox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.geometry_options_groupbox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.timeunit_combo = QtGui.QComboBox(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeunit_combo.sizePolicy().hasHeightForWidth())
        self.timeunit_combo.setSizePolicy(sizePolicy)
        self.timeunit_combo.setMaximumSize(QtCore.QSize(160, 16777215))
        self.timeunit_combo.setObjectName(_fromUtf8("timeunit_combo"))
        self.timeunit_combo.addItem(_fromUtf8(""))
        self.timeunit_combo.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.timeunit_combo)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_4.addWidget(self.geometry_options_groupbox)
        self.mask_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_groupbox.sizePolicy().hasHeightForWidth())
        self.mask_groupbox.setSizePolicy(sizePolicy)
        self.mask_groupbox.setObjectName(_fromUtf8("mask_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mask_groupbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.logvaluefilter_checkBox = QtGui.QCheckBox(self.mask_groupbox)
        self.logvaluefilter_checkBox.setMaximumSize(QtCore.QSize(20, 16777215))
        self.logvaluefilter_checkBox.setText(_fromUtf8(""))
        self.logvaluefilter_checkBox.setObjectName(_fromUtf8("logvaluefilter_checkBox"))
        self.horizontalLayout.addWidget(self.logvaluefilter_checkBox)
        self.mask_help_label = QtGui.QLabel(self.mask_groupbox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setItalic(True)
        self.mask_help_label.setFont(font)
        self.mask_help_label.setObjectName(_fromUtf8("mask_help_label"))
        self.horizontalLayout.addWidget(self.mask_help_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(self.mask_groupbox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.mask_groupbox)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.logname_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.logname_edit.setObjectName(_fromUtf8("logname_edit"))
        self.gridLayout.addWidget(self.logname_edit, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.mask_groupbox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.mask_groupbox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.logminvalue_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.logminvalue_edit.setObjectName(_fromUtf8("logminvalue_edit"))
        self.gridLayout.addWidget(self.logminvalue_edit, 0, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.mask_groupbox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.mask_groupbox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.logtol_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.logtol_edit.setObjectName(_fromUtf8("logtol_edit"))
        self.gridLayout.addWidget(self.logtol_edit, 3, 5, 1, 1)
        self.logmaxvalue_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.logmaxvalue_edit.setObjectName(_fromUtf8("logmaxvalue_edit"))
        self.gridLayout.addWidget(self.logmaxvalue_edit, 2, 5, 1, 1)
        self.valuechange_combo = QtGui.QComboBox(self.mask_groupbox)
        self.valuechange_combo.setMinimumSize(QtCore.QSize(160, 0))
        self.valuechange_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.valuechange_combo.setObjectName(_fromUtf8("valuechange_combo"))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.valuechange_combo, 2, 7, 1, 1)
        self.logintervalvalue_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.logintervalvalue_edit.setObjectName(_fromUtf8("logintervalvalue_edit"))
        self.gridLayout.addWidget(self.logintervalvalue_edit, 3, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.mask_groupbox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.timetol_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.timetol_edit.setObjectName(_fromUtf8("timetol_edit"))
        self.gridLayout.addWidget(self.timetol_edit, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.mask_groupbox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.mask_groupbox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 4, 4, 1, 1)
        self.logbound_combo = QtGui.QComboBox(self.mask_groupbox)
        self.logbound_combo.setObjectName(_fromUtf8("logbound_combo"))
        self.logbound_combo.addItem(_fromUtf8(""))
        self.logbound_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.logbound_combo, 4, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.mask_groupbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_name_label.setText(QtGui.QApplication.translate("Frame", "Event Filter Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.help_button.setText(QtGui.QApplication.translate("Frame", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.reduction_options_group.setTitle(QtGui.QApplication.translate("Frame", "General and Setup Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.att_scale_factor_label.setText(QtGui.QApplication.translate("Frame", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.title_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.title_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Filter Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.starttime_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.starttime_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Filter Stop Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Filter Generator Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_label.setText(QtGui.QApplication.translate("Frame", "Run Number", None, QtGui.QApplication.UnicodeUTF8))
        self.run_number_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.run_number_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.load_button.setText(QtGui.QApplication.translate("Frame", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_log_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.syn_logname_button.setText(QtGui.QApplication.translate("Frame", "Use", None, QtGui.QApplication.UnicodeUTF8))
        self.info_text_browser.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_text_browser.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry_options_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Filter By Time", None, QtGui.QApplication.UnicodeUTF8))
        self.timefilter_checkBox.setToolTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.timefilter_checkBox.setStatusTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.experiment_parameter_help.setText(QtGui.QApplication.translate("Frame", "Characterization file can be overriden or disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.timintervallength_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.timintervallength_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Duration of Time Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Time Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.timeunit_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.timeunit_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Nanoseconds", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Filter By Log Value", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_help_label.setText(QtGui.QApplication.translate("Frame", "Choose a file to set your mask. Note that only the mask information, not the data, will be used in the reduction.\n"
"The data is only used to help you setting the mask.\n"
"The mask information is saved separately so that your data file will NOT be modified.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Log Value Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Value Change Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Log Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Maximum Log Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Log Step Size", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Increase", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(2, QtGui.QApplication.translate("Frame", "Decrease", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Minimum Log Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Time Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "Log Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.logbound_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.logbound_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Left", None, QtGui.QApplication.UnicodeUTF8))

