# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffraction_run_setup.ui'
#
# Created: Fri Mar 15 23:10:09 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1026, 1273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Plain)
        Frame.setLineWidth(8)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1026, 1273))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.instr_name_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instr_name_label.sizePolicy().hasHeightForWidth())
        self.instr_name_label.setSizePolicy(sizePolicy)
        self.instr_name_label.setMinimumSize(QtCore.QSize(160, 30))
        self.instr_name_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instr_name_label.setFont(font)
        self.instr_name_label.setObjectName(_fromUtf8("instr_name_label"))
        self.horizontalLayout_13.addWidget(self.instr_name_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.help_button = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(73, 30))
        self.help_button.setMaximumSize(QtCore.QSize(73, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.help_button.setFont(font)
        self.help_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.help_button.setIconSize(QtCore.QSize(15, 15))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.horizontalLayout_13.addWidget(self.help_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.reduction_options_group = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduction_options_group.sizePolicy().hasHeightForWidth())
        self.reduction_options_group.setSizePolicy(sizePolicy)
        self.reduction_options_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reduction_options_group.setObjectName(_fromUtf8("reduction_options_group"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.reduction_options_group)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.att_scale_factor_label = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.att_scale_factor_label.sizePolicy().hasHeightForWidth())
        self.att_scale_factor_label.setSizePolicy(sizePolicy)
        self.att_scale_factor_label.setMinimumSize(QtCore.QSize(100, 0))
        self.att_scale_factor_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.att_scale_factor_label.setObjectName(_fromUtf8("att_scale_factor_label"))
        self.horizontalLayout_4.addWidget(self.att_scale_factor_label)
        self.runnumbers_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.runnumbers_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.runnumbers_edit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.runnumbers_edit.setObjectName(_fromUtf8("runnumbers_edit"))
        self.horizontalLayout_4.addWidget(self.runnumbers_edit)
        self.sum_checkbox = QtGui.QCheckBox(self.reduction_options_group)
        self.sum_checkbox.setMinimumSize(QtCore.QSize(80, 0))
        self.sum_checkbox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.sum_checkbox.setObjectName(_fromUtf8("sum_checkbox"))
        self.horizontalLayout_4.addWidget(self.sum_checkbox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.monitor_layout = QtGui.QHBoxLayout()
        self.monitor_layout.setObjectName(_fromUtf8("monitor_layout"))
        self.label_3 = QtGui.QLabel(self.reduction_options_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.monitor_layout.addWidget(self.label_3)
        self.calfile_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.calfile_edit.setObjectName(_fromUtf8("calfile_edit"))
        self.monitor_layout.addWidget(self.calfile_edit)
        self.calfile_browse = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calfile_browse.sizePolicy().hasHeightForWidth())
        self.calfile_browse.setSizePolicy(sizePolicy)
        self.calfile_browse.setObjectName(_fromUtf8("calfile_browse"))
        self.monitor_layout.addWidget(self.calfile_browse)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.monitor_layout.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.monitor_layout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.reduction_options_group)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.extension_combo = QtGui.QComboBox(self.reduction_options_group)
        self.extension_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.extension_combo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.extension_combo.setObjectName(_fromUtf8("extension_combo"))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.extension_combo)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.preserveevents_checkbox = QtGui.QCheckBox(self.reduction_options_group)
        self.preserveevents_checkbox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.preserveevents_checkbox.setObjectName(_fromUtf8("preserveevents_checkbox"))
        self.horizontalLayout_6.addWidget(self.preserveevents_checkbox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.abs_scale_direct_beam_layout = QtGui.QHBoxLayout()
        self.abs_scale_direct_beam_layout.setObjectName(_fromUtf8("abs_scale_direct_beam_layout"))
        self.direct_beam_label = QtGui.QLabel(self.reduction_options_group)
        self.direct_beam_label.setMinimumSize(QtCore.QSize(150, 0))
        self.direct_beam_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.direct_beam_label.setObjectName(_fromUtf8("direct_beam_label"))
        self.abs_scale_direct_beam_layout.addWidget(self.direct_beam_label)
        self.charfile_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.charfile_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.charfile_edit.setObjectName(_fromUtf8("charfile_edit"))
        self.abs_scale_direct_beam_layout.addWidget(self.charfile_edit)
        self.charfile_browse = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charfile_browse.sizePolicy().hasHeightForWidth())
        self.charfile_browse.setSizePolicy(sizePolicy)
        self.charfile_browse.setObjectName(_fromUtf8("charfile_browse"))
        self.abs_scale_direct_beam_layout.addWidget(self.charfile_browse)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_direct_beam_layout.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.abs_scale_direct_beam_layout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtGui.QLabel(self.reduction_options_group)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        self.outputdir_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputdir_edit.sizePolicy().hasHeightForWidth())
        self.outputdir_edit.setSizePolicy(sizePolicy)
        self.outputdir_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.outputdir_edit.setBaseSize(QtCore.QSize(0, 0))
        self.outputdir_edit.setObjectName(_fromUtf8("outputdir_edit"))
        self.horizontalLayout_7.addWidget(self.outputdir_edit)
        self.outputdir_browse = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputdir_browse.sizePolicy().hasHeightForWidth())
        self.outputdir_browse.setSizePolicy(sizePolicy)
        self.outputdir_browse.setObjectName(_fromUtf8("outputdir_browse"))
        self.horizontalLayout_7.addWidget(self.outputdir_browse)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.reduction_options_group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.saveas_combo = QtGui.QComboBox(self.reduction_options_group)
        self.saveas_combo.setMinimumSize(QtCore.QSize(120, 0))
        self.saveas_combo.setObjectName(_fromUtf8("saveas_combo"))
        self.saveas_combo.addItem(_fromUtf8(""))
        self.saveas_combo.addItem(_fromUtf8(""))
        self.saveas_combo.addItem(_fromUtf8(""))
        self.saveas_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.saveas_combo)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.label_6 = QtGui.QLabel(self.reduction_options_group)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.unit_combo = QtGui.QComboBox(self.reduction_options_group)
        self.unit_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.unit_combo.setObjectName(_fromUtf8("unit_combo"))
        self.unit_combo.addItem(_fromUtf8(""))
        self.unit_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.unit_combo)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.reduction_options_group)
        self.geometry_options_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometry_options_groupbox.sizePolicy().hasHeightForWidth())
        self.geometry_options_groupbox.setSizePolicy(sizePolicy)
        self.geometry_options_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.geometry_options_groupbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.geometry_options_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.geometry_options_groupbox.setObjectName(_fromUtf8("geometry_options_groupbox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.geometry_options_groupbox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.mask_template_horiz_layout = QtGui.QHBoxLayout()
        self.mask_template_horiz_layout.setSpacing(0)
        self.mask_template_horiz_layout.setObjectName(_fromUtf8("mask_template_horiz_layout"))
        self.experiment_parameter_help = QtGui.QLabel(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experiment_parameter_help.sizePolicy().hasHeightForWidth())
        self.experiment_parameter_help.setSizePolicy(sizePolicy)
        self.experiment_parameter_help.setMinimumSize(QtCore.QSize(150, 0))
        self.experiment_parameter_help.setStyleSheet(_fromUtf8("font: italic 10pt \"Bitstream Charter\";"))
        self.experiment_parameter_help.setObjectName(_fromUtf8("experiment_parameter_help"))
        self.mask_template_horiz_layout.addWidget(self.experiment_parameter_help)
        self.verticalLayout_5.addLayout(self.mask_template_horiz_layout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.disablebkgdcorr_chkbox = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.disablebkgdcorr_chkbox.setWhatsThis(_fromUtf8(""))
        self.disablebkgdcorr_chkbox.setObjectName(_fromUtf8("disablebkgdcorr_chkbox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.disablebkgdcorr_chkbox)
        self.emptyrun_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.emptyrun_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.emptyrun_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.emptyrun_edit.setObjectName(_fromUtf8("emptyrun_edit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.emptyrun_edit)
        self.disablevancorr_chkbox = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.disablevancorr_chkbox.setObjectName(_fromUtf8("disablevancorr_chkbox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.disablevancorr_chkbox)
        self.vanrun_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vanrun_edit.sizePolicy().hasHeightForWidth())
        self.vanrun_edit.setSizePolicy(sizePolicy)
        self.vanrun_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.vanrun_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.vanrun_edit.setObjectName(_fromUtf8("vanrun_edit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.vanrun_edit)
        self.disablevanbkgdcorr_chkbox = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.disablevanbkgdcorr_chkbox.setObjectName(_fromUtf8("disablevanbkgdcorr_chkbox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.disablevanbkgdcorr_chkbox)
        self.vanbkgdrun_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.vanbkgdrun_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.vanbkgdrun_edit.setObjectName(_fromUtf8("vanbkgdrun_edit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.vanbkgdrun_edit)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_4.addWidget(self.geometry_options_groupbox)
        self.mask_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_groupbox.sizePolicy().hasHeightForWidth())
        self.mask_groupbox.setSizePolicy(sizePolicy)
        self.mask_groupbox.setObjectName(_fromUtf8("mask_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mask_groupbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mask_help_label = QtGui.QLabel(self.mask_groupbox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setItalic(True)
        self.mask_help_label.setFont(font)
        self.mask_help_label.setObjectName(_fromUtf8("mask_help_label"))
        self.verticalLayout_2.addWidget(self.mask_help_label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.mask_groupbox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 5, 1, 1)
        self.resamplex_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.resamplex_edit.setObjectName(_fromUtf8("resamplex_edit"))
        self.gridLayout.addWidget(self.resamplex_edit, 2, 1, 1, 1)
        self.bintype_combo = QtGui.QComboBox(self.mask_groupbox)
        self.bintype_combo.setMinimumSize(QtCore.QSize(160, 0))
        self.bintype_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bintype_combo.setObjectName(_fromUtf8("bintype_combo"))
        self.bintype_combo.addItem(_fromUtf8(""))
        self.bintype_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.bintype_combo, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.mask_groupbox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.usebin_button = QtGui.QRadioButton(self.mask_groupbox)
        self.usebin_button.setObjectName(_fromUtf8("usebin_button"))
        self.gridLayout.addWidget(self.usebin_button, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.mask_groupbox)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.binind_checkbox = QtGui.QCheckBox(self.mask_groupbox)
        self.binind_checkbox.setObjectName(_fromUtf8("binind_checkbox"))
        self.gridLayout.addWidget(self.binind_checkbox, 0, 3, 1, 1)
        self.resamplex_button = QtGui.QRadioButton(self.mask_groupbox)
        self.resamplex_button.setObjectName(_fromUtf8("resamplex_button"))
        self.gridLayout.addWidget(self.resamplex_button, 2, 0, 1, 1)
        self.tofmax_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.tofmax_edit.setObjectName(_fromUtf8("tofmax_edit"))
        self.gridLayout.addWidget(self.tofmax_edit, 2, 6, 1, 1)
        self.binning_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.binning_edit.setObjectName(_fromUtf8("binning_edit"))
        self.gridLayout.addWidget(self.binning_edit, 0, 1, 1, 1)
        self.tofmin_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.tofmin_edit.setObjectName(_fromUtf8("tofmin_edit"))
        self.gridLayout.addWidget(self.tofmin_edit, 0, 6, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 2, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 2, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.mask_groupbox)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_name_label.setText(QtGui.QApplication.translate("Frame", "SNS Powder Reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.help_button.setText(QtGui.QApplication.translate("Frame", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.reduction_options_group.setTitle(QtGui.QApplication.translate("Frame", "Reduction Options", None, QtGui.QApplication.UnicodeUTF8))
        self.att_scale_factor_label.setText(QtGui.QApplication.translate("Frame", "Run Numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.runnumbers_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.runnumbers_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.sum_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to normalize to the beam monitor data", None, QtGui.QApplication.UnicodeUTF8))
        self.sum_checkbox.setStatusTip(QtGui.QApplication.translate("Frame", "Select to normalize to the beam monitor data", None, QtGui.QApplication.UnicodeUTF8))
        self.sum_checkbox.setText(QtGui.QApplication.translate("Frame", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Calibration File", None, QtGui.QApplication.UnicodeUTF8))
        self.calfile_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.calfile_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.calfile_browse.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "File Extension", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(0, QtGui.QApplication.translate("Frame", "_event.nxs", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(1, QtGui.QApplication.translate("Frame", "_histo.nxs", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(2, QtGui.QApplication.translate("Frame", "_runinfo.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setStatusTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setText(QtGui.QApplication.translate("Frame", "Preserve Events", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_label.setText(QtGui.QApplication.translate("Frame", "Characterizaton File", None, QtGui.QApplication.UnicodeUTF8))
        self.charfile_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.charfile_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.charfile_browse.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.outputdir_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputdir_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputdir_browse.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.saveas_combo.setItemText(0, QtGui.QApplication.translate("Frame", "gsas", None, QtGui.QApplication.UnicodeUTF8))
        self.saveas_combo.setItemText(1, QtGui.QApplication.translate("Frame", "fullprof", None, QtGui.QApplication.UnicodeUTF8))
        self.saveas_combo.setItemText(2, QtGui.QApplication.translate("Frame", "gsas and fullprof", None, QtGui.QApplication.UnicodeUTF8))
        self.saveas_combo.setItemText(3, QtGui.QApplication.translate("Frame", "gsas and fullprof and pdfgetn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Final Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.unit_combo.setItemText(0, QtGui.QApplication.translate("Frame", "dSpacing", None, QtGui.QApplication.UnicodeUTF8))
        self.unit_combo.setItemText(1, QtGui.QApplication.translate("Frame", "MomentumTransfer", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry_options_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Overriding CharacterizationFile", None, QtGui.QApplication.UnicodeUTF8))
        self.experiment_parameter_help.setText(QtGui.QApplication.translate("Frame", "blablabla.\n"
"blablabla.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablebkgdcorr_chkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablebkgdcorr_chkbox.setStatusTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablebkgdcorr_chkbox.setText(QtGui.QApplication.translate("Frame", "Disable Empty Run Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.emptyrun_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.emptyrun_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablevancorr_chkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to force the sample-detector distance.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablevancorr_chkbox.setStatusTip(QtGui.QApplication.translate("Frame", "Select to force the sample-detector distance.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablevancorr_chkbox.setText(QtGui.QApplication.translate("Frame", "Disable Vanadium Run Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.vanrun_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.vanrun_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.disablevanbkgdcorr_chkbox.setText(QtGui.QApplication.translate("Frame", "Disable Vanariumd Background Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_help_label.setText(QtGui.QApplication.translate("Frame", "Choose a file to set your mask. Note that only the mask information, not the data, will be used in the reduction.\n"
"The data is only used to help you setting the mask.\n"
"The mask information is saved separately so that your data file will NOT be modified.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "TOF Max", None, QtGui.QApplication.UnicodeUTF8))
        self.bintype_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Logarithmic Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.bintype_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Linear Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "TOF Min", None, QtGui.QApplication.UnicodeUTF8))
        self.usebin_button.setText(QtGui.QApplication.translate("Frame", "Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.binind_checkbox.setText(QtGui.QApplication.translate("Frame", "Bin In d-spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.resamplex_button.setText(QtGui.QApplication.translate("Frame", "ResampleX", None, QtGui.QApplication.UnicodeUTF8))

