# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffraction_adv_setup.ui'
#
# Created: Tue Dec  9 11:04:59 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1026, 1273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Plain)
        Frame.setLineWidth(8)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1026, 1273))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.instr_name_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instr_name_label.sizePolicy().hasHeightForWidth())
        self.instr_name_label.setSizePolicy(sizePolicy)
        self.instr_name_label.setMinimumSize(QtCore.QSize(300, 30))
        self.instr_name_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instr_name_label.setFont(font)
        self.instr_name_label.setObjectName(_fromUtf8("instr_name_label"))
        self.horizontalLayout_13.addWidget(self.instr_name_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.help_button = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(73, 30))
        self.help_button.setMaximumSize(QtCore.QSize(73, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.help_button.setFont(font)
        self.help_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.help_button.setIconSize(QtCore.QSize(15, 15))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.horizontalLayout_13.addWidget(self.help_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.advanced_options_group = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_options_group.sizePolicy().hasHeightForWidth())
        self.advanced_options_group.setSizePolicy(sizePolicy)
        self.advanced_options_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.advanced_options_group.setObjectName(_fromUtf8("advanced_options_group"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.advanced_options_group)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.file_extension_label = QtGui.QLabel(self.advanced_options_group)
        self.file_extension_label.setMinimumSize(QtCore.QSize(160, 0))
        self.file_extension_label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.file_extension_label.setObjectName(_fromUtf8("file_extension_label"))
        self.gridLayout_2.addWidget(self.file_extension_label, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.advanced_options_group)
        self.label_6.setMinimumSize(QtCore.QSize(240, 0))
        self.label_6.setMaximumSize(QtCore.QSize(240, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 3, 1, 1)
        self.removepromptwidth_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removepromptwidth_edit.sizePolicy().hasHeightForWidth())
        self.removepromptwidth_edit.setSizePolicy(sizePolicy)
        self.removepromptwidth_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.removepromptwidth_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.removepromptwidth_edit.setObjectName(_fromUtf8("removepromptwidth_edit"))
        self.gridLayout_2.addWidget(self.removepromptwidth_edit, 2, 4, 1, 1)
        self.extension_combo = QtGui.QComboBox(self.advanced_options_group)
        self.extension_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.extension_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.extension_combo.setObjectName(_fromUtf8("extension_combo"))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.extension_combo, 0, 4, 1, 1)
        self.cropwavelengthmin_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropwavelengthmin_edit.sizePolicy().hasHeightForWidth())
        self.cropwavelengthmin_edit.setSizePolicy(sizePolicy)
        self.cropwavelengthmin_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.cropwavelengthmin_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cropwavelengthmin_edit.setObjectName(_fromUtf8("cropwavelengthmin_edit"))
        self.gridLayout_2.addWidget(self.cropwavelengthmin_edit, 1, 4, 1, 1)
        self.unwrap_label = QtGui.QLabel(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unwrap_label.sizePolicy().hasHeightForWidth())
        self.unwrap_label.setSizePolicy(sizePolicy)
        self.unwrap_label.setObjectName(_fromUtf8("unwrap_label"))
        self.gridLayout_2.addWidget(self.unwrap_label, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.pushdatapos_combo = QtGui.QComboBox(self.advanced_options_group)
        self.pushdatapos_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.pushdatapos_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushdatapos_combo.setObjectName(_fromUtf8("pushdatapos_combo"))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pushdatapos_combo, 3, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.advanced_options_group)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 5, 1, 1)
        self.label = QtGui.QLabel(self.advanced_options_group)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.lowres_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowres_edit.sizePolicy().hasHeightForWidth())
        self.lowres_edit.setSizePolicy(sizePolicy)
        self.lowres_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.lowres_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lowres_edit.setObjectName(_fromUtf8("lowres_edit"))
        self.gridLayout_2.addWidget(self.lowres_edit, 1, 1, 1, 1)
        self.pushdatapostive_labe = QtGui.QLabel(self.advanced_options_group)
        self.pushdatapostive_labe.setMinimumSize(QtCore.QSize(160, 0))
        self.pushdatapostive_labe.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushdatapostive_labe.setObjectName(_fromUtf8("pushdatapostive_labe"))
        self.gridLayout_2.addWidget(self.pushdatapostive_labe, 3, 3, 1, 1)
        self.maxchunksize_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxchunksize_edit.sizePolicy().hasHeightForWidth())
        self.maxchunksize_edit.setSizePolicy(sizePolicy)
        self.maxchunksize_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.maxchunksize_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.maxchunksize_edit.setBaseSize(QtCore.QSize(0, 0))
        self.maxchunksize_edit.setStatusTip(_fromUtf8(""))
        self.maxchunksize_edit.setObjectName(_fromUtf8("maxchunksize_edit"))
        self.gridLayout_2.addWidget(self.maxchunksize_edit, 3, 1, 1, 1)
        self.outputfileprefix_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputfileprefix_edit.sizePolicy().hasHeightForWidth())
        self.outputfileprefix_edit.setSizePolicy(sizePolicy)
        self.outputfileprefix_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.outputfileprefix_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.outputfileprefix_edit.setObjectName(_fromUtf8("outputfileprefix_edit"))
        self.gridLayout_2.addWidget(self.outputfileprefix_edit, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.advanced_options_group)
        self.label_10.setMinimumSize(QtCore.QSize(200, 0))
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 1)
        self.low_resolution_label = QtGui.QLabel(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_resolution_label.sizePolicy().hasHeightForWidth())
        self.low_resolution_label.setSizePolicy(sizePolicy)
        self.low_resolution_label.setObjectName(_fromUtf8("low_resolution_label"))
        self.gridLayout_2.addWidget(self.low_resolution_label, 1, 0, 1, 1)
        self.unwrap_edit = QtGui.QLineEdit(self.advanced_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unwrap_edit.sizePolicy().hasHeightForWidth())
        self.unwrap_edit.setSizePolicy(sizePolicy)
        self.unwrap_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.unwrap_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.unwrap_edit.setObjectName(_fromUtf8("unwrap_edit"))
        self.gridLayout_2.addWidget(self.unwrap_edit, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.advanced_options_group)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.scaledata_edit = QtGui.QLineEdit(self.advanced_options_group)
        self.scaledata_edit.setObjectName(_fromUtf8("scaledata_edit"))
        self.gridLayout_2.addWidget(self.scaledata_edit, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.advanced_options_group)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 3, 1, 1)
        self.filterbadpulses_edit = QtGui.QLineEdit(self.advanced_options_group)
        self.filterbadpulses_edit.setObjectName(_fromUtf8("filterbadpulses_edit"))
        self.gridLayout_2.addWidget(self.filterbadpulses_edit, 4, 4, 1, 1)
        self.bkgdsmoothpar_edit = QtGui.QLineEdit(self.advanced_options_group)
        self.bkgdsmoothpar_edit.setObjectName(_fromUtf8("bkgdsmoothpar_edit"))
        self.gridLayout_2.addWidget(self.bkgdsmoothpar_edit, 5, 1, 1, 1)
        self.label_bkgdsmooth = QtGui.QLabel(self.advanced_options_group)
        self.label_bkgdsmooth.setObjectName(_fromUtf8("label_bkgdsmooth"))
        self.gridLayout_2.addWidget(self.label_bkgdsmooth, 5, 0, 1, 1)
        self.preserveevents_checkbox = QtGui.QCheckBox(self.advanced_options_group)
        self.preserveevents_checkbox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.preserveevents_checkbox.setObjectName(_fromUtf8("preserveevents_checkbox"))
        self.gridLayout_2.addWidget(self.preserveevents_checkbox, 5, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.advanced_options_group)
        self.vanadium_correction_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vanadium_correction_groupbox.sizePolicy().hasHeightForWidth())
        self.vanadium_correction_groupbox.setSizePolicy(sizePolicy)
        self.vanadium_correction_groupbox.setObjectName(_fromUtf8("vanadium_correction_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.vanadium_correction_groupbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mask_help_label = QtGui.QLabel(self.vanadium_correction_groupbox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setItalic(True)
        self.mask_help_label.setFont(font)
        self.mask_help_label.setObjectName(_fromUtf8("mask_help_label"))
        self.horizontalLayout_3.addWidget(self.mask_help_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.stripvanpeaks_chkbox = QtGui.QCheckBox(self.vanadium_correction_groupbox)
        self.stripvanpeaks_chkbox.setObjectName(_fromUtf8("stripvanpeaks_chkbox"))
        self.horizontalLayout.addWidget(self.stripvanpeaks_chkbox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vansmoothpar_edit = QtGui.QLineEdit(self.vanadium_correction_groupbox)
        self.vansmoothpar_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.vansmoothpar_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vansmoothpar_edit.setObjectName(_fromUtf8("vansmoothpar_edit"))
        self.gridLayout.addWidget(self.vansmoothpar_edit, 1, 5, 1, 1)
        self.vanpeaktol_edit = QtGui.QLineEdit(self.vanadium_correction_groupbox)
        self.vanpeaktol_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.vanpeaktol_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vanpeaktol_edit.setObjectName(_fromUtf8("vanpeaktol_edit"))
        self.gridLayout.addWidget(self.vanpeaktol_edit, 2, 2, 1, 1)
        self.vanpeakfwhm_edit = QtGui.QLineEdit(self.vanadium_correction_groupbox)
        self.vanpeakfwhm_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.vanpeakfwhm_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vanpeakfwhm_edit.setObjectName(_fromUtf8("vanpeakfwhm_edit"))
        self.gridLayout.addWidget(self.vanpeakfwhm_edit, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.vanadium_correction_groupbox)
        self.label_11.setMinimumSize(QtCore.QSize(200, 0))
        self.label_11.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.vanadium_correction_groupbox)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.vanadium_correction_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(240)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(240, 0))
        self.label_8.setMaximumSize(QtCore.QSize(240, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.vanadium_correction_groupbox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        Frame.setToolTip(_translate("Frame", "Click to browse.", None))
        self.instr_name_label.setText(_translate("Frame", "Advanced Setup of SNS Powder Reduction", None))
        self.help_button.setToolTip(_translate("Frame", "<html><head/><body><p>Advanced setup is for professional users. </p></body></html>", None))
        self.help_button.setText(_translate("Frame", "Help", None))
        self.advanced_options_group.setTitle(_translate("Frame", "Advanced Setup", None))
        self.file_extension_label.setToolTip(_translate("Frame", "<html><head/><body><p>File extension of the run file to load. </p></body></html>", None))
        self.file_extension_label.setText(_translate("Frame", "File Extension", None))
        self.label_6.setText(_translate("Frame", "Minumum Cropped Wavelength", None))
        self.removepromptwidth_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter value for width of events (in microseconds) near the prompt pulse to remove</p></body></html>", None))
        self.extension_combo.setToolTip(_translate("Frame", "<html><head/><body><p>Select a type of file extension to load run with. </p></body></html>", None))
        self.extension_combo.setItemText(0, _translate("Frame", "_event.nxs", None))
        self.extension_combo.setItemText(1, _translate("Frame", "_histo.nxs", None))
        self.extension_combo.setItemText(2, _translate("Frame", "_runinfo.xml", None))
        self.unwrap_label.setToolTip(_translate("Frame", "<html><head/><body><p>Reference total flight path for frame unwrapping.</p></body></html>", None))
        self.unwrap_label.setText(_translate("Frame", "Unwrap Ref", None))
        self.pushdatapos_combo.setToolTip(_translate("Frame", "<html><head/><body><p>Choose a method/algorithm to process negative intensity data. </p></body></html>", None))
        self.pushdatapos_combo.setItemText(0, _translate("Frame", "None", None))
        self.pushdatapos_combo.setItemText(1, _translate("Frame", "ResetToZero", None))
        self.pushdatapos_combo.setItemText(2, _translate("Frame", "AddMinimum", None))
        self.label_2.setText(_translate("Frame", "Output File Prefix", None))
        self.label.setToolTip(_translate("Frame", "<html><head/><body><p>Specify maximum Gbytes of file to read in one chunk. Default is whole file. </p></body></html>", None))
        self.label.setText(_translate("Frame", "Maximum Chunk Size", None))
        self.lowres_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter value for reference DIFC for resolution removal.</p></body></html>", None))
        self.pushdatapostive_labe.setToolTip(_translate("Frame", "<html><head/><body><p>Method/algorithm to process data if negative intensity in corrected diffraction data exists. </p></body></html>", None))
        self.pushdatapostive_labe.setText(_translate("Frame", "Push Data Positive", None))
        self.maxchunksize_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter maximum Gbytes of file to read in one chunk. </p></body></html>", None))
        self.label_10.setToolTip(_translate("Frame", "<html><head/><body><p>Width of events (in microseconds) near the prompt pulse to remove. 0 disables. </p></body></html>", None))
        self.label_10.setText(_translate("Frame", "Remove Prompt Pulse Width", None))
        self.low_resolution_label.setToolTip(_translate("Frame", "<html><head/><body><p>Reference DIFC for resolution removal. Zero skips the correction.</p></body></html>", None))
        self.low_resolution_label.setText(_translate("Frame", "Low Resolution Ref", None))
        self.unwrap_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter value for reference total flight path for frame unwrapping. Zero skips the correction. </p></body></html>", None))
        self.label_3.setText(_translate("Frame", "Scale Data", None))
        self.scaledata_edit.setToolTip(_translate("Frame", "Constant to multiply the data by before writting out", None))
        self.label_4.setText(_translate("Frame", "FilterBadPulses", None))
        self.filterbadpulses_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Check to filter out events measured while proton charge is more than 5% below average </p></body></html>", None))
        self.bkgdsmoothpar_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Parameters to smooth background (can run) by FFT smooth algorithm.</p><p>Enter 2 integers.  The suggested values are &quot;20, 2&quot;. </p></body></html>", None))
        self.label_bkgdsmooth.setToolTip(_translate("Frame", "<html><head/><body><p>Parameters to smooth background (can run) by FFT smooth algorithm.</p></body></html>", None))
        self.label_bkgdsmooth.setText(_translate("Frame", "Background Smooth Parameters", None))
        self.preserveevents_checkbox.setToolTip(_translate("Frame", "<html><head/><body><p>Check to preserve events.  Uncheck to change from events to histograms.</p></body></html>", None))
        self.preserveevents_checkbox.setStatusTip(_translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None))
        self.preserveevents_checkbox.setText(_translate("Frame", "Preserve Events", None))
        self.vanadium_correction_groupbox.setTitle(_translate("Frame", "Strip Vanadium Peaks", None))
        self.mask_help_label.setText(_translate("Frame", "The following input parameters are used to control the algorithm to strip vanadium peaks.\n"
"", None))
        self.stripvanpeaks_chkbox.setToolTip(_translate("Frame", "<html><head/><body><p>Check to subtract fitted vanadium peaks from the known positions. </p></body></html>", None))
        self.stripvanpeaks_chkbox.setText(_translate("Frame", "Strip Vanadium Peaks", None))
        self.vansmoothpar_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter 2 values for FFT smooth on reduced vanadium diffraction data. </p></body></html>", None))
        self.vanpeaktol_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter a value for vanadium peak tolerance. </p></body></html>", None))
        self.vanpeakfwhm_edit.setToolTip(_translate("Frame", "<html><head/><body><p>Enter the estimated vanadium peak FWHM. </p></body></html>", None))
        self.label_11.setToolTip(_translate("Frame", "<html><head/><body><p>Estimated vanadium peak\'s FWHM.  Default is 7 (data points). </p></body></html>", None))
        self.label_11.setText(_translate("Frame", "Peak FWHM", None))
        self.label_12.setToolTip(_translate("Frame", "<html><head/><body><p>How far from the ideal position a vanadium peak can be during StripVanadiumPeaks. Default=0.05, negative turns off </p></body></html>", None))
        self.label_12.setText(_translate("Frame", "Peak Tolerance", None))
        self.label_8.setToolTip(_translate("Frame", "<html><head/><body><p>Smooth parameter for vanadium diffraction pattern.  Default=20,2. </p></body></html>", None))
        self.label_8.setText(_translate("Frame", "Peak Smooth Parameters", None))

