# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffraction_adv_setup.ui'
#
# Created: Mon Mar 18 18:51:29 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1026, 1273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Plain)
        Frame.setLineWidth(8)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1026, 1273))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.instr_name_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instr_name_label.sizePolicy().hasHeightForWidth())
        self.instr_name_label.setSizePolicy(sizePolicy)
        self.instr_name_label.setMinimumSize(QtCore.QSize(300, 30))
        self.instr_name_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instr_name_label.setFont(font)
        self.instr_name_label.setObjectName(_fromUtf8("instr_name_label"))
        self.horizontalLayout_13.addWidget(self.instr_name_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.help_button = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(73, 30))
        self.help_button.setMaximumSize(QtCore.QSize(73, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.help_button.setFont(font)
        self.help_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.help_button.setIconSize(QtCore.QSize(15, 15))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.horizontalLayout_13.addWidget(self.help_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.reduction_options_group = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduction_options_group.sizePolicy().hasHeightForWidth())
        self.reduction_options_group.setSizePolicy(sizePolicy)
        self.reduction_options_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reduction_options_group.setObjectName(_fromUtf8("reduction_options_group"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.reduction_options_group)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.filterbadpulses_chkbox = QtGui.QCheckBox(self.reduction_options_group)
        self.filterbadpulses_chkbox.setObjectName(_fromUtf8("filterbadpulses_chkbox"))
        self.gridLayout_2.addWidget(self.filterbadpulses_chkbox, 5, 3, 1, 1)
        self.preserveevents_checkbox = QtGui.QCheckBox(self.reduction_options_group)
        self.preserveevents_checkbox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.preserveevents_checkbox.setObjectName(_fromUtf8("preserveevents_checkbox"))
        self.gridLayout_2.addWidget(self.preserveevents_checkbox, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.reduction_options_group)
        self.label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.pushdatapos_combo = QtGui.QComboBox(self.reduction_options_group)
        self.pushdatapos_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.pushdatapos_combo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pushdatapos_combo.setObjectName(_fromUtf8("pushdatapos_combo"))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.pushdatapos_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.pushdatapos_combo, 0, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.unwrap_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unwrap_edit.sizePolicy().hasHeightForWidth())
        self.unwrap_edit.setSizePolicy(sizePolicy)
        self.unwrap_edit.setObjectName(_fromUtf8("unwrap_edit"))
        self.gridLayout_2.addWidget(self.unwrap_edit, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lowres_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowres_edit.sizePolicy().hasHeightForWidth())
        self.lowres_edit.setSizePolicy(sizePolicy)
        self.lowres_edit.setMinimumSize(QtCore.QSize(40, 0))
        self.lowres_edit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lowres_edit.setObjectName(_fromUtf8("lowres_edit"))
        self.gridLayout_2.addWidget(self.lowres_edit, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.reduction_options_group)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.cropwavelengthmin_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cropwavelengthmin_edit.sizePolicy().hasHeightForWidth())
        self.cropwavelengthmin_edit.setSizePolicy(sizePolicy)
        self.cropwavelengthmin_edit.setMinimumSize(QtCore.QSize(40, 0))
        self.cropwavelengthmin_edit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.cropwavelengthmin_edit.setObjectName(_fromUtf8("cropwavelengthmin_edit"))
        self.gridLayout_2.addWidget(self.cropwavelengthmin_edit, 2, 1, 1, 1)
        self.removepromptwidth_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removepromptwidth_edit.sizePolicy().hasHeightForWidth())
        self.removepromptwidth_edit.setSizePolicy(sizePolicy)
        self.removepromptwidth_edit.setObjectName(_fromUtf8("removepromptwidth_edit"))
        self.gridLayout_2.addWidget(self.removepromptwidth_edit, 2, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.reduction_options_group)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 1)
        self.extension_combo = QtGui.QComboBox(self.reduction_options_group)
        self.extension_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.extension_combo.setMaximumSize(QtCore.QSize(400, 16777215))
        self.extension_combo.setObjectName(_fromUtf8("extension_combo"))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.extension_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.extension_combo, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.reduction_options_group)
        self.label_4.setMinimumSize(QtCore.QSize(160, 0))
        self.label_4.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.maxchunksize_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxchunksize_edit.sizePolicy().hasHeightForWidth())
        self.maxchunksize_edit.setSizePolicy(sizePolicy)
        self.maxchunksize_edit.setMinimumSize(QtCore.QSize(40, 0))
        self.maxchunksize_edit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.maxchunksize_edit.setBaseSize(QtCore.QSize(0, 0))
        self.maxchunksize_edit.setObjectName(_fromUtf8("maxchunksize_edit"))
        self.gridLayout_2.addWidget(self.maxchunksize_edit, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.reduction_options_group)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.reduction_options_group)
        self.mask_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_groupbox.sizePolicy().hasHeightForWidth())
        self.mask_groupbox.setSizePolicy(sizePolicy)
        self.mask_groupbox.setObjectName(_fromUtf8("mask_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mask_groupbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mask_help_label = QtGui.QLabel(self.mask_groupbox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setItalic(True)
        self.mask_help_label.setFont(font)
        self.mask_help_label.setObjectName(_fromUtf8("mask_help_label"))
        self.verticalLayout_2.addWidget(self.mask_help_label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.mask_groupbox)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.vanpeakfwhm_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.vanpeakfwhm_edit.setObjectName(_fromUtf8("vanpeakfwhm_edit"))
        self.gridLayout.addWidget(self.vanpeakfwhm_edit, 0, 3, 1, 1)
        self.vansmoothpar_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.vansmoothpar_edit.setObjectName(_fromUtf8("vansmoothpar_edit"))
        self.gridLayout.addWidget(self.vansmoothpar_edit, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.mask_groupbox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 6, 1, 1)
        self.label_11 = QtGui.QLabel(self.mask_groupbox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.mask_groupbox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 5, 1, 1)
        self.vanpeaktol_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.vanpeaktol_edit.setObjectName(_fromUtf8("vanpeaktol_edit"))
        self.gridLayout.addWidget(self.vanpeaktol_edit, 0, 7, 1, 1)
        self.stripvanpeaks_chkbox = QtGui.QCheckBox(self.mask_groupbox)
        self.stripvanpeaks_chkbox.setObjectName(_fromUtf8("stripvanpeaks_chkbox"))
        self.gridLayout.addWidget(self.stripvanpeaks_chkbox, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_4.addWidget(self.mask_groupbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_name_label.setText(QtGui.QApplication.translate("Frame", "Advanced Setup of SNS Powder Reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.help_button.setText(QtGui.QApplication.translate("Frame", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.reduction_options_group.setTitle(QtGui.QApplication.translate("Frame", "Advanced Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.filterbadpulses_chkbox.setText(QtGui.QApplication.translate("Frame", "Filter Bad Pulses", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setStatusTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.preserveevents_checkbox.setText(QtGui.QApplication.translate("Frame", "Preserve Events", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Push Data Positive", None, QtGui.QApplication.UnicodeUTF8))
        self.pushdatapos_combo.setItemText(0, QtGui.QApplication.translate("Frame", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.pushdatapos_combo.setItemText(1, QtGui.QApplication.translate("Frame", "ResetToZero", None, QtGui.QApplication.UnicodeUTF8))
        self.pushdatapos_combo.setItemText(2, QtGui.QApplication.translate("Frame", "AddMinimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Low Resolution Ref", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Unwrap Ref", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Minumum Cropped Wavelength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Remove Prompt Pulse Width", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(0, QtGui.QApplication.translate("Frame", "_event.nxs", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(1, QtGui.QApplication.translate("Frame", "_histo.nxs", None, QtGui.QApplication.UnicodeUTF8))
        self.extension_combo.setItemText(2, QtGui.QApplication.translate("Frame", "_runinfo.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "File Extension", None, QtGui.QApplication.UnicodeUTF8))
        self.maxchunksize_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.maxchunksize_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Maximum Chunk Size", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Strip Vanadium Peaks", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_help_label.setText(QtGui.QApplication.translate("Frame", "The following input parameters are used to control the algorithm to strip vanadium peaks.\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Peak Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Peak FWHM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Peak Smooth Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.stripvanpeaks_chkbox.setText(QtGui.QApplication.translate("Frame", "Strip Vanadium Peaks", None, QtGui.QApplication.UnicodeUTF8))

