# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffraction_filter_setup.ui'
#
# Created: Wed Mar 13 18:11:51 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(1028, 1018)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(Frame)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.starttime_edit = QtGui.QLineEdit(self.frame)
        self.starttime_edit.setGeometry(QtCore.QRect(180, 160, 241, 27))
        self.starttime_edit.setObjectName(_fromUtf8("starttime_edit"))
        self.stoptime_edit = QtGui.QLineEdit(self.frame)
        self.stoptime_edit.setGeometry(QtCore.QRect(180, 210, 245, 27))
        self.stoptime_edit.setObjectName(_fromUtf8("stoptime_edit"))
        self.title_edit = QtGui.QLineEdit(self.frame)
        self.title_edit.setGeometry(QtCore.QRect(90, 100, 831, 27))
        self.title_edit.setObjectName(_fromUtf8("title_edit"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 130, 29))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 51, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 122, 29))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 191, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 171, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.timintervallength_edit = QtGui.QLineEdit(self.frame_2)
        self.timintervallength_edit.setGeometry(QtCore.QRect(190, 140, 121, 27))
        self.timintervallength_edit.setObjectName(_fromUtf8("timintervallength_edit"))
        self.timeunit_combo = QtGui.QComboBox(self.frame_2)
        self.timeunit_combo.setGeometry(QtCore.QRect(190, 200, 120, 27))
        self.timeunit_combo.setObjectName(_fromUtf8("timeunit_combo"))
        self.timeunit_combo.addItem(_fromUtf8(""))
        self.timeunit_combo.addItem(_fromUtf8(""))
        self.timeunit_combo.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(70, 110, 66, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.numtimeinterval_edit = QtGui.QLineEdit(self.frame_2)
        self.numtimeinterval_edit.setEnabled(False)
        self.numtimeinterval_edit.setGeometry(QtCore.QRect(190, 70, 121, 27))
        self.numtimeinterval_edit.setObjectName(_fromUtf8("numtimeinterval_edit"))
        self.timefilter_checkBox = QtGui.QCheckBox(self.frame_2)
        self.timefilter_checkBox.setGeometry(QtCore.QRect(140, 10, 97, 22))
        self.timefilter_checkBox.setText(_fromUtf8(""))
        self.timefilter_checkBox.setObjectName(_fromUtf8("timefilter_checkBox"))
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(340, 0, 20, 331))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_17 = QtGui.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(360, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.logminvalue_edit = QtGui.QLineEdit(self.frame_2)
        self.logminvalue_edit.setGeometry(QtCore.QRect(510, 60, 131, 27))
        self.logminvalue_edit.setObjectName(_fromUtf8("logminvalue_edit"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(360, 60, 105, 29))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(360, 110, 108, 29))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.logmaxvalue_edit = QtGui.QLineEdit(self.frame_2)
        self.logmaxvalue_edit.setGeometry(QtCore.QRect(510, 110, 131, 27))
        self.logmaxvalue_edit.setObjectName(_fromUtf8("logmaxvalue_edit"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(670, 50, 161, 39))
        self.label_7.setLineWidth(3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.valuechange_combo = QtGui.QComboBox(self.frame_2)
        self.valuechange_combo.setGeometry(QtCore.QRect(850, 50, 111, 31))
        self.valuechange_combo.setObjectName(_fromUtf8("valuechange_combo"))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.valuechange_combo.addItem(_fromUtf8(""))
        self.label_22 = QtGui.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(360, 160, 121, 29))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.logintervalvalue_edit = QtGui.QLineEdit(self.frame_2)
        self.logintervalvalue_edit.setGeometry(QtCore.QRect(510, 210, 131, 27))
        self.logintervalvalue_edit.setObjectName(_fromUtf8("logintervalvalue_edit"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(410, 200, 61, 29))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.numloginterval_edit = QtGui.QLineEdit(self.frame_2)
        self.numloginterval_edit.setEnabled(False)
        self.numloginterval_edit.setGeometry(QtCore.QRect(510, 160, 131, 27))
        self.numloginterval_edit.setObjectName(_fromUtf8("numloginterval_edit"))
        self.logtol_edit = QtGui.QLineEdit(self.frame_2)
        self.logtol_edit.setGeometry(QtCore.QRect(720, 190, 121, 27))
        self.logtol_edit.setObjectName(_fromUtf8("logtol_edit"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(720, 150, 151, 29))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.logvaluefilter_checkBox = QtGui.QCheckBox(self.frame_2)
        self.logvaluefilter_checkBox.setEnabled(True)
        self.logvaluefilter_checkBox.setGeometry(QtCore.QRect(550, 10, 41, 22))
        self.logvaluefilter_checkBox.setText(_fromUtf8(""))
        self.logvaluefilter_checkBox.setObjectName(_fromUtf8("logvaluefilter_checkBox"))
        self.logname_edit = QtGui.QLineEdit(self.frame_2)
        self.logname_edit.setGeometry(QtCore.QRect(710, 10, 251, 27))
        self.logname_edit.setObjectName(_fromUtf8("logname_edit"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(90, 200, 81, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.usenumstep_radiob = QtGui.QRadioButton(self.frame_2)
        self.usenumstep_radiob.setEnabled(False)
        self.usenumstep_radiob.setGeometry(QtCore.QRect(660, 160, 21, 22))
        self.usenumstep_radiob.setText(_fromUtf8(""))
        self.usenumstep_radiob.setObjectName(_fromUtf8("usenumstep_radiob"))
        self.usesize_radiob = QtGui.QRadioButton(self.frame_2)
        self.usesize_radiob.setEnabled(False)
        self.usesize_radiob.setGeometry(QtCore.QRect(660, 210, 21, 22))
        self.usesize_radiob.setText(_fromUtf8(""))
        self.usesize_radiob.setObjectName(_fromUtf8("usesize_radiob"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(620, 10, 71, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(370, 270, 101, 29))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.timetol_edit = QtGui.QLineEdit(self.frame_2)
        self.timetol_edit.setEnabled(True)
        self.timetol_edit.setGeometry(QtCore.QRect(510, 270, 131, 27))
        self.timetol_edit.setObjectName(_fromUtf8("timetol_edit"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(670, 270, 101, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.logbound_combo = QtGui.QComboBox(self.frame_2)
        self.logbound_combo.setGeometry(QtCore.QRect(780, 270, 131, 27))
        self.logbound_combo.setObjectName(_fromUtf8("logbound_combo"))
        self.logbound_combo.addItem(_fromUtf8(""))
        self.logbound_combo.addItem(_fromUtf8(""))
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(360, 140, 591, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(360, 240, 591, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Frame)
        self.frame_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.info_text_browser = QtGui.QTextBrowser(self.frame_3)
        self.info_text_browser.setGeometry(QtCore.QRect(580, 30, 401, 271))
        self.info_text_browser.setObjectName(_fromUtf8("info_text_browser"))
        self.run_number_edit = QtGui.QLineEdit(self.frame_3)
        self.run_number_edit.setGeometry(QtCore.QRect(130, 80, 171, 27))
        self.run_number_edit.setObjectName(_fromUtf8("run_number_edit"))
        self.load_button = QtGui.QPushButton(self.frame_3)
        self.load_button.setGeometry(QtCore.QRect(330, 80, 71, 27))
        self.load_button.setObjectName(_fromUtf8("load_button"))
        self.plot_log_button = QtGui.QPushButton(self.frame_3)
        self.plot_log_button.setGeometry(QtCore.QRect(330, 140, 71, 27))
        self.plot_log_button.setObjectName(_fromUtf8("plot_log_button"))
        self.log_name_combo = QtGui.QComboBox(self.frame_3)
        self.log_name_combo.setGeometry(QtCore.QRect(10, 140, 291, 27))
        self.log_name_combo.setObjectName(_fromUtf8("log_name_combo"))
        self.syn_logname_button = QtGui.QPushButton(self.frame_3)
        self.syn_logname_button.setGeometry(QtCore.QRect(430, 140, 81, 27))
        self.syn_logname_button.setObjectName(_fromUtf8("syn_logname_button"))
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(20, 80, 91, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Filter Starting Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Filter Ending Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Event Filtering (General Setup)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Number of Time Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Duration of Each Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.timeunit_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.timeunit_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Nanoseconds", None, QtGui.QApplication.UnicodeUTF8))
        self.timeunit_combo.setItemText(2, QtGui.QApplication.translate("Frame", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Filter By Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "Filter By Log Value(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Minimum Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Maximum Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", " Value Change Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Both", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Increase", None, QtGui.QApplication.UnicodeUTF8))
        self.valuechange_combo.setItemText(2, QtGui.QApplication.translate("Frame", "Decrease", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Number of Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Step Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Log Value Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Unit of Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Log Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Time Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "Log Boundary", None, QtGui.QApplication.UnicodeUTF8))
        self.logbound_combo.setItemText(0, QtGui.QApplication.translate("Frame", "Centre", None, QtGui.QApplication.UnicodeUTF8))
        self.logbound_combo.setItemText(1, QtGui.QApplication.translate("Frame", "Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Frame", "Filter Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.load_button.setText(QtGui.QApplication.translate("Frame", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_log_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.syn_logname_button.setText(QtGui.QApplication.translate("Frame", "Use It", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Frame", "Run Number", None, QtGui.QApplication.UnicodeUTF8))

