# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hfir_beam_finder.ui'
#
# Created: Tue Nov 30 14:52:26 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(813, 571)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayoutWidget = QtGui.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.x_pos_edit = QtGui.QLineEdit(self.widget)
        self.x_pos_edit.setGeometry(QtCore.QRect(20, 40, 113, 27))
        self.x_pos_edit.setObjectName("x_pos_edit")
        self.y_pos_edit = QtGui.QLineEdit(self.widget)
        self.y_pos_edit.setGeometry(QtCore.QRect(170, 40, 113, 27))
        self.y_pos_edit.setObjectName("y_pos_edit")
        self.x_pos_label = QtGui.QLabel(self.widget)
        self.x_pos_label.setGeometry(QtCore.QRect(20, 20, 81, 17))
        self.x_pos_label.setObjectName("x_pos_label")
        self.y_pos_label = QtGui.QLabel(self.widget)
        self.y_pos_label.setGeometry(QtCore.QRect(170, 20, 81, 17))
        self.y_pos_label.setObjectName("y_pos_label")
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 611, 141))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 591, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(5)
        self.formLayout.setObjectName("formLayout")
        self.data_file_label = QtGui.QLabel(self.formLayoutWidget)
        self.data_file_label.setObjectName("data_file_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.data_file_label)
        self.direct_beam = QtGui.QRadioButton(self.formLayoutWidget)
        self.direct_beam.setChecked(True)
        self.direct_beam.setObjectName("direct_beam")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.direct_beam)
        self.scattering_data = QtGui.QRadioButton(self.formLayoutWidget)
        self.scattering_data.setObjectName("scattering_data")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.scattering_data)
        self.beam_radius_label = QtGui.QLabel(self.formLayoutWidget)
        self.beam_radius_label.setObjectName("beam_radius_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.beam_radius_label)
        self.beam_radius_edit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_edit.sizePolicy().hasHeightForWidth())
        self.beam_radius_edit.setSizePolicy(sizePolicy)
        self.beam_radius_edit.setMinimumSize(QtCore.QSize(97, 0))
        self.beam_radius_edit.setObjectName("beam_radius_edit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.beam_radius_edit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beam_data_file_edit = QtGui.QLineEdit(self.formLayoutWidget)
        self.beam_data_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.beam_data_file_edit.setObjectName("beam_data_file_edit")
        self.horizontalLayout.addWidget(self.beam_data_file_edit)
        self.data_file_browse_button = QtGui.QPushButton(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_browse_button.sizePolicy().hasHeightForWidth())
        self.data_file_browse_button.setSizePolicy(sizePolicy)
        self.data_file_browse_button.setObjectName("data_file_browse_button")
        self.horizontalLayout.addWidget(self.data_file_browse_button)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.use_beam_finder_checkbox = QtGui.QCheckBox(self.widget)
        self.use_beam_finder_checkbox.setGeometry(QtCore.QRect(20, 80, 181, 22))
        self.use_beam_finder_checkbox.setObjectName("use_beam_finder_checkbox")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Frame)
        QtCore.QObject.connect(self.use_beam_finder_checkbox, QtCore.SIGNAL("clicked()"), Frame.use_beam_finder_changed)
        QtCore.QObject.connect(self.scattering_data, QtCore.SIGNAL("clicked()"), Frame.fit_scattering_data)
        QtCore.QObject.connect(self.direct_beam, QtCore.SIGNAL("clicked()"), Frame.fit_direct_beam)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_edit.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in X, in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_edit.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in Y, in pixels.", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_label.setText(QtGui.QApplication.translate("Frame", "X position", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_label.setText(QtGui.QApplication.translate("Frame", "Y position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Beam Finder", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_label.setText(QtGui.QApplication.translate("Frame", "Data file:                       ", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam.setToolTip(QtGui.QApplication.translate("Frame", "Fit the direct beam to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam.setText(QtGui.QApplication.translate("Frame", "Fit direct beam", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data.setToolTip(QtGui.QApplication.translate("Frame", "Fit only the scattering profile to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data.setText(QtGui.QApplication.translate("Frame", "Fit scattering data", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_label.setText(QtGui.QApplication.translate("Frame", "Beam radius [pixels]", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the radius of the beam in pixels.", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_data_file_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the file path of a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software find the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox.setText(QtGui.QApplication.translate("Frame", "Use beam finder", None, QtGui.QApplication.UnicodeUTF8))

