# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mask.ui'
#
# Created: Fri Apr 15 15:38:14 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(989, 1107)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reduction_options_groupbox = QtGui.QGroupBox(Frame)
        self.reduction_options_groupbox.setObjectName("reduction_options_groupbox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.reduction_options_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.top_edit = QtGui.QLineEdit(self.reduction_options_groupbox)
        self.top_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.top_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.top_edit.setObjectName("top_edit")
        self.gridLayout.addWidget(self.top_edit, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.reduction_options_groupbox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.reduction_options_groupbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.bottom_edit = QtGui.QLineEdit(self.reduction_options_groupbox)
        self.bottom_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.bottom_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bottom_edit.setObjectName("bottom_edit")
        self.gridLayout.addWidget(self.bottom_edit, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.reduction_options_groupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.left_edit = QtGui.QLineEdit(self.reduction_options_groupbox)
        self.left_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.left_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.left_edit.setObjectName("left_edit")
        self.gridLayout.addWidget(self.left_edit, 0, 5, 1, 1)
        self.right_edit = QtGui.QLineEdit(self.reduction_options_groupbox)
        self.right_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.right_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.right_edit.setObjectName("right_edit")
        self.gridLayout.addWidget(self.right_edit, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.reduction_options_groupbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.reduction_options_groupbox)
        self.geometry_options_groupbox = QtGui.QGroupBox(Frame)
        self.geometry_options_groupbox.setObjectName("geometry_options_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.geometry_options_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.x_min_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.x_min_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.x_min_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.x_min_edit.setObjectName("x_min_edit")
        self.gridLayout_2.addWidget(self.x_min_edit, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.geometry_options_groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.geometry_options_groupbox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.x_max_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.x_max_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.x_max_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.x_max_edit.setObjectName("x_max_edit")
        self.gridLayout_2.addWidget(self.x_max_edit, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.geometry_options_groupbox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 4, 1, 1)
        self.y_min_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.y_min_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.y_min_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.y_min_edit.setObjectName("y_min_edit")
        self.gridLayout_2.addWidget(self.y_min_edit, 0, 5, 1, 1)
        self.y_max_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.y_max_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.y_max_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.y_max_edit.setObjectName("y_max_edit")
        self.gridLayout_2.addWidget(self.y_max_edit, 0, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.geometry_options_groupbox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 6, 1, 1)
        self.add_rectangle_button = QtGui.QPushButton(self.geometry_options_groupbox)
        self.add_rectangle_button.setObjectName("add_rectangle_button")
        self.gridLayout_2.addWidget(self.add_rectangle_button, 0, 9, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 8, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.listWidget = QtGui.QListWidget(self.geometry_options_groupbox)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.remove_button = QtGui.QPushButton(self.geometry_options_groupbox)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_2.addWidget(self.remove_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.geometry_options_groupbox)
        self.instrument_groupbox = QtGui.QGroupBox(Frame)
        self.instrument_groupbox.setObjectName("instrument_groupbox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.instrument_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtGui.QLabel(self.instrument_groupbox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.show_instr_button = QtGui.QPushButton(self.instrument_groupbox)
        self.show_instr_button.setObjectName("show_instr_button")
        self.horizontalLayout_3.addWidget(self.show_instr_button)
        self.apply_instr_button = QtGui.QPushButton(self.instrument_groupbox)
        self.apply_instr_button.setObjectName("apply_instr_button")
        self.horizontalLayout_3.addWidget(self.apply_instr_button)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_10 = QtGui.QLabel(self.instrument_groupbox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.verticalLayout.addWidget(self.instrument_groupbox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.reduction_options_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Edges of the Detector", None, QtGui.QApplication.UnicodeUTF8))
        self.top_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the number of pixels to be masked from the top of the detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.bottom_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the number of pixels to be masked from the bottom of the detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.left_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the number of pixels to be masked from the left side of the detector", None, QtGui.QApplication.UnicodeUTF8))
        self.right_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the number of pixels to be masked from the right side of the detector", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry_options_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Rectangular Masks", None, QtGui.QApplication.UnicodeUTF8))
        self.x_min_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "x min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "x max", None, QtGui.QApplication.UnicodeUTF8))
        self.x_max_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "y min", None, QtGui.QApplication.UnicodeUTF8))
        self.y_min_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.y_max_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "y max", None, QtGui.QApplication.UnicodeUTF8))
        self.add_rectangle_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to add a rectangular mask", None, QtGui.QApplication.UnicodeUTF8))
        self.add_rectangle_button.setText(QtGui.QApplication.translate("Frame", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_button.setToolTip(QtGui.QApplication.translate("Frame", "Remove the selected mask item from the list", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_button.setText(QtGui.QApplication.translate("Frame", "Removed Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.instrument_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Instrument Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Frame", "Click the Show Instrument button to mask areas of the detector by hand.\n"
"Click the Apply button to confirm.", None, QtGui.QApplication.UnicodeUTF8))
        self.show_instr_button.setToolTip(QtGui.QApplication.translate("Frame", "Remove the selected mask item from the list", None, QtGui.QApplication.UnicodeUTF8))
        self.show_instr_button.setText(QtGui.QApplication.translate("Frame", "Show Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_instr_button.setToolTip(QtGui.QApplication.translate("Frame", "Remove the selected mask item from the list", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_instr_button.setText(QtGui.QApplication.translate("Frame", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Do the following to define a masked region:\n"
"  -Go to the Pick tab of the instrument window\n"
"  -Select pixels with the mouse\n"
"  -Right-click and select Mask.", None, QtGui.QApplication.UnicodeUTF8))

