{% set version = load_setup_py_data().get('version', '0.0.0') %}

package:
  name: mantid
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantid', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp                            # [osx]
    - libgomp                                # [linux]
    - ninja                                  # [unix]
    - cmake
    - git
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools {{ setuptools }}            # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}          # [linux]
    - {{ cdt('libxxf86vm') }}                # [linux]
    - {{ cdt('libx11-devel') }}              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}      # [linux]
    - libcxx                                 # [osx]

  host:
    - boost {{ boost }}
    - eigen
    - gsl {{ gsl }}
    - h5py
    - hdf5 {{ hdf5 }}
    - jemalloc  # [unix]
    - jsoncpp
    - librdkafka
    - lib3mf  # [win]
    - muparser
    - nexus
    - numpy {{ numpy }}
    - occt
    - python {{ python }}
    - poco {{ poco }}
    - setuptools {{ setuptools }}
    - tbb-devel {{ tbb }}
    - pip
    - openssl
    - versioningit
    - libglu  # [linux]
  run:
    - {{ pin_compatible("boost", max_pin="x.x") }}
    - {{ pin_compatible("gsl", max_pin="x.x") }}
    - h5py
    - {{ pin_compatible("hdf5", max_pin="x.x") }}
    - lib3mf  # [win]
    - nexus
    - {{ pin_compatible("numpy", upper_bound="1.25") }}
    - {{ pin_compatible("occt", max_pin="x.x.x") }}
    - pycifrw {{ pycifrw }}
    - python
    - python-dateutil
    - pyyaml
    - scipy {{ scipy }}
    - openssl
    - euphonic {{ euphonic }}
    - toml
    - libglu  # [linux]
    - libopenblas {{ libopenblas }}  # [osx]

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.
  description: Mantid provides a framework that supports high-performance computing and visualisation of materials science data. To use the optional plotting sub package you must conda install matplotlib 3.5.2 to ensure correct compatibility.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
