# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refl_window.ui'
#
# Created: Tue Jan 27 15:40:39 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_windowRefl(object):
    def setupUi(self, windowRefl):
        windowRefl.setObjectName(_fromUtf8("windowRefl"))
        windowRefl.resize(1000, 400)
        windowRefl.setAcceptDrops(True)
        self.widgetMainRow = QtGui.QWidget(windowRefl)
        self.widgetMainRow.setObjectName(_fromUtf8("widgetMainRow"))
        self.layoutBase = QtGui.QVBoxLayout(self.widgetMainRow)
        self.layoutBase.setObjectName(_fromUtf8("layoutBase"))
        self.layoutTopRow = QtGui.QHBoxLayout()
        self.layoutTopRow.setObjectName(_fromUtf8("layoutTopRow"))
        self.labelInstrument = QtGui.QLabel(self.widgetMainRow)
        self.labelInstrument.setObjectName(_fromUtf8("labelInstrument"))
        self.layoutTopRow.addWidget(self.labelInstrument)
        self.comboInstrument = QtGui.QComboBox(self.widgetMainRow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboInstrument.sizePolicy().hasHeightForWidth())
        self.comboInstrument.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboInstrument.setFont(font)
        self.comboInstrument.setObjectName(_fromUtf8("comboInstrument"))
        self.layoutTopRow.addWidget(self.comboInstrument)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutTopRow.addItem(spacerItem)
        self.labelRuns = QtGui.QLabel(self.widgetMainRow)
        self.labelRuns.setObjectName(_fromUtf8("labelRuns"))
        self.layoutTopRow.addWidget(self.labelRuns)
        self.textRuns = QtGui.QLineEdit(self.widgetMainRow)
        self.textRuns.setMinimumSize(QtCore.QSize(90, 0))
        self.textRuns.setMaximumSize(QtCore.QSize(120, 16777215))
        self.textRuns.setObjectName(_fromUtf8("textRuns"))
        self.layoutTopRow.addWidget(self.textRuns)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutTopRow.addItem(spacerItem1)
        self.labelPolarCorrect = QtGui.QLabel(self.widgetMainRow)
        self.labelPolarCorrect.setObjectName(_fromUtf8("labelPolarCorrect"))
        self.layoutTopRow.addWidget(self.labelPolarCorrect)
        self.comboPolarCorrect = QtGui.QComboBox(self.widgetMainRow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboPolarCorrect.setFont(font)
        self.comboPolarCorrect.setObjectName(_fromUtf8("comboPolarCorrect"))
        self.comboPolarCorrect.addItem(_fromUtf8(""))
        self.comboPolarCorrect.addItem(_fromUtf8(""))
        self.comboPolarCorrect.addItem(_fromUtf8(""))
        self.layoutTopRow.addWidget(self.comboPolarCorrect)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutTopRow.addItem(spacerItem2)
        self.buttonColumns = QtGui.QPushButton(self.widgetMainRow)
        self.buttonColumns.setObjectName(_fromUtf8("buttonColumns"))
        self.layoutTopRow.addWidget(self.buttonColumns)
        self.layoutBase.addLayout(self.layoutTopRow)
        self.layoutMidRow = QtGui.QHBoxLayout()
        self.layoutMidRow.setSpacing(12)
        self.layoutMidRow.setObjectName(_fromUtf8("layoutMidRow"))
        self.labelRB = QtGui.QLabel(self.widgetMainRow)
        self.labelRB.setObjectName(_fromUtf8("labelRB"))
        self.layoutMidRow.addWidget(self.labelRB)
        self.textRB = QtGui.QLineEdit(self.widgetMainRow)
        self.textRB.setMinimumSize(QtCore.QSize(40, 0))
        self.textRB.setMaximumSize(QtCore.QSize(70, 16777215))
        self.textRB.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textRB.setCursorPosition(0)
        self.textRB.setObjectName(_fromUtf8("textRB"))
        self.layoutMidRow.addWidget(self.textRB)
        self.buttonSearch = QtGui.QPushButton(self.widgetMainRow)
        self.buttonSearch.setObjectName(_fromUtf8("buttonSearch"))
        self.layoutMidRow.addWidget(self.buttonSearch)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutMidRow.addItem(spacerItem3)
        self.checkTickAll = QtGui.QCheckBox(self.widgetMainRow)
        self.checkTickAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkTickAll.setTristate(False)
        self.checkTickAll.setObjectName(_fromUtf8("checkTickAll"))
        self.layoutMidRow.addWidget(self.checkTickAll)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutMidRow.addItem(spacerItem4)
        self.buttonAuto = QtGui.QPushButton(self.widgetMainRow)
        self.buttonAuto.setObjectName(_fromUtf8("buttonAuto"))
        self.layoutMidRow.addWidget(self.buttonAuto)
        self.layoutBase.addLayout(self.layoutMidRow)
        self.splitterList = QtGui.QSplitter(self.widgetMainRow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterList.sizePolicy().hasHeightForWidth())
        self.splitterList.setSizePolicy(sizePolicy)
        self.splitterList.setOrientation(QtCore.Qt.Horizontal)
        self.splitterList.setChildrenCollapsible(False)
        self.splitterList.setObjectName(_fromUtf8("splitterList"))
        self.listMain = QtGui.QListWidget(self.splitterList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMain.sizePolicy().hasHeightForWidth())
        self.listMain.setSizePolicy(sizePolicy)
        self.listMain.setMinimumSize(QtCore.QSize(100, 0))
        self.listMain.setMaximumSize(QtCore.QSize(500, 16777215))
        self.listMain.setBaseSize(QtCore.QSize(199, 0))
        self.listMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listMain.setObjectName(_fromUtf8("listMain"))
        self.widgetBottomRight = QtGui.QWidget(self.splitterList)
        self.widgetBottomRight.setObjectName(_fromUtf8("widgetBottomRight"))
        self.layoutBottomRow = QtGui.QHBoxLayout(self.widgetBottomRight)
        self.layoutBottomRow.setMargin(0)
        self.layoutBottomRow.setObjectName(_fromUtf8("layoutBottomRow"))
        self.buttonTransfer = QtGui.QPushButton(self.widgetBottomRight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTransfer.sizePolicy().hasHeightForWidth())
        self.buttonTransfer.setSizePolicy(sizePolicy)
        self.buttonTransfer.setMaximumSize(QtCore.QSize(25, 16777215))
        self.buttonTransfer.setObjectName(_fromUtf8("buttonTransfer"))
        self.layoutBottomRow.addWidget(self.buttonTransfer)
        self.layoutTableColumn = QtGui.QVBoxLayout()
        self.layoutTableColumn.setObjectName(_fromUtf8("layoutTableColumn"))
        self.tableMain = QtGui.QTableWidget(self.widgetBottomRight)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableMain.setFont(font)
        self.tableMain.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tableMain.setAlternatingRowColors(True)
        self.tableMain.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.tableMain.setRowCount(100)
        self.tableMain.setColumnCount(19)
        self.tableMain.setObjectName(_fromUtf8("tableMain"))
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(18, item)
        self.tableMain.horizontalHeader().setCascadingSectionResizes(False)
        self.tableMain.horizontalHeader().setDefaultSectionSize(60)
        self.tableMain.horizontalHeader().setMinimumSectionSize(20)
        self.tableMain.horizontalHeader().setStretchLastSection(False)
        self.tableMain.verticalHeader().setCascadingSectionResizes(False)
        self.tableMain.verticalHeader().setDefaultSectionSize(20)
        self.tableMain.verticalHeader().setStretchLastSection(False)
        self.layoutTableColumn.addWidget(self.tableMain)
        self.layoutTableButton = QtGui.QHBoxLayout()
        self.layoutTableButton.setObjectName(_fromUtf8("layoutTableButton"))
        self.buttonProcess = QtGui.QPushButton(self.widgetBottomRight)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProcess.sizePolicy().hasHeightForWidth())
        self.buttonProcess.setSizePolicy(sizePolicy)
        self.buttonProcess.setObjectName(_fromUtf8("buttonProcess"))
        self.layoutTableButton.addWidget(self.buttonProcess)
        self.buttonClear = QtGui.QPushButton(self.widgetBottomRight)
        self.buttonClear.setObjectName(_fromUtf8("buttonClear"))
        self.layoutTableButton.addWidget(self.buttonClear)
        self.layoutTableColumn.addLayout(self.layoutTableButton)
        self.layoutBottomRow.addLayout(self.layoutTableColumn)
        self.layoutBase.addWidget(self.splitterList)
        windowRefl.setCentralWidget(self.widgetMainRow)
        self.menuBar = QtGui.QMenuBar(windowRefl)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFunction = QtGui.QMenu(self.menuBar)
        self.menuFunction.setObjectName(_fromUtf8("menuFunction"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        windowRefl.setMenuBar(self.menuBar)
        self.statusMain = QtGui.QStatusBar(windowRefl)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusMain.setFont(font)
        self.statusMain.setObjectName(_fromUtf8("statusMain"))
        windowRefl.setStatusBar(self.statusMain)
        self.actionSave_As = QtGui.QAction(windowRefl)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionOpen_Table = QtGui.QAction(windowRefl)
        self.actionOpen_Table.setObjectName(_fromUtf8("actionOpen_Table"))
        self.actionReload_from_Disk = QtGui.QAction(windowRefl)
        self.actionReload_from_Disk.setObjectName(_fromUtf8("actionReload_from_Disk"))
        self.actionSave_Workspaces = QtGui.QAction(windowRefl)
        self.actionSave_Workspaces.setObjectName(_fromUtf8("actionSave_Workspaces"))
        self.actionMantid_Help = QtGui.QAction(windowRefl)
        self.actionMantid_Help.setObjectName(_fromUtf8("actionMantid_Help"))
        self.actionSave = QtGui.QAction(windowRefl)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose_Refl_Gui = QtGui.QAction(windowRefl)
        self.actionClose_Refl_Gui.setObjectName(_fromUtf8("actionClose_Refl_Gui"))
        self.actionAutofill = QtGui.QAction(windowRefl)
        self.actionAutofill.setObjectName(_fromUtf8("actionAutofill"))
        self.actionProcess = QtGui.QAction(windowRefl)
        self.actionProcess.setObjectName(_fromUtf8("actionProcess"))
        self.actionTransfer = QtGui.QAction(windowRefl)
        self.actionTransfer.setObjectName(_fromUtf8("actionTransfer"))
        self.actionClear_Table = QtGui.QAction(windowRefl)
        self.actionClear_Table.setObjectName(_fromUtf8("actionClear_Table"))
        self.actionSearch_RB = QtGui.QAction(windowRefl)
        self.actionSearch_RB.setObjectName(_fromUtf8("actionSearch_RB"))
        self.actionCopy = QtGui.QAction(windowRefl)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(windowRefl)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(windowRefl)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionClear = QtGui.QAction(windowRefl)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionChoose_Columns = QtGui.QAction(windowRefl)
        self.actionChoose_Columns.setObjectName(_fromUtf8("actionChoose_Columns"))
        self.actionRefl_Gui_Options = QtGui.QAction(windowRefl)
        self.actionRefl_Gui_Options.setObjectName(_fromUtf8("actionRefl_Gui_Options"))
        self.actionSlit_Calculator = QtGui.QAction(windowRefl)
        self.actionSlit_Calculator.setObjectName(_fromUtf8("actionSlit_Calculator"))
        self.menuFile.addAction(self.actionOpen_Table)
        self.menuFile.addAction(self.actionReload_from_Disk)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_Workspaces)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Refl_Gui)
        self.menuHelp.addAction(self.actionMantid_Help)
        self.menuHelp.addAction(self.actionSlit_Calculator)
        self.menuFunction.addAction(self.actionTransfer)
        self.menuFunction.addAction(self.actionAutofill)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionProcess)
        self.menuFunction.addAction(self.actionClear_Table)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionSearch_RB)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionClear)
        self.menuOptions.addAction(self.actionChoose_Columns)
        self.menuOptions.addAction(self.actionRefl_Gui_Options)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuFunction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.labelInstrument.setBuddy(self.comboInstrument)
        self.labelRuns.setBuddy(self.textRuns)
        self.labelPolarCorrect.setBuddy(self.comboPolarCorrect)
        self.labelRB.setBuddy(self.textRB)

        self.retranslateUi(windowRefl)
        QtCore.QMetaObject.connectSlotsByName(windowRefl)
        windowRefl.setTabOrder(self.comboInstrument, self.textRuns)
        windowRefl.setTabOrder(self.textRuns, self.comboPolarCorrect)
        windowRefl.setTabOrder(self.comboPolarCorrect, self.textRB)
        windowRefl.setTabOrder(self.textRB, self.buttonSearch)
        windowRefl.setTabOrder(self.buttonSearch, self.checkTickAll)
        windowRefl.setTabOrder(self.checkTickAll, self.buttonAuto)
        windowRefl.setTabOrder(self.buttonAuto, self.buttonTransfer)
        windowRefl.setTabOrder(self.buttonTransfer, self.tableMain)
        windowRefl.setTabOrder(self.tableMain, self.buttonProcess)
        windowRefl.setTabOrder(self.buttonProcess, self.buttonClear)

    def retranslateUi(self, windowRefl):
        windowRefl.setWindowTitle(_translate("windowRefl", "ISIS Reflectometry", None))
        self.labelInstrument.setText(_translate("windowRefl", "Instrument:", None))
        self.comboInstrument.setToolTip(_translate("windowRefl", "Sets the instrument to use.", None))
        self.labelRuns.setText(_translate("windowRefl", "Transmission run(s):", None))
        self.textRuns.setToolTip(_translate("windowRefl", "Transmission run number to be automatically entered into the \'trans\' column when transferring runs.", None))
        self.labelPolarCorrect.setText(_translate("windowRefl", "Polarisation corrections:", None))
        self.comboPolarCorrect.setToolTip(_translate("windowRefl", "Sets the polarisation corrections to be done when processing.", None))
        self.comboPolarCorrect.setItemText(0, _translate("windowRefl", "None", None))
        self.comboPolarCorrect.setItemText(1, _translate("windowRefl", "1-PNR", None))
        self.comboPolarCorrect.setItemText(2, _translate("windowRefl", "2-PA", None))
        self.buttonColumns.setText(_translate("windowRefl", "Choose Columns...", None))
        self.labelRB.setText(_translate("windowRefl", "RB Search:", None))
        self.textRB.setToolTip(_translate("windowRefl", "The term to search the archives for", None))
        self.buttonSearch.setText(_translate("windowRefl", "Search", None))
        self.checkTickAll.setToolTip(_translate("windowRefl", "Toggles selection of the \'Stitch?\' column.", None))
        self.checkTickAll.setText(_translate("windowRefl", "(un)tick all", None))
        self.buttonAuto.setText(_translate("windowRefl", "AutoFill", None))
        self.buttonTransfer.setText(_translate("windowRefl", "=>", None))
        item = self.tableMain.horizontalHeaderItem(0)
        item.setText(_translate("windowRefl", "Run(s)", None))
        item = self.tableMain.horizontalHeaderItem(1)
        item.setText(_translate("windowRefl", "Angle 1", None))
        item = self.tableMain.horizontalHeaderItem(2)
        item.setText(_translate("windowRefl", "trans 1", None))
        item = self.tableMain.horizontalHeaderItem(3)
        item.setText(_translate("windowRefl", "qmin_1", None))
        item = self.tableMain.horizontalHeaderItem(4)
        item.setText(_translate("windowRefl", "qmax_1", None))
        item = self.tableMain.horizontalHeaderItem(5)
        item.setText(_translate("windowRefl", "Run(s)", None))
        item = self.tableMain.horizontalHeaderItem(6)
        item.setText(_translate("windowRefl", "Angle 2", None))
        item = self.tableMain.horizontalHeaderItem(7)
        item.setText(_translate("windowRefl", "trans 2", None))
        item = self.tableMain.horizontalHeaderItem(8)
        item.setText(_translate("windowRefl", "qmin_2", None))
        item = self.tableMain.horizontalHeaderItem(9)
        item.setText(_translate("windowRefl", "qmax_2", None))
        item = self.tableMain.horizontalHeaderItem(10)
        item.setText(_translate("windowRefl", "Run(s)", None))
        item = self.tableMain.horizontalHeaderItem(11)
        item.setText(_translate("windowRefl", "Angle 3", None))
        item = self.tableMain.horizontalHeaderItem(12)
        item.setText(_translate("windowRefl", "trans 3", None))
        item = self.tableMain.horizontalHeaderItem(13)
        item.setText(_translate("windowRefl", "qmin_3", None))
        item = self.tableMain.horizontalHeaderItem(14)
        item.setText(_translate("windowRefl", "qmax_3", None))
        item = self.tableMain.horizontalHeaderItem(15)
        item.setText(_translate("windowRefl", "dq/q", None))
        item = self.tableMain.horizontalHeaderItem(16)
        item.setText(_translate("windowRefl", "Scale", None))
        item = self.tableMain.horizontalHeaderItem(17)
        item.setText(_translate("windowRefl", "Stitch?", None))
        item = self.tableMain.horizontalHeaderItem(18)
        item.setText(_translate("windowRefl", "Plot?", None))
        self.buttonProcess.setText(_translate("windowRefl", "Process", None))
        self.buttonClear.setText(_translate("windowRefl", "Clear all", None))
        self.menuFile.setTitle(_translate("windowRefl", "File", None))
        self.menuHelp.setTitle(_translate("windowRefl", "Help", None))
        self.menuFunction.setTitle(_translate("windowRefl", "Function", None))
        self.menuEdit.setTitle(_translate("windowRefl", "Edit", None))
        self.menuOptions.setTitle(_translate("windowRefl", "Options", None))
        self.actionSave_As.setText(_translate("windowRefl", "Save As...", None))
        self.actionSave_As.setShortcut(_translate("windowRefl", "Ctrl+Alt+S", None))
        self.actionOpen_Table.setText(_translate("windowRefl", "Open Table...", None))
        self.actionOpen_Table.setShortcut(_translate("windowRefl", "Ctrl+O", None))
        self.actionReload_from_Disk.setText(_translate("windowRefl", "Reload from Disk", None))
        self.actionReload_from_Disk.setShortcut(_translate("windowRefl", "Ctrl+R", None))
        self.actionSave_Workspaces.setText(_translate("windowRefl", "Save Workspaces", None))
        self.actionSave_Workspaces.setShortcut(_translate("windowRefl", "Ctrl+Shift+S", None))
        self.actionMantid_Help.setText(_translate("windowRefl", "Mantid Help", None))
        self.actionMantid_Help.setShortcut(_translate("windowRefl", "Ctrl+H", None))
        self.actionSave.setText(_translate("windowRefl", "Save", None))
        self.actionSave.setShortcut(_translate("windowRefl", "Ctrl+S", None))
        self.actionClose_Refl_Gui.setText(_translate("windowRefl", "Close Refl Gui", None))
        self.actionClose_Refl_Gui.setShortcut(_translate("windowRefl", "Ctrl+F4", None))
        self.actionAutofill.setText(_translate("windowRefl", "Autofill", None))
        self.actionAutofill.setShortcut(_translate("windowRefl", "Alt+A", None))
        self.actionProcess.setText(_translate("windowRefl", "Process", None))
        self.actionProcess.setShortcut(_translate("windowRefl", "Alt+P", None))
        self.actionTransfer.setText(_translate("windowRefl", "Transfer", None))
        self.actionTransfer.setShortcut(_translate("windowRefl", "Alt+T", None))
        self.actionClear_Table.setText(_translate("windowRefl", "Clear Table", None))
        self.actionClear_Table.setShortcut(_translate("windowRefl", "Alt+C", None))
        self.actionSearch_RB.setText(_translate("windowRefl", "Search RB", None))
        self.actionSearch_RB.setShortcut(_translate("windowRefl", "Alt+R", None))
        self.actionCopy.setText(_translate("windowRefl", "Copy", None))
        self.actionCopy.setShortcut(_translate("windowRefl", "Ctrl+C", None))
        self.actionPaste.setText(_translate("windowRefl", "Paste", None))
        self.actionPaste.setShortcut(_translate("windowRefl", "Ctrl+V", None))
        self.actionCut.setText(_translate("windowRefl", "Cut", None))
        self.actionCut.setShortcut(_translate("windowRefl", "Ctrl+X", None))
        self.actionClear.setText(_translate("windowRefl", "Clear", None))
        self.actionClear.setShortcut(_translate("windowRefl", "Del", None))
        self.actionChoose_Columns.setText(_translate("windowRefl", "Choose Columns...", None))
        self.actionChoose_Columns.setShortcut(_translate("windowRefl", "Ctrl+M", None))
        self.actionRefl_Gui_Options.setText(_translate("windowRefl", "Refl Gui Options...", None))
        self.actionRefl_Gui_Options.setShortcut(_translate("windowRefl", "Ctrl+Shift+O", None))
        self.actionSlit_Calculator.setText(_translate("windowRefl", "Slit Calculator", None))

