# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reflectometer/advanced.ui'
#
# Created: Tue Sep 20 06:53:33 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1125, 573)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_12 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.advanced_auto_cleanup_switch = QtGui.QCheckBox(self.groupBox)
        self.advanced_auto_cleanup_switch.setObjectName("advanced_auto_cleanup_switch")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_switch)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.advanced_auto_cleanup_percentage_label = QtGui.QLabel(self.groupBox)
        self.advanced_auto_cleanup_percentage_label.setEnabled(False)
        self.advanced_auto_cleanup_percentage_label.setObjectName("advanced_auto_cleanup_percentage_label")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_label)
        self.advanced_auto_cleanup_percentage_value = QtGui.QLineEdit(self.groupBox)
        self.advanced_auto_cleanup_percentage_value.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_auto_cleanup_percentage_value.sizePolicy().hasHeightForWidth())
        self.advanced_auto_cleanup_percentage_value.setSizePolicy(sizePolicy)
        self.advanced_auto_cleanup_percentage_value.setMinimumSize(QtCore.QSize(40, 0))
        self.advanced_auto_cleanup_percentage_value.setMaximumSize(QtCore.QSize(40, 16777215))
        self.advanced_auto_cleanup_percentage_value.setObjectName("advanced_auto_cleanup_percentage_value")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_value)
        self.advanced_auto_cleanup_percentage_label2 = QtGui.QLabel(self.groupBox)
        self.advanced_auto_cleanup_percentage_label2.setEnabled(False)
        self.advanced_auto_cleanup_percentage_label2.setObjectName("advanced_auto_cleanup_percentage_label2")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_label2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.advanced_overwrite_data_geometry_switch = QtGui.QCheckBox(self.groupBox_2)
        self.advanced_overwrite_data_geometry_switch.setMinimumSize(QtCore.QSize(200, 0))
        self.advanced_overwrite_data_geometry_switch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.advanced_overwrite_data_geometry_switch.setObjectName("advanced_overwrite_data_geometry_switch")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_geometry_switch)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.advanced_overwrite_data_button = QtGui.QPushButton(self.groupBox_2)
        self.advanced_overwrite_data_button.setEnabled(False)
        self.advanced_overwrite_data_button.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_data_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.advanced_overwrite_data_button.setObjectName("advanced_overwrite_data_button")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_button)
        self.advanced_overwrite_data_label = QtGui.QLabel(self.groupBox_2)
        self.advanced_overwrite_data_label.setEnabled(False)
        self.advanced_overwrite_data_label.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_data_label.setObjectName("advanced_overwrite_data_label")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.advanced_overwrite_norm_geometry_switch = QtGui.QCheckBox(self.groupBox_2)
        self.advanced_overwrite_norm_geometry_switch.setMinimumSize(QtCore.QSize(250, 0))
        self.advanced_overwrite_norm_geometry_switch.setMaximumSize(QtCore.QSize(250, 16777215))
        self.advanced_overwrite_norm_geometry_switch.setObjectName("advanced_overwrite_norm_geometry_switch")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_geometry_switch)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.advanced_overwrite_norm_button = QtGui.QPushButton(self.groupBox_2)
        self.advanced_overwrite_norm_button.setEnabled(False)
        self.advanced_overwrite_norm_button.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_norm_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.advanced_overwrite_norm_button.setObjectName("advanced_overwrite_norm_button")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_button)
        self.advanced_overwrite_norm_label = QtGui.QLabel(self.groupBox_2)
        self.advanced_overwrite_norm_label.setEnabled(False)
        self.advanced_overwrite_norm_label.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_norm_label.setObjectName("advanced_overwrite_norm_label")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.groupBox_3 = QtGui.QGroupBox(Frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_5.addWidget(self.checkBox_5)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_5.addWidget(self.checkBox_4)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_5.addWidget(self.checkBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_6.addWidget(self.checkBox_8)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_6.addWidget(self.checkBox_7)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_6.addWidget(self.checkBox_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_7.addWidget(self.checkBox_10)
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_7.addWidget(self.checkBox_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_8.addWidget(self.checkBox_12)
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_8.addWidget(self.checkBox_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Frame", "Filtering data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Frame", "dt/d", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_switch.setText(QtGui.QApplication.translate("Frame", "Auto cleanup of reduce data", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_percentage_label.setText(QtGui.QApplication.translate("Frame", "Percentage of Q to remove on both side", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_percentage_label2.setText(QtGui.QApplication.translate("Frame", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_geometry_switch.setText(QtGui.QApplication.translate("Frame", "Overwrite data geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_label.setText(QtGui.QApplication.translate("Frame", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_geometry_switch.setText(QtGui.QApplication.translate("Frame", "Overwrite normalization geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_label.setText(QtGui.QApplication.translate("Frame", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Intermediate files", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Frame", "Data combined background TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Frame", "Data combined specular TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Frame", "Data combined subtracted TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("Frame", "Normalization combined background TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Frame", "Normalization combined specular TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Frame", "Normalization combined subtracted TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("Frame", "R vs TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("Frame", "R vs TOF combined", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("Frame", "R vs Q", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("Frame", "R vs Q after rebinning", None, QtGui.QApplication.UnicodeUTF8))

