# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reflectometer/advanced.ui'
#
# Created: Thu Aug 18 12:24:05 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1140, 565)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_12 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.advanced_auto_cleanup_switch = QtGui.QRadioButton(self.groupBox)
        self.advanced_auto_cleanup_switch.setAutoExclusive(False)
        self.advanced_auto_cleanup_switch.setObjectName("advanced_auto_cleanup_switch")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_switch)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.advanced_auto_cleanup_percentage_label = QtGui.QLabel(self.groupBox)
        self.advanced_auto_cleanup_percentage_label.setEnabled(False)
        self.advanced_auto_cleanup_percentage_label.setObjectName("advanced_auto_cleanup_percentage_label")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_label)
        self.advanced_auto_cleanup_percentage_value = QtGui.QLineEdit(self.groupBox)
        self.advanced_auto_cleanup_percentage_value.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_auto_cleanup_percentage_value.sizePolicy().hasHeightForWidth())
        self.advanced_auto_cleanup_percentage_value.setSizePolicy(sizePolicy)
        self.advanced_auto_cleanup_percentage_value.setMinimumSize(QtCore.QSize(40, 0))
        self.advanced_auto_cleanup_percentage_value.setMaximumSize(QtCore.QSize(40, 16777215))
        self.advanced_auto_cleanup_percentage_value.setObjectName("advanced_auto_cleanup_percentage_value")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_value)
        self.advanced_auto_cleanup_percentage_label2 = QtGui.QLabel(self.groupBox)
        self.advanced_auto_cleanup_percentage_label2.setEnabled(False)
        self.advanced_auto_cleanup_percentage_label2.setObjectName("advanced_auto_cleanup_percentage_label2")
        self.horizontalLayout_8.addWidget(self.advanced_auto_cleanup_percentage_label2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.advanced_overwrite_data_geometry_switch = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_overwrite_data_geometry_switch.sizePolicy().hasHeightForWidth())
        self.advanced_overwrite_data_geometry_switch.setSizePolicy(sizePolicy)
        self.advanced_overwrite_data_geometry_switch.setAutoExclusive(False)
        self.advanced_overwrite_data_geometry_switch.setObjectName("advanced_overwrite_data_geometry_switch")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_geometry_switch)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.advanced_overwrite_data_button = QtGui.QPushButton(self.groupBox_2)
        self.advanced_overwrite_data_button.setEnabled(False)
        self.advanced_overwrite_data_button.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_data_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.advanced_overwrite_data_button.setObjectName("advanced_overwrite_data_button")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_button)
        self.advanced_overwrite_data_label = QtGui.QLabel(self.groupBox_2)
        self.advanced_overwrite_data_label.setEnabled(False)
        self.advanced_overwrite_data_label.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_data_label.setObjectName("advanced_overwrite_data_label")
        self.horizontalLayout_2.addWidget(self.advanced_overwrite_data_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.advanced_overwrite_norm_geometry_switch = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_overwrite_norm_geometry_switch.sizePolicy().hasHeightForWidth())
        self.advanced_overwrite_norm_geometry_switch.setSizePolicy(sizePolicy)
        self.advanced_overwrite_norm_geometry_switch.setAutoExclusive(False)
        self.advanced_overwrite_norm_geometry_switch.setObjectName("advanced_overwrite_norm_geometry_switch")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_geometry_switch)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.advanced_overwrite_norm_button = QtGui.QPushButton(self.groupBox_2)
        self.advanced_overwrite_norm_button.setEnabled(False)
        self.advanced_overwrite_norm_button.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_norm_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.advanced_overwrite_norm_button.setObjectName("advanced_overwrite_norm_button")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_button)
        self.advanced_overwrite_norm_label = QtGui.QLabel(self.groupBox_2)
        self.advanced_overwrite_norm_label.setEnabled(False)
        self.advanced_overwrite_norm_label.setMinimumSize(QtCore.QSize(100, 0))
        self.advanced_overwrite_norm_label.setObjectName("advanced_overwrite_norm_label")
        self.horizontalLayout_7.addWidget(self.advanced_overwrite_norm_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_5.addWidget(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_5.addWidget(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_5.addWidget(self.radioButton_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_6.addWidget(self.radioButton_10)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_6.addWidget(self.radioButton_9)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_6.addWidget(self.radioButton_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_7.addWidget(self.radioButton_12)
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_7.addWidget(self.radioButton_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_8.addWidget(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_8.addWidget(self.radioButton_15)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_11.addWidget(self.groupBox_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Frame", "Filtering data", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("Frame", "dt/d", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_switch.setText(QtGui.QApplication.translate("Frame", "Auto clenaup of reduce data", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_percentage_label.setText(QtGui.QApplication.translate("Frame", "Percentage of Q to remove on both side", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_auto_cleanup_percentage_label2.setText(QtGui.QApplication.translate("Frame", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_geometry_switch.setText(QtGui.QApplication.translate("Frame", "Overwrite data geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_data_label.setText(QtGui.QApplication.translate("Frame", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_geometry_switch.setText(QtGui.QApplication.translate("Frame", "Overwrite normalization geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_overwrite_norm_label.setText(QtGui.QApplication.translate("Frame", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Intermediate files", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("Frame", "Data combined specular TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("Frame", "Data combined background TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_8.setText(QtGui.QApplication.translate("Frame", "Data combined subtracted TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("Frame", "Normalization combined specular TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_9.setText(QtGui.QApplication.translate("Frame", "Normalization combined background TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("Frame", "Normalization combined subtracted TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_12.setText(QtGui.QApplication.translate("Frame", "R vs TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_13.setText(QtGui.QApplication.translate("Frame", "R vs TOF combined", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_14.setText(QtGui.QApplication.translate("Frame", "R vs Q", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("Frame", "R vs Q after rebinning", None, QtGui.QApplication.UnicodeUTF8))

