# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reflectometer/data_refl.ui'
#
# Created: Thu Jan 19 13:45:55 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1221, 587)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_load_nexus_button = QtGui.QPushButton(Frame)
        self.data_load_nexus_button.setObjectName("data_load_nexus_button")
        self.horizontalLayout_5.addWidget(self.data_load_nexus_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtGui.QTableWidget(Frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(Frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.data_peak_narrow_switch = QtGui.QRadioButton(self.groupBox)
        self.data_peak_narrow_switch.setEnabled(True)
        self.data_peak_narrow_switch.setChecked(True)
        self.data_peak_narrow_switch.setAutoExclusive(True)
        self.data_peak_narrow_switch.setObjectName("data_peak_narrow_switch")
        self.horizontalLayout_2.addWidget(self.data_peak_narrow_switch)
        self.data_peak_broad_switch = QtGui.QRadioButton(self.groupBox)
        self.data_peak_broad_switch.setAutoExclusive(True)
        self.data_peak_broad_switch.setObjectName("data_peak_broad_switch")
        self.horizontalLayout_2.addWidget(self.data_peak_broad_switch)
        self.data_peak_discrete_switch = QtGui.QRadioButton(self.groupBox)
        self.data_peak_discrete_switch.setEnabled(True)
        self.data_peak_discrete_switch.setCheckable(True)
        self.data_peak_discrete_switch.setChecked(False)
        self.data_peak_discrete_switch.setObjectName("data_peak_discrete_switch")
        self.horizontalLayout_2.addWidget(self.data_peak_discrete_switch)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.data_peak_load_roi = QtGui.QPushButton(self.groupBox)
        self.data_peak_load_roi.setObjectName("data_peak_load_roi")
        self.horizontalLayout_2.addWidget(self.data_peak_load_roi)
        self.data_peak_save_roi = QtGui.QPushButton(self.groupBox)
        self.data_peak_save_roi.setEnabled(False)
        self.data_peak_save_roi.setObjectName("data_peak_save_roi")
        self.horizontalLayout_2.addWidget(self.data_peak_save_roi)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.data_peak_from_pixel_label = QtGui.QLabel(self.groupBox)
        self.data_peak_from_pixel_label.setObjectName("data_peak_from_pixel_label")
        self.horizontalLayout_3.addWidget(self.data_peak_from_pixel_label)
        self.data_peak_from_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_from_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_from_pixel.setObjectName("data_peak_from_pixel")
        self.horizontalLayout_3.addWidget(self.data_peak_from_pixel)
        self.data_peak_from_pixel_missing = QtGui.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.data_peak_from_pixel_missing.setPalette(palette)
        self.data_peak_from_pixel_missing.setObjectName("data_peak_from_pixel_missing")
        self.horizontalLayout_3.addWidget(self.data_peak_from_pixel_missing)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.data_peak_to_pixel_label = QtGui.QLabel(self.groupBox)
        self.data_peak_to_pixel_label.setObjectName("data_peak_to_pixel_label")
        self.horizontalLayout_3.addWidget(self.data_peak_to_pixel_label)
        self.data_peak_to_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_to_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_to_pixel.setSizePolicy(sizePolicy)
        self.data_peak_to_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_to_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_to_pixel.setObjectName("data_peak_to_pixel")
        self.horizontalLayout_3.addWidget(self.data_peak_to_pixel)
        self.data_peak_to_pixel_missing = QtGui.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_peak_to_pixel_missing.setPalette(palette)
        self.data_peak_to_pixel_missing.setObjectName("data_peak_to_pixel_missing")
        self.horizontalLayout_3.addWidget(self.data_peak_to_pixel_missing)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.data_peak_nbr_selection_label = QtGui.QLabel(self.groupBox)
        self.data_peak_nbr_selection_label.setEnabled(False)
        self.data_peak_nbr_selection_label.setMinimumSize(QtCore.QSize(210, 0))
        self.data_peak_nbr_selection_label.setMaximumSize(QtCore.QSize(210, 16777215))
        self.data_peak_nbr_selection_label.setObjectName("data_peak_nbr_selection_label")
        self.horizontalLayout_6.addWidget(self.data_peak_nbr_selection_label)
        self.data_peak_discrete_selection_missing = QtGui.QLabel(self.groupBox)
        self.data_peak_discrete_selection_missing.setMinimumSize(QtCore.QSize(10, 0))
        self.data_peak_discrete_selection_missing.setMaximumSize(QtCore.QSize(10, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_peak_discrete_selection_missing.setPalette(palette)
        self.data_peak_discrete_selection_missing.setText("")
        self.data_peak_discrete_selection_missing.setObjectName("data_peak_discrete_selection_missing")
        self.horizontalLayout_6.addWidget(self.data_peak_discrete_selection_missing)
        self.data_peak_nbr_selection_value = QtGui.QLabel(self.groupBox)
        self.data_peak_nbr_selection_value.setEnabled(False)
        self.data_peak_nbr_selection_value.setObjectName("data_peak_nbr_selection_value")
        self.horizontalLayout_6.addWidget(self.data_peak_nbr_selection_value)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.data_background_switch = QtGui.QCheckBox(Frame)
        self.data_background_switch.setObjectName("data_background_switch")
        self.horizontalLayout_8.addWidget(self.data_background_switch)
        spacerItem7 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.data_background_from_pixel1_label = QtGui.QLabel(Frame)
        self.data_background_from_pixel1_label.setEnabled(False)
        self.data_background_from_pixel1_label.setObjectName("data_background_from_pixel1_label")
        self.horizontalLayout_12.addWidget(self.data_background_from_pixel1_label)
        self.data_background_from_pixel1 = QtGui.QLineEdit(Frame)
        self.data_background_from_pixel1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel1.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel1.setSizePolicy(sizePolicy)
        self.data_background_from_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_from_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_from_pixel1.setBaseSize(QtCore.QSize(0, 0))
        self.data_background_from_pixel1.setObjectName("data_background_from_pixel1")
        self.horizontalLayout_12.addWidget(self.data_background_from_pixel1)
        self.data_background_from_pixel_missing = QtGui.QLabel(Frame)
        self.data_background_from_pixel_missing.setMinimumSize(QtCore.QSize(10, 0))
        self.data_background_from_pixel_missing.setMaximumSize(QtCore.QSize(10, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_background_from_pixel_missing.setPalette(palette)
        self.data_background_from_pixel_missing.setText("")
        self.data_background_from_pixel_missing.setObjectName("data_background_from_pixel_missing")
        self.horizontalLayout_12.addWidget(self.data_background_from_pixel_missing)
        spacerItem8 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.data_background_to_pixel1_label = QtGui.QLabel(Frame)
        self.data_background_to_pixel1_label.setEnabled(False)
        self.data_background_to_pixel1_label.setObjectName("data_background_to_pixel1_label")
        self.horizontalLayout_12.addWidget(self.data_background_to_pixel1_label)
        self.data_background_to_pixel1 = QtGui.QLineEdit(Frame)
        self.data_background_to_pixel1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel1.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel1.setSizePolicy(sizePolicy)
        self.data_background_to_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_to_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_to_pixel1.setObjectName("data_background_to_pixel1")
        self.horizontalLayout_12.addWidget(self.data_background_to_pixel1)
        self.data_background_to_pixel_missing = QtGui.QLabel(Frame)
        self.data_background_to_pixel_missing.setMinimumSize(QtCore.QSize(10, 0))
        self.data_background_to_pixel_missing.setMaximumSize(QtCore.QSize(10, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_background_to_pixel_missing.setPalette(palette)
        self.data_background_to_pixel_missing.setText("")
        self.data_background_to_pixel_missing.setObjectName("data_background_to_pixel_missing")
        self.horizontalLayout_12.addWidget(self.data_background_to_pixel_missing)
        spacerItem9 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.data_background_from_pixel2_label = QtGui.QLabel(Frame)
        self.data_background_from_pixel2_label.setEnabled(False)
        self.data_background_from_pixel2_label.setObjectName("data_background_from_pixel2_label")
        self.horizontalLayout_13.addWidget(self.data_background_from_pixel2_label)
        self.data_background_from_pixel2 = QtGui.QLineEdit(Frame)
        self.data_background_from_pixel2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel2.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel2.setSizePolicy(sizePolicy)
        self.data_background_from_pixel2.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_from_pixel2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_from_pixel2.setBaseSize(QtCore.QSize(0, 0))
        self.data_background_from_pixel2.setObjectName("data_background_from_pixel2")
        self.horizontalLayout_13.addWidget(self.data_background_from_pixel2)
        self.data_background_from_pixel_missing_2 = QtGui.QLabel(Frame)
        self.data_background_from_pixel_missing_2.setMinimumSize(QtCore.QSize(10, 0))
        self.data_background_from_pixel_missing_2.setMaximumSize(QtCore.QSize(10, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_background_from_pixel_missing_2.setPalette(palette)
        self.data_background_from_pixel_missing_2.setText("")
        self.data_background_from_pixel_missing_2.setObjectName("data_background_from_pixel_missing_2")
        self.horizontalLayout_13.addWidget(self.data_background_from_pixel_missing_2)
        spacerItem10 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.data_background_to_pixel2_label = QtGui.QLabel(Frame)
        self.data_background_to_pixel2_label.setEnabled(False)
        self.data_background_to_pixel2_label.setObjectName("data_background_to_pixel2_label")
        self.horizontalLayout_13.addWidget(self.data_background_to_pixel2_label)
        self.data_background_to_pixel2 = QtGui.QLineEdit(Frame)
        self.data_background_to_pixel2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel2.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel2.setSizePolicy(sizePolicy)
        self.data_background_to_pixel2.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_to_pixel2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_to_pixel2.setObjectName("data_background_to_pixel2")
        self.horizontalLayout_13.addWidget(self.data_background_to_pixel2)
        self.data_background_to_pixel_missing_2 = QtGui.QLabel(Frame)
        self.data_background_to_pixel_missing_2.setMinimumSize(QtCore.QSize(10, 0))
        self.data_background_to_pixel_missing_2.setMaximumSize(QtCore.QSize(10, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_background_to_pixel_missing_2.setPalette(palette)
        self.data_background_to_pixel_missing_2.setText("")
        self.data_background_to_pixel_missing_2.setObjectName("data_background_to_pixel_missing_2")
        self.horizontalLayout_13.addWidget(self.data_background_to_pixel_missing_2)
        spacerItem11 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.data_background_load_button = QtGui.QPushButton(Frame)
        self.data_background_load_button.setEnabled(False)
        self.data_background_load_button.setObjectName("data_background_load_button")
        self.horizontalLayout_8.addWidget(self.data_background_load_button)
        self.data_background_save_button = QtGui.QPushButton(Frame)
        self.data_background_save_button.setEnabled(False)
        self.data_background_save_button.setObjectName("data_background_save_button")
        self.horizontalLayout_8.addWidget(self.data_background_save_button)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.groupBox_2 = QtGui.QGroupBox(Frame)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.data_from_tof = QtGui.QLineEdit(self.groupBox_2)
        self.data_from_tof.setObjectName("data_from_tof")
        self.horizontalLayout_9.addWidget(self.data_from_tof)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.data_to_tof = QtGui.QLineEdit(self.groupBox_2)
        self.data_to_tof.setObjectName("data_to_tof")
        self.horizontalLayout_9.addWidget(self.data_to_tof)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_5 = QtGui.QPushButton(Frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_7 = QtGui.QPushButton(Frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_12 = QtGui.QPushButton(Frame)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.data_load_nexus_button.setText(QtGui.QApplication.translate("Frame", "Load data ...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Peak Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Selection type:", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_narrow_switch.setText(QtGui.QApplication.translate("Frame", "Narrow ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_broad_switch.setText(QtGui.QApplication.translate("Frame", "Broad", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_discrete_switch.setText(QtGui.QApplication.translate("Frame", "Discrete", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_load_roi.setText(QtGui.QApplication.translate("Frame", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_save_roi.setText(QtGui.QApplication.translate("Frame", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel_label.setText(QtGui.QApplication.translate("Frame", "From pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel_missing.setText(QtGui.QApplication.translate("Frame", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel_label.setText(QtGui.QApplication.translate("Frame", "   To pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel_missing.setText(QtGui.QApplication.translate("Frame", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_nbr_selection_label.setText(QtGui.QApplication.translate("Frame", "Number of discrete selection(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_nbr_selection_value.setText(QtGui.QApplication.translate("Frame", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_switch.setText(QtGui.QApplication.translate("Frame", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel1_label.setText(QtGui.QApplication.translate("Frame", "ROI #1:     From pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel1_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel2_label.setText(QtGui.QApplication.translate("Frame", "ROI #2:     From pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel2_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_load_button.setText(QtGui.QApplication.translate("Frame", "Load...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_save_button.setText(QtGui.QApplication.translate("Frame", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "From TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "microS     to     TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "microS", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Frame", "TOF Selection tool", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Frame", "2D Pixels vs TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Frame", "2D Pixels Y vs Pixels X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixels Y", None, QtGui.QApplication.UnicodeUTF8))

