# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reflectometer/parameters_refl.ui'
#
# Created: Thu Aug 18 13:12:20 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1003, 426)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtGui.QGroupBox(Frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.parameters_q_range_automatic_switch = QtGui.QRadioButton(self.groupBox_4)
        self.parameters_q_range_automatic_switch.setChecked(True)
        self.parameters_q_range_automatic_switch.setAutoExclusive(False)
        self.parameters_q_range_automatic_switch.setObjectName("parameters_q_range_automatic_switch")
        self.horizontalLayout_4.addWidget(self.parameters_q_range_automatic_switch)
        self.parameters_q_range_manual_switch = QtGui.QRadioButton(self.groupBox_4)
        self.parameters_q_range_manual_switch.setAutoExclusive(False)
        self.parameters_q_range_manual_switch.setObjectName("parameters_q_range_manual_switch")
        self.horizontalLayout_4.addWidget(self.parameters_q_range_manual_switch)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.parameters_q_range_from_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_from_label.setEnabled(False)
        self.parameters_q_range_from_label.setMinimumSize(QtCore.QSize(50, 0))
        self.parameters_q_range_from_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.parameters_q_range_from_label.setObjectName("parameters_q_range_from_label")
        self.horizontalLayout_12.addWidget(self.parameters_q_range_from_label)
        self.parameters_q_range_from_value = QtGui.QLineEdit(self.groupBox_4)
        self.parameters_q_range_from_value.setEnabled(False)
        self.parameters_q_range_from_value.setMinimumSize(QtCore.QSize(100, 0))
        self.parameters_q_range_from_value.setObjectName("parameters_q_range_from_value")
        self.horizontalLayout_12.addWidget(self.parameters_q_range_from_value)
        self.parameters_q_range_from_unit_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_from_unit_label.setEnabled(False)
        self.parameters_q_range_from_unit_label.setMinimumSize(QtCore.QSize(80, 0))
        self.parameters_q_range_from_unit_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.parameters_q_range_from_unit_label.setObjectName("parameters_q_range_from_unit_label")
        self.horizontalLayout_12.addWidget(self.parameters_q_range_from_unit_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.parameters_q_range_to_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_to_label.setEnabled(False)
        self.parameters_q_range_to_label.setMinimumSize(QtCore.QSize(50, 0))
        self.parameters_q_range_to_label.setObjectName("parameters_q_range_to_label")
        self.horizontalLayout_13.addWidget(self.parameters_q_range_to_label)
        self.parameters_q_range_to_value = QtGui.QLineEdit(self.groupBox_4)
        self.parameters_q_range_to_value.setEnabled(False)
        self.parameters_q_range_to_value.setMinimumSize(QtCore.QSize(100, 0))
        self.parameters_q_range_to_value.setObjectName("parameters_q_range_to_value")
        self.horizontalLayout_13.addWidget(self.parameters_q_range_to_value)
        self.parameters_q_range_to_unit_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_to_unit_label.setEnabled(False)
        self.parameters_q_range_to_unit_label.setMinimumSize(QtCore.QSize(80, 0))
        self.parameters_q_range_to_unit_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.parameters_q_range_to_unit_label.setObjectName("parameters_q_range_to_unit_label")
        self.horizontalLayout_13.addWidget(self.parameters_q_range_to_unit_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.parameters_q_range_nbr_bins_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_nbr_bins_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_q_range_nbr_bins_label.sizePolicy().hasHeightForWidth())
        self.parameters_q_range_nbr_bins_label.setSizePolicy(sizePolicy)
        self.parameters_q_range_nbr_bins_label.setMinimumSize(QtCore.QSize(60, 0))
        self.parameters_q_range_nbr_bins_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.parameters_q_range_nbr_bins_label.setObjectName("parameters_q_range_nbr_bins_label")
        self.horizontalLayout_14.addWidget(self.parameters_q_range_nbr_bins_label)
        self.parameters_q_range_nbr_bins_value = QtGui.QLineEdit(self.groupBox_4)
        self.parameters_q_range_nbr_bins_value.setEnabled(False)
        self.parameters_q_range_nbr_bins_value.setMinimumSize(QtCore.QSize(100, 0))
        self.parameters_q_range_nbr_bins_value.setObjectName("parameters_q_range_nbr_bins_value")
        self.horizontalLayout_14.addWidget(self.parameters_q_range_nbr_bins_value)
        spacerItem1 = QtGui.QSpacerItem(140, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.parameters_q_range_or_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_or_label.setEnabled(False)
        self.parameters_q_range_or_label.setAlignment(QtCore.Qt.AlignCenter)
        self.parameters_q_range_or_label.setObjectName("parameters_q_range_or_label")
        self.verticalLayout_6.addWidget(self.parameters_q_range_or_label)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.parameters_q_range_bin_size_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_bin_size_label.setEnabled(False)
        self.parameters_q_range_bin_size_label.setMinimumSize(QtCore.QSize(60, 0))
        self.parameters_q_range_bin_size_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.parameters_q_range_bin_size_label.setObjectName("parameters_q_range_bin_size_label")
        self.horizontalLayout_15.addWidget(self.parameters_q_range_bin_size_label)
        self.parameters_q_range_bin_size_value = QtGui.QLineEdit(self.groupBox_4)
        self.parameters_q_range_bin_size_value.setEnabled(False)
        self.parameters_q_range_bin_size_value.setMinimumSize(QtCore.QSize(100, 0))
        self.parameters_q_range_bin_size_value.setObjectName("parameters_q_range_bin_size_value")
        self.horizontalLayout_15.addWidget(self.parameters_q_range_bin_size_value)
        self.parameters_q_range_bin_size_unit_label = QtGui.QLabel(self.groupBox_4)
        self.parameters_q_range_bin_size_unit_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_q_range_bin_size_unit_label.sizePolicy().hasHeightForWidth())
        self.parameters_q_range_bin_size_unit_label.setSizePolicy(sizePolicy)
        self.parameters_q_range_bin_size_unit_label.setMinimumSize(QtCore.QSize(80, 0))
        self.parameters_q_range_bin_size_unit_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.parameters_q_range_bin_size_unit_label.setObjectName("parameters_q_range_bin_size_unit_label")
        self.horizontalLayout_15.addWidget(self.parameters_q_range_bin_size_unit_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.parameters_q_range_linear_switch = QtGui.QRadioButton(self.groupBox_4)
        self.parameters_q_range_linear_switch.setEnabled(False)
        self.parameters_q_range_linear_switch.setChecked(True)
        self.parameters_q_range_linear_switch.setAutoExclusive(False)
        self.parameters_q_range_linear_switch.setObjectName("parameters_q_range_linear_switch")
        self.verticalLayout_7.addWidget(self.parameters_q_range_linear_switch)
        self.parameters_q_range_log_switch = QtGui.QRadioButton(self.groupBox_4)
        self.parameters_q_range_log_switch.setEnabled(False)
        self.parameters_q_range_log_switch.setAutoExclusive(False)
        self.parameters_q_range_log_switch.setObjectName("parameters_q_range_log_switch")
        self.verticalLayout_7.addWidget(self.parameters_q_range_log_switch)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setMaximumSize(QtCore.QSize(270, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Q range", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_automatic_switch.setText(QtGui.QApplication.translate("Frame", "Automatic         ", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_manual_switch.setText(QtGui.QApplication.translate("Frame", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_from_label.setText(QtGui.QApplication.translate("Frame", "    from", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_from_unit_label.setText(QtGui.QApplication.translate("Frame", "Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_to_label.setText(QtGui.QApplication.translate("Frame", "        to", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_to_unit_label.setText(QtGui.QApplication.translate("Frame", "Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_nbr_bins_label.setText(QtGui.QApplication.translate("Frame", "Nbr bins", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_or_label.setText(QtGui.QApplication.translate("Frame", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_bin_size_label.setText(QtGui.QApplication.translate("Frame", "bin size", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_bin_size_unit_label.setText(QtGui.QApplication.translate("Frame", "Angstroms        ", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_linear_switch.setText(QtGui.QApplication.translate("Frame", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_q_range_log_switch.setText(QtGui.QApplication.translate("Frame", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Frame", "Output file name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Frame", "~/results/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "File name", None, QtGui.QApplication.UnicodeUTF8))

