# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/reflectometer/parameters_refl.ui'
#
# Created: Thu Aug 18 06:21:45 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(910, 306)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtGui.QGroupBox(Frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 211, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_10 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_4.addWidget(self.radioButton_11)
        self.widget = QtGui.QWidget(self.groupBox_4)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(220, 30, 861, 101))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 207, 84))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_2)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_13.addWidget(self.lineEdit_7)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.layoutWidget_2 = QtGui.QWidget(self.widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(230, 10, 331, 84))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_16 = QtGui.QLabel(self.layoutWidget_2)
        self.label_16.setEnabled(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_14.addWidget(self.lineEdit_8)
        spacerItem = QtGui.QSpacerItem(140, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.label_17 = QtGui.QLabel(self.layoutWidget_2)
        self.label_17.setEnabled(True)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtGui.QLabel(self.layoutWidget_2)
        self.label_18.setEnabled(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_15.addWidget(self.lineEdit_4)
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        self.label_19.setEnabled(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(570, 10, 66, 86))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_14 = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_7.addWidget(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_7.addWidget(self.radioButton_15)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.label_2.setMaximumSize(QtCore.QSize(270, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtGui.QPushButton(self.groupBox_5)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(110, 30, 731, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.label_3.setMaximumSize(QtCore.QSize(270, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(120, 70, 711, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Q range", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_10.setText(QtGui.QApplication.translate("Frame", "Automatic         ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_11.setText(QtGui.QApplication.translate("Frame", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "    from", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame", "Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "        to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Angstroms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "             Nbr bins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "or", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "              bin size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Frame", "Angstroms        ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_14.setText(QtGui.QApplication.translate("Frame", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_15.setText(QtGui.QApplication.translate("Frame", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Frame", "Output file name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Frame", "~/results/", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "File name", None, QtGui.QApplication.UnicodeUTF8))

