#pylint: disable=invalid-name
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refl_sf_calculator.ui'
#
# Created: Wed May 30 07:01:51 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1037, 923)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 998, 930))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setMinimumSize(QtCore.QSize(0, 16))
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.waiting_label = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.waiting_label.setFont(font)
        self.waiting_label.setObjectName("waiting_label")
        self.verticalLayout_6.addWidget(self.waiting_label)
        self.angle_list = QtGui.QListWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_list.sizePolicy().hasHeightForWidth())
        self.angle_list.setSizePolicy(sizePolicy)
        self.angle_list.setMinimumSize(QtCore.QSize(200, 0))
        self.angle_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.angle_list.setDragEnabled(True)
        self.angle_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.angle_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.angle_list.setAlternatingRowColors(True)
        self.angle_list.setObjectName("angle_list")
        self.verticalLayout_6.addWidget(self.angle_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.remove_btn = QtGui.QPushButton(self.groupBox_3)
        self.remove_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.remove_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout_12.addWidget(self.remove_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setMinimumSize(QtCore.QSize(150, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.incident_medium_combobox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incident_medium_combobox.sizePolicy().hasHeightForWidth())
        self.incident_medium_combobox.setSizePolicy(sizePolicy)
        self.incident_medium_combobox.setMinimumSize(QtCore.QSize(200, 0))
        self.incident_medium_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.incident_medium_combobox.setEditable(True)
        self.incident_medium_combobox.setObjectName("incident_medium_combobox")
        self.incident_medium_combobox.addItem("")
        self.incident_medium_combobox.addItem("")
        self.incident_medium_combobox.addItem("")
        self.horizontalLayout_13.addWidget(self.incident_medium_combobox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setMinimumSize(QtCore.QSize(60, 0))
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.tof_min = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tof_min.setMinimumSize(QtCore.QSize(150, 0))
        self.tof_min.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tof_min.setObjectName("tof_min")
        self.horizontalLayout_14.addWidget(self.tof_min)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setMinimumSize(QtCore.QSize(60, 0))
        self.label_18.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.tof_max = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tof_max.setMinimumSize(QtCore.QSize(150, 0))
        self.tof_max.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tof_max.setObjectName("tof_max")
        self.horizontalLayout_14.addWidget(self.tof_max)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.plot_counts_vs_tof_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.plot_counts_vs_tof_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_counts_vs_tof_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_counts_vs_tof_btn.setObjectName("plot_counts_vs_tof_btn")
        self.horizontalLayout_14.addWidget(self.plot_counts_vs_tof_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.data_run_number_edit = QtGui.QLineEdit(self.groupBox)
        self.data_run_number_edit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.data_run_number_edit.setObjectName("data_run_number_edit")
        self.horizontalLayout.addWidget(self.data_run_number_edit)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.data_run_number_processing = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.data_run_number_processing.setFont(font)
        self.data_run_number_processing.setObjectName("data_run_number_processing")
        self.horizontalLayout.addWidget(self.data_run_number_processing)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_5.setSizeIncrement(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.number_of_attenuator = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_of_attenuator.sizePolicy().hasHeightForWidth())
        self.number_of_attenuator.setSizePolicy(sizePolicy)
        self.number_of_attenuator.setMinimumSize(QtCore.QSize(50, 0))
        self.number_of_attenuator.setMaximumSize(QtCore.QSize(50, 16777215))
        self.number_of_attenuator.setObjectName("number_of_attenuator")
        self.horizontalLayout_4.addWidget(self.number_of_attenuator)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.data_peak_from_pixel_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel_label.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_peak_from_pixel_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_peak_from_pixel_label.setIndent(0)
        self.data_peak_from_pixel_label.setObjectName("data_peak_from_pixel_label")
        self.horizontalLayout_3.addWidget(self.data_peak_from_pixel_label)
        self.data_peak_from_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_from_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_from_pixel.setObjectName("data_peak_from_pixel")
        self.horizontalLayout_3.addWidget(self.data_peak_from_pixel)
        self.data_peak_to_pixel_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_to_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_peak_to_pixel_label.setSizePolicy(sizePolicy)
        self.data_peak_to_pixel_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_peak_to_pixel_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_peak_to_pixel_label.setObjectName("data_peak_to_pixel_label")
        self.horizontalLayout_3.addWidget(self.data_peak_to_pixel_label)
        self.data_peak_to_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_to_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_to_pixel.setSizePolicy(sizePolicy)
        self.data_peak_to_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_to_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_to_pixel.setObjectName("data_peak_to_pixel")
        self.horizontalLayout_3.addWidget(self.data_peak_to_pixel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.plot_count_vs_y_btn = QtGui.QPushButton(self.groupBox)
        self.plot_count_vs_y_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_count_vs_y_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_count_vs_y_btn.setObjectName("plot_count_vs_y_btn")
        self.horizontalLayout_3.addWidget(self.plot_count_vs_y_btn)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(150, 0))
        self.label_14.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_14.setIndent(0)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.data_background_from_pixel_label = QtGui.QLabel(self.groupBox)
        self.data_background_from_pixel_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel_label.setSizePolicy(sizePolicy)
        self.data_background_from_pixel_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_background_from_pixel_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_background_from_pixel_label.setIndent(0)
        self.data_background_from_pixel_label.setObjectName("data_background_from_pixel_label")
        self.horizontalLayout_8.addWidget(self.data_background_from_pixel_label)
        self.data_background_from_pixel = QtGui.QLineEdit(self.groupBox)
        self.data_background_from_pixel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel.setSizePolicy(sizePolicy)
        self.data_background_from_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_from_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_from_pixel.setBaseSize(QtCore.QSize(0, 0))
        self.data_background_from_pixel.setObjectName("data_background_from_pixel")
        self.horizontalLayout_8.addWidget(self.data_background_from_pixel)
        self.data_background_to_pixel_label = QtGui.QLabel(self.groupBox)
        self.data_background_to_pixel_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel_label.setSizePolicy(sizePolicy)
        self.data_background_to_pixel_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_background_to_pixel_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_background_to_pixel_label.setObjectName("data_background_to_pixel_label")
        self.horizontalLayout_8.addWidget(self.data_background_to_pixel_label)
        self.data_background_to_pixel = QtGui.QLineEdit(self.groupBox)
        self.data_background_to_pixel.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel.setSizePolicy(sizePolicy)
        self.data_background_to_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_to_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_to_pixel.setObjectName("data_background_to_pixel")
        self.horizontalLayout_8.addWidget(self.data_background_to_pixel)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.plot_count_vs_y_bck_btn = QtGui.QPushButton(self.groupBox)
        self.plot_count_vs_y_bck_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_count_vs_y_bck_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_count_vs_y_bck_btn.setObjectName("plot_count_vs_y_bck_btn")
        self.horizontalLayout_8.addWidget(self.plot_count_vs_y_bck_btn)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setMinimumSize(QtCore.QSize(150, 0))
        self.label_22.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_22.setSizeIncrement(QtCore.QSize(150, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.lambda_request = QtGui.QLabel(self.groupBox_2)
        self.lambda_request.setMinimumSize(QtCore.QSize(100, 0))
        self.lambda_request.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lambda_request.setText("")
        self.lambda_request.setObjectName("lambda_request")
        self.horizontalLayout_18.addWidget(self.lambda_request)
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setMinimumSize(QtCore.QSize(50, 0))
        self.label_23.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_23.setTextFormat(QtCore.Qt.RichText)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setMinimumSize(QtCore.QSize(70, 0))
        self.label_24.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.s1h = QtGui.QLabel(self.groupBox_2)
        self.s1h.setMinimumSize(QtCore.QSize(100, 0))
        self.s1h.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1h.setText("")
        self.s1h.setAlignment(QtCore.Qt.AlignCenter)
        self.s1h.setObjectName("s1h")
        self.horizontalLayout_21.addWidget(self.s1h)
        self.det_angle_unit_label = QtGui.QLabel(self.groupBox_2)
        self.det_angle_unit_label.setMinimumSize(QtCore.QSize(150, 0))
        self.det_angle_unit_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.det_angle_unit_label.setObjectName("det_angle_unit_label")
        self.horizontalLayout_21.addWidget(self.det_angle_unit_label)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setMinimumSize(QtCore.QSize(70, 0))
        self.label_25.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.s2h = QtGui.QLabel(self.groupBox_2)
        self.s2h.setMinimumSize(QtCore.QSize(100, 0))
        self.s2h.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s2h.setText("")
        self.s2h.setAlignment(QtCore.Qt.AlignCenter)
        self.s2h.setObjectName("s2h")
        self.horizontalLayout_21.addWidget(self.s2h)
        self.det_angle_unit_label_2 = QtGui.QLabel(self.groupBox_2)
        self.det_angle_unit_label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.det_angle_unit_label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.det_angle_unit_label_2.setObjectName("det_angle_unit_label_2")
        self.horizontalLayout_21.addWidget(self.det_angle_unit_label_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setMinimumSize(QtCore.QSize(70, 0))
        self.label_26.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_23.addWidget(self.label_26)
        self.s1w = QtGui.QLabel(self.groupBox_2)
        self.s1w.setMinimumSize(QtCore.QSize(100, 0))
        self.s1w.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s1w.setText("")
        self.s1w.setAlignment(QtCore.Qt.AlignCenter)
        self.s1w.setObjectName("s1w")
        self.horizontalLayout_23.addWidget(self.s1w)
        self.det_angle_unit_label_7 = QtGui.QLabel(self.groupBox_2)
        self.det_angle_unit_label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.det_angle_unit_label_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.det_angle_unit_label_7.setObjectName("det_angle_unit_label_7")
        self.horizontalLayout_23.addWidget(self.det_angle_unit_label_7)
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setMinimumSize(QtCore.QSize(70, 0))
        self.label_27.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_23.addWidget(self.label_27)
        self.s2w = QtGui.QLabel(self.groupBox_2)
        self.s2w.setMinimumSize(QtCore.QSize(100, 0))
        self.s2w.setMaximumSize(QtCore.QSize(100, 16777215))
        self.s2w.setText("")
        self.s2w.setAlignment(QtCore.Qt.AlignCenter)
        self.s2w.setObjectName("s2w")
        self.horizontalLayout_23.addWidget(self.s2w)
        self.det_angle_unit_label_3 = QtGui.QLabel(self.groupBox_2)
        self.det_angle_unit_label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.det_angle_unit_label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.det_angle_unit_label_3.setObjectName("det_angle_unit_label_3")
        self.horizontalLayout_23.addWidget(self.det_angle_unit_label_3)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.edited_warning_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.edited_warning_label.setTextFormat(QtCore.Qt.RichText)
        self.edited_warning_label.setObjectName("edited_warning_label")
        self.horizontalLayout_7.addWidget(self.edited_warning_label)
        self.add_dataset_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.add_dataset_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.add_dataset_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.add_dataset_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.add_dataset_btn.setFont(font)
        self.add_dataset_btn.setObjectName("add_dataset_btn")
        self.horizontalLayout_7.addWidget(self.add_dataset_btn)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        spacerItem15 = QtGui.QSpacerItem(9, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(170, 0))
        self.label_11.setMaximumSize(QtCore.QSize(170, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.cfg_scaling_factor_file_name = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.cfg_scaling_factor_file_name.setText("")
        self.cfg_scaling_factor_file_name.setObjectName("cfg_scaling_factor_file_name")
        self.horizontalLayout_9.addWidget(self.cfg_scaling_factor_file_name)
        self.cfg_scaling_factor_file_name_browse = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.cfg_scaling_factor_file_name_browse.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cfg_scaling_factor_file_name_browse.setSizeIncrement(QtCore.QSize(80, 0))
        self.cfg_scaling_factor_file_name_browse.setObjectName("cfg_scaling_factor_file_name_browse")
        self.horizontalLayout_9.addWidget(self.cfg_scaling_factor_file_name_browse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.textBrowser = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 350))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.cfg_scaling_factor_file_name_refresh = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.cfg_scaling_factor_file_name_refresh.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cfg_scaling_factor_file_name_refresh.setSizeIncrement(QtCore.QSize(80, 0))
        self.cfg_scaling_factor_file_name_refresh.setObjectName("cfg_scaling_factor_file_name_refresh")
        self.horizontalLayout_10.addWidget(self.cfg_scaling_factor_file_name_refresh)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem17 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem17)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Angle List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "List of direct beam scans for absolute normalization", None, QtGui.QApplication.UnicodeUTF8))
        self.waiting_label.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa557f;\">Finding data file:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa557f;\">this may take a moment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setToolTip(QtGui.QApplication.translate("Frame", "Remove selected item", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setText(QtGui.QApplication.translate("Frame", "Remove selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "Incident medium ", None, QtGui.QApplication.UnicodeUTF8))
        self.incident_medium_combobox.setItemText(0, QtGui.QApplication.translate("Frame", "H20", None, QtGui.QApplication.UnicodeUTF8))
        self.incident_medium_combobox.setItemText(1, QtGui.QApplication.translate("Frame", "Small Circular SA holder", None, QtGui.QApplication.UnicodeUTF8))
        self.incident_medium_combobox.setItemText(2, QtGui.QApplication.translate("Frame", "Large Circular SA holder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "TOF min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "&#181;s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "TOF max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Frame", "&#181;s", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_counts_vs_tof_btn.setToolTip(QtGui.QApplication.translate("Frame", "Plot detector counts versus Y pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_counts_vs_tof_btn.setText(QtGui.QApplication.translate("Frame", "TOF selection...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Direct beam scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Run number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Hit [ENTER] to refresh Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.data_run_number_processing.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600; color:#aa557f;\">Loading metadata:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600; color:#aa557f;\">this may take a moment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Number of attenuators", None, QtGui.QApplication.UnicodeUTF8))
        self.number_of_attenuator.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Peak selection", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel_label.setText(QtGui.QApplication.translate("Frame", "      to pixel  ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_btn.setToolTip(QtGui.QApplication.translate("Frame", "Plot detector counts versus Y pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Frame", "Background selection", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel_label.setText(QtGui.QApplication.translate("Frame", "      to pixel  ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_bck_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Frame", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Frame", "Lambda requested:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Frame", "&#8491;", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Frame", "S1 height:", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_unit_label.setText(QtGui.QApplication.translate("Frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Frame", "S2 height:", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_unit_label_2.setText(QtGui.QApplication.translate("Frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Frame", "S1 width :", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_unit_label_7.setText(QtGui.QApplication.translate("Frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Frame", "S2 width :", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_unit_label_3.setText(QtGui.QApplication.translate("Frame", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.edited_warning_label.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;color:rgb(0,153,153);\">Click Save To List to apply your changes  →  </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.add_dataset_btn.setToolTip(QtGui.QApplication.translate("Frame", "Click to add the data set above to the reduction list", None, QtGui.QApplication.UnicodeUTF8))
        self.add_dataset_btn.setText(QtGui.QApplication.translate("Frame", "Save to list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Frame", "Scaling Factor File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_scaling_factor_file_name_browse.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.cfg_scaling_factor_file_name_refresh.setText(QtGui.QApplication.translate("Frame", "Refresh", None, QtGui.QApplication.UnicodeUTF8))

