#pylint: disable=invalid-name,line-too-long,too-many-lines,too-many-instance-attributes,too-many-locals,too-many-statements,attribute-defined-outside-init
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refm_reduction.ui'
#
# Created: Fri Nov  9 11:17:21 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1298, 1455)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1274, 1431))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.waiting_label = QtGui.QLabel(self.groupBox_3)
        self.waiting_label.setObjectName("waiting_label")
        self.verticalLayout_6.addWidget(self.waiting_label)
        self.angle_list = QtGui.QListWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_list.sizePolicy().hasHeightForWidth())
        self.angle_list.setSizePolicy(sizePolicy)
        self.angle_list.setMinimumSize(QtCore.QSize(200, 0))
        self.angle_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.angle_list.setDragEnabled(True)
        self.angle_list.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.angle_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.angle_list.setAlternatingRowColors(True)
        self.angle_list.setObjectName("angle_list")
        self.verticalLayout_6.addWidget(self.angle_list)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.remove_btn = QtGui.QPushButton(self.groupBox_3)
        self.remove_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.remove_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout_12.addWidget(self.remove_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.data_low_res_range_switch = QtGui.QCheckBox(self.groupBox)
        self.data_low_res_range_switch.setMinimumSize(QtCore.QSize(170, 0))
        self.data_low_res_range_switch.setMaximumSize(QtCore.QSize(170, 16777215))
        self.data_low_res_range_switch.setObjectName("data_low_res_range_switch")
        self.horizontalLayout_5.addWidget(self.data_low_res_range_switch)
        self.data_low_res_from_label = QtGui.QLabel(self.groupBox)
        self.data_low_res_from_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_low_res_from_label.sizePolicy().hasHeightForWidth())
        self.data_low_res_from_label.setSizePolicy(sizePolicy)
        self.data_low_res_from_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_low_res_from_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_low_res_from_label.setIndent(0)
        self.data_low_res_from_label.setObjectName("data_low_res_from_label")
        self.horizontalLayout_5.addWidget(self.data_low_res_from_label)
        self.x_min_edit = QtGui.QLineEdit(self.groupBox)
        self.x_min_edit.setEnabled(False)
        self.x_min_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.x_min_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_min_edit.setObjectName("x_min_edit")
        self.horizontalLayout_5.addWidget(self.x_min_edit)
        self.x_min_estimate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_min_estimate.sizePolicy().hasHeightForWidth())
        self.x_min_estimate.setSizePolicy(sizePolicy)
        self.x_min_estimate.setMinimumSize(QtCore.QSize(20, 0))
        self.x_min_estimate.setMaximumSize(QtCore.QSize(20, 16777215))
        self.x_min_estimate.setText("")
        self.x_min_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.x_min_estimate.setObjectName("x_min_estimate")
        self.horizontalLayout_5.addWidget(self.x_min_estimate)
        self.data_low_res_to_label = QtGui.QLabel(self.groupBox)
        self.data_low_res_to_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_low_res_to_label.sizePolicy().hasHeightForWidth())
        self.data_low_res_to_label.setSizePolicy(sizePolicy)
        self.data_low_res_to_label.setMinimumSize(QtCore.QSize(60, 0))
        self.data_low_res_to_label.setObjectName("data_low_res_to_label")
        self.horizontalLayout_5.addWidget(self.data_low_res_to_label)
        self.x_max_edit = QtGui.QLineEdit(self.groupBox)
        self.x_max_edit.setEnabled(False)
        self.x_max_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.x_max_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.x_max_edit.setObjectName("x_max_edit")
        self.horizontalLayout_5.addWidget(self.x_max_edit)
        self.x_max_estimate = QtGui.QLabel(self.groupBox)
        self.x_max_estimate.setMinimumSize(QtCore.QSize(20, 0))
        self.x_max_estimate.setMaximumSize(QtCore.QSize(20, 16777215))
        self.x_max_estimate.setText("")
        self.x_max_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.x_max_estimate.setObjectName("x_max_estimate")
        self.horizontalLayout_5.addWidget(self.x_max_estimate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.plot_count_vs_x_btn = QtGui.QPushButton(self.groupBox)
        self.plot_count_vs_x_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_count_vs_x_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_count_vs_x_btn.setObjectName("plot_count_vs_x_btn")
        self.horizontalLayout_5.addWidget(self.plot_count_vs_x_btn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(170, 0))
        self.label_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.data_peak_from_pixel_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel_label.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_peak_from_pixel_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_peak_from_pixel_label.setIndent(0)
        self.data_peak_from_pixel_label.setObjectName("data_peak_from_pixel_label")
        self.horizontalLayout_8.addWidget(self.data_peak_from_pixel_label)
        self.data_peak_from_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_from_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_from_pixel.setObjectName("data_peak_from_pixel")
        self.horizontalLayout_8.addWidget(self.data_peak_from_pixel)
        self.data_peak_from_pixel_estimate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_from_pixel_estimate.sizePolicy().hasHeightForWidth())
        self.data_peak_from_pixel_estimate.setSizePolicy(sizePolicy)
        self.data_peak_from_pixel_estimate.setMinimumSize(QtCore.QSize(20, 0))
        self.data_peak_from_pixel_estimate.setMaximumSize(QtCore.QSize(20, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.data_peak_from_pixel_estimate.setPalette(palette)
        self.data_peak_from_pixel_estimate.setText("")
        self.data_peak_from_pixel_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.data_peak_from_pixel_estimate.setObjectName("data_peak_from_pixel_estimate")
        self.horizontalLayout_8.addWidget(self.data_peak_from_pixel_estimate)
        self.data_peak_to_pixel_label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_to_pixel_label.sizePolicy().hasHeightForWidth())
        self.data_peak_to_pixel_label.setSizePolicy(sizePolicy)
        self.data_peak_to_pixel_label.setMinimumSize(QtCore.QSize(60, 0))
        self.data_peak_to_pixel_label.setObjectName("data_peak_to_pixel_label")
        self.horizontalLayout_8.addWidget(self.data_peak_to_pixel_label)
        self.data_peak_to_pixel = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_peak_to_pixel.sizePolicy().hasHeightForWidth())
        self.data_peak_to_pixel.setSizePolicy(sizePolicy)
        self.data_peak_to_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.data_peak_to_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_peak_to_pixel.setObjectName("data_peak_to_pixel")
        self.horizontalLayout_8.addWidget(self.data_peak_to_pixel)
        self.data_peak_to_pixel_estimate = QtGui.QLabel(self.groupBox)
        self.data_peak_to_pixel_estimate.setMinimumSize(QtCore.QSize(20, 0))
        self.data_peak_to_pixel_estimate.setMaximumSize(QtCore.QSize(20, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_peak_to_pixel_estimate.setPalette(palette)
        self.data_peak_to_pixel_estimate.setText("")
        self.data_peak_to_pixel_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.data_peak_to_pixel_estimate.setObjectName("data_peak_to_pixel_estimate")
        self.horizontalLayout_8.addWidget(self.data_peak_to_pixel_estimate)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.center_pix_edit = QtGui.QLineEdit(self.groupBox)
        self.center_pix_edit.setEnabled(False)
        self.center_pix_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.center_pix_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.center_pix_edit.setObjectName("center_pix_edit")
        self.horizontalLayout_8.addWidget(self.center_pix_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.plot_count_vs_y_btn = QtGui.QPushButton(self.groupBox)
        self.plot_count_vs_y_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_count_vs_y_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_count_vs_y_btn.setObjectName("plot_count_vs_y_btn")
        self.horizontalLayout_8.addWidget(self.plot_count_vs_y_btn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.data_background_switch = QtGui.QCheckBox(self.groupBox)
        self.data_background_switch.setMinimumSize(QtCore.QSize(170, 0))
        self.data_background_switch.setMaximumSize(QtCore.QSize(170, 16777215))
        self.data_background_switch.setChecked(True)
        self.data_background_switch.setObjectName("data_background_switch")
        self.horizontalLayout_17.addWidget(self.data_background_switch)
        self.data_background_from_pixel1_label = QtGui.QLabel(self.groupBox)
        self.data_background_from_pixel1_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel1_label.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel1_label.setSizePolicy(sizePolicy)
        self.data_background_from_pixel1_label.setMinimumSize(QtCore.QSize(80, 0))
        self.data_background_from_pixel1_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.data_background_from_pixel1_label.setIndent(0)
        self.data_background_from_pixel1_label.setObjectName("data_background_from_pixel1_label")
        self.horizontalLayout_17.addWidget(self.data_background_from_pixel1_label)
        self.data_background_from_pixel1 = QtGui.QLineEdit(self.groupBox)
        self.data_background_from_pixel1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel1.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel1.setSizePolicy(sizePolicy)
        self.data_background_from_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_from_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_from_pixel1.setBaseSize(QtCore.QSize(0, 0))
        self.data_background_from_pixel1.setObjectName("data_background_from_pixel1")
        self.horizontalLayout_17.addWidget(self.data_background_from_pixel1)
        self.data_background_from_pixel1_missing = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel1_missing.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel1_missing.setSizePolicy(sizePolicy)
        self.data_background_from_pixel1_missing.setMinimumSize(QtCore.QSize(20, 0))
        self.data_background_from_pixel1_missing.setMaximumSize(QtCore.QSize(20, 16777215))
        self.data_background_from_pixel1_missing.setText("")
        self.data_background_from_pixel1_missing.setObjectName("data_background_from_pixel1_missing")
        self.horizontalLayout_17.addWidget(self.data_background_from_pixel1_missing)
        self.data_background_to_pixel1_label = QtGui.QLabel(self.groupBox)
        self.data_background_to_pixel1_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel1_label.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel1_label.setSizePolicy(sizePolicy)
        self.data_background_to_pixel1_label.setMinimumSize(QtCore.QSize(60, 0))
        self.data_background_to_pixel1_label.setObjectName("data_background_to_pixel1_label")
        self.horizontalLayout_17.addWidget(self.data_background_to_pixel1_label)
        self.data_background_to_pixel1 = QtGui.QLineEdit(self.groupBox)
        self.data_background_to_pixel1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_to_pixel1.sizePolicy().hasHeightForWidth())
        self.data_background_to_pixel1.setSizePolicy(sizePolicy)
        self.data_background_to_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.data_background_to_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.data_background_to_pixel1.setObjectName("data_background_to_pixel1")
        self.horizontalLayout_17.addWidget(self.data_background_to_pixel1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.plot_count_vs_y_bck_btn = QtGui.QPushButton(self.groupBox)
        self.plot_count_vs_y_bck_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_count_vs_y_bck_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_count_vs_y_bck_btn.setObjectName("plot_count_vs_y_bck_btn")
        self.horizontalLayout_17.addWidget(self.plot_count_vs_y_bck_btn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        spacerItem4 = QtGui.QSpacerItem(176, 121, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.plot_data_count_vs_x_2d_btn = QtGui.QPushButton(self.groupBox)
        self.plot_data_count_vs_x_2d_btn.setEnabled(False)
        self.plot_data_count_vs_x_2d_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.plot_data_count_vs_x_2d_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plot_data_count_vs_x_2d_btn.setObjectName("plot_data_count_vs_x_2d_btn")
        self.verticalLayout_14.addWidget(self.plot_data_count_vs_x_2d_btn)
        self.plot_data_count_vs_tof_2d_btn = QtGui.QPushButton(self.groupBox)
        self.plot_data_count_vs_tof_2d_btn.setEnabled(True)
        self.plot_data_count_vs_tof_2d_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.plot_data_count_vs_tof_2d_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plot_data_count_vs_tof_2d_btn.setObjectName("plot_data_count_vs_tof_2d_btn")
        self.verticalLayout_14.addWidget(self.plot_data_count_vs_tof_2d_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        spacerItem5 = QtGui.QSpacerItem(175, 121, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(170, 0))
        self.label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.data_run_number_edit = QtGui.QLineEdit(self.groupBox)
        self.data_run_number_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_run_number_edit.setObjectName("data_run_number_edit")
        self.horizontalLayout.addWidget(self.data_run_number_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.det_angle_check = QtGui.QCheckBox(self.groupBox)
        self.det_angle_check.setMinimumSize(QtCore.QSize(170, 0))
        self.det_angle_check.setMaximumSize(QtCore.QSize(170, 16777215))
        self.det_angle_check.setObjectName("det_angle_check")
        self.horizontalLayout_20.addWidget(self.det_angle_check)
        self.det_angle_edit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.det_angle_edit.sizePolicy().hasHeightForWidth())
        self.det_angle_edit.setSizePolicy(sizePolicy)
        self.det_angle_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.det_angle_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.det_angle_edit.setToolTip("")
        self.det_angle_edit.setObjectName("det_angle_edit")
        self.horizontalLayout_20.addWidget(self.det_angle_edit)
        self.det_angle_unit_label = QtGui.QLabel(self.groupBox)
        self.det_angle_unit_label.setMinimumSize(QtCore.QSize(100, 0))
        self.det_angle_unit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.det_angle_unit_label.setObjectName("det_angle_unit_label")
        self.horizontalLayout_20.addWidget(self.det_angle_unit_label)
        self.det_angle_offset_check = QtGui.QCheckBox(self.groupBox)
        self.det_angle_offset_check.setMinimumSize(QtCore.QSize(190, 0))
        self.det_angle_offset_check.setMaximumSize(QtCore.QSize(190, 16777215))
        self.det_angle_offset_check.setStatusTip("")
        self.det_angle_offset_check.setObjectName("det_angle_offset_check")
        self.horizontalLayout_20.addWidget(self.det_angle_offset_check)
        self.det_angle_offset_edit = QtGui.QLineEdit(self.groupBox)
        self.det_angle_offset_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.det_angle_offset_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.det_angle_offset_edit.setToolTip("")
        self.det_angle_offset_edit.setObjectName("det_angle_offset_edit")
        self.horizontalLayout_20.addWidget(self.det_angle_offset_edit)
        self.det_angle_offset_unit_label = QtGui.QLabel(self.groupBox)
        self.det_angle_offset_unit_label.setObjectName("det_angle_offset_unit_label")
        self.horizontalLayout_20.addWidget(self.det_angle_offset_unit_label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.direct_pixel_check = QtGui.QCheckBox(self.groupBox)
        self.direct_pixel_check.setMinimumSize(QtCore.QSize(170, 0))
        self.direct_pixel_check.setMaximumSize(QtCore.QSize(170, 16777215))
        self.direct_pixel_check.setWhatsThis("")
        self.direct_pixel_check.setObjectName("direct_pixel_check")
        self.horizontalLayout_21.addWidget(self.direct_pixel_check)
        self.direct_pixel_edit = QtGui.QLineEdit(self.groupBox)
        self.direct_pixel_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.direct_pixel_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.direct_pixel_edit.setToolTip("")
        self.direct_pixel_edit.setObjectName("direct_pixel_edit")
        self.horizontalLayout_21.addWidget(self.direct_pixel_edit)
        spacerItem7 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_21.addWidget(self.label_4)
        self.angle_edit = QtGui.QLineEdit(self.groupBox)
        self.angle_edit.setMinimumSize(QtCore.QSize(70, 0))
        self.angle_edit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.angle_edit.setObjectName("angle_edit")
        self.horizontalLayout_21.addWidget(self.angle_edit)
        self.angle_unit_label = QtGui.QLabel(self.groupBox)
        self.angle_unit_label.setObjectName("angle_unit_label")
        self.horizontalLayout_21.addWidget(self.angle_unit_label)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4.addWidget(self.groupBox)
        spacerItem9 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem9)
        self.norm_group_box = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.norm_group_box.setObjectName("norm_group_box")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.norm_group_box)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.norm_switch = QtGui.QCheckBox(self.norm_group_box)
        self.norm_switch.setChecked(True)
        self.norm_switch.setObjectName("norm_switch")
        self.verticalLayout_2.addWidget(self.norm_switch)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.norm_run_number_label = QtGui.QLabel(self.norm_group_box)
        self.norm_run_number_label.setMinimumSize(QtCore.QSize(170, 0))
        self.norm_run_number_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.norm_run_number_label.setObjectName("norm_run_number_label")
        self.horizontalLayout_2.addWidget(self.norm_run_number_label)
        self.norm_run_number_edit = QtGui.QLineEdit(self.norm_group_box)
        self.norm_run_number_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.norm_run_number_edit.setObjectName("norm_run_number_edit")
        self.horizontalLayout_2.addWidget(self.norm_run_number_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.norm_peak_selection_label = QtGui.QLabel(self.norm_group_box)
        self.norm_peak_selection_label.setMinimumSize(QtCore.QSize(170, 0))
        self.norm_peak_selection_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.norm_peak_selection_label.setIndent(0)
        self.norm_peak_selection_label.setObjectName("norm_peak_selection_label")
        self.horizontalLayout_4.addWidget(self.norm_peak_selection_label)
        self.norm_peak_selection_from_label = QtGui.QLabel(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_peak_selection_from_label.sizePolicy().hasHeightForWidth())
        self.norm_peak_selection_from_label.setSizePolicy(sizePolicy)
        self.norm_peak_selection_from_label.setMinimumSize(QtCore.QSize(80, 0))
        self.norm_peak_selection_from_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.norm_peak_selection_from_label.setIndent(0)
        self.norm_peak_selection_from_label.setObjectName("norm_peak_selection_from_label")
        self.horizontalLayout_4.addWidget(self.norm_peak_selection_from_label)
        self.norm_peak_from_pixel = QtGui.QLineEdit(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_peak_from_pixel.sizePolicy().hasHeightForWidth())
        self.norm_peak_from_pixel.setSizePolicy(sizePolicy)
        self.norm_peak_from_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_peak_from_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_peak_from_pixel.setObjectName("norm_peak_from_pixel")
        self.horizontalLayout_4.addWidget(self.norm_peak_from_pixel)
        self.norm_peak_from_pixel_estimate = QtGui.QLabel(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_peak_from_pixel_estimate.sizePolicy().hasHeightForWidth())
        self.norm_peak_from_pixel_estimate.setSizePolicy(sizePolicy)
        self.norm_peak_from_pixel_estimate.setMinimumSize(QtCore.QSize(40, 0))
        self.norm_peak_from_pixel_estimate.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 33, 5))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 133, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 106, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 59, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 8, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 6, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 12, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.norm_peak_from_pixel_estimate.setPalette(palette)
        self.norm_peak_from_pixel_estimate.setText("")
        self.norm_peak_from_pixel_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.norm_peak_from_pixel_estimate.setObjectName("norm_peak_from_pixel_estimate")
        self.horizontalLayout_4.addWidget(self.norm_peak_from_pixel_estimate)
        self.norm_peak_selection_to_label = QtGui.QLabel(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_peak_selection_to_label.sizePolicy().hasHeightForWidth())
        self.norm_peak_selection_to_label.setSizePolicy(sizePolicy)
        self.norm_peak_selection_to_label.setMinimumSize(QtCore.QSize(60, 0))
        self.norm_peak_selection_to_label.setObjectName("norm_peak_selection_to_label")
        self.horizontalLayout_4.addWidget(self.norm_peak_selection_to_label)
        self.norm_peak_to_pixel = QtGui.QLineEdit(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_peak_to_pixel.sizePolicy().hasHeightForWidth())
        self.norm_peak_to_pixel.setSizePolicy(sizePolicy)
        self.norm_peak_to_pixel.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_peak_to_pixel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_peak_to_pixel.setObjectName("norm_peak_to_pixel")
        self.horizontalLayout_4.addWidget(self.norm_peak_to_pixel)
        self.norm_peak_to_pixel_estimate = QtGui.QLabel(self.norm_group_box)
        self.norm_peak_to_pixel_estimate.setMinimumSize(QtCore.QSize(40, 0))
        self.norm_peak_to_pixel_estimate.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.norm_peak_to_pixel_estimate.setPalette(palette)
        self.norm_peak_to_pixel_estimate.setText("")
        self.norm_peak_to_pixel_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.norm_peak_to_pixel_estimate.setObjectName("norm_peak_to_pixel_estimate")
        self.horizontalLayout_4.addWidget(self.norm_peak_to_pixel_estimate)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.norm_count_vs_y_btn = QtGui.QPushButton(self.norm_group_box)
        self.norm_count_vs_y_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.norm_count_vs_y_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.norm_count_vs_y_btn.setObjectName("norm_count_vs_y_btn")
        self.horizontalLayout_4.addWidget(self.norm_count_vs_y_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.norm_background_switch = QtGui.QCheckBox(self.norm_group_box)
        self.norm_background_switch.setMinimumSize(QtCore.QSize(170, 0))
        self.norm_background_switch.setMaximumSize(QtCore.QSize(150, 16777215))
        self.norm_background_switch.setChecked(True)
        self.norm_background_switch.setObjectName("norm_background_switch")
        self.horizontalLayout_10.addWidget(self.norm_background_switch)
        self.norm_background_from_pixel1_label = QtGui.QLabel(self.norm_group_box)
        self.norm_background_from_pixel1_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_background_from_pixel1_label.sizePolicy().hasHeightForWidth())
        self.norm_background_from_pixel1_label.setSizePolicy(sizePolicy)
        self.norm_background_from_pixel1_label.setMinimumSize(QtCore.QSize(80, 0))
        self.norm_background_from_pixel1_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.norm_background_from_pixel1_label.setIndent(0)
        self.norm_background_from_pixel1_label.setObjectName("norm_background_from_pixel1_label")
        self.horizontalLayout_10.addWidget(self.norm_background_from_pixel1_label)
        self.norm_background_from_pixel1 = QtGui.QLineEdit(self.norm_group_box)
        self.norm_background_from_pixel1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_background_from_pixel1.sizePolicy().hasHeightForWidth())
        self.norm_background_from_pixel1.setSizePolicy(sizePolicy)
        self.norm_background_from_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_background_from_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_background_from_pixel1.setBaseSize(QtCore.QSize(0, 0))
        self.norm_background_from_pixel1.setObjectName("norm_background_from_pixel1")
        self.horizontalLayout_10.addWidget(self.norm_background_from_pixel1)
        self.data_background_from_pixel_missing_2 = QtGui.QLabel(self.norm_group_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_background_from_pixel_missing_2.sizePolicy().hasHeightForWidth())
        self.data_background_from_pixel_missing_2.setSizePolicy(sizePolicy)
        self.data_background_from_pixel_missing_2.setMinimumSize(QtCore.QSize(40, 0))
        self.data_background_from_pixel_missing_2.setMaximumSize(QtCore.QSize(40, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 27, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_background_from_pixel_missing_2.setPalette(palette)
        self.data_background_from_pixel_missing_2.setText("")
        self.data_background_from_pixel_missing_2.setObjectName("data_background_from_pixel_missing_2")
        self.horizontalLayout_10.addWidget(self.data_background_from_pixel_missing_2)
        self.norm_background_to_pixel1_label = QtGui.QLabel(self.norm_group_box)
        self.norm_background_to_pixel1_label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_background_to_pixel1_label.sizePolicy().hasHeightForWidth())
        self.norm_background_to_pixel1_label.setSizePolicy(sizePolicy)
        self.norm_background_to_pixel1_label.setMinimumSize(QtCore.QSize(60, 0))
        self.norm_background_to_pixel1_label.setObjectName("norm_background_to_pixel1_label")
        self.horizontalLayout_10.addWidget(self.norm_background_to_pixel1_label)
        self.norm_background_to_pixel1 = QtGui.QLineEdit(self.norm_group_box)
        self.norm_background_to_pixel1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_background_to_pixel1.sizePolicy().hasHeightForWidth())
        self.norm_background_to_pixel1.setSizePolicy(sizePolicy)
        self.norm_background_to_pixel1.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_background_to_pixel1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_background_to_pixel1.setObjectName("norm_background_to_pixel1")
        self.horizontalLayout_10.addWidget(self.norm_background_to_pixel1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.norm_count_vs_y_bck_btn = QtGui.QPushButton(self.norm_group_box)
        self.norm_count_vs_y_bck_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.norm_count_vs_y_bck_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.norm_count_vs_y_bck_btn.setObjectName("norm_count_vs_y_bck_btn")
        self.horizontalLayout_10.addWidget(self.norm_count_vs_y_bck_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.norm_low_res_range_switch = QtGui.QCheckBox(self.norm_group_box)
        self.norm_low_res_range_switch.setMinimumSize(QtCore.QSize(170, 0))
        self.norm_low_res_range_switch.setMaximumSize(QtCore.QSize(170, 16777215))
        self.norm_low_res_range_switch.setObjectName("norm_low_res_range_switch")
        self.horizontalLayout_15.addWidget(self.norm_low_res_range_switch)
        self.norm_low_res_from_label = QtGui.QLabel(self.norm_group_box)
        self.norm_low_res_from_label.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.norm_low_res_from_label.sizePolicy().hasHeightForWidth())
        self.norm_low_res_from_label.setSizePolicy(sizePolicy)
        self.norm_low_res_from_label.setMinimumSize(QtCore.QSize(80, 0))
        self.norm_low_res_from_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.norm_low_res_from_label.setIndent(0)
        self.norm_low_res_from_label.setObjectName("norm_low_res_from_label")
        self.horizontalLayout_15.addWidget(self.norm_low_res_from_label)
        self.norm_x_min_edit = QtGui.QLineEdit(self.norm_group_box)
        self.norm_x_min_edit.setEnabled(False)
        self.norm_x_min_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_x_min_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_x_min_edit.setObjectName("norm_x_min_edit")
        self.horizontalLayout_15.addWidget(self.norm_x_min_edit)
        self.norm_xmin_estimate = QtGui.QLabel(self.norm_group_box)
        self.norm_xmin_estimate.setMinimumSize(QtCore.QSize(40, 0))
        self.norm_xmin_estimate.setMaximumSize(QtCore.QSize(40, 16777215))
        self.norm_xmin_estimate.setText("")
        self.norm_xmin_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.norm_xmin_estimate.setObjectName("norm_xmin_estimate")
        self.horizontalLayout_15.addWidget(self.norm_xmin_estimate)
        self.norm_low_res_to_label = QtGui.QLabel(self.norm_group_box)
        self.norm_low_res_to_label.setEnabled(False)
        self.norm_low_res_to_label.setMinimumSize(QtCore.QSize(60, 0))
        self.norm_low_res_to_label.setObjectName("norm_low_res_to_label")
        self.horizontalLayout_15.addWidget(self.norm_low_res_to_label)
        self.norm_x_max_edit = QtGui.QLineEdit(self.norm_group_box)
        self.norm_x_max_edit.setEnabled(False)
        self.norm_x_max_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.norm_x_max_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.norm_x_max_edit.setObjectName("norm_x_max_edit")
        self.horizontalLayout_15.addWidget(self.norm_x_max_edit)
        self.norm_xmax_estimate = QtGui.QLabel(self.norm_group_box)
        self.norm_xmax_estimate.setMinimumSize(QtCore.QSize(40, 0))
        self.norm_xmax_estimate.setMaximumSize(QtCore.QSize(40, 16777215))
        self.norm_xmax_estimate.setText("")
        self.norm_xmax_estimate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.norm_xmax_estimate.setObjectName("norm_xmax_estimate")
        self.horizontalLayout_15.addWidget(self.norm_xmax_estimate)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.norm_count_vs_x_btn = QtGui.QPushButton(self.norm_group_box)
        self.norm_count_vs_x_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.norm_count_vs_x_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.norm_count_vs_x_btn.setObjectName("norm_count_vs_x_btn")
        self.horizontalLayout_15.addWidget(self.norm_count_vs_x_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4.addWidget(self.norm_group_box)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tof_min_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tof_min_label.sizePolicy().hasHeightForWidth())
        self.tof_min_label.setSizePolicy(sizePolicy)
        self.tof_min_label.setMinimumSize(QtCore.QSize(0, 0))
        self.tof_min_label.setMaximumSize(QtCore.QSize(70, 50))
        self.tof_min_label.setObjectName("tof_min_label")
        self.horizontalLayout_9.addWidget(self.tof_min_label)
        self.data_from_tof = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.data_from_tof.setMinimumSize(QtCore.QSize(70, 0))
        self.data_from_tof.setMaximumSize(QtCore.QSize(70, 16777215))
        self.data_from_tof.setObjectName("data_from_tof")
        self.horizontalLayout_9.addWidget(self.data_from_tof)
        self.tof_min_label2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tof_min_label2.setMinimumSize(QtCore.QSize(50, 0))
        self.tof_min_label2.setMaximumSize(QtCore.QSize(50, 50))
        self.tof_min_label2.setObjectName("tof_min_label2")
        self.horizontalLayout_9.addWidget(self.tof_min_label2)
        self.tof_bin_width_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tof_bin_width_label.setMinimumSize(QtCore.QSize(0, 0))
        self.tof_bin_width_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tof_bin_width_label.setObjectName("tof_bin_width_label")
        self.horizontalLayout_9.addWidget(self.tof_bin_width_label)
        self.tof_bin_width_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tof_bin_width_edit.setMinimumSize(QtCore.QSize(50, 0))
        self.tof_bin_width_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tof_bin_width_edit.setObjectName("tof_bin_width_edit")
        self.horizontalLayout_9.addWidget(self.tof_bin_width_edit)
        self.tof_bin_width_unit_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tof_bin_width_unit_label.setMinimumSize(QtCore.QSize(50, 0))
        self.tof_bin_width_unit_label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tof_bin_width_unit_label.setObjectName("tof_bin_width_unit_label")
        self.horizontalLayout_9.addWidget(self.tof_bin_width_unit_label)
        self.tof_max_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tof_max_label.setMinimumSize(QtCore.QSize(70, 0))
        self.tof_max_label.setMaximumSize(QtCore.QSize(70, 50))
        self.tof_max_label.setObjectName("tof_max_label")
        self.horizontalLayout_9.addWidget(self.tof_max_label)
        self.data_to_tof = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.data_to_tof.setMinimumSize(QtCore.QSize(70, 0))
        self.data_to_tof.setMaximumSize(QtCore.QSize(70, 16777215))
        self.data_to_tof.setObjectName("data_to_tof")
        self.horizontalLayout_9.addWidget(self.data_to_tof)
        self.tof_max_label2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tof_max_label2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tof_max_label2.setObjectName("tof_max_label2")
        self.horizontalLayout_9.addWidget(self.tof_max_label2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.plot_tof_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.plot_tof_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.plot_tof_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.plot_tof_btn.setObjectName("plot_tof_btn")
        self.horizontalLayout_9.addWidget(self.plot_tof_btn)
        spacerItem14 = QtGui.QSpacerItem(9, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.edited_warning_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.edited_warning_label.setTextFormat(QtCore.Qt.RichText)
        self.edited_warning_label.setObjectName("edited_warning_label")
        self.horizontalLayout_7.addWidget(self.edited_warning_label)
        self.add_dataset_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.add_dataset_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.add_dataset_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 242, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.add_dataset_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.add_dataset_btn.setFont(font)
        self.add_dataset_btn.setObjectName("add_dataset_btn")
        self.horizontalLayout_7.addWidget(self.add_dataset_btn)
        spacerItem16 = QtGui.QSpacerItem(9, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.q_min_label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_min_label.sizePolicy().hasHeightForWidth())
        self.q_min_label.setSizePolicy(sizePolicy)
        self.q_min_label.setMinimumSize(QtCore.QSize(150, 0))
        self.q_min_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.q_min_label.setObjectName("q_min_label")
        self.horizontalLayout_14.addWidget(self.q_min_label)
        self.q_min_edit = QtGui.QLineEdit(self.groupBox_4)
        self.q_min_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.q_min_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_min_edit.setObjectName("q_min_edit")
        self.horizontalLayout_14.addWidget(self.q_min_edit)
        self.q_min_unit_label = QtGui.QLabel(self.groupBox_4)
        self.q_min_unit_label.setMinimumSize(QtCore.QSize(70, 0))
        self.q_min_unit_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.q_min_unit_label.setObjectName("q_min_unit_label")
        self.horizontalLayout_14.addWidget(self.q_min_unit_label)
        self.q_bins_label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.q_bins_label.sizePolicy().hasHeightForWidth())
        self.q_bins_label.setSizePolicy(sizePolicy)
        self.q_bins_label.setMinimumSize(QtCore.QSize(150, 0))
        self.q_bins_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.q_bins_label.setObjectName("q_bins_label")
        self.horizontalLayout_14.addWidget(self.q_bins_label)
        self.q_step_label = QtGui.QLabel(self.groupBox_4)
        self.q_step_label.setMinimumSize(QtCore.QSize(70, 0))
        self.q_step_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.q_step_label.setObjectName("q_step_label")
        self.horizontalLayout_14.addWidget(self.q_step_label)
        self.q_step_edit = QtGui.QLineEdit(self.groupBox_4)
        self.q_step_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.q_step_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_step_edit.setObjectName("q_step_edit")
        self.horizontalLayout_14.addWidget(self.q_step_edit)
        self.q_step_unit_label = QtGui.QLabel(self.groupBox_4)
        self.q_step_unit_label.setObjectName("q_step_unit_label")
        self.horizontalLayout_14.addWidget(self.q_step_unit_label)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.log_scale_chk = QtGui.QCheckBox(self.groupBox_4)
        self.log_scale_chk.setObjectName("log_scale_chk")
        self.horizontalLayout_14.addWidget(self.log_scale_chk)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.angle_offset_label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_offset_label.sizePolicy().hasHeightForWidth())
        self.angle_offset_label.setSizePolicy(sizePolicy)
        self.angle_offset_label.setMinimumSize(QtCore.QSize(150, 0))
        self.angle_offset_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.angle_offset_label.setObjectName("angle_offset_label")
        self.horizontalLayout_16.addWidget(self.angle_offset_label)
        self.angle_offset_edit = QtGui.QLineEdit(self.groupBox_4)
        self.angle_offset_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.angle_offset_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.angle_offset_edit.setObjectName("angle_offset_edit")
        self.horizontalLayout_16.addWidget(self.angle_offset_edit)
        self.angle_offset_pm_label = QtGui.QLabel(self.groupBox_4)
        self.angle_offset_pm_label.setObjectName("angle_offset_pm_label")
        self.horizontalLayout_16.addWidget(self.angle_offset_pm_label)
        self.angle_offset_error_edit = QtGui.QLineEdit(self.groupBox_4)
        self.angle_offset_error_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.angle_offset_error_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.angle_offset_error_edit.setObjectName("angle_offset_error_edit")
        self.horizontalLayout_16.addWidget(self.angle_offset_error_edit)
        self.angle_offset_unit_label = QtGui.QLabel(self.groupBox_4)
        self.angle_offset_unit_label.setObjectName("angle_offset_unit_label")
        self.horizontalLayout_16.addWidget(self.angle_offset_unit_label)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.outdir_label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outdir_label.sizePolicy().hasHeightForWidth())
        self.outdir_label.setSizePolicy(sizePolicy)
        self.outdir_label.setMinimumSize(QtCore.QSize(150, 0))
        self.outdir_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.outdir_label.setObjectName("outdir_label")
        self.horizontalLayout_19.addWidget(self.outdir_label)
        self.outdir_edit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outdir_edit.sizePolicy().hasHeightForWidth())
        self.outdir_edit.setSizePolicy(sizePolicy)
        self.outdir_edit.setObjectName("outdir_edit")
        self.horizontalLayout_19.addWidget(self.outdir_edit)
        self.outdir_browse_button = QtGui.QPushButton(self.groupBox_4)
        self.outdir_browse_button.setMinimumSize(QtCore.QSize(150, 0))
        self.outdir_browse_button.setMaximumSize(QtCore.QSize(150, 16777215))
        self.outdir_browse_button.setObjectName("outdir_browse_button")
        self.horizontalLayout_19.addWidget(self.outdir_browse_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem20 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem20)
        self.auto_reduce_help_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auto_reduce_help_label.sizePolicy().hasHeightForWidth())
        self.auto_reduce_help_label.setSizePolicy(sizePolicy)
        self.auto_reduce_help_label.setObjectName("auto_reduce_help_label")
        self.verticalLayout_4.addWidget(self.auto_reduce_help_label)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.auto_reduce_tip_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.auto_reduce_tip_label.setFont(font)
        self.auto_reduce_tip_label.setObjectName("auto_reduce_tip_label")
        self.horizontalLayout_13.addWidget(self.auto_reduce_tip_label)
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem22)
        self.auto_reduce_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.auto_reduce_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.auto_reduce_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.auto_reduce_btn.setObjectName("auto_reduce_btn")
        self.horizontalLayout_13.addWidget(self.auto_reduce_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem23)
        self.auto_reduce_check = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.auto_reduce_check.setObjectName("auto_reduce_check")
        self.verticalLayout_4.addWidget(self.auto_reduce_check)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Frame", "Angle List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "List of runs to be \n"\
"stitched together.", None, QtGui.QApplication.UnicodeUTF8))
        self.waiting_label.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa557f;\">Finding data file:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa557f;\">this may take a moment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setToolTip(QtGui.QApplication.translate("Frame", "Remove selected item", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setText(QtGui.QApplication.translate("Frame", "Remove selected", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Frame", "Data Set", None, QtGui.QApplication.UnicodeUTF8))
        self.data_low_res_range_switch.setText(QtGui.QApplication.translate("Frame", "Y-axis range     ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_low_res_from_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.x_min_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.data_low_res_to_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.x_max_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_x_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Peak selection", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_from_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_peak_to_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Ref pixel ", None, QtGui.QApplication.UnicodeUTF8))
        self.center_pix_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Reflectivity pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.center_pix_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_btn.setToolTip(QtGui.QApplication.translate("Frame", "Plot detector counts versus Y pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_switch.setText(QtGui.QApplication.translate("Frame", "Background                    ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel1_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_from_pixel1.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel1_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.data_background_to_pixel1.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_count_vs_y_bck_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_data_count_vs_x_2d_btn.setText(QtGui.QApplication.translate("Frame", " Y vs X (2D)", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_data_count_vs_tof_2d_btn.setText(QtGui.QApplication.translate("Frame", " Y vs TOF (2D)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Run number", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_check.setToolTip(QtGui.QApplication.translate("Frame", "Detector angle (DANGLE)", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_check.setText(QtGui.QApplication.translate("Frame", "Detector angle", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Detector angle (DANGLE)", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_edit.setText(QtGui.QApplication.translate("Frame", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_unit_label.setText(QtGui.QApplication.translate("Frame", "  degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_offset_check.setToolTip(QtGui.QApplication.translate("Frame", "Detector angle reference (DANGLE0)", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_offset_check.setText(QtGui.QApplication.translate("Frame", "Det angle reference", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_offset_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Detector angle reference (DANGLE0)", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_offset_edit.setText(QtGui.QApplication.translate("Frame", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.det_angle_offset_unit_label.setText(QtGui.QApplication.translate("Frame", "  degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_pixel_check.setToolTip(QtGui.QApplication.translate("Frame", "Direct beam pixel (DIRPIX)", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_pixel_check.setText(QtGui.QApplication.translate("Frame", "Direct pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_pixel_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Direct beam pixel (DIRPIX)", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_pixel_edit.setText(QtGui.QApplication.translate("Frame", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Scattering angle  ", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Scattering angle (corrected SANGLE)", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_edit.setText(QtGui.QApplication.translate("Frame", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_unit_label.setText(QtGui.QApplication.translate("Frame", "  degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_group_box.setTitle(QtGui.QApplication.translate("Frame", "Normalization", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_switch.setText(QtGui.QApplication.translate("Frame", "Apply normalization", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_run_number_label.setText(QtGui.QApplication.translate("Frame", "Run number", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_peak_selection_label.setText(QtGui.QApplication.translate("Frame", "Peak selection", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_peak_selection_from_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_peak_from_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_peak_selection_to_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_peak_to_pixel.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_count_vs_y_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_background_switch.setText(QtGui.QApplication.translate("Frame", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_background_from_pixel1_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_background_from_pixel1.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_background_to_pixel1_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_background_to_pixel1.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_count_vs_y_bck_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_low_res_range_switch.setText(QtGui.QApplication.translate("Frame", "Y-axis range     ", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_low_res_from_label.setText(QtGui.QApplication.translate("Frame", "from pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_x_min_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_low_res_to_label.setText(QtGui.QApplication.translate("Frame", "to pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_x_max_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.norm_count_vs_x_btn.setText(QtGui.QApplication.translate("Frame", "Counts vs Pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_min_label.setText(QtGui.QApplication.translate("Frame", "TOF min  ", None, QtGui.QApplication.UnicodeUTF8))
        self.data_from_tof.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_min_label2.setText(QtGui.QApplication.translate("Frame", " µs", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_bin_width_label.setText(QtGui.QApplication.translate("Frame", "TOF step  ", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_bin_width_edit.setText(QtGui.QApplication.translate("Frame", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_bin_width_unit_label.setText(QtGui.QApplication.translate("Frame", " µs", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_max_label.setText(QtGui.QApplication.translate("Frame", "TOF max", None, QtGui.QApplication.UnicodeUTF8))
        self.data_to_tof.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_max_label2.setText(QtGui.QApplication.translate("Frame", " µs", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_tof_btn.setToolTip(QtGui.QApplication.translate("Frame", "Plot TOF distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.plot_tof_btn.setText(QtGui.QApplication.translate("Frame", "TOF distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.edited_warning_label.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;color:rgb(0,153,153);\">Click Save To List to apply your changes  →  </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.add_dataset_btn.setToolTip(QtGui.QApplication.translate("Frame", "Click to add the data set above to the reduction list", None, QtGui.QApplication.UnicodeUTF8))
        self.add_dataset_btn.setText(QtGui.QApplication.translate("Frame", "Save to list", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Frame", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.q_min_label.setText(QtGui.QApplication.translate("Frame", "Q min", None, QtGui.QApplication.UnicodeUTF8))
        self.q_min_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.q_min_unit_label.setText(QtGui.QApplication.translate("Frame", " 1/Å", None, QtGui.QApplication.UnicodeUTF8))
        self.q_bins_label.setText(QtGui.QApplication.translate("Frame", "Number of bins  ", None, QtGui.QApplication.UnicodeUTF8))
        self.q_step_label.setText(QtGui.QApplication.translate("Frame", "Q steps ", None, QtGui.QApplication.UnicodeUTF8))
        self.q_step_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.q_step_unit_label.setText(QtGui.QApplication.translate("Frame", " 1/Å", None, QtGui.QApplication.UnicodeUTF8))
        self.log_scale_chk.setText(QtGui.QApplication.translate("Frame", "Log scale", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_offset_label.setText(QtGui.QApplication.translate("Frame", "Angle offset", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_offset_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_offset_pm_label.setText(QtGui.QApplication.translate("Frame", " ± ", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_offset_error_edit.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.angle_offset_unit_label.setText(QtGui.QApplication.translate("Frame", "  degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.outdir_label.setText(QtGui.QApplication.translate("Frame", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.outdir_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_reduce_help_label.setText(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Automated Reduction</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">Once you click the &quot;Apply Changes&quot; button, the parameters above</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">will be used to reduce all your data files until you change them again.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_reduce_tip_label.setText(QtGui.QApplication.translate("Frame", "Click to apply changes to the automated reduction process:", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_reduce_btn.setToolTip(QtGui.QApplication.translate("Frame", "Click to apply changes to the automated reduction process", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_reduce_btn.setText(QtGui.QApplication.translate("Frame", "Apply Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_reduce_check.setText(QtGui.QApplication.translate("Frame", "Show automated reduction information", None, QtGui.QApplication.UnicodeUTF8))

