#For MantidDataHandling

import os
import MantidBuild

#GET LIST OF CPPS files
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder) 

#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_DATA_HANDLING',1)])
listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidDataHandling', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'], PDB='lib/MantidDataHandling.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': ['MantidDataHandling'] }
Return('retval')
