#!/usr/bin/env bash

declare -a protected_branches=("master" "release.*") # Add branches which you want to confirm here. Standard REGEX applies
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for i in "${protected_branches[@]}"; do
    if [ "echo $i | grep -q -E $current_branch" ] # '=~' Operator not available in git bash (msysgit)
    then  
        read -p "You're about to push to $current_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
            echo
            if echo $REPLY | grep -q -E '^[Yy]$' 
            then
                exit 0 # push will execute
            else
                exit 1 # push will not execute
                fi
    fi
    # Check all remaining before continuing
done
exit 0 # No branches matched so not 'protected'