#!/bin/sh
# @file check_build check for rpm build
#
# run this from cron at regular intervals
#
# @author Freddie Akeroyd, STFC ISIS Facility
# @date 30/03/2009
#
LOCK_FILE=/tmp/`basename $0`.lock
if test -e $LOCK_FILE; then
    echo "$LOCK_FILE exists"
    exit
else
    touch $LOCK_FILE
fi
trap "rm -f $LOCK_FILE" 0

echo "Running $0"
if [ "`cat /etc/redhat-release`" = "Red Hat Enterprise Linux Server release 6.0 (Santiago)" ]; then
        rhel_version=6
else
    	rhel_version=5
fi

MBUILD=/tmp/mantid_build
[ -d $MBUILD ] || mkdir -p $MBUILD
LOGDIR=/tmp/mantid/rpmlogs
[ -d ${LOGDIR} ] || mkdir -p ${LOGDIR}
n=`ls $MBUILD | wc -l`
if [ $n -gt 0 ]; then
    rev=`( cd $MBUILD; ls ) | head -1`
    rm -f $MBUILD/$rev
    if test "$rev" = "release"; then
	rev=`svn info http://svn.mantidproject.org/mantid/tags/systemtested  |  grep "Last Changed Rev:"  |  awk '{print $4}'`
	repo="release"
	log_file=${LOGDIR}/build_${rev}_release_rhel${rhel_version}.log
	echo "Building $rev for release" > $log_file
    else
	repo=""
	log_file=${LOGDIR}/build_${rev}_rhel${rhel_version}.log
	echo "Building $rev for testing" > $log_file
    fi
    echo "Building $rev" > $log_file
    sh nightly_build "$rev" $log_file $repo >> $log_file 2>&1
fi
if test "$1" = "HEAD" -o "`date +%H%M`" = "0227"; then
    log_file=${LOGDIR}/build_HEAD_rhel${rhel_version}.log
    if test "$1" = "HEAD"; then
	rev=""
        echo "Building HEAD"
        echo "Building HEAD" > $log_file
    else
	rev=`svn info http://svn.mantidproject.org/mantid/tags/systemtested  |  grep "Last Changed Rev:"  |  awk '{print $4}'`
        echo "Building system tested version ($rev)"
        echo "Building system tested version ($rev)" > $log_file
    fi
    sh nightly_build "$rev" $log_file >> $log_file 2>&1
fi
if test -r "$log_file"; then
    scp $log_file isisupdate@shadow.nd.rl.ac.uk:/isis/www/mantidproject_download/logs/Linux/rpmbuild
fi
