#!/bin/bash
#
# Nightly RPM build kit
#
# @file nightly_build
# @author Freddie Akeroyd, STFC ISIS facility
#
trap error_found ERR
MESS=/tmp/build_mantid.$$
if [ "`cat /etc/redhat-release`" = "Red Hat Enterprise Linux Server release 6.0 (Santiago)" ]; then
	rhel_version=6
else
	rhel_version=5
fi

function error_found() {
    local exit_status=${1:-$?}
    echo "Subject: FAILED: RHEL${rhel_version} - RPM build R$rev" > $MESS
    echo >> $MESS
    echo "RPM build of svn R$rev FAILED with error code $exit_status - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
    echo >> $MESS
    echo "** Last few lines of build error **" >> $MESS:wq

    echo >> $MESS
    tail -60 $log_file >> $MESS
    /usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
    rm -f $MESS
    echo Exiting $0 with $exit_status
    exit $exit_status
}

current_rev=""
function current_revision() {
    current_rev=`svnversion -n`
    current_rev=`expr match $current_rev '\([0-9]*\).*'`
}

build_base=$HOME/mybuilds
find $build_base -type f -name 'Mantid-*' -exec rm -f {} \;
# Move back to repository root
cd ../../../../
svn update
svn update # do twice in case of network issue
current_revision
log_file="$2"
if test -z "$1"; then
    rev=$current_rev
else
    rev="$1"
fi
# Back to the build kit directory
cd Code/Mantid/Installers/RPM_Kit
if test "$3" = "release"; then
    revfile="_$rev"
    yum_base=/isis/yum/rhel/${rhel_version}   # official build
else
    revfile=""
    yum_base=/isis/yum/rhel/testing/${rhel_version}   # test build
fi
if [ "${rhel_version}" = "6" ]; then
    sh make_rpm_rhel6.sh -r $rev
else
    sh make_rpm_rhel5.sh -r $rev
fi	
scp $build_base/SRPMS/Mantid-*.*-0.svnR$rev.*.src.rpm isisupdate@shadow:$yum_base/SRPMS
if test -n "`ls $build_base/RPMS/x86_64 | grep debuginfo | grep R${rev}`"; then
    scp $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64/debug
    # remove to avoid copying debug twice
    rm -f $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm
fi
scp $build_base/RPMS/x86_64/Mantid-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64
build_src=`ls -t *.tar.gz | head -1`
scp $build_src isisupdate@shadow:/isis/www/mantidproject_download/CurrentBuild
echo "Subject: Success: RHEL${rhel_version} - RPM build R$rev" > $MESS
echo >> $MESS
echo "RPM build of svn R$rev SUCCEEDED - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
/usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
rm -f $MESS
exit 0
