#!/bin/bash
#
# Nightly RPM build kit
#
# @file nightly_build
# @author Freddie Akeroyd, STFC ISIS facility
#
trap error_found ERR
MESS=/tmp/build_mantid.$$

function error_found() {
    local exit_status=${1:-$?}
    echo "Subject: FAILED: Redhat - RPM build R$rev" > $MESS
    echo >> $MESS
    echo "RPM build of svn R$rev FAILED with error code $exit_status - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
    echo >> $MESS
    echo "** Last few lines of build error **" >> $MESS:wq

    echo >> $MESS
    tail -60 $log_file >> $MESS
    /usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
    rm -f $MESS
    echo Exiting $0 with $exit_status
    exit $exit_status
}

current_rev=""
function current_revision() {
    current_rev=`svnversion -n`
    current_rev=`expr match $current_rev '\([0-9]*\).*'`
}

build_base=$HOME/mybuilds
find $build_base -type f -name 'Mantid-*' -exec rm -f {} \;
cd ../..
svn update
svn update # do twice in case of network issue
current_revision
log_file="$2"
if test -z "$1"; then
    rev=$current_rev
else
    rev="$1"
fi
if test "$3" = "release"; then
    revfile="_$rev"
    yum_base=/isis/yum/rhel/5   # official build
else
    revfile=""
    yum_base=/isis/yum/rhel/testing/5   # test build
fi
cd Code/Mantid/Installers/RPM_Kit
sh make_rpm_rhel5.sh -r $rev
scp $build_base/SRPMS/Mantid-*.*-0.svnR$rev.*.src.rpm isisupdate@shadow:$yum_base/SRPMS
scp $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64/debug
# remove to avoid copying debug twice
rm -f $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm
scp $build_base/RPMS/x86_64/Mantid-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64
build_src=`ls -t *.tar.gz | head -1`
scp $build_src isisupdate@shadow:/isis/www/mantidproject_download/CurrentBuild
echo "Subject: Success: Redhat - RPM build R$rev" > $MESS
echo >> $MESS
echo "RPM build of svn R$rev SUCCEEDED - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
/usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
rm -f $MESS
exit 0
