#For MantidKernel

import os

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = []

if os.path.exists(codeFolder):
	files = os.listdir(codeFolder)
	for file in files:
		if file.endswith('.cpp'):
			print file
			listCpps.append(codeFolder + '/' +  file)

#Import environment
Import('cppPaths')
Import('cflags')

env = Environment(CPPPATH=cppPaths)
env.Append( CCFLAGS = cflags)

#BUILD CODE
env.SharedLibrary('lib/MantidKernel', listCpps, LIBS=[ ], LIBPATH=[ ])
