{% set version = load_setup_py_data().get('version', '0.0.0') %}

package:
  name: mantidqt
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mantidqt', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp {{ llvm_openmp }} # [osx]
    - libgomp  # [linux]
    - ninja {{ ninja }}
    - cmake {{ cmake }}
    - git
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - pyqt {{ pyqt }}                        # [build_platform != target_platform]
    - pyqt5-sip {{ pyqt5_sip }}              # [build_platform != target_platform]
    - pyqtwebengine                          # [build_platform != target_platform]
    - qt-main {{ qt_main }}                  # [build_platform != target_platform]
    - sip                                    # [build_platform != target_platform]

  host:
    - libboost-devel {{ libboost }}
    - libboost-python-devel {{ libboost }}
    - eigen {{ eigen }}
    - libopenblas {{ libopenblas }}  # [osx or linux]
    - mantid {{ version }}
    - python {{ python }}
    - pyqt {{ pyqt }}
    - pyqt5-sip {{ pyqt5_sip }}
    - pyqtwebengine
    - qscintilla2 {{ qscintilla2 }}
    - qt-main {{ qt_main }}
    - qt-webengine
    - setuptools
    - tbb-devel {{ tbb }}
    - versioningit {{ versioningit }}
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - libgl-devel  # [linux]
    - xorg-libxxf86vm  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
  run:
    - matplotlib {{ matplotlib }}
    - {{ pin_compatible("qscintilla2", max_pin="x.x") }}
    - {{ pin_compatible("qt-main", max_pin="x.x") }}
    - qtpy {{ qtpy }}
    - python
    - qt-gtk-platformtheme # [linux]

test:
  imports:
    - mantidqt
    - mantidqt.icons

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
