schema_version: 1

context:
  # Version is injected via an environment variable
  version: ${{ env.get('MANTID_VERSION', default='0.0.0') }}

package:
  name: mantidqt
  version: ${{ version }}

source:
  path: ../../../

build:
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ninja ${{ ninja }}
    - cmake ${{ cmake }}
    - git
    - if: linux
      then:
        - ${{ stdlib("c") }}
        - libgomp
  host:
    - libboost-devel ${{ libboost }}
    - libboost-python-devel ${{ libboost }}
    - eigen ${{ eigen }}
    - mantid == ${{ version }}
    - python ${{ python }}
    - pip ${{ pip }}
    - pyqt ${{ pyqt }}
    - pyqt5-sip ${{ pyqt5_sip }}
    - pyqtwebengine
    - qscintilla2 ${{ qscintilla2 }}
    - qt-main ${{ qt_main }}
    - qt-webengine
    - setuptools
    - tbb-devel ${{ tbb }}
    - versioningit ${{ versioningit }}
    - if: linux
      then:
        - libgl-devel
        - xorg-libxxf86vm
        - xorg-libx11
        - xorg-xorgproto
    - if: osx or linux
      then:
        - libopenblas ${{ libopenblas }}
  run:
    - mantid == ${{ version }}
    - matplotlib ${{ matplotlib }}
    - ${{ pin_compatible("qscintilla2", upper_bound="x.x") }}
    - ${{ pin_compatible("qt-main", upper_bound="x.x") }}
    - qtpy ${{ qtpy }}
    - python
    - if: linux
      then:
        - qt-gtk-platformtheme
  run_exports:
    - ${{ pin_subpackage('mantidqt', upper_bound='x.x.x') }}

tests:
  - python:
      imports:
        - mantid.kernel
        - mantidqt
        - mantidqt.icons

about:
  license: GPL-3.0-or-later
  summary: Mantid provides a framework that supports high-performance computing and visualisation of materials science data.
  homepage: https://github.com/mantidproject/mantid

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
    - peterfpeterson
