# extensions associated with c++
cpp: &files_cpp
 - '**/*.cxx'
 - '**/*.cpp'
 - '**/*.h'
 - '**/*.hxx'
 - '**/*.tcc'
# extensions associated with python
py: &files_py
 - '**/*.py'
# pixi environment files
pixi: &files_pixi
 - .pixi-version
 - pixi.lock
 - pixi.toml
# files that affect the build configuration
configuration: &files_config
 - CMakePresets.json
 - 'buildconfig/CMake/**'
 - pyproject.toml
 - setup.py
# files that affect CI
workflows: &files_workflow
 - 'buildconfig/Jenkins/**'
 - '.github/actions/**'
 - '.github/matchers/**'
 - '.github/workflows/**'
 - '.github/filters.yaml'
### filters used in individual jobs and steps
doxygen:
 - *files_config
 - *files_pixi
 - *files_cpp
 - 'Framework/Doxygen/**'
 - 'conda/recipes/mantid-developer/**'
 - 'conda/recipes/conda_build_config.yaml'
 - '.github/filters.yaml'
 - '.github/actions/doxygen-build/**'
 - '.github/workflows/doxygen-publish.yml'
devsite:
 - *files_config
 - *files_pixi
 - 'dev-docs/**'
 - 'conda/recipes/mantid-developer/**'
 - 'conda/recipes/conda_build_config.yaml'
 - '.github/filters.yaml'
 - '.github/actions/devsite-build/**'
 - '.github/workflows/devdocs-publish.yml'
code_changes: &files_code_changes
 - *files_cpp
 - *files_py
 - *files_config
 - *files_pixi
 - *files_workflow
 - 'Framework/**'
 - 'instrument/**'
 - 'qt/**'
 - 'scripts/**'
 - 'tools/**'
user_docs:
 - *files_code_changes
 - 'docs/**'
# files that specifically affect the cppcheck job
cppcheck: &files_cppcheck_config
 - 'buildconfig/CMake/CppCheckSetup.cmake'
 - 'buildconfig/CMake/FindCppcheck.cmake'
 - 'buildconfig/CMake/CppCheck_Suppressions.txt.in'
 - 'buildconfig/CMake/cppcheck-clean-compile-commands.py'
 - CMakePresets.json
 - '.github/filters.yaml'
 - '.github/actions/cppcheck-build/**'
 - '.github/matchers/cppcheck.json'
 - '.github/workflows/pr_build_and_test.yml'
# cpp source changes OR cppcheck config changes -> run cppcheck
files_cppcheck:
 - *files_cpp
 - *files_cppcheck_config
 - *files_pixi
