# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - Roadmap
# Label to use when marking an issue as stale
staleLabel: Stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in 6 months. It will be closed in 7 days if no further activity occurs.

  Allowing issues to close as stale helps us filter out issues which can wait
  for future development time. All issues closed by stale bot act like normal issues; they can be searched for, commented on or reopened at any point.

  If you'd like a closed stale issue to be considered,
  feel free to either re-open the issue directly or contact a developer.

  To extend the lifetime of an issue please comment below,
  it helps us see that this is still affecting you and you want
  it fixed in the near-future. Extending the lifetime of an issue
  may cause the development team to prioritise it over other issues,
  which may be closed as stale instead.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed automatically. If this still affects you please
  re-open this issue with a comment or contact us so we can look into resolving it.
