import os

print 'In SConscript'

#GET LIST OF TESTS
path = '../'
testfolder = '/test'

testsToRun = []

#get list of directories in trunk
dirList = os.listdir(path)

for fname in dirList:
	if os.path.isdir(path + fname):
		if os.path.isdir(fname) != '.svn' and os.path.isdir(fname) != 'LinuxBuildScripts' and os.path.isdir(fname) != 'Tests':
			#does folder contain /test?
			if os.path.exists(path + fname + testfolder):
				files = os.listdir(path + fname + testfolder)
				for file in files:
					if file.endswith('.h'):
						testsToRun.append(fname + testfolder + '/' +  file + '\n')
			
			
		

f=open('../TestsToRun', 'w')
f.writelines(testsToRun)
f.close()

env=Environment()

f=open('../TestsToRun', 'r')

for test in f:
	doth = '../' + test.strip() 
	print doth
	temp= test.split('/')
	dotcpp = temp[-1].strip().rstrip('.h') + '.cpp'
	print dotcpp
	os.popen('cxxtestgen.pl --error-printer -o ' + dotcpp + ' ' + doth)
	env.Program(dotcpp)
