#pylint: disable=invalid-name
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/inelastic/dgs_diagnose_detectors.ui'
#
# Created: Tue Oct 16 09:29:18 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DiagDetsFrame(object):
    def setupUi(self, DiagDetsFrame):
        DiagDetsFrame.setObjectName(_fromUtf8("DiagDetsFrame"))
        DiagDetsFrame.resize(883, 1036)
        DiagDetsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        DiagDetsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_4 = QtGui.QVBoxLayout(DiagDetsFrame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.white_beam_tests_gb = QtGui.QGroupBox(DiagDetsFrame)
        self.white_beam_tests_gb.setObjectName(_fromUtf8("white_beam_tests_gb"))
        self.verticalLayout = QtGui.QVBoxLayout(self.white_beam_tests_gb)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.high_counts_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.high_counts_label.setMinimumSize(QtCore.QSize(137, 0))
        self.high_counts_label.setObjectName(_fromUtf8("high_counts_label"))
        self.horizontalLayout_4.addWidget(self.high_counts_label)
        self.high_counts_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.high_counts_edit.sizePolicy().hasHeightForWidth())
        self.high_counts_edit.setSizePolicy(sizePolicy)
        self.high_counts_edit.setObjectName(_fromUtf8("high_counts_edit"))
        self.horizontalLayout_4.addWidget(self.high_counts_edit)
        self.low_counts_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.low_counts_label.setMinimumSize(QtCore.QSize(135, 0))
        self.low_counts_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.low_counts_label.setObjectName(_fromUtf8("low_counts_label"))
        self.horizontalLayout_4.addWidget(self.low_counts_label)
        self.low_counts_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_counts_edit.sizePolicy().hasHeightForWidth())
        self.low_counts_edit.setSizePolicy(sizePolicy)
        self.low_counts_edit.setObjectName(_fromUtf8("low_counts_edit"))
        self.horizontalLayout_4.addWidget(self.low_counts_edit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.median_test_high_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.median_test_high_label.setMinimumSize(QtCore.QSize(137, 0))
        self.median_test_high_label.setObjectName(_fromUtf8("median_test_high_label"))
        self.horizontalLayout_5.addWidget(self.median_test_high_label)
        self.median_test_high_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.median_test_high_edit.sizePolicy().hasHeightForWidth())
        self.median_test_high_edit.setSizePolicy(sizePolicy)
        self.median_test_high_edit.setObjectName(_fromUtf8("median_test_high_edit"))
        self.horizontalLayout_5.addWidget(self.median_test_high_edit)
        self.median_test_low_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.median_test_low_label.setMinimumSize(QtCore.QSize(135, 0))
        self.median_test_low_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.median_test_low_label.setObjectName(_fromUtf8("median_test_low_label"))
        self.horizontalLayout_5.addWidget(self.median_test_low_label)
        self.median_test_low_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.median_test_low_edit.sizePolicy().hasHeightForWidth())
        self.median_test_low_edit.setSizePolicy(sizePolicy)
        self.median_test_low_edit.setObjectName(_fromUtf8("median_test_low_edit"))
        self.horizontalLayout_5.addWidget(self.median_test_low_edit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.median_test_out_high_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.median_test_out_high_label.setMinimumSize(QtCore.QSize(137, 0))
        self.median_test_out_high_label.setObjectName(_fromUtf8("median_test_out_high_label"))
        self.horizontalLayout_12.addWidget(self.median_test_out_high_label)
        self.median_test_out_high_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.median_test_out_high_edit.sizePolicy().hasHeightForWidth())
        self.median_test_out_high_edit.setSizePolicy(sizePolicy)
        self.median_test_out_high_edit.setObjectName(_fromUtf8("median_test_out_high_edit"))
        self.horizontalLayout_12.addWidget(self.median_test_out_high_edit)
        self.median_test_out_low_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.median_test_out_low_label.setMinimumSize(QtCore.QSize(135, 0))
        self.median_test_out_low_label.setObjectName(_fromUtf8("median_test_out_low_label"))
        self.horizontalLayout_12.addWidget(self.median_test_out_low_label)
        self.median_test_out_low_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.median_test_out_low_edit.sizePolicy().hasHeightForWidth())
        self.median_test_out_low_edit.setSizePolicy(sizePolicy)
        self.median_test_out_low_edit.setObjectName(_fromUtf8("median_test_out_low_edit"))
        self.horizontalLayout_12.addWidget(self.median_test_out_low_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.errorbar_crit_label = QtGui.QLabel(self.white_beam_tests_gb)
        self.errorbar_crit_label.setMinimumSize(QtCore.QSize(137, 0))
        self.errorbar_crit_label.setObjectName(_fromUtf8("errorbar_crit_label"))
        self.horizontalLayout_10.addWidget(self.errorbar_crit_label)
        self.errorbar_crit_edit = QtGui.QLineEdit(self.white_beam_tests_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorbar_crit_edit.sizePolicy().hasHeightForWidth())
        self.errorbar_crit_edit.setSizePolicy(sizePolicy)
        self.errorbar_crit_edit.setObjectName(_fromUtf8("errorbar_crit_edit"))
        self.horizontalLayout_10.addWidget(self.errorbar_crit_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addWidget(self.white_beam_tests_gb)
        self.eff_var_test_gb = QtGui.QGroupBox(DiagDetsFrame)
        self.eff_var_test_gb.setObjectName(_fromUtf8("eff_var_test_gb"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.eff_var_test_gb)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.det_van2_label = QtGui.QLabel(self.eff_var_test_gb)
        self.det_van2_label.setMinimumSize(QtCore.QSize(160, 0))
        self.det_van2_label.setObjectName(_fromUtf8("det_van2_label"))
        self.horizontalLayout_6.addWidget(self.det_van2_label)
        self.det_van2_edit = QtGui.QLineEdit(self.eff_var_test_gb)
        self.det_van2_edit.setObjectName(_fromUtf8("det_van2_edit"))
        self.horizontalLayout_6.addWidget(self.det_van2_edit)
        self.det_van2_browse = QtGui.QPushButton(self.eff_var_test_gb)
        self.det_van2_browse.setObjectName(_fromUtf8("det_van2_browse"))
        self.horizontalLayout_6.addWidget(self.det_van2_browse)
        spacerItem4 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ratio_var_crit_label = QtGui.QLabel(self.eff_var_test_gb)
        self.ratio_var_crit_label.setMinimumSize(QtCore.QSize(160, 0))
        self.ratio_var_crit_label.setObjectName(_fromUtf8("ratio_var_crit_label"))
        self.horizontalLayout_7.addWidget(self.ratio_var_crit_label)
        self.ratio_var_crit_edit = QtGui.QLineEdit(self.eff_var_test_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratio_var_crit_edit.sizePolicy().hasHeightForWidth())
        self.ratio_var_crit_edit.setSizePolicy(sizePolicy)
        self.ratio_var_crit_edit.setObjectName(_fromUtf8("ratio_var_crit_edit"))
        self.horizontalLayout_7.addWidget(self.ratio_var_crit_edit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.eff_var_test_gb)
        self.background_check_gb = QtGui.QGroupBox(DiagDetsFrame)
        self.background_check_gb.setCheckable(True)
        self.background_check_gb.setChecked(False)
        self.background_check_gb.setObjectName(_fromUtf8("background_check_gb"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.background_check_gb)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.sambkg_median_test_high_label = QtGui.QLabel(self.background_check_gb)
        self.sambkg_median_test_high_label.setMinimumSize(QtCore.QSize(133, 0))
        self.sambkg_median_test_high_label.setObjectName(_fromUtf8("sambkg_median_test_high_label"))
        self.horizontalLayout_8.addWidget(self.sambkg_median_test_high_label)
        self.sambkg_median_test_high_edit = QtGui.QLineEdit(self.background_check_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sambkg_median_test_high_edit.sizePolicy().hasHeightForWidth())
        self.sambkg_median_test_high_edit.setSizePolicy(sizePolicy)
        self.sambkg_median_test_high_edit.setObjectName(_fromUtf8("sambkg_median_test_high_edit"))
        self.horizontalLayout_8.addWidget(self.sambkg_median_test_high_edit)
        self.sambkg_median_test_low_label = QtGui.QLabel(self.background_check_gb)
        self.sambkg_median_test_low_label.setMinimumSize(QtCore.QSize(110, 0))
        self.sambkg_median_test_low_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sambkg_median_test_low_label.setObjectName(_fromUtf8("sambkg_median_test_low_label"))
        self.horizontalLayout_8.addWidget(self.sambkg_median_test_low_label)
        self.sambkg_median_test_low_edit = QtGui.QLineEdit(self.background_check_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sambkg_median_test_low_edit.sizePolicy().hasHeightForWidth())
        self.sambkg_median_test_low_edit.setSizePolicy(sizePolicy)
        self.sambkg_median_test_low_edit.setObjectName(_fromUtf8("sambkg_median_test_low_edit"))
        self.horizontalLayout_8.addWidget(self.sambkg_median_test_low_edit)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sambkg_errorbar_crit_label = QtGui.QLabel(self.background_check_gb)
        self.sambkg_errorbar_crit_label.setMinimumSize(QtCore.QSize(133, 0))
        self.sambkg_errorbar_crit_label.setObjectName(_fromUtf8("sambkg_errorbar_crit_label"))
        self.horizontalLayout_2.addWidget(self.sambkg_errorbar_crit_label)
        self.sambkg_errorbar_crit_edit = QtGui.QLineEdit(self.background_check_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sambkg_errorbar_crit_edit.sizePolicy().hasHeightForWidth())
        self.sambkg_errorbar_crit_edit.setSizePolicy(sizePolicy)
        self.sambkg_errorbar_crit_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sambkg_errorbar_crit_edit.setObjectName(_fromUtf8("sambkg_errorbar_crit_edit"))
        self.horizontalLayout_2.addWidget(self.sambkg_errorbar_crit_edit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tof_start_label = QtGui.QLabel(self.background_check_gb)
        self.tof_start_label.setMinimumSize(QtCore.QSize(133, 0))
        self.tof_start_label.setObjectName(_fromUtf8("tof_start_label"))
        self.horizontalLayout_9.addWidget(self.tof_start_label)
        self.tof_start_edit = QtGui.QLineEdit(self.background_check_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tof_start_edit.sizePolicy().hasHeightForWidth())
        self.tof_start_edit.setSizePolicy(sizePolicy)
        self.tof_start_edit.setObjectName(_fromUtf8("tof_start_edit"))
        self.horizontalLayout_9.addWidget(self.tof_start_edit)
        self.tof_end_label = QtGui.QLabel(self.background_check_gb)
        self.tof_end_label.setMinimumSize(QtCore.QSize(110, 0))
        self.tof_end_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tof_end_label.setObjectName(_fromUtf8("tof_end_label"))
        self.horizontalLayout_9.addWidget(self.tof_end_label)
        self.tof_end_edit = QtGui.QLineEdit(self.background_check_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tof_end_edit.sizePolicy().hasHeightForWidth())
        self.tof_end_edit.setSizePolicy(sizePolicy)
        self.tof_end_edit.setObjectName(_fromUtf8("tof_end_edit"))
        self.horizontalLayout_9.addWidget(self.tof_end_edit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.background_check_gb)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reject_zero_bg_cb = QtGui.QCheckBox(DiagDetsFrame)
        self.reject_zero_bg_cb.setStyleSheet(_fromUtf8(".QCheckBox { font: bold; }"))
        self.reject_zero_bg_cb.setChecked(False)
        self.reject_zero_bg_cb.setObjectName(_fromUtf8("reject_zero_bg_cb"))
        self.horizontalLayout_3.addWidget(self.reject_zero_bg_cb)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.psd_bleed_gb = QtGui.QGroupBox(DiagDetsFrame)
        self.psd_bleed_gb.setCheckable(True)
        self.psd_bleed_gb.setChecked(False)
        self.psd_bleed_gb.setObjectName(_fromUtf8("psd_bleed_gb"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.psd_bleed_gb)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.max_framerate_label = QtGui.QLabel(self.psd_bleed_gb)
        self.max_framerate_label.setMinimumSize(QtCore.QSize(133, 0))
        self.max_framerate_label.setObjectName(_fromUtf8("max_framerate_label"))
        self.horizontalLayout_11.addWidget(self.max_framerate_label)
        self.max_framerate_edit = QtGui.QLineEdit(self.psd_bleed_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_framerate_edit.sizePolicy().hasHeightForWidth())
        self.max_framerate_edit.setSizePolicy(sizePolicy)
        self.max_framerate_edit.setObjectName(_fromUtf8("max_framerate_edit"))
        self.horizontalLayout_11.addWidget(self.max_framerate_edit)
        self.ignored_pixels_label = QtGui.QLabel(self.psd_bleed_gb)
        self.ignored_pixels_label.setMinimumSize(QtCore.QSize(110, 0))
        self.ignored_pixels_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ignored_pixels_label.setObjectName(_fromUtf8("ignored_pixels_label"))
        self.horizontalLayout_11.addWidget(self.ignored_pixels_label)
        self.ignored_pixels_edit = QtGui.QLineEdit(self.psd_bleed_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ignored_pixels_edit.sizePolicy().hasHeightForWidth())
        self.ignored_pixels_edit.setSizePolicy(sizePolicy)
        self.ignored_pixels_edit.setObjectName(_fromUtf8("ignored_pixels_edit"))
        self.horizontalLayout_11.addWidget(self.ignored_pixels_edit)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.psd_bleed_gb)
        spacerItem11 = QtGui.QSpacerItem(17, 453, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)

        self.retranslateUi(DiagDetsFrame)
        QtCore.QMetaObject.connectSlotsByName(DiagDetsFrame)

    def retranslateUi(self, DiagDetsFrame):
        DiagDetsFrame.setWindowTitle(QtGui.QApplication.translate("DiagDetsFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.white_beam_tests_gb.setTitle(QtGui.QApplication.translate("DiagDetsFrame", "Detector Vanadium Tests", None, QtGui.QApplication.UnicodeUTF8))
        self.high_counts_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "High counts", None, QtGui.QApplication.UnicodeUTF8))
        self.low_counts_label.setText(QtGui.QApplication.translate("DiagDetsFrame", " Low counts", None, QtGui.QApplication.UnicodeUTF8))
        self.median_test_high_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Median test high", None, QtGui.QApplication.UnicodeUTF8))
        self.median_test_low_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "        Median test low", None, QtGui.QApplication.UnicodeUTF8))
        self.median_test_out_high_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Median high outliers", None, QtGui.QApplication.UnicodeUTF8))
        self.median_test_out_low_label.setText(QtGui.QApplication.translate("DiagDetsFrame", " Median low outliers", None, QtGui.QApplication.UnicodeUTF8))
        self.errorbar_crit_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Errorbar Criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.eff_var_test_gb.setTitle(QtGui.QApplication.translate("DiagDetsFrame", "Efficiency Variation Test", None, QtGui.QApplication.UnicodeUTF8))
        self.det_van2_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Detector Van 2", None, QtGui.QApplication.UnicodeUTF8))
        self.det_van2_browse.setText(QtGui.QApplication.translate("DiagDetsFrame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.ratio_var_crit_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Ratio variation criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.background_check_gb.setTitle(QtGui.QApplication.translate("DiagDetsFrame", "Background Check", None, QtGui.QApplication.UnicodeUTF8))
        self.sambkg_median_test_high_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Median test high", None, QtGui.QApplication.UnicodeUTF8))
        self.sambkg_median_test_low_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Median test low", None, QtGui.QApplication.UnicodeUTF8))
        self.sambkg_errorbar_crit_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Errorbar Criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_start_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "TOF Start", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_end_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "TOF End", None, QtGui.QApplication.UnicodeUTF8))
        self.reject_zero_bg_cb.setText(QtGui.QApplication.translate("DiagDetsFrame", "Reject zero background", None, QtGui.QApplication.UnicodeUTF8))
        self.psd_bleed_gb.setTitle(QtGui.QApplication.translate("DiagDetsFrame", "PSD Bleed", None, QtGui.QApplication.UnicodeUTF8))
        self.max_framerate_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Max framerate", None, QtGui.QApplication.UnicodeUTF8))
        self.ignored_pixels_label.setText(QtGui.QApplication.translate("DiagDetsFrame", "Ignored pixels", None, QtGui.QApplication.UnicodeUTF8))

