reviews:
  review_status: false
  auto_review:
    enabled: false

tools:
  github-checks:
    enabled: false

chat:
  auto_reply: false

# for our friends across the pond
code_generation:
  docstrings:
    language: en-GB
