#ifndef MANTID_CURVEFITTINGTEST_PRECOMPILED_HEADER_H_
#define MANTID_CURVEFITTINGTEST_PRECOMPILED_HEADER_H_

#include <cxxTest/TestSuite.h>
#undef _CXXTEST_LONGLONG // Kill a warning

#endif //MANTID_CURVEFITTING_PRECOMPILED_HEADER_H_