#ifndef MANTID_MDALGORITHMS_PRECOMPILEDHEADER_H_
#define MANTID_MDALGORITHMS_PRECOMPILEDHEADER_H_

#include "MantidAPI/Algorithm.h"
#include "MantidKernel/Exception.h"

#endif // MANTID_MDALGORITHMS_PRECOMPILEDHEA
