#!/bin/sh
#
# Copyright 2013 ISIS Rutherford Appleton Laboratory & NScD Oak Ridge National Laboratory
#
# This file is part of Mantid.
#
# Mantid is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Mantid is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File change history is stored at: <https://github.com/mantidproject/mantid>

# Set top-level command name
CMD_NAME="new"
# Prefix for branch names
DEFAULT_PREFIX="feature/"
# Base branch for new branches
BASE_BRANCH="origin/master"

# Get directory of this file
# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export CMDFILE_DIR=$(dirname "$(echo "$0" | sed -e 's@\\@/@g')")

usage() {
    echo "Usage: git ${CMD_NAME} [SWITCHES] <ticketno> <short_descr>"
    echo "Start working on a new ticket by creating a branch from the information"
    echo "supplied. The branch is created using origin/master as a start point and"
    echo "a 'git fetch' is performed beforehand. The branch prefix can be specified"
    echo "using the -p flag."
    echo
    echo "If the branch name exists in the list given by 'git branch -r' an error"
    echo "is raised."
    echo
    echo "Equivalent to:"
    echo "  git fetch -p"
    echo "  git checkout --no-track -b [PREFIX]<ticketno>_short_descr"
    echo
    echo "Positional arguments:"
    echo "  ticketno      The TRAC ticket reference number"
    echo "  short_descr   A short description of the branch (without spaces)"
    echo 
    echo "Switches:"
    echo "  -p            When creating a branch use this prefix in the"
    echo "                name (default=feature/)"
}

get_opts() {
    # Can't use getopt cross-platform
    # Allow either 2 or 4 arguments
    if [ ! $# -eq 2 -a ! $# -eq 4 ]; then
	usage
	exit 1
    fi
    
    branchprefix=${DEFAULT_PREFIX}
    prefix_next=0
    pos_arg=0
    for i in "$@"; do
	if [ "$i" = "-p" ]; then
	    prefix_next=1
	    continue
	fi
	if [ ${prefix_next} -eq 1 ]; then
	    prefix_next=0
	    branchprefix=${i}
	else
	    case $pos_arg in
		0) ticketno=$i;;
		1) descr=$i;;
	    esac
	    pos_arg=$((pos_arg+1))
	fi
    done

    # Make sure the prefix ends with a / by removing it
    # if it exists and adding it back
    branchprefix=${branchprefix%%"/"}
    branchprefix=${branchprefix}"/"
}

main() {
  get_opts "$@"
 
  echo "Creating new branch ${branchprefix}${ticketno}_${descr} based on ${BASE_BRANCH}"
  # Check if there are changes and warn as user may have forgotten


}

main "$@"
