#!/bin/sh
# 
# Supports the git finish command
#
# Copyright 2013 ISIS Rutherford Appleton Laboratory & NScD Oak Ridge National Laboratory
#
# This file is part of Mantid.
#
# Mantid is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Mantid is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# File change history is stored at: <https://github.com/mantidproject/mantid>

# Set top-level command name
CMD_NAME="finish"
# Branch that the build servers see
BUILDER_BRANCH="develop"

# Set git to merge silently if everything succceeded
# See http://git-blame.blogspot.co.uk/2012/02/anticipating-git-1710.html
export GIT_MERGE_AUTOEDIT=no

# Get directory of this file
# The sed expression here replaces all backslashes by forward slashes.
# This helps our Windows users, while not bothering our Unix users.
export CMDFILE_DIR=$(dirname "$(echo "$0" | sed -e 's@\\@/@g')")

usage() {
    echo "Usage: git ${CMD_NAME} [SWITCHES]"
    echo "'Finishes' the current branch. In reality this simply means pushing pushing"
    echo "the branch to origin so that it can be tested. If it is detected that some commits on"
    echo "this branch have not been merged to develop first, it prints a warning to do so."
    echo
    echo "The current branch must not be master or ${BUILDER_BRANCH}, if it is then the script"
    echo "aborts. "
    echo
    echo "Equivalent to:"    
    echo "  git push origin <branchname>"
    echo
    echo "Switches:"
    echo "  -h  Prints this help"
}

checkargs() {
    # Can't use getopt cross-platform
    if [  $# -ne 0 -a $# -ne 1 ]; then
        usage
    exit 1
    fi

    args=$@
    for i in $args; do
        case $i in
            "-h")
                usage
                exit 0
                ;;
        esac
    done
}

main() {
    # Helper functions
    . "${CMDFILE_DIR}/gitworkflow-helpers"
    
    checkargs "$@"

    # Sanity check
    currentbranch=$(current_branch)
    if [ ${currentbranch} = "${BUILDER_BRANCH}" -o ${currentbranch} = "master" ]; then
        echo "Current branch is ${current}, do not use git ${CMD_NAME} to push ${current}."
        exit 1
    fi

    # Require a clean state, i.e. no local modifications
    local_modifications
    if [ $? -eq 1 ]; then
        echo "You have local modifications, it does not look like you are finished. Either:"
        echo " 1) Commit the changes and rerun this command or"
        echo " 2) Run 'git stash' and then rerun this command. This will NOT include them in changes on the branch."
        exit 1
    fi

    git_halt_on_error fetch -p
    branch_is_merged HEAD origin/${BUILDER_BRANCH}
    if [ $? -eq 0 ]; then
        echo "Error: Branch has not been fully merged to ${BUILDER_BRANCH}."
        echo "Run 'git checkbuild' to check the branch on the buildservers and then rerun this command."
        exit 1
    fi
    
    # Run the macro
    git_halt_on_error push origin ${currentbranch}
}

main "$@"
