#For MantidKernel

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder, recursive=False)

#Import environment
Import('env')
myenv = env.Clone()
# DLL_EXPORTS macro for ANN library
myenv.Append(CPPDEFINES=[('IN_MANTID_KERNEL',1), 'DLL_EXPORTS'])

listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidKernel', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'], PDB='lib/MantidKernel.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': [ 'MantidKernel' ] }
Return('retval')
