# Note that this a workaround
# When introduced? During the Python2 to Python3 conversion
# Why introduced? The autogenerated file ui_MainWindow.py contains a line
#                 from MplFigureCancas import MplFigureCanvas
#                 which should be
#                 from .MpsFigureCanvas import MplFigureCanvas
#                 for Python3, but since it is autogenerated we cannot change
#                 this easily.
import mantid
import os
import sys
path = mantid.config["pythonscripts.directories"].split(";")[0]
path = os.path.join(path[:path.index("scripts")], "scripts", "FilterEvents")
sys.path.append(path)
