#For MantidNexus

import os
import MantidBuild

#GET LIST OF CPPS files
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_NEXUS',1),'NOMINMAX']])
listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidNexus', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'], PDB='lib/MantidNexus.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': ['MantidNexus'] }
Return('retval')
