#!/bin/bash -ex

# This script expects to be in a POSIX environment, it will run our CI workflow on a POSIX environment depending
# on the flags and args passed. This script will clean up build areas
#
# Script usage:
# clean-builder <path-to-workspace> [options]
#
# Example command to run a PR build on ubuntu:
# clean-builder /jenkins/workspace_dir/
#
# Expected args:
#   1. WORKSPACE: path to the workspace/source code that this should run inside
#
# Possible flags:
#   --clean-build: Clear the build folder and build from scratch
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
start_time=$(date +%s)

# Check arguments passed are 2 or higher, and aren't optional flags.
if [[ $# < 1 || $1 == "--"* ]]; then
    echo "Pass 1 argument followed by optional flags usage: clean-builder <path-to-workspace> [options]"
    exit 1
fi

WORKSPACE=$1
shift

BUILD_DIR=$WORKSPACE/build

CLEAN_BUILD=false

# Handle flag inputs
while [ ! $# -eq 0 ]
do
    case "$1" in
        --clean-build) CLEAN_BUILD=true ;;
        *)
            echo "Argument not accepted: $1"
            exit 1
            ;;
  esac
  shift
done

# Clean the source tree to remove stale configured files. Only remove
# the build and Miniforge directories if this is a clean build
pushd $WORKSPACE
if [[ $CLEAN_BUILD  == true ]]; then
    # git clean will delete most things in build but leave subrepositories such as build/_deps/span-src
    # so we need to remove the whole of build/ by hand
    rm -fr $BUILD_DIR
    rm -fr "$WORKSPACE/.pixi/" # less logs with rm
else
    git_clean_excludes_extra="--exclude=build --exclude=miniforge --exclude=.pixi"
fi
# -d is recurse into directories
# -x ignores what is listed in the .gitignore
git clean -d -x --force --exclude=".Xauthority-*" $git_clean_excludes_extra

# Delete old files from incremental builds
if [ -d $BUILD_DIR ]; then
    rm -rf ${BUILD_DIR}/bin ${BUILD_DIR}/ExternalData ${BUILD_DIR}/Testing
    find $WORKSPACE \( -iname 'TEST-*.xml' -o -name 'Test.xml' \) -delete
fi

# Clean up artifacts from previous builds
rm -f -- *.dmg *.rpm *.deb *.tar.gz *.tar.xz *.exe
# Remove test logs from previous builds
rm -rf  $BUILD_DIR/test_logs

popd # go back to starting location
