#!/bin/bash -ex

# This script will set up a conda environment before running the pre-commit shell script.
#
# Script usage:
# conda-pre-commit <job-name> <path-to-workspace>
#
# Example command to run a PR build on ubuntu:
# conda-pre-commit pull_requests-cppcheck ${WORKSPACE}
#
# Expected args:
#   1. JOB_NAME: If the name of the job contains 'pull_requests', then pre-commit only runs in he diff
#   2. WORKSPACE: path to the workspace/source code that this should run inside, Windows Caveat: Only use / for
#                 this argument do not use \\ or \ in the path.

# Check arguments passed are 2, and aren't optional flags.
if [[ $# -lt 2 ]]; then
    echo "Usage: conda-pre-commit <job-name> <path-to-workspace>"
    exit 1
fi

# SCRIPT_DIR discovery from https://stackoverflow.com/a/9107028 by https://stackoverflow.com/users/1184238/andrew-norrie
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JOB_NAME=$1
WORKSPACE=$2
shift 2

EXPECTED_MAMBAFORGE_PATH=$WORKSPACE/mambaforge # Install into the WORKSPACE_DIR
EXPECTED_CONDA_PATH=$EXPECTED_MAMBAFORGE_PATH/bin/mamba
CONDA_ENV_NAME="pre-commit"
CLEAN_BUILD=false

# Setup Mambaforge
$SCRIPT_DIR/download-and-install-mambaforge $EXPECTED_MAMBAFORGE_PATH $EXPECTED_CONDA_PATH $CLEAN_BUILD
$SCRIPT_DIR/setup-conda-env $WORKSPACE $EXPECTED_CONDA_PATH $CONDA_ENV_NAME
 $WORKSPACE/mambaforge/etc/profile.d/conda.sh
conda activate $CONDA_ENV_NAME

# Run the script that handles the actual building
$SCRIPT_DIR/pre-commit.sh
