#!/bin/bash -ex

# This script will set up a conda environment before running the cppcheck shell script.
#
# Script usage:
# conda-cppcheck <path-to-workspace>
#
# Example command to run a PR build on ubuntu:
# conda-cppcheck /jenkins/workspace_dir/
#
# Expected args:
#   1. WORKSPACE: path to the workspace/source code that this should run inside, Windows Caveat: Only use / for
#                 this argument do not use \\ or \ in the path.

# Check arguments passed are 2 or higher, and aren't optional flags.
if [[ $# < 1 || $1 == "--"* ]]; then
    echo "Pass 1 argument: conda-cppcheck <path-to-workspace>"
    exit 1
fi

# SCRIPT_DIR discovery from https://stackoverflow.com/a/9107028 by https://stackoverflow.com/users/1184238/andrew-norrie
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE=$1
shift

EXPECTED_MAMBAFORGE_PATH=$WORKSPACE/mambaforge # Install into the WORKSPACE_DIR
if [[ $OSTYPE == "msys" ]]; then
    EXPECTED_CONDA_PATH=$EXPECTED_MAMBAFORGE_PATH/condabin/mamba.bat
else
    EXPECTED_CONDA_PATH=$EXPECTED_MAMBAFORGE_PATH/bin/mamba
fi

CONDA_ENV_NAME="mantid-developer"

CLEAN_BUILD=false

# Setup Mambaforge
$SCRIPT_DIR/download-and-install-mambaforge $EXPECTED_MAMBAFORGE_PATH $EXPECTED_CONDA_PATH $CLEAN_BUILD

# Setup Conda environment
$SCRIPT_DIR/setup-conda-env $WORKSPACE $EXPECTED_CONDA_PATH $CONDA_ENV_NAME

# Activate Conda environment
. $WORKSPACE/mambaforge/etc/profile.d/conda.sh
conda activate $CONDA_ENV_NAME

# Run the script that handles the actual building
$SCRIPT_DIR/cppcheck.sh

