#!/bin/bash -ex

# This script will set up a conda environment before running the pre-commit shell script.
#
# Script usage:
# conda-pre-commit <path-to-workspace> <git-sha> <job-type>
#
# Example command to run a PR build on ubuntu:
# conda-pre-commit pull_requests-cppcheck ${WORKSPACE}
#
# Expected args:
#   1. WORKSPACE: path to the workspace/source code that this should run inside, Windows Caveat: Only use / for
#                 this argument do not use \\ or \ in the path.
#   2. GIT_COMMIT_SHA: SHA of the commit to compare with the base when checking diffs
#   2. JOB_TYPE: An optional job type. If it contains 'pull_requests', then pre-commit only runs in he diff
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/mamba-utils

# Check arguments passed are 2, and aren't optional flags.
if [[ $# -lt 2 ]]; then
    echo "Usage: conda-pre-commit  <path-to-workspace> <job-name>"
    exit 1
fi
SOURCE_DIR=$1
GIT_SHA=$2
JOB_TYPE=$3

# Mamba
setup_mamba $SOURCE_DIR/miniforge "pre-commit"
# rstcheck fails with exit code -11 with Python 3.13
mamba install --yes pre-commit python=3.12

# Run
$SCRIPT_DIR/pre-commit ${SOURCE_DIR} ${GIT_SHA} ${JOB_TYPE}
