#!/bin/bash -ex

# This script will download and install mambaforge if it's not present where expected
#
# Expected args:
#   1. EXPECTED_MAMBAFORGE_PATH: path to where mambaforge should be installed
#   2. CLEAN_BUILD: whether or not to force mambaforge to be removed before attempting to install it again

EXPECTED_MAMBAFORGE_PATH=$1
CLEAN_BUILD=$2
MAMBAFORGE_VERSION=4.11.0-0

LINUX_SHA256="49268ee30d4418be4de852dda3aa4387f8c95b55a76f43fb1af68dcbf8b205c3  Mambaforge-4.11.0-0-Linux-x86_64.sh"
MAC_SHA256="2039f744e272d47878f0bc2ae372f03c7f07881f39a93d693d5445744f36f19d  Mambaforge-4.11.0-0-MacOSX-x86_64.sh"
WINDOWS_SHA256="70e8cb24f329f867155a81bb90b48d9f6d105ca1414e8382cac4f4fd7a1c6529 *Mambaforge-4.11.0-0-Windows-x86_64.exe"

# Only supporting x86_64 at this time for the build process
EXPECTED_MAMBA_EXE=$EXPECTED_MAMBAFORGE_PATH/bin/mamba
if [[ $OSTYPE == 'msys'* ]]; then
    MAMBAFORGE_SCRIPT_NAME=Mambaforge-$MAMBAFORGE_VERSION-Windows-x86_64.exe
    EXPECTED_INSTALLER_SHA=$WINDOWS_SHA256
    EXPECTED_MAMBA_EXE=$EXPECTED_MAMBAFORGE_PATH/condabin/mamba.bat
elif [[ $OSTYPE == 'darwin'* ]]; then
    MAMBAFORGE_SCRIPT_NAME=Mambaforge-$MAMBAFORGE_VERSION-MacOSX-x86_64.sh
    EXPECTED_INSTALLER_SHA=$MAC_SHA256
else
    MAMBAFORGE_SCRIPT_NAME=Mambaforge-$MAMBAFORGE_VERSION-$(uname)-x86_64.sh
    EXPECTED_INSTALLER_SHA=$LINUX_SHA256
fi
URL=https://github.com/conda-forge/miniforge/releases/download/$MAMBAFORGE_VERSION/$MAMBAFORGE_SCRIPT_NAME

if [[ $CLEAN_BUILD  == true ]]; then
    rm -rf $EXPECTED_MAMBAFORGE_PATH
    if [[ -f $MAMBAFORGE_SCRIPT_NAME ]]; then
        rm $MAMBAFORGE_SCRIPT_NAME
    fi
fi

# Ensure conda is installed
if [ ! -f $EXPECTED_MAMBA_EXE ]; then
    echo "Mambaforge not found. Installing version ${MAMBAFORGE_VERSION}"
    if [ ! -f $MAMBAFORGE_SCRIPT_NAME ]; then
        # Download mambaforge
        if [ -x "$(which curl)" ]; then
            curl -L -O $URL
        elif [ -x "$(which wget)" ] ; then
            wget $URL
        else
            echo "Could not download Conda as wget and curl are not installed."
            exit 1
        fi
    fi

    # Compare the sha256 of the downloaded file to the expected sha256
    if [[ $OSTYPE == 'darwin'* ]]; then
        SHA256_DOWNLOADED=$(shasum -a 256 $MAMBAFORGE_SCRIPT_NAME)
    else
        SHA256_DOWNLOADED=$(sha256sum $MAMBAFORGE_SCRIPT_NAME)
    fi

    if [[ $SHA256_DOWNLOADED != $EXPECTED_INSTALLER_SHA ]]; then
        echo "sha256 of downloaded file does not match expected sha256, failing..."
        exit 1
    fi

    if [[ $OSTYPE == 'msys'* ]]; then
        # Replace all / with \ for windows batch support before passing in $EXPECTED_MAMBAFORGE_PATH
        cmd.exe /C "START /wait "" $MAMBAFORGE_SCRIPT_NAME /InstallationType=JustMe /RegisterPython=0 /S /D=${EXPECTED_MAMBAFORGE_PATH////\\}"
        # The paths in the Conda environment shell environments are Windows style. Convert to cygwin style
        cp $EXPECTED_MAMBAFORGE_PATH/etc/profile.d/conda.sh{,.orig}
        cat $EXPECTED_MAMBAFORGE_PATH/etc/profile.d/conda.sh.orig | \
          sed -e '/^export\ CONDA_/s/\\/\//g' | \
          sed -e '/^export\ CONDA_/s/\(\w\)\:/\/\1/g' > $EXPECTED_MAMBAFORGE_PATH/etc/profile.d/conda.sh
    else
        bash $MAMBAFORGE_SCRIPT_NAME -b -p $EXPECTED_MAMBAFORGE_PATH
    fi
    rm $MAMBAFORGE_SCRIPT_NAME
fi
