#!/bin/bash
# Collection of utility functions related to Mamba

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Download mamba, install into a given location &
# source the profiles to ensure mamba is callable
# Args:
#   1. Install prefix
#   2. Optional. If provided, the name of an environment to create and activate
#   3. Optional. If true is specified any existing mamba installation is removed
#   4. Optional. Target platform, e.g. linux-64
setup_mamba () {
  local install_prefix=$1
  local env_name=$2
  local clean=$3
  local platform=$4
  $SCRIPT_DIR/download-and-install-miniforge $install_prefix $clean
  source $install_prefix/etc/profile.d/conda.sh
  source $install_prefix/etc/profile.d/mamba.sh

  if [ -n "$env_name" ]; then
    create_and_activate_env "$env_name" "$platform"
  fi
}

# Assuming the mamba command is available,
# create and activate a mamba environment
# Args:
#   1. Name of environment.
#   2. Optional platform, e.g. linux-64
create_and_activate_env() {
  local env_name=$1
  local conda_subdir_str=$2
  CONDA_SUBDIR=$conda_subdir_str mamba create --yes --name $env_name
  mamba activate $env_name

  if [[ -n "$conda_subdir_str" ]]; then
    conda config --env --set subdir "$conda_subdir_str"
  fi
}
