#!/bin/bash -ex

# This script expects to be in a POSIX environment, the script clones the conda-recipes
# repo and then runs conda builds based on passed args. By default it only clones the
# source, you need to pass a flag to actually build something useful. If building a
# package dependent on a different one it will build and produce that package too.
#
# Script usage:
# package-conda WORKSPACE [options]
#
# Example command to build all of the packages:
# package-conda $WORKSPACE --build-mantid --build-qt --build-docs --build-workbench
#
# Expected args:
#   1. WORKSPACE: path to the base of the working space for a build. The source
#                 must be checked out into a subdirectory and the final conda-bld
#                 outputs are placed in $WORKSPACE/conda-bld
#                 Windows Caveat: Only use / for this argument do
#                 not use \\ or \ in the path.
#
# Possible flags:
#   --build-mantid: build the mantid package using conda-build
#   --build-qt: build the qt package using conda-build (this will implicitly build mantid)
#   --build-docs: build the HTML/Qthelp documentation
#   --build-workbench: build the workbench package using conda-build (this will implicitly build qt and mantid)
#   --git-tag: specify a tag for a release or nightly version
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/mamba-utils

# Setup expected variables
REPO_ROOT_DIR=$SCRIPT_DIR/../../
WORKSPACE=$1
if [[ -z "$WORKSPACE" ]]; then
    echo "A workspace argument is required"
    exit 1
fi
shift
if [[ $OSTYPE == "msys"* ]]; then
    if [[ "$WORKSPACE" == *'\'* ]]; then
        echo "You have \ or \\ in your Workspace path, this is not supported on Windows."
        exit 1
    fi
    WORKSPACE=${WORKSPACE////\\} # Replace // with \
    # Require git settings so that paths can be checked out with longer file names than 260 characters
    if [[ ! $(git config --system --get core.longpaths) == true ]]; then
        echo "This windows machine is does not have longpaths enabled for git, please run this command: git config --system core.longpaths true"
        exit 1
    fi
fi
RECIPES_DIR=$REPO_ROOT_DIR/conda/recipes/

# Parse flags
ENABLE_BUILD_MANTID=false
ENABLE_BUILD_QT=false
ENABLE_BUILD_WORKBENCH=false
ENABLE_BUILD_DOCS=false

# Handle flag inputs
while [ ! $# -eq 0 ]
do
    case "$1" in
        --build-mantid) ENABLE_BUILD_MANTID=true ;;
        --build-qt) ENABLE_BUILD_QT=true ;;
        --build-workbench) ENABLE_BUILD_WORKBENCH=true ;;
        --build-docs) ENABLE_BUILD_DOCS=true ;;
        --git-tag)
            GIT_TAG="$2"
            shift ;;
        *)
            echo "Argument not accepted: $1"
            exit 1
            ;;
  esac
  shift
done

# Mamba
setup_mamba $WORKSPACE/mambaforge "package-conda"
mamba install --yes boa conda-verify versioningit

# Clean up any legacy conda-recipes git clones
cd $WORKSPACE
if [[ -d conda-recipes ]]; then
    rm -rf conda-recipes
fi

# Create a git tag to be used for version information
cd $REPO_ROOT_DIR
if [[ -n "$GIT_TAG" ]]; then
    # If the tag already exists remove it first
    if [[ -n "$(git tag -l $GIT_TAG)" ]]; then
        git tag -d $GIT_TAG
    fi
    git tag -a $GIT_TAG -m "Tagging $GIT_TAG"
fi

# Run conda build. Use a known path so packages built in other steps can be
# copied to a known location and reused.
# Use the workspace root outside of the git tree or conda-build cannot
# copy the source to a working folder
export CONDA_BLD_PATH=$WORKSPACE/conda-bld
if [[ -d $CONDA_BLD_PATH ]]; then
    conda index $CONDA_BLD_PATH
fi
cd $RECIPES_DIR

if [[ $OSTYPE == "msys" ]]; then
    EXTRA_BUILD_OPTIONS="--no-build-id" # Do not use build id as it makes the path too long (>260 chars) for CMake (Legacy Windows API issue)
fi

if [[ $ENABLE_BUILD_MANTID == true ]]; then
    conda mambabuild ./mantid/ $EXTRA_BUILD_OPTIONS
fi
if [[ $ENABLE_BUILD_QT == true ]]; then
    conda mambabuild ./mantidqt/ $EXTRA_BUILD_OPTIONS
fi
if [[ $ENABLE_BUILD_DOCS == true ]]; then
    conda mambabuild ./mantiddocs/ $EXTRA_BUILD_OPTIONS
fi
if [[ $ENABLE_BUILD_WORKBENCH == true ]]; then
    conda mambabuild ./mantidworkbench/ $EXTRA_BUILD_OPTIONS
fi
