#!/bin/bash

# Download and install pixi
install_pixi() {
  # check if pixi is not installed
  if ! command -v pixi >/dev/null 2>&1
  then
    curl -fsSL https://pixi.sh/install.sh | sh
    source ~/.bashrc
  fi
}

# The pixi.toml (manifest) file we use for ci is build programmatically and not kept in git
# since it modifies itself.
setup_pixi_toml() {
  PATH_TO_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  LOCAL_MANIFEST=$PATH_TO_HERE/pixi.toml
  LOCAL_LOCK=$PATH_TO_HERE/pixi.lock
  if [[ -f $LOCAL_MANIFEST ]]; then
    rm $LOCAL_MANIFEST
  fi
  if [[ -f $LOCAL_LOCK ]]; then
    rm $LOCAL_LOCK
  fi

  # if you pass pixi init a path it will make a new directory, so cd there instead
  cd $PATH_TO_HERE
  pixi init -c conda-forge -c neutrons -p linux-64 -p win-64 -p osx-arm64
  pixi workspace --manifest-path $LOCAL_MANIFEST name set mantid-ci
  # environment for running rattler-build
  pixi add --manifest-path $LOCAL_MANIFEST -f rattler-builder rattler-build=0.47 rattler-index versioningit
  pixi add --manifest-path $LOCAL_MANIFEST -f rattler-builder -p linux-64 jq
  pixi add --manifest-path $LOCAL_MANIFEST -f rattler-builder -p osx-arm64 jq
  pixi add --manifest-path $LOCAL_MANIFEST -f rattler-builder -p win-64 m2w64-jq
  pixi workspace --manifest-path $LOCAL_MANIFEST environment add rattler-builder --feature rattler-builder --no-default-feature
  # environment for local mantid-developer build to be installed into
  pixi workspace --manifest-path $LOCAL_MANIFEST channel add -f mantid-developer-ci conda-forge
  pixi workspace --manifest-path $LOCAL_MANIFEST channel add -f mantid-developer-ci neutrons
  pixi workspace --manifest-path $LOCAL_MANIFEST environment add mantid-developer-ci --feature mantid-developer-ci --no-default-feature
  cd -
}

normalise_windows_path() {
    local p="$1"

    # 1. Convert backslashes → forward slashes
    p="${p//\\//}"

    # 2. Strip any leading slash before drive letter: /c/... → c/...
    p="${p#/}"

    # 3. Uppercase the drive letter: c/... → C/...
    p="$(printf '%s' "$p" | sed -E 's/^([a-zA-Z])/\U\1/')"

    # 4. Add colon after drive letter if missing: C/... → C:/...
    p="$(printf '%s' "$p" | sed -E 's/^([A-Z]):?/\1:/')"

    echo "$p"
}

create_mantid_developer_ci() {
  MANTID_ROOT=$1
  if [[ $OSTYPE == "msys"* ]]; then
    MANTID_ROOT=normalise_windows_path "$MANTID_ROOT"
  fi
  PATH_TO_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  setup_pixi_toml
  sh $PATH_TO_HERE/package-conda $MANTID_ROOT --build-mantid-developer
  PLATFORM=$(pixi run --manifest-path $PATH_TO_HERE/pixi.toml -e rattler-builder "pixi info --json | jq -r .platform")
  pixi workspace --manifest-path $PATH_TO_HERE/pixi.toml channel add $MANTID_ROOT/conda-bld -f mantid-developer-ci --prepend
  pixi add --manifest-path $PATH_TO_HERE/pixi.toml --platform $PLATFORM -f mantid-developer-ci mantid-developer
}
