#!/bin/bash -ex

# This script expects an environment to exist in the workspace directory, and
# activated that contains conda-build.
#
# Expected args:
#   1. WORKSPACE: path to the workspace/source code that this should run inside
#                 (mantid repo). Windows Caveat: Only use / for this argument do
#                 not use \\ or \ in the path.
#   2. TOKEN: Token for uploading to anaconda.org
#   3. CHANNEL: Channel to upload to
#   4. LABEL: The label used when uploading to anaconda
#   5. PACKAGES: A list of args that will be uploaded to anaconda cloud.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/mamba-utils

# Parse arguments
WORKSPACE=$1
TOKEN=$2
CHANNEL=$3
LABEL=$4
shift 4

# Setup Mamba
setup_mamba $WORKSPACE/miniforge "publish-anaconda"
mamba install --yes anaconda-client

for package in "$@"
do
    # Skip the Workspace, Token, and Channel args, then upload every other package to the given User
    if [[ $package == *"mantid"* ]]
    then
        echo "Uploading $package"
        anaconda -t $TOKEN upload -u $CHANNEL $package --label $LABEL --force
    fi
done
