#!/bin/bash

# This script expects a setup environment with all dependencies availiable in
# the environment
#
# Expected args:
#   1. WORKSPACE: path to the workspace/source code that this should run inside
#   2. ENABLE_SYSTEM_TESTS: whether or not system tests are being ran/built
#

WORKSPACE=$1
ENABLE_SYSTEM_TESTS=$2

XVFB_SERVER_NUM=101

function run_with_xvfb {
    if [ $(command -v xvfb-run) ]; then
        # Use -e because a bug on RHEL7 means --error-file produces an error: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=337703;msg=2
        # Use -noreset because of an X Display bug caused by a race condition in xvfb: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1102
        xvfb-run -e /dev/stderr --server-args="-core -noreset -screen 0 640x480x24" \
        --server-num=${XVFB_SERVER_NUM} $@
    else
        eval $@
    fi
}

function terminate_xvfb_sessions {
    if [ $(command -v xvfb-run) ]; then
        echo "Terminating existing Xvfb sessions"

        # Kill Xvfb processes
        killall Xvfb || true

        # Remove Xvfb X server lock files
        rm -f /tmp/.X${XVFB_SERVER_NUM}-lock
    fi
}

# Run unit tests
cd $WORKSPACE/build
run_with_xvfb ctest -j$CPU_COUNT --no-compress-output -T Test --schedule-random --output-on-failure
terminate_xvfb_sessions

if [[ ENABLE_SYSTEM_TESTS == true ]]; then
    #TODO: system tests
fi