#!/bin/bash


# This script will setup a working conda environment given the arguements
#
# Expected args:
#   1. WORKSPACE: path to the workspace
#   2. EXPECTED_MAMBAFORGE_PATH: path to where mambaforge should be installed
#   3. EXPECTED_CONDA_PATH: path to the conda executable
#   4. CONDA_ENV_NAME: name of the conda environment

WORKSPACE=$1
EXPECTED_MAMBAFORGE_PATH=$2
EXPECTED_CONDA_PATH=$3
CONDA_ENV_NAME=$4

# If conda env already exists delete it, so the current version of the environment is tested against
ENVS=$($EXPECTED_CONDA_PATH env list)
if [[ $ENVS = *"$EXPECTED_MAMBAFORGE_PATH/envs/$CONDA_ENV_NAME"* ]]; then
    $EXPECTED_CONDA_PATH env remove -n $CONDA_ENV_NAME
fi

# Always create the new environment:
$EXPECTED_CONDA_PATH env create -f $WORKSPACE/mantid-developer-linux.yml