#For MantidDataObjects

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')

#BUILD CODE
shared = env.SharedLibrary('lib/MantidDataObjects', listCpps, LIBS=[ ], LIBPATH=[ ])
static = env.StaticLibrary('lib/MantidDataObjectsStatic', listCpps, LIBS=[ ], LIBPATH=[ ])
retval = { 'shared': shared, 'static': static, 'libs': [ 'MantidDataObjects' ] }
Return('retval')
