# Setup for a faster linker (Linux only). mold links large shared libraries (e.g. Algorithms, DataHandling)
# significantly faster than the default bfd/gold linker.
if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND (CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
  option(USE_MOLD_LINKER "Use the mold linker if available" ON)
  if(USE_MOLD_LINKER)
    find_program(MOLD_FOUND ld.mold)
    if(MOLD_FOUND)
      message(STATUS "Using mold linker")
      string(APPEND CMAKE_EXE_LINKER_FLAGS " -fuse-ld=mold")
      string(APPEND CMAKE_SHARED_LINKER_FLAGS " -fuse-ld=mold")
      string(APPEND CMAKE_MODULE_LINKER_FLAGS " -fuse-ld=mold")
    endif()
  endif()
endif()
