# CMake generated Testfile for 
# Source directory: /home/ewan/mantid/scripts/test/Muon
# Build directory: /home/ewan/mantid/scripts/test/Muon
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(python.Muon.FFTPresenter_test.FFTPresenter_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/FFTPresenter_test.py")
set_tests_properties(python.Muon.FFTPresenter_test.FFTPresenter_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.FFTModel_test.FFTModel_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/FFTModel_test.py")
set_tests_properties(python.Muon.FFTModel_test.FFTModel_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.MaxEntPresenter_test.MaxEntPresenter_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/MaxEntPresenter_test.py")
set_tests_properties(python.Muon.MaxEntPresenter_test.MaxEntPresenter_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.MaxEntModel_test.MaxEntModel_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/MaxEntModel_test.py")
set_tests_properties(python.Muon.MaxEntModel_test.MaxEntModel_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.transformWidget_test.transformWidget_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/transformWidget_test.py")
set_tests_properties(python.Muon.transformWidget_test.transformWidget_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.PeriodicTablePresenter_test.PeriodicTablePresenter_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/PeriodicTablePresenter_test.py")
set_tests_properties(python.Muon.PeriodicTablePresenter_test.PeriodicTablePresenter_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.PeriodicTableModel_test.PeriodicTableModel_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/PeriodicTableModel_test.py")
set_tests_properties(python.Muon.PeriodicTableModel_test.PeriodicTableModel_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.AxisChangerView_test.AxisChangerView_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/AxisChangerView_test.py")
set_tests_properties(python.Muon.AxisChangerView_test.AxisChangerView_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.AxisChangerPresenter_test.AxisChangerPresenter_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/AxisChangerPresenter_test.py")
set_tests_properties(python.Muon.AxisChangerPresenter_test.AxisChangerPresenter_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.PlottingView_test.PlottingView_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/PlottingView_test.py")
set_tests_properties(python.Muon.PlottingView_test.PlottingView_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.PlottingPresenter_test.PlottingPresenter_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/PlottingPresenter_test.py")
set_tests_properties(python.Muon.PlottingPresenter_test.PlottingPresenter_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
add_test(python.Muon.PlottingUtils_test.PlottingUtils_test "/home/ewan/mantid/bin/mantidpython" "--classic" "/home/ewan/mantid/Framework/PythonInterface/test/testhelpers/testrunner.py" "/home/ewan/mantid/scripts/test/Muon/PlottingUtils_test.py")
set_tests_properties(python.Muon.PlottingUtils_test.PlottingUtils_test PROPERTIES  ENVIRONMENT "PYTHONPATH=/home/ewan/mantid/python-xmlrunner-src:/home/ewan/mantid/scripts/test/Muon:" TIMEOUT "300" WORKING_DIRECTORY "/home/ewan/mantid/bin/Testing")
