#ifndef MANTIDPARAVIEWQT_MANTIDPARAVIEWWIDGETS_DLLOPTION_H_
#define MANTIDPARAVIEWQT_MANTIDPARAVIEWWIDGETS_DLLOPTION_H_

#include <MantidKernel/System.h>

#ifdef IN_MANTIDPARAVIEWQT_MANTIDPARAVIEWWIDGETS
#define EXPORT_OPT_MANTIDPARVIEW DLLExport 
#else
#define EXPORT_OPT_MANTIDPARVIEW DLLImport
#endif /* IN_MANTIDQT_MANTIDWIDGETS */

#endif //MANTIDQT_MANTIDWIDGETS_DLLOPTION_H_
