#! /bin/sh
# -------------------------------------------------------------------------
#
# Some libraries (DataObjects & Nexus) have moved in the CPack Mac
# installer. We need to be sure to clean things up if there's a
# previous Mantid install on the machine.
#
# -------------------------------------------------------------------------

echo "=== Starting preflight installer hook ==="
echo

echo "=== Removing old version ==="
if [ -d "/Applications/MantidPlot.app" ]; then
    rm -Rf /Applications/MantidPlot.app
fi

# -------------------------------------------------------------------------
#
# We don't want the Mantid Python modules inside the Python 
# distribution anymore
#
# -------------------------------------------------------------------------

PY_SITE_DIR=/Library/Python/2.6/site-packages
echo "=== Removing Mantid Python package from ${PY_SITE_DIR} ==="
if [ -d "${PY_SITE_DIR}/MantidFramework" ]; then
  rm -Rf ${PY_SITE_DIR}/MantidFramework
fi

if [ -f "${PY_SITE_DIR}/Mantid-1.0-py2.6.egg-info" ]; then
  rm -f ${PY_SITE_DIR}/Mantid-1.0-py2.6.egg-info
fi

# -------------------------------------------------------------------------
#
# Remove MANTIDPATH from environment.plist (but back it up)
#
# -------------------------------------------------------------------------
PLIST=${HOME}/.MacOS/environment.plist
if [ -f ${PLIST} ]; then
  # Backup
  mv ${PLIST} ${PLIST}.bak
  cat ${PLIST}.bak | sed -e 's@<key>MANTIDPATH</key>@@g' | sed -e 's@<string>/Applications/MantidPlot.app/Contents/MacOS</string>@@g' > ${PLIST}
fi

# -------------------------------------------------------------------------
#
# Remove MANTIDPATH references from .profile (but back it up)
#
# -------------------------------------------------------------------------
PROFILE=${HOME}/.profile
if [ -f ${PROFILE} ]; then
  # Backup
  mv ${PROFILE} ${PROFILE}.bak
  cat ${PROFILE}.bak | sed -e 's@export MANTIDPATH=/Applications/MantidPlot.app/Contents/MacOS@@g' | sed -e 's@:$MANTIDPATH@@g' > ${PROFILE}
fi

