#!/bin/sh
# @file check_build check for rpm build
#
# run this from cron at regular intervals
#
# @author Freddie Akeroyd, STFC ISIS Facility
# @date 30/03/2009
#
LOCK_FILE=/tmp/`basename $0`.lock
if test -e $LOCK_FILE; then
    echo "$LOCK_FILE exists"
    exit
else
    touch $LOCK_FILE
fi
trap "rm -f $LOCK_FILE" 0

echo "Running $0"

MBUILD=/tmp/mantid_build
[ -d $MBUILD ] || mkdir $MBUILD
n=`ls $MBUILD | wc -l`
if [ $n -gt 0 ]; then
    rev=`( cd $MBUILD; ls ) | head -1`
    rm -f $MBUILD/$rev
    log_file=/var/www/html/buildlog/build_$rev.log
    echo "Building $rev"
    echo "Building $rev" > $log_file
    sh nightly_build "$rev" $log_file >> $log_file 2>&1
fi
if test "$1" = "HEAD" -o "`date +%H%M`" = "2227"; then
    log_file=/var/www/html/buildlog/build.log
    if test "$1" = "HEAD"; then
	rev=""
        echo "Building HEAD"
        echo "Building HEAD" > $log_file
    else
	rev=`svn info http://svn.mantidproject.org/mantid/tags/systemtested  |  grep "Last Changed Rev:"  |  awk '{print $4}'`
        echo "Building system tested version ($rev)"
        echo "Building system tested version ($rev)" > $log_file
    fi
    sh nightly_build "$rev" $log_file >> $log_file 2>&1
fi
if test -r "$log_file"; then
    scp $log_file mantidlog@shadow.nd.rl.ac.uk:/isis/www/mantidproject_download/logs/Linux/rpmbuild
fi
