#!/bin/sh
# 
# RPM build script for Mantid
#
# @author Freddie Akeroyd, STFC ISIS Facility
# @date 30/03/2009
#
svn_rev="HEAD"
mantid_version="1.0"
mantid_release="0.`date +%Y%m%d`svn"
#
mantid_svn="http://svn.mantidproject.org/mantid/trunk"
echo "Exporing mantid source revision $svn_rev from subversion ..."
rm -fr Mantid-$mantid_version
mkdir Mantid-$mantid_version
svn -q --non-interactive export -r "$svn_rev" $mantid_svn/Code/RPM_Kit/Mantid Mantid-$mantid_version/Mantid
( cd Mantid-$mantid_version/Mantid; \
  echo "images ..."; \
  svn -q --non-interactive export --force -r "$svn_rev" $mantid_svn/Images images; \
  echo "MantidPlot ..."; \
  svn -q --non-interactive export --force -r "$svn_rev" $mantid_svn/Code/qtiplot MantidPlot; \
  echo "src ..."; \
  svn -q --non-interactive export --force -r "$svn_rev" $mantid_svn/Code/Mantid src; \
  echo "instrument ..."; \
  svn -q --non-interactive export --force -r "$svn_rev" $mantid_svn/Test/instrument instrument; \
)
echo "Exporting complete - making spec file for version $mantid_version release $mantid_release"
sed -e "s/MANTID_VERSION/$mantid_version/" -e "s/MANTID_RELEASE/$mantid_release/" < mantid.spec.template > mantid.spec
echo "Buliding tar file Mantid-$mantid_version.tar.gz"
rm -f Mantid-$mantid_version.tar.gz
tar -cpzf Mantid-$mantid_version.tar.gz Mantid-$mantid_version
topdir=`rpm --showrc|grep topdir| awk '{print $3}' | tail -1`
if test ! -e "$topdir"; then
    echo "Unable to determine RPM topdir from rpmrc; assuming /usr/src/redhat"
    topdir="/usr/src/redhat"
fi
if test ! -w "$topdir"; then
    echo "ERROR: RPM build directory not writable - check README.rpm"
    exit
fi
mytop=`pwd`
ln -sf $mytop/Mantid-$mantid_version.tar.gz $topdir/SOURCES
cp -f mantid.spec $topdir/SPECS
rm -f mantid.spec
cd $topdir/SPECS
echo "Building RPM file in $topdir/RPMS"
rpmbuild -ba mantid.spec
