#!/bin/bash
#
# Nightly RPM build kit
#
# @file nightly_build
# @author Freddie Akeroyd, STFC ISIS facility
#
trap error_found ERR
MESS=/tmp/build_mantid.$$

function error_found() {
    local exit_status=${1:-$?}
    echo "Subject: RPM build R$rev FAILED" > $MESS
    echo >> $MESS
    echo "RPM build of svn R$rev FAILED with error code $exit_status - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
    echo >> $MESS
    echo "** Last few lines of build error **" >> $MESS:wq

    echo >> $MESS
    tail -60 $log_file >> $MESS
    /usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
    rm -f $MESS
    echo Exiting $0 with $exit_status
    exit $exit_status
}

build_base=/home/faa59/mybuilds
find $build_base -type f -name 'Mantid-*' -exec rm -f {} \;
cd ~faa59/Mantid
svn update
svn update # do twice in case of network issue
log_file="$2"
if ! test -z "$1"; then
    rev="$1"
    revfile="_$1"
    yum_base=/isis/yum/rhel/5   # official build
else
    rev=`svnversion -n`
    rev=`expr match $rev '\([0-9]*\).*'`   # remove trailing M if any
    revfile=""
    yum_base=/isis/yum/rhel/testing/5   # test build
fi
cd Code/RPM_Kit
sh make_rpm_rhel5.sh -r $rev
scp $build_base/SRPMS/Mantid-*.*-0.svnR$rev.*.src.rpm isisupdate@shadow:$yum_base/SRPMS
scp $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64/debug
# remove to avoid copying debug twice
rm -f $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm
scp $build_base/RPMS/x86_64/Mantid-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64
scp Mantid-1.0.tar.gz isisupdate@shadow:/isis/www/mantidproject_download/CurrentBuild
echo "Subject: RPM build R$rev SUCCEEDED" > $MESS
echo >> $MESS
echo "RPM build of svn R$rev SUCCEEDED - see http://download.mantidproject.org/logs/Linux/rpmbuild/`basename $log_file`" >> $MESS
/usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
rm -f $MESS
exit 0
