#!/usr/bin/env python
from __future__ import (absolute_import)

import os.path as osp
import sys

currdir = osp.dirname(osp.abspath(__file__))
sys.path.append(osp.abspath(osp.sep.join([currdir, '..'])))
import cxxtest.cxxtestgen
cxxtest.cxxtestgen.main()
