#! /usr/bin/env python
#
# The CxxTest driver script, which uses the cxxtest Python package.
#

import sys
from os.path import abspath, dirname
sys.path.insert(0, dirname(dirname(abspath(__file__))))
sys.path.append(".")

import cxxtest  # noqa: E402

cxxtest.main(sys.argv)
