name: 'Build developer site'
description: 'Builds the Sphinx developer documentation'
runs:
  using: "composite"
  steps:
    - name: Build developer site
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Create build directory if needed
        [ -d build/devsite-html ] || mkdir -p build/devsite-html

        # Set locale for sphinx/latex
        export LC_ALL=C

        echo "::group::Build developer documentation"

        pixi run \
          --manifest-path pixi.toml \
          -e devsite \
          --frozen \
          sphinx-build \
          -b html \
          dev-docs/source \
          build/devsite-html

        echo "::endgroup::"