#For MantidServices

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_SERVICES',1)])

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidServices', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'], PDB='lib/MantidServices.pdb')
static = myenv.StaticLibrary('libstatic/MantidServices', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'], PDB='libstatic/MantidServices.pdb')
retval = { 'shared': shared, 'static': static, 'libs': [ 'MantidServices' ] }
Return('retval')
