#For MantidServices

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')

#BUILD CODE
shared = env.SharedLibrary('lib/MantidServices', listCpps, LIBS=[ ], LIBPATH=[ ])
static = env.StaticLibrary('lib/MantidServicesStatic', listCpps, LIBS=[ ], LIBPATH=[ ])
retval = { 'shared': shared, 'static': static, 'libs': [ 'MantidServices' ] }
Return('retval')
