#ifndef MANTIDQT_FACTORY_DLLOPTION_H_
#define MANTIDQT_FACTORY_DLLOPTION_H_

#include "MantidKernel/System.h"

#ifdef IN_MANTIDQT_FACTORY
#define EXPORT_OPT_MANTIDQT_FACTORY DLLExport
#else
#define EXPORT_OPT_MANTIDQT_FACTORY DLLImport
#endif /* IN_MANTIDQT_API */

#endif // MANTIDQT_FACTORY_DLLOPTION_H_
