#ifndef MANTID_CURVEFITTING_PRECOMPILEDHEADER_H_
#define MANTID_CURVEFITTING_PRECOMPILEDHEADER_H_

#include <set>
#include <string>
#include <vector>

#endif // MANTID_CURVEFITTING_PRECOMPILEDHEADER_H_