#!/bin/bash -ex

script_full_path=$(dirname "$0")

# Check for SCL outside Python, since this modifies the env
# and running with shell=true in subprocess is a security risk
scl_command=""
if command -v scl &> /dev/null
then
    scl_command="scl enable devtoolset-7 -- "
fi

# -u : Run Python without output buffering so output matches subprocess stdout
$scl_command python3 -u $script_full_path/posix_build.py
