#!/bin/bash

# From https://stackoverflow.com/a/9107028 by https://stackoverflow.com/users/1184238/andrew-norrie
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Ensure conda is installed
if ! conda --version; then
    if [[ ! -f Miniconda3-latest-Linux-x86_64.sh ]]; then
        # Download miniconda
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    fi
    sh Miniconda3-latest-Linux-x86_64.sh -b
    rm Miniconda3-latest-Linux-x86_64.sh
fi

EXPECTED_MINICONDA_DIR_PATH=~/miniconda3
EXPECTED_CONDA_PATH=$EXPECTED_MINICONDA_DIR_PATH/bin/conda

# With miniconda we can grab the mantid environment if it doesn't already exist
ENVS=$($EXPECTED_CONDA_PATH env list)
if [[ ! $ENVS = *"$EXPECTED_MINICONDA_DIR_PATH/envs/mantid"* ]]; then
    # THIS IS JUST A TEST PATH:
    $EXPECTED_CONDA_PATH env create -f $SCRIPT_DIR/../../mantid-developer-linux.yml
else
    echo "Conda environment already setup."
    exit
fi

echo "Setup Done! Run the run.sh script to launch Mantid."
exit