#!/bin/bash

# From https://stackoverflow.com/a/9107028 by https://stackoverflow.com/users/1184238/andrew-norrie
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

EXPECTED_MINICONDA_DIR_PATH=$HOME/mambaforge
EXPECTED_CONDA_PATH=$EXPECTED_MINICONDA_DIR_PATH/bin/conda

# Ensure conda is installed
if [[ ! -f $EXPECTED_CONDA_PATH ]]; then
    if [[ ! -f Mambaforge-Linux-x86_64.sh ]]; then
        # Download miniconda
        curl -O "https://github.com/conda-forge/miniforge/releases/download/4.10.1-5/Mambaforge-Linux-x86_64.sh"
    fi
    sh Mambaforge-Linux-x86_64.sh -b -p $EXPECTED_MINICONDA_DIR_PATH
    rm Mambaforge-Linux-x86_64.sh
fi

# With miniconda we can grab the mantid environment if it doesn't already exist
ENVS=$($EXPECTED_CONDA_PATH env list)
if [[ ! $ENVS = *"$EXPECTED_MINICONDA_DIR_PATH/envs/mantid"* ]]; then
    # THIS IS JUST A TEST PATH:
    $EXPECTED_CONDA_PATH env create -f $SCRIPT_DIR/../../mantid-developer-linux.yml
else
    echo "Conda environment already setup."
fi

echo "Conda is now configured, and setup."
exit