#ifndef MANTIDQTCUSTOMINTERFACES_ENGGDIFFRACTION_GSASREFINEMENTMETHOD_H_
#define MANTIDQTCUSTOMINTERFACES_ENGGDIFFRACTION_GSASREFINEMENTMETHOD_H_

namespace MantidQt {
namespace CustomInterfaces {

enum class GSASRefinementMethod { PAWLEY, RIETVELD };
}
}

#endif // MANTIDQTCUSTOMINTERFACES_ENGGDIFFRACTION_GSASREFINEMENTMETHOD_H_
