#ifndef MANTID_GEOMETRYTEST_PRECOMPILED_HEADER_H_
#define MANTID_GEOMETRYTEST_PRECOMPILED_HEADER_H_

#include <cxxTest/TestSuite.h>
#undef _CXXTEST_LONGLONG // Kill a warning

#endif //MANTID_GEOMETRYTEST_PRECOMPILED_HEADER_H_