name: 'Setup Pixi'
description: 'Setup Pixi executable after detecting version from .pixi-version. Most variables are forwarded directly setup-pixi'
inputs: # copied from prefix-dev/setup-pixi
  run-install:
    description: Whether to run `pixi install` after installing pixi.
    required: false
    default: false
  activate-environment:
    description: |
      If the installed environment should be "activated" for the current job, modifying `$GITHUB_ENV` and
      `$GITHUB_PATH`. If more than one environment is specified in `environments`, this must be the name of the
      environment. Defaults to `false`. Requires at least pixi v0.21.0.
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Read pixi version
      id: pixi-version
      shell: bash
      working-directory: ${{ github.workspace }}
      run: echo "version=$(cat .pixi-version)" >> "$GITHUB_OUTPUT"
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.9.5
      with:
        pixi-version: v${{ steps.pixi-version.outputs.version }}
        run-install: ${{ inputs.run-install }}
        frozen: ${{ inputs.run-install }}
        activate-environment: ${{ inputs.activate-environment }}
