#For MantidAPI

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')
myenv = env.Clone()

myenv.Append(CPPDEFINES=[('IN_MANTID_API',1)])

listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidAPI', listCpps, LIBS=myenv['MYLIBLIST'], LIBPATH=myenv['MYLIBDIRLIST'], PDB='lib/MantidAPI.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': [ 'MantidAPI' ] }
Return('retval')
