#For MantidAPI

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')

#BUILD CODE
if os.name == 'nt':
	shared = env.SharedLibrary('lib/MantidAPI', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'])
	static = env.StaticLibrary('lib/MantidAPIStatic', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'])
else:
	shared = env.SharedLibrary('lib/MantidAPI', listCpps, LIBS=[ ], LIBPATH=[ ])
	static = env.StaticLibrary('lib/MantidAPIStatic', listCpps, LIBS=[ ], LIBPATH=[ ])
	
retval = { 'shared': shared, 'static': static, 'libs': [ 'MantidAPI' ] }
Return('retval')
