# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hfir_background.ui'
#
# Created: Tue Nov 30 14:37:00 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(818, 708)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayoutWidget = QtGui.QWidget(Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 681, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dark_current_edit = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_current_edit.sizePolicy().hasHeightForWidth())
        self.dark_current_edit.setSizePolicy(sizePolicy)
        self.dark_current_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.dark_current_edit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.dark_current_edit.setObjectName("dark_current_edit")
        self.gridLayout.addWidget(self.dark_current_edit, 0, 1, 1, 1)
        self.dark_current_browse = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_current_browse.sizePolicy().hasHeightForWidth())
        self.dark_current_browse.setSizePolicy(sizePolicy)
        self.dark_current_browse.setObjectName("dark_current_browse")
        self.gridLayout.addWidget(self.dark_current_browse, 0, 2, 1, 1)
        self.background_chk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.background_chk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background_chk.setObjectName("background_chk")
        self.gridLayout.addWidget(self.background_chk, 1, 0, 1, 1)
        self.background_edit = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_edit.sizePolicy().hasHeightForWidth())
        self.background_edit.setSizePolicy(sizePolicy)
        self.background_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.background_edit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.background_edit.setObjectName("background_edit")
        self.gridLayout.addWidget(self.background_edit, 1, 1, 1, 1)
        self.background_browse = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_browse.sizePolicy().hasHeightForWidth())
        self.background_browse.setSizePolicy(sizePolicy)
        self.background_browse.setObjectName("background_browse")
        self.gridLayout.addWidget(self.background_browse, 1, 2, 1, 1)
        self.dark_current_chk = QtGui.QCheckBox(self.gridLayoutWidget)
        self.dark_current_chk.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dark_current_chk.setObjectName("dark_current_chk")
        self.gridLayout.addWidget(self.dark_current_chk, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 230, 671, 264))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.widget_placeholder = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.widget_placeholder.setObjectName("widget_placeholder")
        self.calculate_trans_chk = QtGui.QCheckBox(Frame)
        self.calculate_trans_chk.setGeometry(QtCore.QRect(80, 160, 332, 22))
        self.calculate_trans_chk.setObjectName("calculate_trans_chk")
        self.bck_trans_label = QtGui.QLabel(Frame)
        self.bck_trans_label.setGeometry(QtCore.QRect(80, 120, 181, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bck_trans_label.sizePolicy().hasHeightForWidth())
        self.bck_trans_label.setSizePolicy(sizePolicy)
        self.bck_trans_label.setObjectName("bck_trans_label")
        self.trans_direct_chk = QtGui.QRadioButton(Frame)
        self.trans_direct_chk.setGeometry(QtCore.QRect(130, 190, 109, 22))
        self.trans_direct_chk.setObjectName("trans_direct_chk")
        self.trans_spreader_chk = QtGui.QRadioButton(Frame)
        self.trans_spreader_chk.setGeometry(QtCore.QRect(260, 190, 131, 22))
        self.trans_spreader_chk.setObjectName("trans_spreader_chk")
        self.bck_trans_err_label = QtGui.QLabel(Frame)
        self.bck_trans_err_label.setGeometry(QtCore.QRect(390, 130, 62, 17))
        self.bck_trans_err_label.setObjectName("bck_trans_err_label")
        self.dtransmission_edit = QtGui.QLineEdit(Frame)
        self.dtransmission_edit.setEnabled(True)
        self.dtransmission_edit.setGeometry(QtCore.QRect(420, 120, 113, 27))
        self.dtransmission_edit.setObjectName("dtransmission_edit")
        self.transmission_edit = QtGui.QLineEdit(Frame)
        self.transmission_edit.setEnabled(False)
        self.transmission_edit.setGeometry(QtCore.QRect(270, 120, 113, 27))
        self.transmission_edit.setObjectName("transmission_edit")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid data file path.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_browse.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.background_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply a background subtraction.", None, QtGui.QApplication.UnicodeUTF8))
        self.background_chk.setText(QtGui.QApplication.translate("Frame", "Background data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.background_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid data file path.", None, QtGui.QApplication.UnicodeUTF8))
        self.background_browse.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply a dark current subtraction.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_chk.setText(QtGui.QApplication.translate("Frame", "Dark current data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_trans_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software calculate the background transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_trans_chk.setText(QtGui.QApplication.translate("Frame", "Calculate background transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.bck_trans_label.setText(QtGui.QApplication.translate("Frame", "Background transmission:", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_direct_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to use the direct beam method for transmission calculation.", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_direct_chk.setText(QtGui.QApplication.translate("Frame", "Direct beam", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_spreader_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to use the beam spreader (glassy carbon) method for transmission calculation.", None, QtGui.QApplication.UnicodeUTF8))
        self.trans_spreader_chk.setText(QtGui.QApplication.translate("Frame", "Beam spreader", None, QtGui.QApplication.UnicodeUTF8))
        self.bck_trans_err_label.setText(QtGui.QApplication.translate("Frame", "+/-", None, QtGui.QApplication.UnicodeUTF8))
        self.dtransmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Uncertainty on the background transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.transmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Transmission value for the background in %.", None, QtGui.QApplication.UnicodeUTF8))

