# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Tue Apr 21 16:26:31 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

from MplFigureCanvas import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1412, 1216)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_expNo = QtGui.QLabel(self.centralwidget)
        self.label_expNo.setObjectName(_fromUtf8("label_expNo"))
        self.horizontalLayout.addWidget(self.label_expNo)
        self.lineEdit_expNo = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_expNo.setObjectName(_fromUtf8("lineEdit_expNo"))
        self.horizontalLayout.addWidget(self.lineEdit_expNo)
        self.label_scanNo = QtGui.QLabel(self.centralwidget)
        self.label_scanNo.setObjectName(_fromUtf8("label_scanNo"))
        self.horizontalLayout.addWidget(self.label_scanNo)
        self.lineEdit_scanNo = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_scanNo.setObjectName(_fromUtf8("lineEdit_scanNo"))
        self.horizontalLayout.addWidget(self.lineEdit_scanNo)
        self.pushButton_loadData = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadData.setObjectName(_fromUtf8("pushButton_loadData"))
        self.horizontalLayout.addWidget(self.pushButton_loadData)
        self.label_calibration = QtGui.QLabel(self.centralwidget)
        self.label_calibration.setText(_fromUtf8(""))
        self.label_calibration.setObjectName(_fromUtf8("label_calibration"))
        self.horizontalLayout.addWidget(self.label_calibration)
        self.label_wavelength = QtGui.QLabel(self.centralwidget)
        self.label_wavelength.setObjectName(_fromUtf8("label_wavelength"))
        self.horizontalLayout.addWidget(self.label_wavelength)
        self.comboBox_wavelength = QtGui.QComboBox(self.centralwidget)
        self.comboBox_wavelength.setObjectName(_fromUtf8("comboBox_wavelength"))
        self.comboBox_wavelength.addItem(_fromUtf8(""))
        self.comboBox_wavelength.addItem(_fromUtf8(""))
        self.comboBox_wavelength.addItem(_fromUtf8(""))
        self.comboBox_wavelength.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_wavelength)
        self.lineEdit_wavelength = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_wavelength.setObjectName(_fromUtf8("lineEdit_wavelength"))
        self.horizontalLayout.addWidget(self.lineEdit_wavelength)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_25.addWidget(self.checkBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.label_detEffFileName = QtGui.QLabel(self.centralwidget)
        self.label_detEffFileName.setObjectName(_fromUtf8("label_detEffFileName"))
        self.horizontalLayout_25.addWidget(self.label_detEffFileName)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_25.addWidget(self.pushButton_2)
        self.comboBox_effCorrect = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_effCorrect.sizePolicy().hasHeightForWidth())
        self.comboBox_effCorrect.setSizePolicy(sizePolicy)
        self.comboBox_effCorrect.setObjectName(_fromUtf8("comboBox_effCorrect"))
        self.horizontalLayout_25.addWidget(self.comboBox_effCorrect)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_24.addWidget(self.checkBox_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.label_excFileName = QtGui.QLabel(self.centralwidget)
        self.label_excFileName.setObjectName(_fromUtf8("label_excFileName"))
        self.horizontalLayout_24.addWidget(self.label_excFileName)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.label_detExcluded = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_detExcluded.sizePolicy().hasHeightForWidth())
        self.label_detExcluded.setSizePolicy(sizePolicy)
        self.label_detExcluded.setMinimumSize(QtCore.QSize(155, 0))
        self.label_detExcluded.setObjectName(_fromUtf8("label_detExcluded"))
        self.horizontalLayout_24.addWidget(self.label_detExcluded)
        self.lineEdit_detExcluded = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_detExcluded.sizePolicy().hasHeightForWidth())
        self.lineEdit_detExcluded.setSizePolicy(sizePolicy)
        self.lineEdit_detExcluded.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_detExcluded.setObjectName(_fromUtf8("lineEdit_detExcluded"))
        self.horizontalLayout_24.addWidget(self.lineEdit_detExcluded)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.comboBox_rawDetMode = QtGui.QComboBox(self.tab_3)
        self.comboBox_rawDetMode.setObjectName(_fromUtf8("comboBox_rawDetMode"))
        self.comboBox_rawDetMode.addItem(_fromUtf8(""))
        self.comboBox_rawDetMode.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.comboBox_rawDetMode)
        self.lineEdit_ptNo = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ptNo.sizePolicy().hasHeightForWidth())
        self.lineEdit_ptNo.setSizePolicy(sizePolicy)
        self.lineEdit_ptNo.setObjectName(_fromUtf8("lineEdit_ptNo"))
        self.horizontalLayout_13.addWidget(self.lineEdit_ptNo)
        self.label_ptInfo = QtGui.QLabel(self.tab_3)
        self.label_ptInfo.setObjectName(_fromUtf8("label_ptInfo"))
        self.horizontalLayout_13.addWidget(self.label_ptInfo)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.graphicsView_Raw = Qt4MplPlotView(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_Raw.sizePolicy().hasHeightForWidth())
        self.graphicsView_Raw.setSizePolicy(sizePolicy)
        self.graphicsView_Raw.setObjectName(_fromUtf8("graphicsView_Raw"))
        self.horizontalLayout_14.addWidget(self.graphicsView_Raw)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.pushButton_plotRaw = QtGui.QPushButton(self.tab_3)
        self.pushButton_plotRaw.setObjectName(_fromUtf8("pushButton_plotRaw"))
        self.verticalLayout_9.addWidget(self.pushButton_plotRaw)
        self.checkBox_overpltRawDet = QtGui.QCheckBox(self.tab_3)
        self.checkBox_overpltRawDet.setObjectName(_fromUtf8("checkBox_overpltRawDet"))
        self.verticalLayout_9.addWidget(self.checkBox_overpltRawDet)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem7)
        self.pushButton_ptUp = QtGui.QPushButton(self.tab_3)
        self.pushButton_ptUp.setObjectName(_fromUtf8("pushButton_ptUp"))
        self.verticalLayout_9.addWidget(self.pushButton_ptUp)
        self.pushButton_ptDown = QtGui.QPushButton(self.tab_3)
        self.pushButton_ptDown.setObjectName(_fromUtf8("pushButton_ptDown"))
        self.verticalLayout_9.addWidget(self.pushButton_ptDown)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem8)
        self.pushButton_clearRawDets = QtGui.QPushButton(self.tab_3)
        self.pushButton_clearRawDets.setObjectName(_fromUtf8("pushButton_clearRawDets"))
        self.verticalLayout_9.addWidget(self.pushButton_clearRawDets)
        self.horizontalLayout_14.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.textBrowser_RawDetInfo = QtGui.QTextBrowser(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_RawDetInfo.sizePolicy().hasHeightForWidth())
        self.textBrowser_RawDetInfo.setSizePolicy(sizePolicy)
        self.textBrowser_RawDetInfo.setObjectName(_fromUtf8("textBrowser_RawDetInfo"))
        self.horizontalLayout_12.addWidget(self.textBrowser_RawDetInfo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_21.addWidget(self.label_11)
        self.lineEdit_detID = QtGui.QLineEdit(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_detID.sizePolicy().hasHeightForWidth())
        self.lineEdit_detID.setSizePolicy(sizePolicy)
        self.lineEdit_detID.setObjectName(_fromUtf8("lineEdit_detID"))
        self.horizontalLayout_21.addWidget(self.lineEdit_detID)
        self.label_17 = QtGui.QLabel(self.tab_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_21.addWidget(self.label_17)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.graphicsView_indvDet = Qt4MplPlotView(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_indvDet.sizePolicy().hasHeightForWidth())
        self.graphicsView_indvDet.setSizePolicy(sizePolicy)
        self.graphicsView_indvDet.setObjectName(_fromUtf8("graphicsView_indvDet"))
        self.verticalLayout_13.addWidget(self.graphicsView_indvDet)
        self.comboBox_indvDetXLabel = QtGui.QComboBox(self.tab_5)
        self.comboBox_indvDetXLabel.setObjectName(_fromUtf8("comboBox_indvDetXLabel"))
        self.verticalLayout_13.addWidget(self.comboBox_indvDetXLabel)
        self.horizontalLayout_23.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pushButton_plotIndvDet = QtGui.QPushButton(self.tab_5)
        self.pushButton_plotIndvDet.setObjectName(_fromUtf8("pushButton_plotIndvDet"))
        self.verticalLayout_12.addWidget(self.pushButton_plotIndvDet)
        self.checkBox_overPlotIndvDet = QtGui.QCheckBox(self.tab_5)
        self.checkBox_overPlotIndvDet.setObjectName(_fromUtf8("checkBox_overPlotIndvDet"))
        self.verticalLayout_12.addWidget(self.checkBox_overPlotIndvDet)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem10)
        self.pushButton_plotAllDet = QtGui.QPushButton(self.tab_5)
        self.pushButton_plotAllDet.setObjectName(_fromUtf8("pushButton_plotAllDet"))
        self.verticalLayout_12.addWidget(self.pushButton_plotAllDet)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_12.addItem(spacerItem11)
        self.pushButton_plotPrevDet = QtGui.QPushButton(self.tab_5)
        self.pushButton_plotPrevDet.setObjectName(_fromUtf8("pushButton_plotPrevDet"))
        self.verticalLayout_12.addWidget(self.pushButton_plotPrevDet)
        self.pushButton_plotNextDet = QtGui.QPushButton(self.tab_5)
        self.pushButton_plotNextDet.setObjectName(_fromUtf8("pushButton_plotNextDet"))
        self.verticalLayout_12.addWidget(self.pushButton_plotNextDet)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.pushButton_clearCanvasIndDet = QtGui.QPushButton(self.tab_5)
        self.pushButton_clearCanvasIndDet.setObjectName(_fromUtf8("pushButton_clearCanvasIndDet"))
        self.verticalLayout_12.addWidget(self.pushButton_clearCanvasIndDet)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem13)
        self.comboBox_indvDetYLabel = QtGui.QComboBox(self.tab_5)
        self.comboBox_indvDetYLabel.setObjectName(_fromUtf8("comboBox_indvDetYLabel"))
        self.verticalLayout_12.addWidget(self.comboBox_indvDetYLabel)
        self.pushButton_plotLog = QtGui.QPushButton(self.tab_5)
        self.pushButton_plotLog.setObjectName(_fromUtf8("pushButton_plotLog"))
        self.verticalLayout_12.addWidget(self.pushButton_plotLog)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem14)
        self.horizontalLayout_23.addLayout(self.verticalLayout_12)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_normalizeMonitor = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_normalizeMonitor.sizePolicy().hasHeightForWidth())
        self.label_normalizeMonitor.setSizePolicy(sizePolicy)
        self.label_normalizeMonitor.setMinimumSize(QtCore.QSize(155, 0))
        self.label_normalizeMonitor.setObjectName(_fromUtf8("label_normalizeMonitor"))
        self.horizontalLayout_3.addWidget(self.label_normalizeMonitor)
        self.lineEdit_normalizeMonitor = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_normalizeMonitor.sizePolicy().hasHeightForWidth())
        self.lineEdit_normalizeMonitor.setSizePolicy(sizePolicy)
        self.lineEdit_normalizeMonitor.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_normalizeMonitor.setObjectName(_fromUtf8("lineEdit_normalizeMonitor"))
        self.horizontalLayout_3.addWidget(self.lineEdit_normalizeMonitor)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_outputFormat = QtGui.QLabel(self.tab)
        self.label_outputFormat.setObjectName(_fromUtf8("label_outputFormat"))
        self.horizontalLayout_22.addWidget(self.label_outputFormat)
        self.comboBox_outputFormat = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_outputFormat.sizePolicy().hasHeightForWidth())
        self.comboBox_outputFormat.setSizePolicy(sizePolicy)
        self.comboBox_outputFormat.setObjectName(_fromUtf8("comboBox_outputFormat"))
        self.horizontalLayout_22.addWidget(self.comboBox_outputFormat)
        self.lineEdit_outputFileName = QtGui.QLineEdit(self.tab)
        self.lineEdit_outputFileName.setObjectName(_fromUtf8("lineEdit_outputFileName"))
        self.horizontalLayout_22.addWidget(self.lineEdit_outputFileName)
        self.pushButton_saveData = QtGui.QPushButton(self.tab)
        self.pushButton_saveData.setObjectName(_fromUtf8("pushButton_saveData"))
        self.horizontalLayout_22.addWidget(self.pushButton_saveData)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_reductionView = QtGui.QGridLayout()
        self.gridLayout_reductionView.setObjectName(_fromUtf8("gridLayout_reductionView"))
        self.graphicsView_reducedData = Qt4MplPlotView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_reducedData.sizePolicy().hasHeightForWidth())
        self.graphicsView_reducedData.setSizePolicy(sizePolicy)
        self.graphicsView_reducedData.setObjectName(_fromUtf8("graphicsView_reducedData"))
        self.gridLayout_reductionView.addWidget(self.graphicsView_reducedData, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_reductionView)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_prevScan = QtGui.QPushButton(self.tab)
        self.pushButton_prevScan.setObjectName(_fromUtf8("pushButton_prevScan"))
        self.verticalLayout_3.addWidget(self.pushButton_prevScan)
        self.pushButton_nextScan = QtGui.QPushButton(self.tab)
        self.pushButton_nextScan.setObjectName(_fromUtf8("pushButton_nextScan"))
        self.verticalLayout_3.addWidget(self.pushButton_nextScan)
        self.checkBox_clearPrevious = QtGui.QCheckBox(self.tab)
        self.checkBox_clearPrevious.setObjectName(_fromUtf8("checkBox_clearPrevious"))
        self.verticalLayout_3.addWidget(self.checkBox_clearPrevious)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem17)
        self.label_xmin = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xmin.sizePolicy().hasHeightForWidth())
        self.label_xmin.setSizePolicy(sizePolicy)
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.verticalLayout_3.addWidget(self.label_xmin)
        self.lineEdit_xmin = QtGui.QLineEdit(self.tab)
        self.lineEdit_xmin.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_xmin.sizePolicy().hasHeightForWidth())
        self.lineEdit_xmin.setSizePolicy(sizePolicy)
        self.lineEdit_xmin.setObjectName(_fromUtf8("lineEdit_xmin"))
        self.verticalLayout_3.addWidget(self.lineEdit_xmin)
        self.label_xmax_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xmax_2.sizePolicy().hasHeightForWidth())
        self.label_xmax_2.setSizePolicy(sizePolicy)
        self.label_xmax_2.setObjectName(_fromUtf8("label_xmax_2"))
        self.verticalLayout_3.addWidget(self.label_xmax_2)
        self.lineEdit_xmax = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_xmax.sizePolicy().hasHeightForWidth())
        self.lineEdit_xmax.setSizePolicy(sizePolicy)
        self.lineEdit_xmax.setObjectName(_fromUtf8("lineEdit_xmax"))
        self.verticalLayout_3.addWidget(self.lineEdit_xmax)
        self.label_binsize = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_binsize.sizePolicy().hasHeightForWidth())
        self.label_binsize.setSizePolicy(sizePolicy)
        self.label_binsize.setObjectName(_fromUtf8("label_binsize"))
        self.verticalLayout_3.addWidget(self.label_binsize)
        self.lineEdit_binsize = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_binsize.sizePolicy().hasHeightForWidth())
        self.lineEdit_binsize.setSizePolicy(sizePolicy)
        self.lineEdit_binsize.setObjectName(_fromUtf8("lineEdit_binsize"))
        self.verticalLayout_3.addWidget(self.lineEdit_binsize)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem18)
        self.pushButton_unit2theta = QtGui.QPushButton(self.tab)
        self.pushButton_unit2theta.setObjectName(_fromUtf8("pushButton_unit2theta"))
        self.verticalLayout_3.addWidget(self.pushButton_unit2theta)
        self.pushButton_unitD = QtGui.QPushButton(self.tab)
        self.pushButton_unitD.setObjectName(_fromUtf8("pushButton_unitD"))
        self.verticalLayout_3.addWidget(self.pushButton_unitD)
        self.pushButton_unitQ = QtGui.QPushButton(self.tab)
        self.pushButton_unitQ.setObjectName(_fromUtf8("pushButton_unitQ"))
        self.verticalLayout_3.addWidget(self.pushButton_unitQ)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_merge = QtGui.QWidget()
        self.tab_merge.setObjectName(_fromUtf8("tab_merge"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_merge)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_merge = QtGui.QVBoxLayout()
        self.verticalLayout_merge.setObjectName(_fromUtf8("verticalLayout_merge"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_8 = QtGui.QLabel(self.tab_merge)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_19.addWidget(self.label_8)
        self.lineEdit_scanStart = QtGui.QLineEdit(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scanStart.sizePolicy().hasHeightForWidth())
        self.lineEdit_scanStart.setSizePolicy(sizePolicy)
        self.lineEdit_scanStart.setObjectName(_fromUtf8("lineEdit_scanStart"))
        self.horizontalLayout_19.addWidget(self.lineEdit_scanStart)
        self.label_9 = QtGui.QLabel(self.tab_merge)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_19.addWidget(self.label_9)
        self.lineEdit_scanEnd = QtGui.QLineEdit(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scanEnd.sizePolicy().hasHeightForWidth())
        self.lineEdit_scanEnd.setSizePolicy(sizePolicy)
        self.lineEdit_scanEnd.setObjectName(_fromUtf8("lineEdit_scanEnd"))
        self.horizontalLayout_19.addWidget(self.lineEdit_scanEnd)
        self.label_12 = QtGui.QLabel(self.tab_merge)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_19.addWidget(self.label_12)
        self.lineEdit_extraScans = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_extraScans.setObjectName(_fromUtf8("lineEdit_extraScans"))
        self.horizontalLayout_19.addWidget(self.lineEdit_extraScans)
        self.label_10 = QtGui.QLabel(self.tab_merge)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_19.addWidget(self.label_10)
        self.lineEdit_exclScans = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_exclScans.setObjectName(_fromUtf8("lineEdit_exclScans"))
        self.horizontalLayout_19.addWidget(self.lineEdit_exclScans)
        self.pushButton = QtGui.QPushButton(self.tab_merge)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_19.addWidget(self.pushButton)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_15 = QtGui.QLabel(self.tab_merge)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_18.addWidget(self.label_15)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_18.addWidget(self.lineEdit_3)
        self.label_14 = QtGui.QLabel(self.tab_merge)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_18.addWidget(self.label_14)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_18.addWidget(self.lineEdit_4)
        self.label_16 = QtGui.QLabel(self.tab_merge)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_18.addWidget(self.label_16)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_merge)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_18.addWidget(self.lineEdit_5)
        self.label_6 = QtGui.QLabel(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_18.addWidget(self.label_6)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_mergeView = QtGui.QVBoxLayout()
        self.verticalLayout_mergeView.setObjectName(_fromUtf8("verticalLayout_mergeView"))
        self.graphicsView_mergeRun = Qt4MplPlotView(self.tab_merge)
        self.graphicsView_mergeRun.setObjectName(_fromUtf8("graphicsView_mergeRun"))
        self.verticalLayout_mergeView.addWidget(self.graphicsView_mergeRun)
        self.horizontalLayout_16.addLayout(self.verticalLayout_mergeView)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_11.addItem(spacerItem21)
        self.pushButton_viewWaterFall = QtGui.QPushButton(self.tab_merge)
        self.pushButton_viewWaterFall.setObjectName(_fromUtf8("pushButton_viewWaterFall"))
        self.verticalLayout_11.addWidget(self.pushButton_viewWaterFall)
        self.pushButton_view2D = QtGui.QPushButton(self.tab_merge)
        self.pushButton_view2D.setObjectName(_fromUtf8("pushButton_view2D"))
        self.verticalLayout_11.addWidget(self.pushButton_view2D)
        self.pushButton_saveAllIndScans = QtGui.QPushButton(self.tab_merge)
        self.pushButton_saveAllIndScans.setObjectName(_fromUtf8("pushButton_saveAllIndScans"))
        self.verticalLayout_11.addWidget(self.pushButton_saveAllIndScans)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem22)
        self.pushButton_mergeScans = QtGui.QPushButton(self.tab_merge)
        self.pushButton_mergeScans.setObjectName(_fromUtf8("pushButton_mergeScans"))
        self.verticalLayout_11.addWidget(self.pushButton_mergeScans)
        self.pushButton_viewMerge = QtGui.QPushButton(self.tab_merge)
        self.pushButton_viewMerge.setObjectName(_fromUtf8("pushButton_viewMerge"))
        self.verticalLayout_11.addWidget(self.pushButton_viewMerge)
        self.pushButton_saveMerge = QtGui.QPushButton(self.tab_merge)
        self.pushButton_saveMerge.setObjectName(_fromUtf8("pushButton_saveMerge"))
        self.verticalLayout_11.addWidget(self.pushButton_saveMerge)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_11.addItem(spacerItem23)
        self.pushButton_clearMultCanvas = QtGui.QPushButton(self.tab_merge)
        self.pushButton_clearMultCanvas.setObjectName(_fromUtf8("pushButton_clearMultCanvas"))
        self.verticalLayout_11.addWidget(self.pushButton_clearMultCanvas)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem24)
        self.horizontalLayout_16.addLayout(self.verticalLayout_11)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_13 = QtGui.QLabel(self.tab_merge)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_20.addWidget(self.label_13)
        self.comboBox_2 = QtGui.QComboBox(self.tab_merge)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_20.addWidget(self.comboBox_2)
        self.label_7 = QtGui.QLabel(self.tab_merge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_20.addWidget(self.label_7)
        self.verticalLayout_merge.addLayout(self.horizontalLayout_20)
        self.gridLayout_6.addLayout(self.verticalLayout_merge, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_merge, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_15.addWidget(self.label_2)
        self.lineEdit_stripVPeaks = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_stripVPeaks.setEnabled(False)
        self.lineEdit_stripVPeaks.setObjectName(_fromUtf8("lineEdit_stripVPeaks"))
        self.horizontalLayout_15.addWidget(self.lineEdit_stripVPeaks)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem25)
        self.pushButton_resetVanPeakList = QtGui.QPushButton(self.tab_4)
        self.pushButton_resetVanPeakList.setObjectName(_fromUtf8("pushButton_resetVanPeakList"))
        self.horizontalLayout_15.addWidget(self.pushButton_resetVanPeakList)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.graphicsView_vanPeaks = Qt4MplPlotView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_vanPeaks.sizePolicy().hasHeightForWidth())
        self.graphicsView_vanPeaks.setSizePolicy(sizePolicy)
        self.graphicsView_vanPeaks.setObjectName(_fromUtf8("graphicsView_vanPeaks"))
        self.horizontalLayout_11.addWidget(self.graphicsView_vanPeaks)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem26)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.lineEdit_min2Theta = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_min2Theta.sizePolicy().hasHeightForWidth())
        self.lineEdit_min2Theta.setSizePolicy(sizePolicy)
        self.lineEdit_min2Theta.setObjectName(_fromUtf8("lineEdit_min2Theta"))
        self.verticalLayout_6.addWidget(self.lineEdit_min2Theta)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEdit_max2Theta = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_max2Theta.sizePolicy().hasHeightForWidth())
        self.lineEdit_max2Theta.setSizePolicy(sizePolicy)
        self.lineEdit_max2Theta.setObjectName(_fromUtf8("lineEdit_max2Theta"))
        self.verticalLayout_6.addWidget(self.lineEdit_max2Theta)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineEdit_binsize2Theta = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_binsize2Theta.sizePolicy().hasHeightForWidth())
        self.lineEdit_binsize2Theta.setSizePolicy(sizePolicy)
        self.lineEdit_binsize2Theta.setObjectName(_fromUtf8("lineEdit_binsize2Theta"))
        self.verticalLayout_6.addWidget(self.lineEdit_binsize2Theta)
        self.pushButton_rebin2Theta = QtGui.QPushButton(self.tab_4)
        self.pushButton_rebin2Theta.setObjectName(_fromUtf8("pushButton_rebin2Theta"))
        self.verticalLayout_6.addWidget(self.pushButton_rebin2Theta)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem27)
        self.pushButton_stripVanPeaks = QtGui.QPushButton(self.tab_4)
        self.pushButton_stripVanPeaks.setObjectName(_fromUtf8("pushButton_stripVanPeaks"))
        self.verticalLayout_6.addWidget(self.pushButton_stripVanPeaks)
        self.pushButton_saveVanRun = QtGui.QPushButton(self.tab_4)
        self.pushButton_saveVanRun.setObjectName(_fromUtf8("pushButton_saveVanRun"))
        self.verticalLayout_6.addWidget(self.pushButton_saveVanRun)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem28)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_instrument = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_instrument.sizePolicy().hasHeightForWidth())
        self.label_instrument.setSizePolicy(sizePolicy)
        self.label_instrument.setMinimumSize(QtCore.QSize(155, 0))
        self.label_instrument.setObjectName(_fromUtf8("label_instrument"))
        self.horizontalLayout_10.addWidget(self.label_instrument)
        self.comboBox_instrument = QtGui.QComboBox(self.tab_2)
        self.comboBox_instrument.setObjectName(_fromUtf8("comboBox_instrument"))
        self.comboBox_instrument.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.comboBox_instrument)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem29)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem30)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_cache = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cache.sizePolicy().hasHeightForWidth())
        self.label_cache.setSizePolicy(sizePolicy)
        self.label_cache.setMinimumSize(QtCore.QSize(155, 0))
        self.label_cache.setObjectName(_fromUtf8("label_cache"))
        self.horizontalLayout_7.addWidget(self.label_cache)
        self.lineEdit_cache = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cache.sizePolicy().hasHeightForWidth())
        self.lineEdit_cache.setSizePolicy(sizePolicy)
        self.lineEdit_cache.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_cache.setObjectName(_fromUtf8("lineEdit_cache"))
        self.horizontalLayout_7.addWidget(self.lineEdit_cache)
        self.pushButton_browseCache = QtGui.QPushButton(self.tab_2)
        self.pushButton_browseCache.setObjectName(_fromUtf8("pushButton_browseCache"))
        self.horizontalLayout_7.addWidget(self.pushButton_browseCache)
        self.checkBox_delCache = QtGui.QCheckBox(self.tab_2)
        self.checkBox_delCache.setObjectName(_fromUtf8("checkBox_delCache"))
        self.horizontalLayout_7.addWidget(self.checkBox_delCache)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem31)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_useServer = QtGui.QRadioButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_useServer.sizePolicy().hasHeightForWidth())
        self.radioButton_useServer.setSizePolicy(sizePolicy)
        self.radioButton_useServer.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_useServer.setText(_fromUtf8(""))
        self.radioButton_useServer.setObjectName(_fromUtf8("radioButton_useServer"))
        self.horizontalLayout_8.addWidget(self.radioButton_useServer)
        self.label = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(135, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_8.addWidget(self.label)
        self.lineEdit_dataIP = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dataIP.sizePolicy().hasHeightForWidth())
        self.lineEdit_dataIP.setSizePolicy(sizePolicy)
        self.lineEdit_dataIP.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_dataIP.setObjectName(_fromUtf8("lineEdit_dataIP"))
        self.horizontalLayout_8.addWidget(self.lineEdit_dataIP)
        self.pushButton_chkServer = QtGui.QPushButton(self.tab_2)
        self.pushButton_chkServer.setObjectName(_fromUtf8("pushButton_chkServer"))
        self.horizontalLayout_8.addWidget(self.pushButton_chkServer)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem32)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.radioButton_useLocal = QtGui.QRadioButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_useLocal.sizePolicy().hasHeightForWidth())
        self.radioButton_useLocal.setSizePolicy(sizePolicy)
        self.radioButton_useLocal.setMinimumSize(QtCore.QSize(20, 0))
        self.radioButton_useLocal.setText(_fromUtf8(""))
        self.radioButton_useLocal.setObjectName(_fromUtf8("radioButton_useLocal"))
        self.horizontalLayout_9.addWidget(self.radioButton_useLocal)
        self.label_localSrc = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_localSrc.sizePolicy().hasHeightForWidth())
        self.label_localSrc.setSizePolicy(sizePolicy)
        self.label_localSrc.setMinimumSize(QtCore.QSize(135, 0))
        self.label_localSrc.setObjectName(_fromUtf8("label_localSrc"))
        self.horizontalLayout_9.addWidget(self.label_localSrc)
        self.lineEdit_localSrc = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_localSrc.sizePolicy().hasHeightForWidth())
        self.lineEdit_localSrc.setSizePolicy(sizePolicy)
        self.lineEdit_localSrc.setMinimumSize(QtCore.QSize(400, 0))
        self.lineEdit_localSrc.setObjectName(_fromUtf8("lineEdit_localSrc"))
        self.horizontalLayout_9.addWidget(self.lineEdit_localSrc)
        self.pushButton_browseLocalSrc = QtGui.QPushButton(self.tab_2)
        self.pushButton_browseLocalSrc.setObjectName(_fromUtf8("pushButton_browseLocalSrc"))
        self.horizontalLayout_9.addWidget(self.pushButton_browseLocalSrc)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem33)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem34, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1412, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuTool = QtGui.QMenu(self.menubar)
        self.menuTool.setObjectName(_fromUtf8("menuTool"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName(_fromUtf8("actionOpen_2"))
        self.actionLoad_Setup_File = QtGui.QAction(MainWindow)
        self.actionLoad_Setup_File.setObjectName(_fromUtf8("actionLoad_Setup_File"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addAction(self.actionLog)
        self.menuTool.addAction(self.actionLoad_Setup_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_expNo.setText(_translate("MainWindow", "Exp No", None))
        self.label_scanNo.setText(_translate("MainWindow", "Scan No", None))
        self.pushButton_loadData.setText(_translate("MainWindow", "Load Data", None))
        self.label_wavelength.setText(_translate("MainWindow", "Wavelength", None))
        self.comboBox_wavelength.setItemText(0, _translate("MainWindow", "Ge 113 IN Config 2.41 Å,", None))
        self.comboBox_wavelength.setItemText(1, _translate("MainWindow", "(115) 1.54 Å", None))
        self.comboBox_wavelength.setItemText(2, _translate("MainWindow", "(117) 1.12 Å.", None))
        self.comboBox_wavelength.setItemText(3, _translate("MainWindow", "User Specified", None))
        self.checkBox.setText(_translate("MainWindow", "Detectors Efficiency Correction", None))
        self.label_detEffFileName.setText(_translate("MainWindow", "(Detectors Efficiency File)", None))
        self.pushButton_2.setText(_translate("MainWindow", "View Correction", None))
        self.comboBox_effCorrect.setToolTip(_translate("MainWindow", "<html><head/><body><p>File name for efficiency correction</p></body></html>", None))
        self.checkBox_2.setText(_translate("MainWindow", "Using Exclusion File", None))
        self.label_excFileName.setText(_translate("MainWindow", "(Excluded Detector File)", None))
        self.label_detExcluded.setText(_translate("MainWindow", "Detectors to Exclude   ", None))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Question about use case of tab\'Raw Detectors\': What do you want to see?</p><p>1. single detector\'s counts in all Pt.? </p><p>&gt; what is the X-axis? Pt. or 2theta? </p><p>2. all detectors\' counts in one Pt.?</p><p>&gt; what is the X-axis? Det no or 2theta? </p></body></html>", None))
        self.comboBox_rawDetMode.setItemText(0, _translate("MainWindow", "All Pts.", None))
        self.comboBox_rawDetMode.setItemText(1, _translate("MainWindow", "Single Pts.", None))
        self.label_ptInfo.setText(_translate("MainWindow", "Pt. Number From 1 To ?", None))
        self.pushButton_plotRaw.setText(_translate("MainWindow", "Plot Raw Detector", None))
        self.checkBox_overpltRawDet.setText(_translate("MainWindow", "Over Plot Previous", None))
        self.pushButton_ptUp.setText(_translate("MainWindow", "Previous Pt.", None))
        self.pushButton_ptDown.setText(_translate("MainWindow", "Next Pt.", None))
        self.pushButton_clearRawDets.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Raw Detectors", None))
        self.label_11.setText(_translate("MainWindow", "Detector ID", None))
        self.label_17.setText(_translate("MainWindow", "Detector IDs From 1 to 44", None))
        self.pushButton_plotIndvDet.setText(_translate("MainWindow", "Plot", None))
        self.checkBox_overPlotIndvDet.setText(_translate("MainWindow", "Over Plot Previous", None))
        self.pushButton_plotAllDet.setText(_translate("MainWindow", "Plot All ", None))
        self.pushButton_plotPrevDet.setText(_translate("MainWindow", "Previous Detector", None))
        self.pushButton_plotNextDet.setText(_translate("MainWindow", "Next Detector", None))
        self.pushButton_clearCanvasIndDet.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_plotLog.setText(_translate("MainWindow", "Plot Sample Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Individual Detector", None))
        self.label_normalizeMonitor.setText(_translate("MainWindow", "Normalization Monitor", None))
        self.label_outputFormat.setText(_translate("MainWindow", "Save As", None))
        self.pushButton_saveData.setText(_translate("MainWindow", "Save", None))
        self.pushButton_prevScan.setText(_translate("MainWindow", "Prev Scan", None))
        self.pushButton_nextScan.setText(_translate("MainWindow", "Next Scan", None))
        self.checkBox_clearPrevious.setText(_translate("MainWindow", "Clear Previous Plot", None))
        self.label_xmin.setText(_translate("MainWindow", "Minimum X", None))
        self.label_xmax_2.setText(_translate("MainWindow", "Maximum X", None))
        self.label_binsize.setText(_translate("MainWindow", "Bin Size", None))
        self.pushButton_unit2theta.setText(_translate("MainWindow", "2theta", None))
        self.pushButton_unitD.setText(_translate("MainWindow", "dSpacing", None))
        self.pushButton_unitQ.setText(_translate("MainWindow", "Q", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Normalized", None))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Starting scan number</p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "From", None))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Last scan number included </p></body></html>", None))
        self.label_9.setText(_translate("MainWindow", "To", None))
        self.label_12.setText(_translate("MainWindow", "Others", None))
        self.label_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scan numbers that are excluded from merging beween \'from\' and \'to\'</p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "Excluded Scans", None))
        self.pushButton.setText(_translate("MainWindow", "Load All", None))
        self.label_15.setText(_translate("MainWindow", "Maximum X", None))
        self.label_14.setText(_translate("MainWindow", "Minimum X", None))
        self.label_16.setText(_translate("MainWindow", "Binning", None))
        self.label_6.setText(_translate("MainWindow", "Message", None))
        self.pushButton_viewWaterFall.setText(_translate("MainWindow", "Waterfall ", None))
        self.pushButton_view2D.setText(_translate("MainWindow", "View 2D", None))
        self.pushButton_saveAllIndScans.setText(_translate("MainWindow", "Save All", None))
        self.pushButton_mergeScans.setText(_translate("MainWindow", "Merge", None))
        self.pushButton_viewMerge.setText(_translate("MainWindow", "View Merged", None))
        self.pushButton_saveMerge.setText(_translate("MainWindow", "Save Merged", None))
        self.pushButton_clearMultCanvas.setText(_translate("MainWindow", "Clear", None))
        self.label_13.setText(_translate("MainWindow", "Vertical Label In 2D Plot", None))
        self.label_7.setText(_translate("MainWindow", "Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_merge), _translate("MainWindow", "Multiple Scans", None))
        self.label_2.setText(_translate("MainWindow", "Vanadium Peak List", None))
        self.pushButton_resetVanPeakList.setText(_translate("MainWindow", "Reset Vanadium Peaks List", None))
        self.label_3.setText(_translate("MainWindow", "Minimum 2Theta (Degrees)", None))
        self.label_4.setText(_translate("MainWindow", "Maximum 2Theta (Degrees)", None))
        self.label_5.setText(_translate("MainWindow", "Bin size in 2Theta", None))
        self.pushButton_rebin2Theta.setText(_translate("MainWindow", "Rebin", None))
        self.pushButton_stripVanPeaks.setText(_translate("MainWindow", "Strip Vanadium Peaks", None))
        self.pushButton_saveVanRun.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Vanadium", None))
        self.label_instrument.setText(_translate("MainWindow", "Instrument", None))
        self.comboBox_instrument.setItemText(0, _translate("MainWindow", "HB2A", None))
        self.label_cache.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cache data file download from server to local disk. </p><p>The default is current working directory.  </p><p>The cached files will be deleted with normal quit. </p></body></html>", None))
        self.label_cache.setText(_translate("MainWindow", "Cache Raw Data File", None))
        self.pushButton_browseCache.setText(_translate("MainWindow", "Browse", None))
        self.checkBox_delCache.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cached files will be deleted upon quitting normally.</p></body></html>", None))
        self.checkBox_delCache.setText(_translate("MainWindow", "Delete Cache Before Quit", None))
        self.label.setText(_translate("MainWindow", "Server    Address", None))
        self.pushButton_chkServer.setText(_translate("MainWindow", "Check URL", None))
        self.label_localSrc.setText(_translate("MainWindow", "Local Data Storage", None))
        self.pushButton_browseLocalSrc.setText(_translate("MainWindow", "Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced Setup", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuWindow.setTitle(_translate("MainWindow", "Window", None))
        self.menuTool.setTitle(_translate("MainWindow", "Tool", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionLog.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen_2.setText(_translate("MainWindow", "Open", None))
        self.actionOpen_2.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionLoad_Setup_File.setText(_translate("MainWindow", "Load Setup File", None))

