#For MantidPythonAPI

import os
import sys
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_PYTHON_API',1)])
# linux/mac
if os.name == 'posix':
   #myenv.Append(CPPPATH='/usr/include/python' + sys.version[0:3])
   myenv.Append(MYLIBLIST='python' + sys.version[0:3])
   myenv.Replace(SHLIBSUFFIX='.so')
   myenv.Append(MYLIBLIST='boost_python'+MantidBuild.findBoost('','','libboost_python')['append'])
# windows
else:
   #python_path = 'C:/Python25/'
   #myenv.Append(CPPPATH=python_path+'include/')
   #myenv.Append(MYLIBDIRLIST=python_path+'libs/')
   #myenv.Append(MYLIBLIST=python25)
   myenv.Replace(SHLIBSUFFIX='.pyd')
listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidPythonAPI', listCpps, LIBS=myenv['MYLIBLIST'], LIBPATH=myenv['MYLIBDIRLIST'], PDB='lib/MantidPythonAPI.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': [ 'MantidPythonAPI' ] }
Return('retval')
