#For MantidPythonAPI

import platform
import os
import sys
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)

#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_PYTHON_API',1)])
# linux/mac
if os.name == 'posix':
   libraries = myenv['MYLIBLIST']
   # This avoids segfaulting on some systems when using Mantid in a standalone interpreter
   # It must be linked before lGL
   mylibraries = ['stdc++'] + libraries
   myenv['MYLIBLIST'] = mylibraries
   myenv.Append(MYLIBLIST='python' + sys.version[0:3])
   if platform.system() == 'Darwin':
      myenv.Replace(SHLIBSUFFIX='.dylib')
   else:
      myenv.Replace(SHLIBSUFFIX='.so')
   myenv.Append(MYLIBLIST='boost_python' + myenv['BOOST_APPEND'])
# windows
else:
   #python_path = 'C:/Python25/'
   #myenv.Append(CPPPATH=python_path+'include/')
   #myenv.Append(MYLIBDIRLIST=python_path+'libs/')
   #myenv.Append(MYLIBLIST=python25)
   myenv.Replace(SHLIBSUFFIX='.pyd')
listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidPythonAPI', listCpps, LIBS=myenv['MYLIBLIST'], LIBPATH=myenv['MYLIBDIRLIST'], PDB='lib/MantidPythonAPI.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': [ 'MantidPythonAPI' ] }
Return('retval')
