#For MantidGeometry

import os
import MantidBuild

#GET LIST OF CPPS
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder)
codeFolder = os.path.abspath('./Deprecated/src')
listCpps.append(MantidBuild.getCPPFiles(codeFolder))

# at the moment not all of geometry works
# listCpps = []
# listCpps.append(os.path.abspath('src/CompAssembly.cpp'))
# listCpps.append(os.path.abspath('src/Component.cpp'))
# istCpps.append(os.path.abspath('src/Detector.cpp'))
# listCpps.append(os.path.abspath('src/ObjComponent.cpp'))
# listCpps.append(os.path.abspath('src/Quat.cpp'))
# listCpps.append(os.path.abspath('src/V3D.cpp'))

#Import environment
Import('env')

#BUILD CODE
shared = env.SharedLibrary('lib/MantidGeometry', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'])
static = env.StaticLibrary('libstatic/MantidGeometry', listCpps, LIBS=env['MYLIBLIST'], LIBPATH=env['MYLIBDIRLIST'])
retval = { 'shared': shared, 'static': static, 'libs': [ 'MantidGeometry' ] }
Return('retval')
