CxxTestBuilder_path = '../../build_tools/SCons/cxxtest.py'
CxxTest_dir = '../..'

# First a little python magic to pull in CxxTestBuilder
from importlib.machinery import SourceFileLoader
cxxtest = SourceFileLoader('cxxtest', CxxTestBuilder_path).load_module()
env = Environment()
cxxtest.generate(env, CXXTEST_INSTALL_DIR=CxxTest_dir)

for test in env.Glob('*.t.h'):
  env.CxxTest(test)
