#!/usr/bin/env bash
INSTALLDIR=$(cd "$(dirname "$0")"; pwd)
PLUGIN_DIR=$INSTALLDIR/../PlugIns

# On first launch of quarantined apps launchd passes a command line parameter of the form -psn_0_XXXXXX
# to the application. We discard this otherwise workbench's argparse will choke on it.
# https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder
if [[ "${1}" == -psn_* ]]; then
  shift 1
fi
env PYTHONPATH=${INSTALLDIR}:${PYTHONPATH} env QT_PLUGIN_PATH=$PLUGIN_DIR ${INSTALLDIR}/workbench-script $* || /usr/bin/python $INSTALLDIR/../../scripts/ErrorReporter/error_dialog_app.py --exitcode=$? --directory=$INSTALLDIR --qtdir=$PLUGIN_DIR --application=workbench
