#!/usr/bin/env bash
#
# For OS X only
# Launch an ipython console using the mantidpython script

# Get the path of this script
# This method should be robust; work through nested symlinks etc
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
  while([ -h "${SCRIPT_PATH}" ]) do 
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")"; 
  done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd  > /dev/null

MANTID_PATH=${SCRIPT_PATH}/../../../MantidPlot.app/Contents/MacOS

."${MANTID_PATH}"/mantidpython qtconsole
