#pylint: disable=invalid-name
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sans/eqsans_instrument.ui'
#
# Created: Wed Jun 19 11:05:08 2013
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1026, 1273)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Plain)
        Frame.setLineWidth(8)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1026, 1273))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.instr_name_label = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instr_name_label.sizePolicy().hasHeightForWidth())
        self.instr_name_label.setSizePolicy(sizePolicy)
        self.instr_name_label.setMinimumSize(QtCore.QSize(100, 30))
        self.instr_name_label.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.instr_name_label.setFont(font)
        self.instr_name_label.setObjectName("instr_name_label")
        self.horizontalLayout_13.addWidget(self.instr_name_label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.help_button = QtGui.QCommandLinkButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        self.help_button.setMinimumSize(QtCore.QSize(73, 30))
        self.help_button.setMaximumSize(QtCore.QSize(73, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.help_button.setFont(font)
        self.help_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.help_button.setIconSize(QtCore.QSize(15, 15))
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_13.addWidget(self.help_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.reduction_options_group = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduction_options_group.sizePolicy().hasHeightForWidth())
        self.reduction_options_group.setSizePolicy(sizePolicy)
        self.reduction_options_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reduction_options_group.setObjectName("reduction_options_group")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.reduction_options_group)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.monitor_layout = QtGui.QHBoxLayout()
        self.monitor_layout.setObjectName("monitor_layout")
        self.beam_monitor_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.beam_monitor_chk.setMinimumSize(QtCore.QSize(180, 0))
        self.beam_monitor_chk.setMaximumSize(QtCore.QSize(180, 16777215))
        self.beam_monitor_chk.setObjectName("beam_monitor_chk")
        self.monitor_layout.addWidget(self.beam_monitor_chk)
        self.beam_monitor_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.beam_monitor_edit.setObjectName("beam_monitor_edit")
        self.monitor_layout.addWidget(self.beam_monitor_edit)
        self.beam_monitor_browse_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_monitor_browse_button.sizePolicy().hasHeightForWidth())
        self.beam_monitor_browse_button.setSizePolicy(sizePolicy)
        self.beam_monitor_browse_button.setObjectName("beam_monitor_browse_button")
        self.monitor_layout.addWidget(self.beam_monitor_browse_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.monitor_layout.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.monitor_layout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.att_scale_factor_label = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.att_scale_factor_label.sizePolicy().hasHeightForWidth())
        self.att_scale_factor_label.setSizePolicy(sizePolicy)
        self.att_scale_factor_label.setMinimumSize(QtCore.QSize(180, 0))
        self.att_scale_factor_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.att_scale_factor_label.setObjectName("att_scale_factor_label")
        self.horizontalLayout_4.addWidget(self.att_scale_factor_label)
        self.scale_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.scale_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.scale_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scale_edit.setObjectName("scale_edit")
        self.horizontalLayout_4.addWidget(self.scale_edit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scale_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.scale_chk.setObjectName("scale_chk")
        self.horizontalLayout_6.addWidget(self.scale_chk)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.abs_scale_direct_beam_layout = QtGui.QHBoxLayout()
        self.abs_scale_direct_beam_layout.setObjectName("abs_scale_direct_beam_layout")
        spacerItem3 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_direct_beam_layout.addItem(spacerItem3)
        self.direct_beam_label = QtGui.QLabel(self.reduction_options_group)
        self.direct_beam_label.setMinimumSize(QtCore.QSize(150, 0))
        self.direct_beam_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.direct_beam_label.setObjectName("direct_beam_label")
        self.abs_scale_direct_beam_layout.addWidget(self.direct_beam_label)
        self.scale_data_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.scale_data_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.scale_data_edit.setObjectName("scale_data_edit")
        self.abs_scale_direct_beam_layout.addWidget(self.scale_data_edit)
        self.scale_data_browse_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_data_browse_button.sizePolicy().hasHeightForWidth())
        self.scale_data_browse_button.setSizePolicy(sizePolicy)
        self.scale_data_browse_button.setObjectName("scale_data_browse_button")
        self.abs_scale_direct_beam_layout.addWidget(self.scale_data_browse_button)
        self.scale_data_plot_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_data_plot_button.sizePolicy().hasHeightForWidth())
        self.scale_data_plot_button.setSizePolicy(sizePolicy)
        self.scale_data_plot_button.setObjectName("scale_data_plot_button")
        self.abs_scale_direct_beam_layout.addWidget(self.scale_data_plot_button)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_direct_beam_layout.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.abs_scale_direct_beam_layout)
        self.abs_scale_options_layout = QtGui.QHBoxLayout()
        self.abs_scale_options_layout.setObjectName("abs_scale_options_layout")
        spacerItem5 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_options_layout.addItem(spacerItem5)
        self.beamstop_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.beamstop_chk.setObjectName("beamstop_chk")
        self.abs_scale_options_layout.addWidget(self.beamstop_chk)
        self.scale_beam_radius_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.scale_beam_radius_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.scale_beam_radius_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scale_beam_radius_edit.setObjectName("scale_beam_radius_edit")
        self.abs_scale_options_layout.addWidget(self.scale_beam_radius_edit)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.abs_scale_options_layout.addItem(spacerItem6)
        self.att_trans_label = QtGui.QLabel(self.reduction_options_group)
        self.att_trans_label.setObjectName("att_trans_label")
        self.abs_scale_options_layout.addWidget(self.att_trans_label)
        self.scale_att_trans_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scale_att_trans_edit.sizePolicy().hasHeightForWidth())
        self.scale_att_trans_edit.setSizePolicy(sizePolicy)
        self.scale_att_trans_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.scale_att_trans_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.scale_att_trans_edit.setObjectName("scale_att_trans_edit")
        self.abs_scale_options_layout.addWidget(self.scale_att_trans_edit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.abs_scale_options_layout.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.abs_scale_options_layout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dark_current_check = QtGui.QCheckBox(self.reduction_options_group)
        self.dark_current_check.setMinimumSize(QtCore.QSize(180, 0))
        self.dark_current_check.setMaximumSize(QtCore.QSize(180, 16777215))
        self.dark_current_check.setObjectName("dark_current_check")
        self.horizontalLayout_7.addWidget(self.dark_current_check)
        self.dark_file_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_file_edit.sizePolicy().hasHeightForWidth())
        self.dark_file_edit.setSizePolicy(sizePolicy)
        self.dark_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.dark_file_edit.setBaseSize(QtCore.QSize(0, 0))
        self.dark_file_edit.setObjectName("dark_file_edit")
        self.horizontalLayout_7.addWidget(self.dark_file_edit)
        self.dark_browse_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_browse_button.sizePolicy().hasHeightForWidth())
        self.dark_browse_button.setSizePolicy(sizePolicy)
        self.dark_browse_button.setObjectName("dark_browse_button")
        self.horizontalLayout_7.addWidget(self.dark_browse_button)
        self.dark_plot_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_plot_button.sizePolicy().hasHeightForWidth())
        self.dark_plot_button.setSizePolicy(sizePolicy)
        self.dark_plot_button.setMinimumSize(QtCore.QSize(0, 0))
        self.dark_plot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dark_plot_button.setObjectName("dark_plot_button")
        self.horizontalLayout_7.addWidget(self.dark_plot_button)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.solid_angle_chk = QtGui.QCheckBox(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solid_angle_chk.sizePolicy().hasHeightForWidth())
        self.solid_angle_chk.setSizePolicy(sizePolicy)
        self.solid_angle_chk.setObjectName("solid_angle_chk")
        self.horizontalLayout_8.addWidget(self.solid_angle_chk)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.resolution_layout = QtGui.QHBoxLayout()
        self.resolution_layout.setObjectName("resolution_layout")
        self.resolution_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.resolution_chk.setMinimumSize(QtCore.QSize(180, 0))
        self.resolution_chk.setMaximumSize(QtCore.QSize(180, 16777215))
        self.resolution_chk.setObjectName("resolution_chk")
        self.resolution_layout.addWidget(self.resolution_chk)
        self.sample_apert_label = QtGui.QLabel(self.reduction_options_group)
        self.sample_apert_label.setMinimumSize(QtCore.QSize(150, 0))
        self.sample_apert_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sample_apert_label.setObjectName("sample_apert_label")
        self.resolution_layout.addWidget(self.sample_apert_label)
        self.sample_apert_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.sample_apert_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.sample_apert_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sample_apert_edit.setObjectName("sample_apert_edit")
        self.resolution_layout.addWidget(self.sample_apert_edit)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.resolution_layout.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.resolution_layout)
        self.config_options_layout = QtGui.QHBoxLayout()
        self.config_options_layout.setObjectName("config_options_layout")
        self.low_tof_label = QtGui.QLabel(self.reduction_options_group)
        self.low_tof_label.setMinimumSize(QtCore.QSize(180, 0))
        self.low_tof_label.setObjectName("low_tof_label")
        self.config_options_layout.addWidget(self.low_tof_label)
        self.low_tof_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_tof_edit.sizePolicy().hasHeightForWidth())
        self.low_tof_edit.setSizePolicy(sizePolicy)
        self.low_tof_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.low_tof_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.low_tof_edit.setObjectName("low_tof_edit")
        self.config_options_layout.addWidget(self.low_tof_edit)
        self.high_tof_label = QtGui.QLabel(self.reduction_options_group)
        self.high_tof_label.setObjectName("high_tof_label")
        self.config_options_layout.addWidget(self.high_tof_label)
        self.high_tof_edit = QtGui.QLineEdit(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.high_tof_edit.sizePolicy().hasHeightForWidth())
        self.high_tof_edit.setSizePolicy(sizePolicy)
        self.high_tof_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.high_tof_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.high_tof_edit.setObjectName("high_tof_edit")
        self.config_options_layout.addWidget(self.high_tof_edit)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.config_options_layout.addItem(spacerItem11)
        self.tof_cut_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.tof_cut_chk.setObjectName("tof_cut_chk")
        self.config_options_layout.addWidget(self.tof_cut_chk)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.config_options_layout.addItem(spacerItem12)
        self.tof_correction_chk = QtGui.QCheckBox(self.reduction_options_group)
        self.tof_correction_chk.setObjectName("tof_correction_chk")
        self.config_options_layout.addWidget(self.tof_correction_chk)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.config_options_layout.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.config_options_layout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(180, 0))
        self.label_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.n_q_bins_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.n_q_bins_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.n_q_bins_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.n_q_bins_edit.setObjectName("n_q_bins_edit")
        self.horizontalLayout_9.addWidget(self.n_q_bins_edit)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.lin_binning_radio = QtGui.QRadioButton(self.reduction_options_group)
        self.lin_binning_radio.setObjectName("lin_binning_radio")
        self.horizontalLayout_9.addWidget(self.lin_binning_radio)
        self.log_binning_radio = QtGui.QRadioButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_binning_radio.sizePolicy().hasHeightForWidth())
        self.log_binning_radio.setSizePolicy(sizePolicy)
        self.log_binning_radio.setMinimumSize(QtCore.QSize(120, 0))
        self.log_binning_radio.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.log_binning_radio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.log_binning_radio.setObjectName("log_binning_radio")
        self.horizontalLayout_9.addWidget(self.log_binning_radio)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_5 = QtGui.QLabel(self.reduction_options_group)
        self.label_5.setMinimumSize(QtCore.QSize(180, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.use_data_dir_radio = QtGui.QRadioButton(self.reduction_options_group)
        self.use_data_dir_radio.setAutoExclusive(False)
        self.use_data_dir_radio.setObjectName("use_data_dir_radio")
        self.horizontalLayout_14.addWidget(self.use_data_dir_radio)
        self.select_output_dir_radio = QtGui.QRadioButton(self.reduction_options_group)
        self.select_output_dir_radio.setAutoExclusive(False)
        self.select_output_dir_radio.setObjectName("select_output_dir_radio")
        self.horizontalLayout_14.addWidget(self.select_output_dir_radio)
        self.output_dir_edit = QtGui.QLineEdit(self.reduction_options_group)
        self.output_dir_edit.setObjectName("output_dir_edit")
        self.horizontalLayout_14.addWidget(self.output_dir_edit)
        self.output_dir_browse_button = QtGui.QPushButton(self.reduction_options_group)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_dir_browse_button.sizePolicy().hasHeightForWidth())
        self.output_dir_browse_button.setSizePolicy(sizePolicy)
        self.output_dir_browse_button.setObjectName("output_dir_browse_button")
        self.horizontalLayout_14.addWidget(self.output_dir_browse_button)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addWidget(self.reduction_options_group)
        self.geometry_options_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometry_options_groupbox.sizePolicy().hasHeightForWidth())
        self.geometry_options_groupbox.setSizePolicy(sizePolicy)
        self.geometry_options_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.geometry_options_groupbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.geometry_options_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.geometry_options_groupbox.setObjectName("geometry_options_groupbox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.geometry_options_groupbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mask_template_horiz_layout = QtGui.QHBoxLayout()
        self.mask_template_horiz_layout.setSpacing(0)
        self.mask_template_horiz_layout.setObjectName("mask_template_horiz_layout")
        self.experiment_parameter_help = QtGui.QLabel(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experiment_parameter_help.sizePolicy().hasHeightForWidth())
        self.experiment_parameter_help.setSizePolicy(sizePolicy)
        self.experiment_parameter_help.setMinimumSize(QtCore.QSize(150, 0))
        self.experiment_parameter_help.setStyleSheet("font: italic 10pt \"Bitstream Charter\";")
        self.experiment_parameter_help.setObjectName("experiment_parameter_help")
        self.mask_template_horiz_layout.addWidget(self.experiment_parameter_help)
        self.verticalLayout_5.addLayout(self.mask_template_horiz_layout)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.detector_offset_chk = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.detector_offset_chk.setWhatsThis("")
        self.detector_offset_chk.setObjectName("detector_offset_chk")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.detector_offset_chk)
        self.detector_offset_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        self.detector_offset_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.detector_offset_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.detector_offset_edit.setObjectName("detector_offset_edit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.detector_offset_edit)
        self.sample_dist_chk = QtGui.QCheckBox(self.geometry_options_groupbox)
        self.sample_dist_chk.setObjectName("sample_dist_chk")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.sample_dist_chk)
        self.sample_dist_edit = QtGui.QLineEdit(self.geometry_options_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_dist_edit.sizePolicy().hasHeightForWidth())
        self.sample_dist_edit.setSizePolicy(sizePolicy)
        self.sample_dist_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.sample_dist_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sample_dist_edit.setObjectName("sample_dist_edit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.sample_dist_edit)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_4.addWidget(self.geometry_options_groupbox)
        self.mask_groupbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_groupbox.sizePolicy().hasHeightForWidth())
        self.mask_groupbox.setSizePolicy(sizePolicy)
        self.mask_groupbox.setObjectName("mask_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.mask_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.config_mask_chk = QtGui.QCheckBox(self.mask_groupbox)
        self.config_mask_chk.setObjectName("config_mask_chk")
        self.verticalLayout_2.addWidget(self.config_mask_chk)
        self.mask_help_label = QtGui.QLabel(self.mask_groupbox)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setItalic(True)
        self.mask_help_label.setFont(font)
        self.mask_help_label.setObjectName("mask_help_label")
        self.verticalLayout_2.addWidget(self.mask_help_label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mask_check = QtGui.QCheckBox(self.mask_groupbox)
        self.mask_check.setMinimumSize(QtCore.QSize(180, 0))
        self.mask_check.setObjectName("mask_check")
        self.horizontalLayout.addWidget(self.mask_check)
        self.mask_edit = QtGui.QLineEdit(self.mask_groupbox)
        self.mask_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.mask_edit.setObjectName("mask_edit")
        self.horizontalLayout.addWidget(self.mask_edit)
        self.mask_browse_button = QtGui.QPushButton(self.mask_groupbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_browse_button.sizePolicy().hasHeightForWidth())
        self.mask_browse_button.setSizePolicy(sizePolicy)
        self.mask_browse_button.setObjectName("mask_browse_button")
        self.horizontalLayout.addWidget(self.mask_browse_button)
        self.mask_plot_button = QtGui.QPushButton(self.mask_groupbox)
        self.mask_plot_button.setObjectName("mask_plot_button")
        self.horizontalLayout.addWidget(self.mask_plot_button)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.mask_groupbox)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_name_label.setText(QtGui.QApplication.translate("Frame", "EQSANS", None, QtGui.QApplication.UnicodeUTF8))
        self.help_button.setText(QtGui.QApplication.translate("Frame", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.reduction_options_group.setTitle(QtGui.QApplication.translate("Frame", "Reduction Options", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to normalize to the beam monitor data", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to normalize to the beam monitor data", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_chk.setText(QtGui.QApplication.translate("Frame", "Monitor reference", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid path for the beam monitor reference file.", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_monitor_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.att_scale_factor_label.setText(QtGui.QApplication.translate("Frame", "Absolute scale factor", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a scaling factor to be multiplied to I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_chk.setToolTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Check to calculate the absolute scale factor using the direct beam method.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_chk.setText(QtGui.QApplication.translate("Frame", "Calculate absolute scale factor", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_label.setText(QtGui.QApplication.translate("Frame", "Direct beam file", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_data_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_data_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path for a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_data_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_data_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_data_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.beamstop_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to overright the beam diameter.", None, QtGui.QApplication.UnicodeUTF8))
        self.beamstop_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to overright the beam diameter.", None, QtGui.QApplication.UnicodeUTF8))
        self.beamstop_chk.setText(QtGui.QApplication.translate("Frame", "Beam spot diameter [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_beam_radius_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the diameter around the beam center to include when measuring the total beam signal, in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_beam_radius_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the diameter around the beam center to include when measuring the total beam signal, in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.att_trans_label.setText(QtGui.QApplication.translate("Frame", "Attenuator Transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_att_trans_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the attenuator transmission from the Attenuator Efficiency Chart.", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_att_trans_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the attenuator transmission from the Attenuator Efficiency Chart.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_check.setToolTip(QtGui.QApplication.translate("Frame", "Select to specify a dark current data set.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_check.setStatusTip(QtGui.QApplication.translate("Frame", "Select to specify a dark current data set.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_check.setText(QtGui.QApplication.translate("Frame", "Dark current file", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_file_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_file_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.solid_angle_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to perform a solid angle correction.", None, QtGui.QApplication.UnicodeUTF8))
        self.solid_angle_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to perform a solid angle correction.", None, QtGui.QApplication.UnicodeUTF8))
        self.solid_angle_chk.setText(QtGui.QApplication.translate("Frame", "Perform solid angle correction", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to compute the Q resolution.", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to compute the Q resolution.", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_chk.setText(QtGui.QApplication.translate("Frame", "Q resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_apert_label.setText(QtGui.QApplication.translate("Frame", "Sample aperture diameter [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_apert_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a value for the sample aperture diameter in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_apert_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a value for the sample aperture diameter in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.low_tof_label.setText(QtGui.QApplication.translate("Frame", "Low TOF [microsec]", None, QtGui.QApplication.UnicodeUTF8))
        self.low_tof_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter TOF range to discard at the low end of the TOF spectrum.", None, QtGui.QApplication.UnicodeUTF8))
        self.low_tof_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter TOF range to discard at the low end of the TOF spectrum.", None, QtGui.QApplication.UnicodeUTF8))
        self.high_tof_label.setText(QtGui.QApplication.translate("Frame", "High TOF [microsec]", None, QtGui.QApplication.UnicodeUTF8))
        self.high_tof_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter TOF range to discard at the high end of the TOF spectrum.", None, QtGui.QApplication.UnicodeUTF8))
        self.high_tof_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter TOF range to discard at the high end of the TOF spectrum.", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_cut_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to use to TOF cut information from the configuration file, as applicable.", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_cut_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to use to TOF cut information from the configuration file, as applicable.", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_cut_chk.setText(QtGui.QApplication.translate("Frame", "Use configuration file", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_correction_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to perform the EQSANS TOF correction", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_correction_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to perform the EQSANS TOF correction", None, QtGui.QApplication.UnicodeUTF8))
        self.tof_correction_chk.setText(QtGui.QApplication.translate("Frame", "Correct TOF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Radial averaging", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Number of Q bins  ", None, QtGui.QApplication.UnicodeUTF8))
        self.n_q_bins_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the number of Q bins for the output I(Q) distribution.", None, QtGui.QApplication.UnicodeUTF8))
        self.n_q_bins_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the number of Q bins for the output I(Q) distribution.", None, QtGui.QApplication.UnicodeUTF8))
        self.lin_binning_radio.setToolTip(QtGui.QApplication.translate("Frame", "Select to use linear binning for I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.lin_binning_radio.setStatusTip(QtGui.QApplication.translate("Frame", "Select to use linear binning for I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.lin_binning_radio.setText(QtGui.QApplication.translate("Frame", "Linear Q binning", None, QtGui.QApplication.UnicodeUTF8))
        self.log_binning_radio.setToolTip(QtGui.QApplication.translate("Frame", "Select to use logarithmic binning for I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.log_binning_radio.setStatusTip(QtGui.QApplication.translate("Frame", "Select to use logarithmic binning for I(Q).", None, QtGui.QApplication.UnicodeUTF8))
        self.log_binning_radio.setText(QtGui.QApplication.translate("Frame", "Log Q binning", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.use_data_dir_radio.setToolTip(QtGui.QApplication.translate("Frame", "Select to write the output files in the data directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_data_dir_radio.setStatusTip(QtGui.QApplication.translate("Frame", "Select to write the output files in the data directory.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_data_dir_radio.setText(QtGui.QApplication.translate("Frame", "Use data directory", None, QtGui.QApplication.UnicodeUTF8))
        self.select_output_dir_radio.setToolTip(QtGui.QApplication.translate("Frame", "Select to choose where to write the output files.", None, QtGui.QApplication.UnicodeUTF8))
        self.select_output_dir_radio.setStatusTip(QtGui.QApplication.translate("Frame", "Select to choose where to write the output files.", None, QtGui.QApplication.UnicodeUTF8))
        self.select_output_dir_radio.setText(QtGui.QApplication.translate("Frame", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.output_dir_edit.setToolTip(QtGui.QApplication.translate("Frame", "Output directory for reduced data.", None, QtGui.QApplication.UnicodeUTF8))
        self.output_dir_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Output directory for reduced data.", None, QtGui.QApplication.UnicodeUTF8))
        self.output_dir_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry_options_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Experiment Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.experiment_parameter_help.setText(QtGui.QApplication.translate("Frame", "The sample-detector distance is updated automatically when a sample data file is selected.\n"\
"Values can be selected by hand by checking the boxes below.", None, QtGui.QApplication.UnicodeUTF8))
        self.detector_offset_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.detector_offset_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to set the detector distance offset.", None, QtGui.QApplication.UnicodeUTF8))
        self.detector_offset_chk.setText(QtGui.QApplication.translate("Frame", "Detector distance offset [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.detector_offset_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.detector_offset_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the detector distance offset in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_dist_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to force the sample-detector distance.", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_dist_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to force the sample-detector distance.", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_dist_chk.setText(QtGui.QApplication.translate("Frame", "Sample-detector distance [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_dist_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_dist_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter the value of the sample-to-detector distance in mm.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_groupbox.setTitle(QtGui.QApplication.translate("Frame", "Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.config_mask_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to mask detectors as specified in the configuration file, as applicable.", None, QtGui.QApplication.UnicodeUTF8))
        self.config_mask_chk.setStatusTip(QtGui.QApplication.translate("Frame", "Select to mask detectors as specified in the configuration file, as applicable.", None, QtGui.QApplication.UnicodeUTF8))
        self.config_mask_chk.setText(QtGui.QApplication.translate("Frame", "Use mask from configuration file as applicable", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_help_label.setText(QtGui.QApplication.translate("Frame", "Choose a file to set your mask. Note that only the mask information, not the data, will be used in the reduction.\n"\
"The data is only used to help you setting the mask.\n"
"The mask information is saved separately so that your data file will NOT be modified.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_check.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply the mask built from the specified data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_check.setStatusTip(QtGui.QApplication.translate("Frame", "Select to apply the mask built from the specified data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_check.setText(QtGui.QApplication.translate("Frame", "Mask file", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a file to be used to create your mask.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_edit.setStatusTip(QtGui.QApplication.translate("Frame", "Enter a file to be used to create your mask.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot 2D data and edit mask.", None, QtGui.QApplication.UnicodeUTF8))
        self.mask_plot_button.setText(QtGui.QApplication.translate("Frame", "Edit Mask", None, QtGui.QApplication.UnicodeUTF8))

