# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sans/eqsans_background.ui'
#
# Created: Tue Aug 23 06:54:05 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setEnabled(True)
        Frame.resize(961, 721)
        Frame.setFrameShape(QtGui.QFrame.NoFrame)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 961, 721))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.background_chk = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_chk.sizePolicy().hasHeightForWidth())
        self.background_chk.setSizePolicy(sizePolicy)
        self.background_chk.setMinimumSize(QtCore.QSize(175, 0))
        self.background_chk.setMaximumSize(QtCore.QSize(175, 16777215))
        self.background_chk.setObjectName("background_chk")
        self.horizontalLayout_4.addWidget(self.background_chk)
        spacerItem = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.background_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_edit.sizePolicy().hasHeightForWidth())
        self.background_edit.setSizePolicy(sizePolicy)
        self.background_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.background_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background_edit.setObjectName("background_edit")
        self.horizontalLayout_4.addWidget(self.background_edit)
        self.background_browse = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_browse.sizePolicy().hasHeightForWidth())
        self.background_browse.setSizePolicy(sizePolicy)
        self.background_browse.setMinimumSize(QtCore.QSize(0, 0))
        self.background_browse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background_browse.setObjectName("background_browse")
        self.horizontalLayout_4.addWidget(self.background_browse)
        self.background_plot_button = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background_plot_button.sizePolicy().hasHeightForWidth())
        self.background_plot_button.setSizePolicy(sizePolicy)
        self.background_plot_button.setMinimumSize(QtCore.QSize(0, 0))
        self.background_plot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background_plot_button.setToolTip("")
        self.background_plot_button.setObjectName("background_plot_button")
        self.horizontalLayout_4.addWidget(self.background_plot_button)
        spacerItem1 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.transmission_grpbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.transmission_grpbox.setObjectName("transmission_grpbox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.transmission_grpbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bck_trans_label = QtGui.QLabel(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bck_trans_label.sizePolicy().hasHeightForWidth())
        self.bck_trans_label.setSizePolicy(sizePolicy)
        self.bck_trans_label.setMinimumSize(QtCore.QSize(180, 0))
        self.bck_trans_label.setMaximumSize(QtCore.QSize(180, 16777215))
        self.bck_trans_label.setObjectName("bck_trans_label")
        self.horizontalLayout.addWidget(self.bck_trans_label)
        spacerItem3 = QtGui.QSpacerItem(63, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.transmission_edit = QtGui.QLineEdit(self.transmission_grpbox)
        self.transmission_edit.setEnabled(False)
        self.transmission_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.transmission_edit.setMaximumSize(QtCore.QSize(80, 30))
        self.transmission_edit.setObjectName("transmission_edit")
        self.horizontalLayout.addWidget(self.transmission_edit)
        self.bck_trans_err_label = QtGui.QLabel(self.transmission_grpbox)
        self.bck_trans_err_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bck_trans_err_label.setObjectName("bck_trans_err_label")
        self.horizontalLayout.addWidget(self.bck_trans_err_label)
        self.dtransmission_edit = QtGui.QLineEdit(self.transmission_grpbox)
        self.dtransmission_edit.setEnabled(True)
        self.dtransmission_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.dtransmission_edit.setMaximumSize(QtCore.QSize(80, 30))
        self.dtransmission_edit.setObjectName("dtransmission_edit")
        self.horizontalLayout.addWidget(self.dtransmission_edit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.theta_dep_chk = QtGui.QCheckBox(self.transmission_grpbox)
        self.theta_dep_chk.setObjectName("theta_dep_chk")
        self.verticalLayout_3.addWidget(self.theta_dep_chk)
        self.calculate_trans_chk = QtGui.QCheckBox(self.transmission_grpbox)
        self.calculate_trans_chk.setObjectName("calculate_trans_chk")
        self.verticalLayout_3.addWidget(self.calculate_trans_chk)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.sample_label = QtGui.QLabel(self.transmission_grpbox)
        self.sample_label.setMinimumSize(QtCore.QSize(203, 0))
        self.sample_label.setMaximumSize(QtCore.QSize(203, 16777215))
        self.sample_label.setObjectName("sample_label")
        self.horizontalLayout_5.addWidget(self.sample_label)
        self.sample_edit = QtGui.QLineEdit(self.transmission_grpbox)
        self.sample_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.sample_edit.setObjectName("sample_edit")
        self.horizontalLayout_5.addWidget(self.sample_edit)
        self.sample_button = QtGui.QPushButton(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_button.sizePolicy().hasHeightForWidth())
        self.sample_button.setSizePolicy(sizePolicy)
        self.sample_button.setObjectName("sample_button")
        self.horizontalLayout_5.addWidget(self.sample_button)
        self.sample_plot_button = QtGui.QPushButton(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_plot_button.sizePolicy().hasHeightForWidth())
        self.sample_plot_button.setSizePolicy(sizePolicy)
        self.sample_plot_button.setObjectName("sample_plot_button")
        self.horizontalLayout_5.addWidget(self.sample_plot_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.empty_label = QtGui.QLabel(self.transmission_grpbox)
        self.empty_label.setMinimumSize(QtCore.QSize(203, 0))
        self.empty_label.setMaximumSize(QtCore.QSize(203, 16777215))
        self.empty_label.setObjectName("empty_label")
        self.horizontalLayout_2.addWidget(self.empty_label)
        self.empty_edit = QtGui.QLineEdit(self.transmission_grpbox)
        self.empty_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.empty_edit.setObjectName("empty_edit")
        self.horizontalLayout_2.addWidget(self.empty_edit)
        self.empty_button = QtGui.QPushButton(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_button.sizePolicy().hasHeightForWidth())
        self.empty_button.setSizePolicy(sizePolicy)
        self.empty_button.setObjectName("empty_button")
        self.horizontalLayout_2.addWidget(self.empty_button)
        self.empty_plot_button = QtGui.QPushButton(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_plot_button.sizePolicy().hasHeightForWidth())
        self.empty_plot_button.setSizePolicy(sizePolicy)
        self.empty_plot_button.setObjectName("empty_plot_button")
        self.horizontalLayout_2.addWidget(self.empty_plot_button)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.beam_radius_label = QtGui.QLabel(self.transmission_grpbox)
        self.beam_radius_label.setMinimumSize(QtCore.QSize(203, 0))
        self.beam_radius_label.setMaximumSize(QtCore.QSize(203, 16777215))
        self.beam_radius_label.setObjectName("beam_radius_label")
        self.horizontalLayout_6.addWidget(self.beam_radius_label)
        self.beam_radius_edit = QtGui.QLineEdit(self.transmission_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_edit.sizePolicy().hasHeightForWidth())
        self.beam_radius_edit.setSizePolicy(sizePolicy)
        self.beam_radius_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.beam_radius_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.beam_radius_edit.setObjectName("beam_radius_edit")
        self.horizontalLayout_6.addWidget(self.beam_radius_edit)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.fit_together_check = QtGui.QCheckBox(self.transmission_grpbox)
        self.fit_together_check.setObjectName("fit_together_check")
        self.horizontalLayout_7.addWidget(self.fit_together_check)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.transmission_grpbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.background_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply a background subtraction.", None, QtGui.QApplication.UnicodeUTF8))
        self.background_chk.setText(QtGui.QApplication.translate("Frame", "Background data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.background_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid data file path.", None, QtGui.QApplication.UnicodeUTF8))
        self.background_browse.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.background_browse.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.background_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.transmission_grpbox.setTitle(QtGui.QApplication.translate("Frame", "Transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.bck_trans_label.setText(QtGui.QApplication.translate("Frame", "Background transmission:", None, QtGui.QApplication.UnicodeUTF8))
        self.transmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Transmission value for the background in %.", None, QtGui.QApplication.UnicodeUTF8))
        self.bck_trans_err_label.setText(QtGui.QApplication.translate("Frame", "+/-", None, QtGui.QApplication.UnicodeUTF8))
        self.dtransmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Uncertainty on the background transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.theta_dep_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply a theta-dependent transmission correction.", None, QtGui.QApplication.UnicodeUTF8))
        self.theta_dep_chk.setText(QtGui.QApplication.translate("Frame", "Theta-dependent correction", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_trans_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software calculate the background transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_trans_chk.setText(QtGui.QApplication.translate("Frame", "Calculate background transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_label.setText(QtGui.QApplication.translate("Frame", "Sample direct beam data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.sample_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.empty_label.setText(QtGui.QApplication.translate("Frame", "Empty direct beam data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.empty_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.empty_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_label.setText(QtGui.QApplication.translate("Frame", "Beam radius (pixels)", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_together_check.setToolTip(QtGui.QApplication.translate("Frame", "Select to fit the two frames together when in frame-skipping mode.", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_together_check.setText(QtGui.QApplication.translate("Frame", "Fit frames together", None, QtGui.QApplication.UnicodeUTF8))

