# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sans/hfir_detector.ui'
#
# Created: Fri Apr 15 15:10:01 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1030, 731)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1010, 711))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.beam_center_grpbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_center_grpbox.sizePolicy().hasHeightForWidth())
        self.beam_center_grpbox.setSizePolicy(sizePolicy)
        self.beam_center_grpbox.setObjectName("beam_center_grpbox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.beam_center_grpbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setMargin(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_pos_label = QtGui.QLabel(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_pos_label.sizePolicy().hasHeightForWidth())
        self.x_pos_label.setSizePolicy(sizePolicy)
        self.x_pos_label.setObjectName("x_pos_label")
        self.horizontalLayout.addWidget(self.x_pos_label)
        self.x_pos_edit = QtGui.QLineEdit(self.beam_center_grpbox)
        self.x_pos_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.x_pos_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.x_pos_edit.setObjectName("x_pos_edit")
        self.horizontalLayout.addWidget(self.x_pos_edit)
        self.y_pos_label = QtGui.QLabel(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_pos_label.sizePolicy().hasHeightForWidth())
        self.y_pos_label.setSizePolicy(sizePolicy)
        self.y_pos_label.setObjectName("y_pos_label")
        self.horizontalLayout.addWidget(self.y_pos_label)
        self.y_pos_edit = QtGui.QLineEdit(self.beam_center_grpbox)
        self.y_pos_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.y_pos_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.y_pos_edit.setObjectName("y_pos_edit")
        self.horizontalLayout.addWidget(self.y_pos_edit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.use_beam_finder_checkbox = QtGui.QCheckBox(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_beam_finder_checkbox.sizePolicy().hasHeightForWidth())
        self.use_beam_finder_checkbox.setSizePolicy(sizePolicy)
        self.use_beam_finder_checkbox.setObjectName("use_beam_finder_checkbox")
        self.verticalLayout_4.addWidget(self.use_beam_finder_checkbox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.direct_beam = QtGui.QRadioButton(self.beam_center_grpbox)
        self.direct_beam.setMinimumSize(QtCore.QSize(168, 0))
        self.direct_beam.setChecked(True)
        self.direct_beam.setObjectName("direct_beam")
        self.horizontalLayout_2.addWidget(self.direct_beam)
        self.scattering_data = QtGui.QRadioButton(self.beam_center_grpbox)
        self.scattering_data.setObjectName("scattering_data")
        self.horizontalLayout_2.addWidget(self.scattering_data)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.data_file_label = QtGui.QLabel(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_label.sizePolicy().hasHeightForWidth())
        self.data_file_label.setSizePolicy(sizePolicy)
        self.data_file_label.setMinimumSize(QtCore.QSize(170, 0))
        self.data_file_label.setMaximumSize(QtCore.QSize(170, 16777215))
        self.data_file_label.setObjectName("data_file_label")
        self.horizontalLayout_4.addWidget(self.data_file_label)
        self.beam_data_file_edit = QtGui.QLineEdit(self.beam_center_grpbox)
        self.beam_data_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.beam_data_file_edit.setObjectName("beam_data_file_edit")
        self.horizontalLayout_4.addWidget(self.beam_data_file_edit)
        self.data_file_browse_button = QtGui.QPushButton(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_browse_button.sizePolicy().hasHeightForWidth())
        self.data_file_browse_button.setSizePolicy(sizePolicy)
        self.data_file_browse_button.setObjectName("data_file_browse_button")
        self.horizontalLayout_4.addWidget(self.data_file_browse_button)
        self.data_file_plot_button = QtGui.QPushButton(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_plot_button.sizePolicy().hasHeightForWidth())
        self.data_file_plot_button.setSizePolicy(sizePolicy)
        self.data_file_plot_button.setMinimumSize(QtCore.QSize(0, 0))
        self.data_file_plot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_file_plot_button.setObjectName("data_file_plot_button")
        self.horizontalLayout_4.addWidget(self.data_file_plot_button)
        spacerItem2 = QtGui.QSpacerItem(35, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.beam_radius_label = QtGui.QLabel(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_label.sizePolicy().hasHeightForWidth())
        self.beam_radius_label.setSizePolicy(sizePolicy)
        self.beam_radius_label.setMinimumSize(QtCore.QSize(170, 0))
        self.beam_radius_label.setObjectName("beam_radius_label")
        self.horizontalLayout_3.addWidget(self.beam_radius_label)
        self.beam_radius_edit = QtGui.QLineEdit(self.beam_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_edit.sizePolicy().hasHeightForWidth())
        self.beam_radius_edit.setSizePolicy(sizePolicy)
        self.beam_radius_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.beam_radius_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.beam_radius_edit.setObjectName("beam_radius_edit")
        self.horizontalLayout_3.addWidget(self.beam_radius_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addWidget(self.beam_center_grpbox)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem4)
        self.sensitivity_grpbox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_grpbox.sizePolicy().hasHeightForWidth())
        self.sensitivity_grpbox.setSizePolicy(sizePolicy)
        self.sensitivity_grpbox.setObjectName("sensitivity_grpbox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.sensitivity_grpbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sensitivity_chk = QtGui.QCheckBox(self.sensitivity_grpbox)
        self.sensitivity_chk.setObjectName("sensitivity_chk")
        self.verticalLayout_8.addWidget(self.sensitivity_chk)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sensitivity_file_label = QtGui.QLabel(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_file_label.sizePolicy().hasHeightForWidth())
        self.sensitivity_file_label.setSizePolicy(sizePolicy)
        self.sensitivity_file_label.setMinimumSize(QtCore.QSize(175, 0))
        self.sensitivity_file_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sensitivity_file_label.setWordWrap(False)
        self.sensitivity_file_label.setIndent(0)
        self.sensitivity_file_label.setObjectName("sensitivity_file_label")
        self.horizontalLayout_9.addWidget(self.sensitivity_file_label)
        self.sensitivity_file_edit = QtGui.QLineEdit(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_file_edit.sizePolicy().hasHeightForWidth())
        self.sensitivity_file_edit.setSizePolicy(sizePolicy)
        self.sensitivity_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.sensitivity_file_edit.setBaseSize(QtCore.QSize(0, 0))
        self.sensitivity_file_edit.setObjectName("sensitivity_file_edit")
        self.horizontalLayout_9.addWidget(self.sensitivity_file_edit)
        self.sensitivity_browse_button = QtGui.QPushButton(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_browse_button.sizePolicy().hasHeightForWidth())
        self.sensitivity_browse_button.setSizePolicy(sizePolicy)
        self.sensitivity_browse_button.setObjectName("sensitivity_browse_button")
        self.horizontalLayout_9.addWidget(self.sensitivity_browse_button)
        self.sensitivity_plot_button = QtGui.QPushButton(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_plot_button.sizePolicy().hasHeightForWidth())
        self.sensitivity_plot_button.setSizePolicy(sizePolicy)
        self.sensitivity_plot_button.setMinimumSize(QtCore.QSize(0, 0))
        self.sensitivity_plot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensitivity_plot_button.setObjectName("sensitivity_plot_button")
        self.horizontalLayout_9.addWidget(self.sensitivity_plot_button)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sensitivity_dark_file_label = QtGui.QLabel(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_dark_file_label.sizePolicy().hasHeightForWidth())
        self.sensitivity_dark_file_label.setSizePolicy(sizePolicy)
        self.sensitivity_dark_file_label.setMinimumSize(QtCore.QSize(175, 0))
        self.sensitivity_dark_file_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sensitivity_dark_file_label.setWordWrap(False)
        self.sensitivity_dark_file_label.setIndent(0)
        self.sensitivity_dark_file_label.setObjectName("sensitivity_dark_file_label")
        self.horizontalLayout_10.addWidget(self.sensitivity_dark_file_label)
        self.sensitivity_dark_file_edit = QtGui.QLineEdit(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_dark_file_edit.sizePolicy().hasHeightForWidth())
        self.sensitivity_dark_file_edit.setSizePolicy(sizePolicy)
        self.sensitivity_dark_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.sensitivity_dark_file_edit.setBaseSize(QtCore.QSize(0, 0))
        self.sensitivity_dark_file_edit.setObjectName("sensitivity_dark_file_edit")
        self.horizontalLayout_10.addWidget(self.sensitivity_dark_file_edit)
        self.sensitivity_dark_browse_button = QtGui.QPushButton(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_dark_browse_button.sizePolicy().hasHeightForWidth())
        self.sensitivity_dark_browse_button.setSizePolicy(sizePolicy)
        self.sensitivity_dark_browse_button.setObjectName("sensitivity_dark_browse_button")
        self.horizontalLayout_10.addWidget(self.sensitivity_dark_browse_button)
        self.sensitivity_dark_plot_button = QtGui.QPushButton(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_dark_plot_button.sizePolicy().hasHeightForWidth())
        self.sensitivity_dark_plot_button.setSizePolicy(sizePolicy)
        self.sensitivity_dark_plot_button.setMinimumSize(QtCore.QSize(0, 0))
        self.sensitivity_dark_plot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensitivity_dark_plot_button.setObjectName("sensitivity_dark_plot_button")
        self.horizontalLayout_10.addWidget(self.sensitivity_dark_plot_button)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sensitivity_range_label = QtGui.QLabel(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_range_label.sizePolicy().hasHeightForWidth())
        self.sensitivity_range_label.setSizePolicy(sizePolicy)
        self.sensitivity_range_label.setMinimumSize(QtCore.QSize(175, 0))
        self.sensitivity_range_label.setIndent(0)
        self.sensitivity_range_label.setObjectName("sensitivity_range_label")
        self.horizontalLayout_11.addWidget(self.sensitivity_range_label)
        self.sensitivity_min_label = QtGui.QLabel(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_min_label.sizePolicy().hasHeightForWidth())
        self.sensitivity_min_label.setSizePolicy(sizePolicy)
        self.sensitivity_min_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensitivity_min_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sensitivity_min_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sensitivity_min_label.setObjectName("sensitivity_min_label")
        self.horizontalLayout_11.addWidget(self.sensitivity_min_label)
        self.min_sensitivity_edit = QtGui.QLineEdit(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_sensitivity_edit.sizePolicy().hasHeightForWidth())
        self.min_sensitivity_edit.setSizePolicy(sizePolicy)
        self.min_sensitivity_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.min_sensitivity_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.min_sensitivity_edit.setObjectName("min_sensitivity_edit")
        self.horizontalLayout_11.addWidget(self.min_sensitivity_edit)
        self.sensitivity_max_label = QtGui.QLabel(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivity_max_label.sizePolicy().hasHeightForWidth())
        self.sensitivity_max_label.setSizePolicy(sizePolicy)
        self.sensitivity_max_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensitivity_max_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sensitivity_max_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sensitivity_max_label.setObjectName("sensitivity_max_label")
        self.horizontalLayout_11.addWidget(self.sensitivity_max_label)
        self.max_sensitivity_edit = QtGui.QLineEdit(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_sensitivity_edit.sizePolicy().hasHeightForWidth())
        self.max_sensitivity_edit.setSizePolicy(sizePolicy)
        self.max_sensitivity_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.max_sensitivity_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.max_sensitivity_edit.setObjectName("max_sensitivity_edit")
        self.horizontalLayout_11.addWidget(self.max_sensitivity_edit)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem8)
        self.flood_center_grpbox = QtGui.QGroupBox(self.sensitivity_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flood_center_grpbox.sizePolicy().hasHeightForWidth())
        self.flood_center_grpbox.setSizePolicy(sizePolicy)
        self.flood_center_grpbox.setObjectName("flood_center_grpbox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.flood_center_grpbox)
        self.verticalLayout_6.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_7.setMargin(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.use_sample_center_checkbox = QtGui.QCheckBox(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_sample_center_checkbox.sizePolicy().hasHeightForWidth())
        self.use_sample_center_checkbox.setSizePolicy(sizePolicy)
        self.use_sample_center_checkbox.setObjectName("use_sample_center_checkbox")
        self.verticalLayout_7.addWidget(self.use_sample_center_checkbox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.x_pos_label_2 = QtGui.QLabel(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_pos_label_2.sizePolicy().hasHeightForWidth())
        self.x_pos_label_2.setSizePolicy(sizePolicy)
        self.x_pos_label_2.setObjectName("x_pos_label_2")
        self.horizontalLayout_5.addWidget(self.x_pos_label_2)
        self.x_pos_edit_2 = QtGui.QLineEdit(self.flood_center_grpbox)
        self.x_pos_edit_2.setMinimumSize(QtCore.QSize(80, 0))
        self.x_pos_edit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.x_pos_edit_2.setObjectName("x_pos_edit_2")
        self.horizontalLayout_5.addWidget(self.x_pos_edit_2)
        self.y_pos_label_2 = QtGui.QLabel(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_pos_label_2.sizePolicy().hasHeightForWidth())
        self.y_pos_label_2.setSizePolicy(sizePolicy)
        self.y_pos_label_2.setObjectName("y_pos_label_2")
        self.horizontalLayout_5.addWidget(self.y_pos_label_2)
        self.y_pos_edit_2 = QtGui.QLineEdit(self.flood_center_grpbox)
        self.y_pos_edit_2.setMinimumSize(QtCore.QSize(80, 0))
        self.y_pos_edit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.y_pos_edit_2.setObjectName("y_pos_edit_2")
        self.horizontalLayout_5.addWidget(self.y_pos_edit_2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.use_beam_finder_checkbox_2 = QtGui.QCheckBox(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_beam_finder_checkbox_2.sizePolicy().hasHeightForWidth())
        self.use_beam_finder_checkbox_2.setSizePolicy(sizePolicy)
        self.use_beam_finder_checkbox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.use_beam_finder_checkbox_2.setObjectName("use_beam_finder_checkbox_2")
        self.horizontalLayout_12.addWidget(self.use_beam_finder_checkbox_2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.direct_beam_2 = QtGui.QRadioButton(self.flood_center_grpbox)
        self.direct_beam_2.setMinimumSize(QtCore.QSize(151, 0))
        self.direct_beam_2.setChecked(True)
        self.direct_beam_2.setObjectName("direct_beam_2")
        self.horizontalLayout_7.addWidget(self.direct_beam_2)
        self.scattering_data_2 = QtGui.QRadioButton(self.flood_center_grpbox)
        self.scattering_data_2.setObjectName("scattering_data_2")
        self.horizontalLayout_7.addWidget(self.scattering_data_2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.data_file_label_2 = QtGui.QLabel(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_label_2.sizePolicy().hasHeightForWidth())
        self.data_file_label_2.setSizePolicy(sizePolicy)
        self.data_file_label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.data_file_label_2.setObjectName("data_file_label_2")
        self.horizontalLayout_6.addWidget(self.data_file_label_2)
        self.beam_data_file_edit_2 = QtGui.QLineEdit(self.flood_center_grpbox)
        self.beam_data_file_edit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.beam_data_file_edit_2.setObjectName("beam_data_file_edit_2")
        self.horizontalLayout_6.addWidget(self.beam_data_file_edit_2)
        self.data_file_browse_button_2 = QtGui.QPushButton(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_browse_button_2.sizePolicy().hasHeightForWidth())
        self.data_file_browse_button_2.setSizePolicy(sizePolicy)
        self.data_file_browse_button_2.setObjectName("data_file_browse_button_2")
        self.horizontalLayout_6.addWidget(self.data_file_browse_button_2)
        self.data_file_plot_button_2 = QtGui.QPushButton(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_file_plot_button_2.sizePolicy().hasHeightForWidth())
        self.data_file_plot_button_2.setSizePolicy(sizePolicy)
        self.data_file_plot_button_2.setMinimumSize(QtCore.QSize(0, 0))
        self.data_file_plot_button_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.data_file_plot_button_2.setObjectName("data_file_plot_button_2")
        self.horizontalLayout_6.addWidget(self.data_file_plot_button_2)
        spacerItem12 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.beam_radius_label_2 = QtGui.QLabel(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_label_2.sizePolicy().hasHeightForWidth())
        self.beam_radius_label_2.setSizePolicy(sizePolicy)
        self.beam_radius_label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.beam_radius_label_2.setObjectName("beam_radius_label_2")
        self.horizontalLayout_8.addWidget(self.beam_radius_label_2)
        self.beam_radius_edit_2 = QtGui.QLineEdit(self.flood_center_grpbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_radius_edit_2.sizePolicy().hasHeightForWidth())
        self.beam_radius_edit_2.setSizePolicy(sizePolicy)
        self.beam_radius_edit_2.setMinimumSize(QtCore.QSize(80, 0))
        self.beam_radius_edit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.beam_radius_edit_2.setObjectName("beam_radius_edit_2")
        self.horizontalLayout_8.addWidget(self.beam_radius_edit_2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.flood_center_grpbox)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.verticalLayout_9.addWidget(self.sensitivity_grpbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_center_grpbox.setTitle(QtGui.QApplication.translate("Frame", "Beam Center", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_label.setText(QtGui.QApplication.translate("Frame", "X position", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_edit.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in X, in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_label.setText(QtGui.QApplication.translate("Frame", "Y position", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_edit.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in Y, in pixels.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software find the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox.setText(QtGui.QApplication.translate("Frame", "Use beam finder", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam.setToolTip(QtGui.QApplication.translate("Frame", "Fit the direct beam to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam.setText(QtGui.QApplication.translate("Frame", "Fit direct beam", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data.setToolTip(QtGui.QApplication.translate("Frame", "Fit only the scattering profile to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data.setText(QtGui.QApplication.translate("Frame", "Fit scattering data", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_label.setText(QtGui.QApplication.translate("Frame", "Data file ", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_data_file_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the file path of a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot data 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_label.setText(QtGui.QApplication.translate("Frame", "Beam radius [pixels]", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the radius of the beam in pixels.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_grpbox.setTitle(QtGui.QApplication.translate("Frame", "Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to perform a detector sensitivity correction.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_chk.setText(QtGui.QApplication.translate("Frame", "Perform sensitivity correction", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_file_label.setText(QtGui.QApplication.translate("Frame", "Sensitivity data file", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_file_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the detector sensitivity data.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_browse_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot data 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_file_label.setText(QtGui.QApplication.translate("Frame", "Dark current data file", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_file_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_browse_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_plot_button.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot data 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_dark_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_range_label.setText(QtGui.QApplication.translate("Frame", "Allowed sensitivity range:", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_min_label.setText(QtGui.QApplication.translate("Frame", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.min_sensitivity_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the minimum allowed relative sensitivity for any given pixel.", None, QtGui.QApplication.UnicodeUTF8))
        self.sensitivity_max_label.setText(QtGui.QApplication.translate("Frame", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.max_sensitivity_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter the maximum allowed relative sensitivity for any given pixel.", None, QtGui.QApplication.UnicodeUTF8))
        self.flood_center_grpbox.setTitle(QtGui.QApplication.translate("Frame", "Flood Data Beam Center", None, QtGui.QApplication.UnicodeUTF8))
        self.use_sample_center_checkbox.setToolTip(QtGui.QApplication.translate("Frame", "Select to use the same beam center for the sensitivity flood data as for the sample data.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_sample_center_checkbox.setText(QtGui.QApplication.translate("Frame", "Use sample beam center", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_label_2.setText(QtGui.QApplication.translate("Frame", "X position", None, QtGui.QApplication.UnicodeUTF8))
        self.x_pos_edit_2.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in X, in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_label_2.setText(QtGui.QApplication.translate("Frame", "Y position", None, QtGui.QApplication.UnicodeUTF8))
        self.y_pos_edit_2.setToolTip(QtGui.QApplication.translate("Frame", "Position of the beam in Y, in pixels.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox_2.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software find the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_beam_finder_checkbox_2.setText(QtGui.QApplication.translate("Frame", "Use beam finder", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_2.setToolTip(QtGui.QApplication.translate("Frame", "Fit the direct beam to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_2.setText(QtGui.QApplication.translate("Frame", "Fit direct beam", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data_2.setToolTip(QtGui.QApplication.translate("Frame", "Fit only the scattering profile to obtain the beam center.", None, QtGui.QApplication.UnicodeUTF8))
        self.scattering_data_2.setText(QtGui.QApplication.translate("Frame", "Fit scattering data", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_label_2.setText(QtGui.QApplication.translate("Frame", "Data file", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_data_file_edit_2.setToolTip(QtGui.QApplication.translate("Frame", "Enter the file path of a direct beam data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button_2.setToolTip(QtGui.QApplication.translate("Frame", "Click to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button_2.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_plot_button_2.setToolTip(QtGui.QApplication.translate("Frame", "Click to plot data 2D data.", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_plot_button_2.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_label_2.setText(QtGui.QApplication.translate("Frame", "Beam radius [pixels]", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_radius_edit_2.setToolTip(QtGui.QApplication.translate("Frame", "Enter the radius of the beam in pixels.", None, QtGui.QApplication.UnicodeUTF8))

