# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sans/hfir_sample_data.ui'
#
# Created: Tue Mar 29 11:35:11 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(807, 459)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(Frame)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 805, 423))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.theta_dep_chk = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.theta_dep_chk.setObjectName("theta_dep_chk")
        self.gridLayout.addWidget(self.theta_dep_chk, 3, 0, 1, 1)
        self.calculate_chk = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.calculate_chk.setObjectName("calculate_chk")
        self.gridLayout.addWidget(self.calculate_chk, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.direct_beam_chk = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direct_beam_chk.sizePolicy().hasHeightForWidth())
        self.direct_beam_chk.setSizePolicy(sizePolicy)
        self.direct_beam_chk.setObjectName("direct_beam_chk")
        self.horizontalLayout_2.addWidget(self.direct_beam_chk)
        self.beam_spreader_chk = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam_spreader_chk.sizePolicy().hasHeightForWidth())
        self.beam_spreader_chk.setSizePolicy(sizePolicy)
        self.beam_spreader_chk.setObjectName("beam_spreader_chk")
        self.horizontalLayout_2.addWidget(self.beam_spreader_chk)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(151, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.transmission_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transmission_edit.sizePolicy().hasHeightForWidth())
        self.transmission_edit.setSizePolicy(sizePolicy)
        self.transmission_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.transmission_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.transmission_edit.setObjectName("transmission_edit")
        self.horizontalLayout.addWidget(self.transmission_edit)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dtransmission_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtransmission_edit.sizePolicy().hasHeightForWidth())
        self.dtransmission_edit.setSizePolicy(sizePolicy)
        self.dtransmission_edit.setMinimumSize(QtCore.QSize(80, 0))
        self.dtransmission_edit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dtransmission_edit.setObjectName("dtransmission_edit")
        self.horizontalLayout.addWidget(self.dtransmission_edit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.dark_current_label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_current_label.sizePolicy().hasHeightForWidth())
        self.dark_current_label.setSizePolicy(sizePolicy)
        self.dark_current_label.setMinimumSize(QtCore.QSize(0, 27))
        self.dark_current_label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dark_current_label.setObjectName("dark_current_label")
        self.horizontalLayout_4.addWidget(self.dark_current_label)
        self.dark_current_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_current_edit.sizePolicy().hasHeightForWidth())
        self.dark_current_edit.setSizePolicy(sizePolicy)
        self.dark_current_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.dark_current_edit.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dark_current_edit.setObjectName("dark_current_edit")
        self.horizontalLayout_4.addWidget(self.dark_current_edit)
        self.dark_current_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dark_current_button.sizePolicy().hasHeightForWidth())
        self.dark_current_button.setSizePolicy(sizePolicy)
        self.dark_current_button.setMinimumSize(QtCore.QSize(85, 0))
        self.dark_current_button.setMaximumSize(QtCore.QSize(16777215, 27))
        self.dark_current_button.setObjectName("dark_current_button")
        self.horizontalLayout_4.addWidget(self.dark_current_button)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        spacerItem6 = QtGui.QSpacerItem(110, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.data_file_edit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.data_file_edit.setMinimumSize(QtCore.QSize(300, 0))
        self.data_file_edit.setObjectName("data_file_edit")
        self.horizontalLayout_7.addWidget(self.data_file_edit)
        self.data_file_browse_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.data_file_browse_button.setMinimumSize(QtCore.QSize(85, 0))
        self.data_file_browse_button.setMaximumSize(QtCore.QSize(85, 16777215))
        self.data_file_browse_button.setObjectName("data_file_browse_button")
        self.horizontalLayout_7.addWidget(self.data_file_browse_button)
        self.data_file_plot_button = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.data_file_plot_button.setMinimumSize(QtCore.QSize(85, 0))
        self.data_file_plot_button.setMaximumSize(QtCore.QSize(85, 16777215))
        self.data_file_plot_button.setObjectName("data_file_plot_button")
        self.horizontalLayout_7.addWidget(self.data_file_plot_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.widget_placeholder = QtGui.QVBoxLayout()
        self.widget_placeholder.setSpacing(0)
        self.widget_placeholder.setObjectName("widget_placeholder")
        self.verticalLayout_2.addLayout(self.widget_placeholder)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.theta_dep_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to apply a theta-dependent transmission correction.", None, QtGui.QApplication.UnicodeUTF8))
        self.theta_dep_chk.setText(QtGui.QApplication.translate("Frame", "Theta-dependent correction", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to let the reduction software calculate the transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.calculate_chk.setText(QtGui.QApplication.translate("Frame", "Calculate transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to use the direct beam method for transmission calculation.", None, QtGui.QApplication.UnicodeUTF8))
        self.direct_beam_chk.setText(QtGui.QApplication.translate("Frame", "Direct beam", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_spreader_chk.setToolTip(QtGui.QApplication.translate("Frame", "Select to use the beam spreader (glassy carbon) method for transmission calculation.", None, QtGui.QApplication.UnicodeUTF8))
        self.beam_spreader_chk.setText(QtGui.QApplication.translate("Frame", "Beam spreader", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Transmission:", None, QtGui.QApplication.UnicodeUTF8))
        self.transmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Sample transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "+/-", None, QtGui.QApplication.UnicodeUTF8))
        self.dtransmission_edit.setToolTip(QtGui.QApplication.translate("Frame", "Uncertainty on the sample transmission.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_label.setText(QtGui.QApplication.translate("Frame", "Dark current for transmission:", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_edit.setToolTip(QtGui.QApplication.translate("Frame", "Enter a valid file path to be used for the dark current data.", None, QtGui.QApplication.UnicodeUTF8))
        self.dark_current_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Scattering data file:", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_browse_button.setText(QtGui.QApplication.translate("Frame", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.data_file_plot_button.setText(QtGui.QApplication.translate("Frame", "Plot", None, QtGui.QApplication.UnicodeUTF8))

