from __future__ import (absolute_import, division, print_function)

#                 Maps friendly user name -> script name
attr_mapping = [("attenuation_file_path",       "attenuation_file_path"),
                ("config_file",                 "config_file_name"),
                ("calibration_config_path",     "cal_map_path"),
                ("calibration_directory",       "calibration_dir"),
                ("do_absorb_corrections",       "absorb_corrections"),
                ("focus_mode",                  "focus_mode"),
                ("long_mode",                   "long_mode"),
                ("monitor_lambda_crop_range",   "monitor_lambda"),
                ("monitor_integration_range",   "monitor_integration_range"),
                ("monitor_spectrum_number",     "monitor_spec_no"),
                ("monitor_spline_coefficient",  "monitor_spline"),
                ("output_directory",            "output_dir"),
                ("perform_attenuation",         "perform_atten"),
                ("raw_data_tof_cropping",       "raw_data_crop_vals"),
                ("run_in_cycle",                "run_in_range"),
                ("run_number",                  "run_number"),
                ("spline_coefficient",          "spline_coefficient"),
                ("tof_cropping_ranges",         "tof_cropping_values"),
                ("tt88_grouping",               "tt88_grouping"),
                ("tt70_grouping",               "tt70_grouping"),
                ("tt35_grouping",               "tt35_grouping"),
                ("tt_mode",                     "tt_mode"),
                ("user_name",                   "user_name"),
                ("vanadium_absorb_file",        "van_absorb_file"),
                ("vanadium_tof_cropping",       "van_tof_cropping"),
                ("vanadium_normalisation",      "van_norm")]
