#ifndef MANTID_ALGORITHMSTEST_PRECOMPILED_HEADER_H_
#define MANTID_ALGORITHMSTEST_PRECOMPILED_HEADER_H_

#include <cxxTest/TestSuite.h>
#undef _CXXTEST_LONGLONG // Kill a warning

#include "MantidAPI/Algorithm.h"

#endif //MANTID_PYTHONAPI_PRECOMPILED_HEADER_H_