name: 'Build Doxygen'
description: 'Builds the doxygen documentation'
runs:
  using: "composite"
  steps:
    - name: Configure cmake
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Create the build directory if it doesn't exist
        [ -d build ] || mkdir build
        cd build

        # Set locale to C for latex
        export LC_ALL=C

        # Configure and generate build files
        pixi run --frozen cmake --preset=doxygen-ci ..
    - name: Build doxygen
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Build doxygen target
        pixi run --frozen cmake --build . --target doxygen
