{% set version = load_setup_py_data().get('version', '0.0.0') %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  entry_points:
    - workbench = workbench.app.main:main
  osx_is_app: true
  ignore_run_exports_from:
      - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja  # [osx or linux]
    - cmake {{ cmake }}
    - git
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - pyqt {{ pyqt }}                        # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - setuptools
    - mantidqt {{ version }}
    - python {{ python }}
    - versioningit
  run:
    - ipykernel
    - psutil
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - qtconsole {{ qtconsole }}
    - {{ pin_compatible("setuptools", max_pin="x.x") }}
    {% if environ.get('INCLUDE_MANTIDDOCS', 'True') != 'False' %}
    - mantiddocs {{ version }}
    {% endif %}
    - mslice

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: MantidWorkbench provides a graphical user interface to the Mantid framework, supporting high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
