{% set version = load_setup_py_data().get('version', '0.0.0') %}

package:
  name: mantidworkbench
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  entry_points:
    - workbench = workbench.app.mantidworkbench_launch_wrapper:launch
    - mantidworkbench = workbench.app.mantidworkbench_launch_wrapper:launch
  osx_is_app: true
  ignore_run_exports_from:
      - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja {{ ninja }}  # [osx or linux]
    - cmake {{ cmake }}
    - git
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
    - pyqt {{ pyqt }}                        # [build_platform != target_platform]
  host:
    - setuptools
    - mantidqt {{ version }}
    - python {{ python }}
    - versioningit {{ versioningit }}
    - libgl-devel  # [linux]
    - xorg-libxxf86vm  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
  run:
    - ipykernel
    - lz4  # [linux]
    - psutil {{ psutil }}
    - {{ pin_compatible("python", max_pin="x.x") }}
    - matplotlib {{ matplotlib }}
    - python.app  # [osx]
    - pystack  # [linux]
    - qtconsole {{ qtconsole }}
    - {{ pin_compatible("setuptools", max_pin="x.x") }}
    {% if environ.get('INCLUDE_MANTIDDOCS', 'True') != 'False' %}
    - mantiddocs {{ version }}
    {% endif %}
  run_constrained:
    - mslice {{ mslice }}

test:
  imports:
    - workbench

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: MantidWorkbench provides a graphical user interface to the Mantid framework, supporting high-performance computing and visualisation of materials science data.

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
