# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../Code/Mantid/MantidPlot/SysMon/ui_sysmon.ui'
#
# Created: Fri Sep 19 12:44:16 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(230, 331)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 320, 293))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelComputerName = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelComputerName.sizePolicy().hasHeightForWidth())
        self.labelComputerName.setSizePolicy(sizePolicy)
        self.labelComputerName.setMinimumSize(QtCore.QSize(0, 0))
        self.labelComputerName.setObjectName(_fromUtf8("labelComputerName"))
        self.gridLayout_7.addWidget(self.labelComputerName, 0, 0, 1, 1)
        self.labelOS = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOS.sizePolicy().hasHeightForWidth())
        self.labelOS.setSizePolicy(sizePolicy)
        self.labelOS.setMinimumSize(QtCore.QSize(0, 0))
        self.labelOS.setObjectName(_fromUtf8("labelOS"))
        self.gridLayout_7.addWidget(self.labelOS, 1, 0, 1, 1)
        self.labelProcFam = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProcFam.sizePolicy().hasHeightForWidth())
        self.labelProcFam.setSizePolicy(sizePolicy)
        self.labelProcFam.setMinimumSize(QtCore.QSize(0, 0))
        self.labelProcFam.setObjectName(_fromUtf8("labelProcFam"))
        self.gridLayout_7.addWidget(self.labelProcFam, 2, 0, 1, 1)
        self.labelNUsers = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNUsers.sizePolicy().hasHeightForWidth())
        self.labelNUsers.setSizePolicy(sizePolicy)
        self.labelNUsers.setMinimumSize(QtCore.QSize(0, 0))
        self.labelNUsers.setObjectName(_fromUtf8("labelNUsers"))
        self.gridLayout_7.addWidget(self.labelNUsers, 3, 0, 1, 1)
        self.labelUptime = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUptime.sizePolicy().hasHeightForWidth())
        self.labelUptime.setSizePolicy(sizePolicy)
        self.labelUptime.setMinimumSize(QtCore.QSize(0, 0))
        self.labelUptime.setObjectName(_fromUtf8("labelUptime"))
        self.gridLayout_7.addWidget(self.labelUptime, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.labelMemUsage = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.labelMemUsage.setFont(font)
        self.labelMemUsage.setObjectName(_fromUtf8("labelMemUsage"))
        self.gridLayout_6.addWidget(self.labelMemUsage, 0, 0, 1, 1)
        self.labelCPUCount = QtGui.QLabel(self.groupBox_5)
        self.labelCPUCount.setObjectName(_fromUtf8("labelCPUCount"))
        self.gridLayout_6.addWidget(self.labelCPUCount, 3, 0, 1, 1)
        self.labelMaxMem = QtGui.QLabel(self.groupBox_5)
        self.labelMaxMem.setObjectName(_fromUtf8("labelMaxMem"))
        self.gridLayout_6.addWidget(self.labelMaxMem, 1, 0, 1, 1)
        self.label_102 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_102.setFont(font)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_6.addWidget(self.label_102, 2, 0, 1, 1)
        self.progressBarStatusCPU = QtGui.QProgressBar(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarStatusCPU.sizePolicy().hasHeightForWidth())
        self.progressBarStatusCPU.setSizePolicy(sizePolicy)
        self.progressBarStatusCPU.setProperty("value", 24)
        self.progressBarStatusCPU.setObjectName(_fromUtf8("progressBarStatusCPU"))
        self.gridLayout_6.addWidget(self.progressBarStatusCPU, 2, 1, 2, 1)
        self.progressBarStatusMemory = QtGui.QProgressBar(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarStatusMemory.sizePolicy().hasHeightForWidth())
        self.progressBarStatusMemory.setSizePolicy(sizePolicy)
        self.progressBarStatusMemory.setProperty("value", 24)
        self.progressBarStatusMemory.setObjectName(_fromUtf8("progressBarStatusMemory"))
        self.gridLayout_6.addWidget(self.progressBarStatusMemory, 0, 1, 2, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.framePlot = QtGui.QFrame(self.tab_2)
        self.framePlot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePlot.setFrameShadow(QtGui.QFrame.Raised)
        self.framePlot.setObjectName(_fromUtf8("framePlot"))
        self.horizontalLayout_2.addWidget(self.framePlot)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelLastUpdate = QtGui.QLabel(self.tab_3)
        self.labelLastUpdate.setMinimumSize(QtCore.QSize(0, 0))
        self.labelLastUpdate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.labelLastUpdate.setObjectName(_fromUtf8("labelLastUpdate"))
        self.horizontalLayout_3.addWidget(self.labelLastUpdate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tableWidgetProcess = QtGui.QTableWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableWidgetProcess.sizePolicy().hasHeightForWidth())
        self.tableWidgetProcess.setSizePolicy(sizePolicy)
        self.tableWidgetProcess.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetProcess.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetProcess.setRowCount(10)
        self.tableWidgetProcess.setColumnCount(5)
        self.tableWidgetProcess.setObjectName(_fromUtf8("tableWidgetProcess"))
        item = QtGui.QTableWidgetItem()
        self.tableWidgetProcess.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetProcess.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetProcess.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetProcess.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetProcess.setHorizontalHeaderItem(4, item)
        self.tableWidgetProcess.horizontalHeader().setDefaultSectionSize(57)
        self.tableWidgetProcess.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetProcess.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetProcess.verticalHeader().setVisible(False)
        self.tableWidgetProcess.verticalHeader().setDefaultSectionSize(20)
        self.tableWidgetProcess.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidgetProcess)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButtonUpdate = QtGui.QPushButton(self.tab_3)
        self.pushButtonUpdate.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonUpdate.setMaximumSize(QtCore.QSize(80, 15))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonUpdate.setFont(font)
        self.pushButtonUpdate.setObjectName(_fromUtf8("pushButtonUpdate"))
        self.horizontalLayout_7.addWidget(self.pushButtonUpdate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setContentsMargins(-1, 3, -1, 2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButtonCPU = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonCPU.sizePolicy().hasHeightForWidth())
        self.radioButtonCPU.setSizePolicy(sizePolicy)
        self.radioButtonCPU.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButtonCPU.setObjectName(_fromUtf8("radioButtonCPU"))
        self.horizontalLayout_6.addWidget(self.radioButtonCPU)
        self.radioButtonMem = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonMem.sizePolicy().hasHeightForWidth())
        self.radioButtonMem.setSizePolicy(sizePolicy)
        self.radioButtonMem.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButtonMem.setChecked(True)
        self.radioButtonMem.setObjectName(_fromUtf8("radioButtonMem"))
        self.horizontalLayout_6.addWidget(self.radioButtonMem)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.frameBar = QtGui.QFrame(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBar.sizePolicy().hasHeightForWidth())
        self.frameBar.setSizePolicy(sizePolicy)
        self.frameBar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBar.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBar.setObjectName(_fromUtf8("frameBar"))
        self.verticalLayout_6.addWidget(self.frameBar)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 303, 244))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton60Secs = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton60Secs.setChecked(True)
        self.radioButton60Secs.setObjectName(_fromUtf8("radioButton60Secs"))
        self.verticalLayout_5.addWidget(self.radioButton60Secs)
        self.radioButton300Secs = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton300Secs.setObjectName(_fromUtf8("radioButton300Secs"))
        self.verticalLayout_5.addWidget(self.radioButton300Secs)
        self.radioButton600Secs = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton600Secs.setObjectName(_fromUtf8("radioButton600Secs"))
        self.verticalLayout_5.addWidget(self.radioButton600Secs)
        self.radioButton3600Secs = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton3600Secs.setObjectName(_fromUtf8("radioButton3600Secs"))
        self.verticalLayout_5.addWidget(self.radioButton3600Secs)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton1Sec = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton1Sec.setObjectName(_fromUtf8("radioButton1Sec"))
        self.verticalLayout_4.addWidget(self.radioButton1Sec)
        self.radioButton2Secs = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton2Secs.setChecked(True)
        self.radioButton2Secs.setObjectName(_fromUtf8("radioButton2Secs"))
        self.verticalLayout_4.addWidget(self.radioButton2Secs)
        self.radioButton5Secs = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton5Secs.setObjectName(_fromUtf8("radioButton5Secs"))
        self.verticalLayout_4.addWidget(self.radioButton5Secs)
        self.radioButton10Secs = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton10Secs.setObjectName(_fromUtf8("radioButton10Secs"))
        self.verticalLayout_4.addWidget(self.radioButton10Secs)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_3.setTitle(_translate("Form", "System Info", None))
        self.labelComputerName.setText(_translate("Form", "Computer Name: ", None))
        self.labelOS.setText(_translate("Form", "Operating System:", None))
        self.labelProcFam.setText(_translate("Form", "Processor Family:", None))
        self.labelNUsers.setText(_translate("Form", "Number of Users Logged On:", None))
        self.labelUptime.setText(_translate("Form", "System Uptime: ", None))
        self.groupBox_5.setTitle(_translate("Form", "Composite System Status", None))
        self.labelMemUsage.setText(_translate("Form", "Memory Usage", None))
        self.labelCPUCount.setText(_translate("Form", "CPU count:", None))
        self.labelMaxMem.setText(_translate("Form", "Max Mem:", None))
        self.label_102.setText(_translate("Form", "Composite CPU Usage", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "System", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "History", None))
        self.labelLastUpdate.setText(_translate("Form", "Last Update: ", None))
        self.tableWidgetProcess.setSortingEnabled(True)
        item = self.tableWidgetProcess.horizontalHeaderItem(0)
        item.setText(_translate("Form", "PID", None))
        item = self.tableWidgetProcess.horizontalHeaderItem(1)
        item.setText(_translate("Form", "USER", None))
        item = self.tableWidgetProcess.horizontalHeaderItem(2)
        item.setText(_translate("Form", "CPU%", None))
        item = self.tableWidgetProcess.horizontalHeaderItem(3)
        item.setText(_translate("Form", "MEM%", None))
        item = self.tableWidgetProcess.horizontalHeaderItem(4)
        item.setText(_translate("Form", "NAME", None))
        self.pushButtonUpdate.setText(_translate("Form", "Hold Updates", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Processes", None))
        self.groupBox.setTitle(_translate("Form", "Sort", None))
        self.radioButtonCPU.setText(_translate("Form", "CPU", None))
        self.radioButtonMem.setText(_translate("Form", "Memory", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Users", None))
        self.groupBox_6.setTitle(_translate("Form", "Display Period", None))
        self.radioButton60Secs.setText(_translate("Form", "60 Seconds", None))
        self.radioButton300Secs.setText(_translate("Form", "300 Seconds", None))
        self.radioButton600Secs.setText(_translate("Form", "600 Seconds", None))
        self.radioButton3600Secs.setText(_translate("Form", "3600 Seconds", None))
        self.groupBox_4.setTitle(_translate("Form", "Update Rate", None))
        self.radioButton1Sec.setText(_translate("Form", "1 Second", None))
        self.radioButton2Secs.setText(_translate("Form", "2 Seconds", None))
        self.radioButton5Secs.setText(_translate("Form", "5 Seconds", None))
        self.radioButton10Secs.setText(_translate("Form", "10 Seconds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Options", None))

