env = Environment()
incs = ['../API/inc', '../Kernel/inc', '../Geometry/inc']

env.Append(CPPPATH=incs)
shared = env.SharedLibrary('UsersAlgorithms', 'HelloWorldAlgorithm.cpp')
retval = { 'shared': shared}
Return('retval')

