#pylint: disable=invalid-name,relative-import,too-many-lines,too-many-instance-attributes,too-many-statements,line-too-longtoo-many-locals,attribute-defined-outside-init
#pylint: disable=invalid-name,relative-import,too-many-lines,too-many-instance-attributes,too-many-statements,line-too-long,too-many-locals,attribute-defined-outside-init
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Mon Jul 13 13:45:09 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

from MplFigureCanvas import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1016, 804)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_General = QtGui.QHBoxLayout()
        self.horizontalLayout_General.setObjectName(_fromUtf8("horizontalLayout_General"))
        self.label_exp = QtGui.QLabel(self.centralwidget)
        self.label_exp.setObjectName(_fromUtf8("label_exp"))
        self.horizontalLayout_General.addWidget(self.label_exp)
        self.lineEdit_exp = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_exp.setObjectName(_fromUtf8("lineEdit_exp"))
        self.horizontalLayout_General.addWidget(self.lineEdit_exp)
        self.pushButton_setExp = QtGui.QPushButton(self.centralwidget)
        self.pushButton_setExp.setObjectName(_fromUtf8("pushButton_setExp"))
        self.horizontalLayout_General.addWidget(self.pushButton_setExp)
        self.verticalLayout_3.addLayout(self.horizontalLayout_General)
        self.horizontalLayout_Tab = QtGui.QHBoxLayout()
        self.horizontalLayout_Tab.setObjectName(_fromUtf8("horizontalLayout_Tab"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_dir = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_dir.sizePolicy().hasHeightForWidth())
        self.label_dir.setSizePolicy(sizePolicy)
        self.label_dir.setMinimumSize(QtCore.QSize(80, 0))
        self.label_dir.setObjectName(_fromUtf8("label_dir"))
        self.horizontalLayout_6.addWidget(self.label_dir)
        self.lineEdit_dirSave = QtGui.QLineEdit(self.tab)
        self.lineEdit_dirSave.setObjectName(_fromUtf8("lineEdit_dirSave"))
        self.horizontalLayout_6.addWidget(self.lineEdit_dirSave)
        self.pushButton_browseSaveDir = QtGui.QPushButton(self.tab)
        self.pushButton_browseSaveDir.setObjectName(_fromUtf8("pushButton_browseSaveDir"))
        self.horizontalLayout_6.addWidget(self.pushButton_browseSaveDir)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_url = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_url.sizePolicy().hasHeightForWidth())
        self.label_url.setSizePolicy(sizePolicy)
        self.label_url.setMinimumSize(QtCore.QSize(80, 0))
        self.label_url.setObjectName(_fromUtf8("label_url"))
        self.horizontalLayout_5.addWidget(self.label_url)
        self.lineEdit_url = QtGui.QLineEdit(self.tab)
        self.lineEdit_url.setObjectName(_fromUtf8("lineEdit_url"))
        self.horizontalLayout_5.addWidget(self.lineEdit_url)
        self.pushButton_testURLs = QtGui.QPushButton(self.tab)
        self.pushButton_testURLs.setObjectName(_fromUtf8("pushButton_testURLs"))
        self.horizontalLayout_5.addWidget(self.pushButton_testURLs)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_downloadScans = QtGui.QLineEdit(self.tab)
        self.lineEdit_downloadScans.setObjectName(_fromUtf8("lineEdit_downloadScans"))
        self.horizontalLayout_2.addWidget(self.lineEdit_downloadScans)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_downloadAll = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_downloadAll.setFont(font)
        self.pushButton_downloadAll.setObjectName(_fromUtf8("pushButton_downloadAll"))
        self.horizontalLayout_2.addWidget(self.pushButton_downloadAll)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_datamode = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_datamode.sizePolicy().hasHeightForWidth())
        self.label_datamode.setSizePolicy(sizePolicy)
        self.label_datamode.setMinimumSize(QtCore.QSize(80, 0))
        self.label_datamode.setObjectName(_fromUtf8("label_datamode"))
        self.horizontalLayout_4.addWidget(self.label_datamode)
        self.comboBox_mode = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mode.sizePolicy().hasHeightForWidth())
        self.comboBox_mode.setSizePolicy(sizePolicy)
        self.comboBox_mode.setObjectName(_fromUtf8("comboBox_mode"))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.comboBox_mode.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_mode)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_runPtPlot = QtGui.QLabel(self.tab_4)
        self.label_runPtPlot.setObjectName(_fromUtf8("label_runPtPlot"))
        self.verticalLayout_5.addWidget(self.label_runPtPlot)
        self.lineEdit_run = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_run.sizePolicy().hasHeightForWidth())
        self.lineEdit_run.setSizePolicy(sizePolicy)
        self.lineEdit_run.setObjectName(_fromUtf8("lineEdit_run"))
        self.verticalLayout_5.addWidget(self.lineEdit_run)
        self.pushButton_load = QtGui.QPushButton(self.tab_4)
        self.pushButton_load.setObjectName(_fromUtf8("pushButton_load"))
        self.verticalLayout_5.addWidget(self.pushButton_load)
        self.lineEdit_ptPlot = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ptPlot.sizePolicy().hasHeightForWidth())
        self.lineEdit_ptPlot.setSizePolicy(sizePolicy)
        self.lineEdit_ptPlot.setObjectName(_fromUtf8("lineEdit_ptPlot"))
        self.verticalLayout_5.addWidget(self.lineEdit_ptPlot)
        self.pushButton_plotScan = QtGui.QPushButton(self.tab_4)
        self.pushButton_plotScan.setObjectName(_fromUtf8("pushButton_plotScan"))
        self.verticalLayout_5.addWidget(self.pushButton_plotScan)
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.pushButton_prevScan = QtGui.QPushButton(self.tab_4)
        self.pushButton_prevScan.setObjectName(_fromUtf8("pushButton_prevScan"))
        self.verticalLayout_5.addWidget(self.pushButton_prevScan)
        self.label_5 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.pushButton_nextScan = QtGui.QPushButton(self.tab_4)
        self.pushButton_nextScan.setObjectName(_fromUtf8("pushButton_nextScan"))
        self.verticalLayout_5.addWidget(self.pushButton_nextScan)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 3, 1, 1)
        self.graphicsView = Qt4MplPlotView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_scanNo = QtGui.QLabel(self.tab_2)
        self.label_scanNo.setObjectName(_fromUtf8("label_scanNo"))
        self.horizontalLayout_9.addWidget(self.label_scanNo)
        self.lineEdit_scanNumber = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_scanNumber.setObjectName(_fromUtf8("lineEdit_scanNumber"))
        self.horizontalLayout_9.addWidget(self.lineEdit_scanNumber)
        self.label_PtNo = QtGui.QLabel(self.tab_2)
        self.label_PtNo.setObjectName(_fromUtf8("label_PtNo"))
        self.horizontalLayout_9.addWidget(self.label_PtNo)
        self.lineEdit_ptNumber = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_ptNumber.setObjectName(_fromUtf8("lineEdit_ptNumber"))
        self.horizontalLayout_9.addWidget(self.lineEdit_ptNumber)
        self.pushButton_findPeak = QtGui.QPushButton(self.tab_2)
        self.pushButton_findPeak.setObjectName(_fromUtf8("pushButton_findPeak"))
        self.horizontalLayout_9.addWidget(self.pushButton_findPeak)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_sampleQx = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sampleQx.setEnabled(False)
        self.lineEdit_sampleQx.setObjectName(_fromUtf8("lineEdit_sampleQx"))
        self.horizontalLayout_10.addWidget(self.lineEdit_sampleQx)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.lineEdit_sampleQy = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sampleQy.setEnabled(False)
        self.lineEdit_sampleQy.setObjectName(_fromUtf8("lineEdit_sampleQy"))
        self.horizontalLayout_10.addWidget(self.lineEdit_sampleQy)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_sampleQz = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sampleQz.setEnabled(False)
        self.lineEdit_sampleQz.setObjectName(_fromUtf8("lineEdit_sampleQz"))
        self.horizontalLayout_10.addWidget(self.lineEdit_sampleQz)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.lineEdit_H = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_H.setObjectName(_fromUtf8("lineEdit_H"))
        self.horizontalLayout_12.addWidget(self.lineEdit_H)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_K = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_K.setObjectName(_fromUtf8("lineEdit_K"))
        self.horizontalLayout_12.addWidget(self.lineEdit_K)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_12.addWidget(self.label_6)
        self.lineEdit_L = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_L.setObjectName(_fromUtf8("lineEdit_L"))
        self.horizontalLayout_12.addWidget(self.lineEdit_L)
        self.pushButton_addPeakToCalUB = QtGui.QPushButton(self.tab_2)
        self.pushButton_addPeakToCalUB.setObjectName(_fromUtf8("pushButton_addPeakToCalUB"))
        self.horizontalLayout_12.addWidget(self.pushButton_addPeakToCalUB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tableWidget_peaksCalUB = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_peaksCalUB.setObjectName(_fromUtf8("tableWidget_peaksCalUB"))
        self.tableWidget_peaksCalUB.setColumnCount(0)
        self.tableWidget_peaksCalUB.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.tableWidget_peaksCalUB)
        self.pushButton_calUB = QtGui.QPushButton(self.tab_2)
        self.pushButton_calUB.setObjectName(_fromUtf8("pushButton_calUB"))
        self.horizontalLayout_7.addWidget(self.pushButton_calUB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.tableWidget_ubMatrix = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_ubMatrix.setObjectName(_fromUtf8("tableWidget_ubMatrix"))
        self.tableWidget_ubMatrix.setColumnCount(0)
        self.tableWidget_ubMatrix.setRowCount(0)
        self.horizontalLayout_13.addWidget(self.tableWidget_ubMatrix)
        self.pushButton_acceptUB = QtGui.QPushButton(self.tab_2)
        self.pushButton_acceptUB.setObjectName(_fromUtf8("pushButton_acceptUB"))
        self.horizontalLayout_13.addWidget(self.pushButton_acceptUB)
        self.pushButton_resetCalUB = QtGui.QPushButton(self.tab_2)
        self.pushButton_resetCalUB.setObjectName(_fromUtf8("pushButton_resetCalUB"))
        self.horizontalLayout_13.addWidget(self.pushButton_resetCalUB)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lineEdit_scanRefineUB = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_scanRefineUB.sizePolicy().hasHeightForWidth())
        self.lineEdit_scanRefineUB.setSizePolicy(sizePolicy)
        self.lineEdit_scanRefineUB.setObjectName(_fromUtf8("lineEdit_scanRefineUB"))
        self.horizontalLayout_14.addWidget(self.lineEdit_scanRefineUB)
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lineEdit_ptRefineUB = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ptRefineUB.sizePolicy().hasHeightForWidth())
        self.lineEdit_ptRefineUB.setSizePolicy(sizePolicy)
        self.lineEdit_ptRefineUB.setObjectName(_fromUtf8("lineEdit_ptRefineUB"))
        self.horizontalLayout_14.addWidget(self.lineEdit_ptRefineUB)
        self.pushButton_addToRefine = QtGui.QPushButton(self.tab_3)
        self.pushButton_addToRefine.setObjectName(_fromUtf8("pushButton_addToRefine"))
        self.horizontalLayout_14.addWidget(self.pushButton_addToRefine)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.pushButton_addAllRefineUB = QtGui.QPushButton(self.tab_3)
        self.pushButton_addAllRefineUB.setObjectName(_fromUtf8("pushButton_addAllRefineUB"))
        self.horizontalLayout_14.addWidget(self.pushButton_addAllRefineUB)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tableView_refinedUB = QtGui.QTableView(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_refinedUB.sizePolicy().hasHeightForWidth())
        self.tableView_refinedUB.setSizePolicy(sizePolicy)
        self.tableView_refinedUB.setObjectName(_fromUtf8("tableView_refinedUB"))
        self.verticalLayout_7.addWidget(self.tableView_refinedUB)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_10.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_10.addWidget(self.pushButton_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 0, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 0, 5, 1, 1)
        self.lineEdit_bUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_bUnitCell.setObjectName(_fromUtf8("lineEdit_bUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_bUnitCell, 1, 1, 1, 1)
        self.lineEdit_cUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_cUnitCell.setObjectName(_fromUtf8("lineEdit_cUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_cUnitCell, 1, 2, 1, 1)
        self.lineEdit_alphaUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_alphaUnitCell.setObjectName(_fromUtf8("lineEdit_alphaUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_alphaUnitCell, 1, 3, 1, 1)
        self.lineEdit_bError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_bError.setObjectName(_fromUtf8("lineEdit_bError"))
        self.gridLayout_7.addWidget(self.lineEdit_bError, 2, 1, 1, 1)
        self.lineEdit_betaUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_betaUnitCell.setObjectName(_fromUtf8("lineEdit_betaUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_betaUnitCell, 1, 4, 1, 1)
        self.lineEdit_aUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_aUnitCell.setObjectName(_fromUtf8("lineEdit_aUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_aUnitCell, 1, 0, 1, 1)
        self.lineEdit_cError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_cError.setObjectName(_fromUtf8("lineEdit_cError"))
        self.gridLayout_7.addWidget(self.lineEdit_cError, 2, 2, 1, 1)
        self.lineEdit_aError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_aError.setObjectName(_fromUtf8("lineEdit_aError"))
        self.gridLayout_7.addWidget(self.lineEdit_aError, 2, 0, 1, 1)
        self.lineEdit_alphaError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_alphaError.setObjectName(_fromUtf8("lineEdit_alphaError"))
        self.gridLayout_7.addWidget(self.lineEdit_alphaError, 2, 3, 1, 1)
        self.lineEdit_betaError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_betaError.setObjectName(_fromUtf8("lineEdit_betaError"))
        self.gridLayout_7.addWidget(self.lineEdit_betaError, 2, 4, 1, 1)
        self.lineEdit_gammaUnitCell = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_gammaUnitCell.setObjectName(_fromUtf8("lineEdit_gammaUnitCell"))
        self.gridLayout_7.addWidget(self.lineEdit_gammaUnitCell, 1, 5, 1, 1)
        self.lineEdit_gammaError = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_gammaError.setObjectName(_fromUtf8("lineEdit_gammaError"))
        self.gridLayout_7.addWidget(self.lineEdit_gammaError, 2, 5, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_advsetup = QtGui.QWidget()
        self.tab_advsetup.setObjectName(_fromUtf8("tab_advsetup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_advsetup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.tab_advsetup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.lineEdit_localSrcDir = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_localSrcDir.setObjectName(_fromUtf8("lineEdit_localSrcDir"))
        self.horizontalLayout_8.addWidget(self.lineEdit_localSrcDir)
        self.pushButton_browseLocalData = QtGui.QPushButton(self.tab_advsetup)
        self.pushButton_browseLocalData.setObjectName(_fromUtf8("pushButton_browseLocalData"))
        self.horizontalLayout_8.addWidget(self.pushButton_browseLocalData)
        self.checkBox_dataLocal = QtGui.QCheckBox(self.tab_advsetup)
        self.checkBox_dataLocal.setText(_fromUtf8(""))
        self.checkBox_dataLocal.setObjectName(_fromUtf8("checkBox_dataLocal"))
        self.horizontalLayout_8.addWidget(self.checkBox_dataLocal)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_advsetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_advsetup, _fromUtf8(""))
        self.horizontalLayout_Tab.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_Tab)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeWidget_scan = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeWidget_scan.setObjectName(_fromUtf8("treeWidget_scan"))
        self.treeWidget_scan.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_2.addWidget(self.treeWidget_scan, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName(_fromUtf8("actionOpen_2"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addAction(self.actionSave)
        self.menuView.addAction(self.actionLog)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_exp.setText(_translate("MainWindow", "Experiment", None))
        self.pushButton_setExp.setText(_translate("MainWindow", "Set", None))
        self.label_dir.setToolTip(_translate("MainWindow", "<html><head/><body><p>Directory for local data storage</p></body></html>", None))
        self.label_dir.setText(_translate("MainWindow", "Location", None))
        self.lineEdit_dirSave.setToolTip(_translate("MainWindow", "<html><head/><body><p>Directory for local data storage</p></body></html>", None))
        self.pushButton_browseSaveDir.setText(_translate("MainWindow", "Browse", None))
        self.label_url.setToolTip(_translate("MainWindow", "<html><head/><body><p>URL of the http server to download HB3A data</p></body></html>", None))
        self.label_url.setText(_translate("MainWindow", "URL", None))
        self.pushButton_testURLs.setText(_translate("MainWindow", "Test", None))
        self.label.setText(_translate("MainWindow", "Scans List", None))
        self.pushButton_downloadAll.setText(_translate("MainWindow", "Download Experiment", None))
        self.label_datamode.setText(_translate("MainWindow", "Mode", None))
        self.comboBox_mode.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mode &quot;download&quot;: download data to local disk;</p><p>Mode &quot;http server only&quot;: download data to cache, process and delete cached data upon returning</p></body></html>", None))
        self.comboBox_mode.setItemText(0, _translate("MainWindow", "Download", None))
        self.comboBox_mode.setItemText(1, _translate("MainWindow", "Http Access Only", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data Access", None))
        self.label_runPtPlot.setText(_translate("MainWindow", "Scan", None))
        self.pushButton_load.setText(_translate("MainWindow", "Load", None))
        self.pushButton_plotScan.setText(_translate("MainWindow", "Plot", None))
        self.pushButton_prevScan.setText(_translate("MainWindow", "Previous", None))
        self.label_5.setText(_translate("MainWindow", "[Current Pt.]", None))
        self.pushButton_nextScan.setText(_translate("MainWindow", "Next", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "View Raw Data", None))
        self.label_scanNo.setText(_translate("MainWindow", "Scan Number", None))
        self.label_PtNo.setText(_translate("MainWindow", "Pt Number", None))
        self.pushButton_findPeak.setText(_translate("MainWindow", "Find Peak", None))
        self.label_7.setText(_translate("MainWindow", "Found Peak Q Sample", None))
        self.label_8.setText(_translate("MainWindow", "Qx", None))
        self.label_9.setText(_translate("MainWindow", "Qy", None))
        self.label_10.setText(_translate("MainWindow", "Qz", None))
        self.label_12.setText(_translate("MainWindow", "H", None))
        self.label_11.setText(_translate("MainWindow", "K", None))
        self.label_6.setText(_translate("MainWindow", "L", None))
        self.pushButton_addPeakToCalUB.setText(_translate("MainWindow", "Add Peak", None))
        self.pushButton_calUB.setText(_translate("MainWindow", "Calculate UB Matrix", None))
        self.pushButton_acceptUB.setText(_translate("MainWindow", "Accept", None))
        self.pushButton_resetCalUB.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calculate UB", None))
        self.label_14.setText(_translate("MainWindow", "Scan", None))
        self.label_13.setText(_translate("MainWindow", "Pt.", None))
        self.pushButton_addToRefine.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add a data point or data points (defined by scan number and pt number) to the list to refine UB matrix; </p><p><br/></p><p>Scan number can be a list of integers;</p><p><br/></p><p>Pt number can be empty such that all Pt. of that scan will be searched for peak and then used to refine UB matrix</p></body></html>", None))
        self.pushButton_addToRefine.setText(_translate("MainWindow", "Add", None))
        self.pushButton_addAllRefineUB.setText(_translate("MainWindow", "Add All", None))
        self.pushButton.setText(_translate("MainWindow", "Accept", None))
        self.pushButton_2.setText(_translate("MainWindow", "Reset", None))
        self.label_17.setText(_translate("MainWindow", "a", None))
        self.label_19.setText(_translate("MainWindow", "c", None))
        self.label_21.setText(_translate("MainWindow", "beta", None))
        self.label_18.setText(_translate("MainWindow", "b", None))
        self.label_20.setText(_translate("MainWindow", "alpha", None))
        self.label_22.setText(_translate("MainWindow", "gamma", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Refine UB", None))
        self.label_4.setText(_translate("MainWindow", "Local Disk", None))
        self.pushButton_browseLocalData.setText(_translate("MainWindow", "Browse", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advsetup), _translate("MainWindow", "Advanced Setup", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "New", None))
        self.actionOpen_2.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLog.setText(_translate("MainWindow", "Log", None))
        self.actionLog.setShortcut(_translate("MainWindow", "Ctrl+L", None))

