export PATH=$PATH:$HOME/bin
# This allows cmake to find POCO libraries
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
# Load modules available on lens
module load git
module load cmake/2.8.6
module load hdf5
module load python/2.7
# OpenMPI with the gnu (gcc) compiler
module load ompi/1.4.3-gnu4.4.4
# Get latest gcc
module load gcc/4.4.4
# Run this after building your own python
export PYTHONPATH=$HOME/lib/python2.7/site-packages/
