#PBS -A CSC035
#PBS -N Mantid_CNCS_mpi_example
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -l nodes=2:ppn=16
# Email when it ends #PBS -m e

# Make sure your .bash_profile file is set and loads modules esp. gcc/4.4.4

cd /ccs/home/8oz/Code/Mantid/Code/Mantid/Framework/MPIAlgorithms/scripts
export MANTIDPATH=$HOME/Code/Mantid/framework/bin 
export PYTHONPATH=$MANTIDPATH 
mpirun ~/bin/python2.7 CNCS_mpi_example.py
