#For test main

import os
import platform
import sys
import re
import shutil
from socket import gethostname

import MantidBuild

Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_MAIN',1)])
libList = myenv['MYLIBLIST']
libDirList = myenv['MYLIBDIRLIST']

if platform.system() == 'Linux':
    # MG: By default, ld populates the symbol table with only those referenced within the linked libraries.
    # Given that we use dlopen we may not necessarily reference all symbols at link time so we need to 
    # ensure that the symbol table is populated with all symbols defined within the linked libraries.
    myenv.Append(LINKFLAGS=['-Wl,--export-dynamic'])


#GET LIST OF CPPS
codeFolder = os.path.abspath('.')
listCpps = MantidBuild.getCPPFiles(codeFolder)

myenv.Append(LIBS=libList)
myenv.Append(LIBPATH=libDirList)
shared = myenv.Program('main',listCpps, PDB='main.pdb')

retval = { 'shared': shared }
Return('retval')
