#ifndef INSTRUMENTWINDOWTYPES_H_
#define INSTRUMENTWINDOWTYPES_H_

class InstrumentWindowTypes {

public:
  enum SurfaceType {
    FULL3D = 0,
    CYLINDRICAL_X,
    CYLINDRICAL_Y,
    CYLINDRICAL_Z,
    SPHERICAL_X,
    SPHERICAL_Y,
    SPHERICAL_Z,
    SIDE_BY_SIDE,
    RENDERMODE_SIZE
  };
};
#endif /*INSTRUMENTWINDOWTYPES_H_*/
