{% set version = load_setup_py_data().get('version', '0.0.0') %}

package:
  name: mantiddocs
  version: {{ version }}

source:
  path: ../../../

build:
  noarch: generic
  number: 0
  ignore_run_exports_from:
      - {{ compiler('cxx') }}
      - python
  script_env:
      - MANTID_DATA_STORE={{ environ.get('MANTID_DATA_STORE', '~/MantidExternalData') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja {{ ninja }}  # [osx or linux]
    - cmake {{ cmake }}
    - git
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - numpy {{ numpy }}                      # [build_platform != target_platform]
  host:
    - python {{ python }}
    - setuptools
    - sphinx {{ sphinx }}
    - sphinx_bootstrap_theme {{ sphinx_bootstrap_theme }}
    - mantidqt {{ version }}
    - versioningit {{ versioningit }}
    - graphviz {{ graphviz }}
    - texlive-core {{ texlive_core }}
    - libgl-devel  # [linux]
    - xorg-libxxf86vm  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
    - pystog {{ pystog }}

# there are no run requirements as it's just pure html

test:
  files:
    - share/doc/html/index.html
    - share/doc/html/mantid.png

about:
  home: https://github.com/mantidproject/mantid
  license: GPL-3.0-or-later
  summary: HTML Documentation for Mantid

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
