# there are no run requirements as it's just pure html
schema_version: 1

context:
  # Version is injected via an environment variable
  version: ${{ env.get('MANTID_VERSION', default='0.0.0') }}

package:
  name: mantiddocs
  version: ${{ version }}

source:
  path: ../../../

build:
  number: 0
  noarch: generic
  script_env:
      - MANTID_DATA_STORE={{ environ.get('MANTID_DATA_STORE', '~/MantidExternalData') }}

requirements:
  build:
    - ${{ compiler("cxx") }}
    - if: osx or linux
      then: ninja ${{ ninja }}
    - cmake ${{ cmake }}
    - git
    - if: build_platform != target_platform
      then:
        - python ${{ python }}
        - cross-python_${{ target_platform }}
        - setuptools
        - numpy ${{ numpy }}
  host:
    - python ${{ python }}
    - setuptools
    - sphinx ${{ sphinx }}
    - sphinx_bootstrap_theme ${{ sphinx_bootstrap_theme }}
    - mantidqt == ${{ version }}
    - versioningit ${{ versioningit }}
    - graphviz ${{ graphviz }}
    - pystog ${{ pystog }}
    - texlive-core ${{ texlive_core }}
  ignore_run_exports:
    from_package:
      - ${{ compiler('cxx') }}
      - python

tests:
  - package_contents:
      files:
        - share/doc/html/index.html
        - share/doc/html/mantid.png

about:
  license: GPL-3.0-or-later
  summary: HTML Documentation for Mantid
  homepage: https://github.com/mantidproject/mantid

extra:
  recipe-maintainers:
    - thomashampson
    - sf1919
    - martyngigg
