#ifndef MANTID_NEXUSGEOMETRY_DLLCONFIG_H_
#define MANTID_NEXUSGEOMETRY_DLLCONFIG_H_

#include "MantidKernel/System.h"

#ifdef IN_MANTID_NEXUSGEOMETRY
#define MANTID_NEXUSGEOMETRY_DLL DLLExport
#else
#define MANTID_NEXUSGEOMETRY_DLL DLLImport
#endif

#endif // MANTID_NEXUSGEOMETRY_DLLCONFIG_H_
