#For MantidICat

import os
import MantidBuild
import platform

#GET LIST OF CPPS files
codeFolder = os.path.abspath('./src')
listCpps = MantidBuild.getCPPFiles(codeFolder, recursive=False) 

#Import environment
Import('env')
myenv = env.Clone()
myenv.Append(CPPDEFINES=[('IN_MANTID_ICAT',1),'WITH_NONAMESPACES','WITH_OPENSSL'])
listSharedObjects = MantidBuild.getSharedObjects(listCpps, myenv)

# Link to the appropriate version of Poco
if int(env['debug']) == 1:
    myenv.Append(MYLIBLIST='PocoNetd')
else:
    myenv.Append(MYLIBLIST='PocoNet')

if platform.system() == "Windows":
    ssl_libs = ['ssleay32','libeay32']
else:
    ssl_libs = ['ssl','crypto']
    
myenv.Append(MYLIBLIST=ssl_libs)

#BUILD CODE
shared = myenv.SharedLibrary('lib/MantidICat', listCpps, LIBS=myenv['MYLIBLIST'], LIBPATH=myenv['MYLIBDIRLIST'], PDB='lib/MantidICat.pdb')
retval = { 'shared': shared, 'sharedobjs' : listSharedObjects, 'libs': ['MantidICat'] }
Return('retval')
