name: 'Remove old nightly pre-releases from GitHub'
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  delete-old-nightly-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: thomashampson/delete-older-releases@main
        with:
          keep_latest: 3
          # Nightly tags are of the form v{major}.{minor}.{date}.{time}
          delete_tag_regex: v\d+\.\d+\.\d{8}\.\d{4}
          prerelease_only: true
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
