name: doxygen documentation build and publish
on:
  push:
    branches: [main]

# cancel previous job if new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    if: ${{ github.repository_owner == 'mantidproject' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: .github/filters.yaml

      - uses: prefix-dev/setup-pixi@v0.9.5
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}
        with:
          frozen: true

      - uses: ./.github/actions/doxygen-build
        name: build doxygen
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}

      # publish documentation if on main branch of mantidproject/mantid
      - name: Checkout Doxygen repository
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}
        uses: actions/checkout@v6
        with:
          repository: mantidproject/doxygen
          path: doxygen_repo
          token: ${{ secrets.DOXYGEN_REPO_TOKEN }}

      - name: Copy Doxygen artifacts
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}
        run: |
          rm -rf doxygen_repo/* # delete old version of the repository
          cp -r $GITHUB_WORKSPACE/build/doxygen/html/* doxygen_repo/

      - name: Commit Doxygen and push
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}
        working-directory: doxygen_repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Doxygen docs from mantidproject/mantid@${{ github.sha }}"
          git push origin main
