on:
  push:
    branches: [main]

# cancel previous job if new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    if: ${{ github.repository_owner == 'mantidproject' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: .github/filters.yaml

      - uses: prefix-dev/setup-pixi@v0.9.4
        if: steps.changes.outputs.doxygen == 'true'
        with:
          frozen: true

      - uses: ./.github/actions/doxygen-build
        name: build doxygen
        if: steps.changes.outputs.doxygen == 'true'

      # publish documentation if on main branch of mantidproject/mantid
      - name: Checkout Doxygen repository
        # TODO
        if: ${{ github.ref_name == 'publish_doxygen' && steps.changes.outputs.doxygen == 'true' }}
        uses: actions/checkout@v6
        with:
          repo: mantidproject/doxygen
          path: doxygen_repo

      - name: Copy Doxygen artifacts
        # TODO
        if: ${{ github.ref_name == 'publish_doxygen' && steps.changes.outputs.doxygen == 'true' }}
        run: |
          rm -rf doxygen_repo/*
          cp -r $GITHUB_WORKSPACE/build/doxygen/html/* doxygen_repo/

      - name: Commit Doxygen and push
        # TODO
        if: ${{ github.ref_name == 'publish_doxygen' && steps.changes.outputs.doxygen == 'true' }}
        working-directory: doxygen_repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Doxygen docs"
          # TODO uncommentgit push origin main
