name: Linux

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      RUNNER_LABEL:
        description: 'Match Runner Label'
        required: false
        type: string


# cancel previous job if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: .github/filters.yaml

      - uses: prefix-dev/setup-pixi@v0.9.5
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}
        with:
          frozen: true

      - uses: ./.github/actions/doxygen-build
        name: Build doxygen
        if: ${{ steps.changes.outputs.doxygen == 'true' || steps.changes.outputs.cpp == 'true' }}

  build-and-test:
    needs: [doxygen]
    runs-on:
      - ${{ (inputs.RUNNER_LABEL == '' && 'self-hosted') || inputs.RUNNER_LABEL }}
      - self-hosted
      - Linux
      - X64
    #
    # If the user who clicked "Run Workflow" button left the RUNNER_LABEL field blank,
    # the default evaluated output is the string 'self-hosted'.
    # Otherwise set it to the value the user specified when they clicked "Run Workflow"
    #

    env:
      CMAKE_PRESET: linux-64-ci
      EXTRA_CMAKE_FLAGS: "-DENABLE_PRECOMMIT=OFF"
      ENABLE_BUILD_CODE: true
      ENABLE_UNIT_TESTS: true
      ENABLE_SYSTEM_TESTS: true # default is false
      ENABLE_DOCS: false
      ENABLE_DOC_TESTS: false
      ENABLE_DEV_DOCS: false
      ENABLE_COVERITY: false

    steps:
      - name: Print shell environment vars (debug)
        if: github.event_name == 'workflow_dispatch'
        run: |
          env -0 | while IFS='' read -d '' line ; do printf '%s\t: %s\n' "${line%%=*}" "${line#*=}" | expand -t 30 | sed ':a;N;$!ba;s/\n/ /g'; done | LC_COLLATE=C sort -b
      #
      # If this workflow was triggered manually,
      # print a sorted list of all shell environment variables
      #

      - uses: actions/checkout@v6
        with:
          # Needed to fetch the tags for versioningit
          fetch-depth: 100
          fetch-tags: true

      - name: Install pixi
        run: |
          source ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/pixi-utils
          install_pixi
          # Add pixi to path for use in other steps
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Clean build tree
        # supplying --clean-build or CLEAN_BUILD=true should be added here
        run: ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/clean-builder ${GITHUB_WORKSPACE}

      - name: Build code
        run: |
          cd ${GITHUB_WORKSPACE}
          echo "::add-matcher::.github/matchers/gcc.json"
          pixi run --frozen bash -ex ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/build ${GITHUB_WORKSPACE} $CMAKE_PRESET $ENABLE_DOCS $ENABLE_DEV_DOCS $ENABLE_BUILD_CODE $ENABLE_UNIT_TESTS $ENABLE_SYSTEM_TESTS $ENABLE_DOC_TESTS $ENABLE_COVERITY $EXTRA_CMAKE_FLAGS
          echo "::remove-matcher owner=gcc-problem-matcher::"

      - name: Run unit tests
        id: testunit
        run: |
          cd ${GITHUB_WORKSPACE}
          # Not physical but logical cores, includes hyper threaded - different for darwin
          BUILD_THREADS="$(grep -c ^processor /proc/cpuinfo)"
          # bool flags for this are
          # SYSTEM_TESTS UNIT_TESTS DOCS DOC_TESTS
          pixi run --frozen bash -ex ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/run-tests ${GITHUB_WORKSPACE} false true $ENABLE_DOCS $ENABLE_DOC_TESTS ${BUILD_THREADS}

      - name: Unit test report
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: ${{ failure() && steps.testunit.conclusion == 'failure' }}
        with:
          check_name: "Unit test results"
          check_run: false
          files: build/Testing/*unittest.xml

      - name: Run system tests
        id: testsystem
        run: |
          cd ${GITHUB_WORKSPACE}
          # Not physical but logical cores, includes hyper threaded - different for darwin
          BUILD_THREADS="$(grep -c ^processor /proc/cpuinfo)"
          # bool flags for this are
          # SYSTEM_TESTS UNIT_TESTS DOCS DOC_TESTS
          pixi run --frozen bash -ex ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/run-tests ${GITHUB_WORKSPACE} true false $ENABLE_DOCS $ENABLE_DOC_TESTS ${BUILD_THREADS}

      - name: Upload system test mismatch files
        uses: actions/upload-artifact@v7
        if: ${{ failure() && steps.testsystem.conclusion == 'failure' }}
        with:
          name: system_test_mismatches
          if-no-files-found: ignore
          path: ${{ github.workspace }}/build/**/*-mismatch.nxs

      - name: System test report
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: ${{ failure() && steps.testsystem.conclusion == 'failure' }}
        with:
          check_name: "System test results"
          check_run: false
          files: build/Testing/SystemTests/**/TEST-systemtests*.xml

      - name: Upload build and test log artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test_logs
          path: ${{ github.workspace }}/build/test_logs/*.log
