name: PR Cpp Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      RUNNER_LABEL:
        description: 'Match Runner Label'
        required: false
        type: string


# cancel previous job if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cppcheck:
    runs-on:
      - ${{ (inputs.RUNNER_LABEL == '' && 'self-hosted') || inputs.RUNNER_LABEL }}
      - self-hosted
      - Linux
      - X64

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: .github/filters.yaml

      - name: Install pixi
        uses: ./.github/actions/setup-pixi
        if: ${{ steps.changes.outputs.files_cppcheck == 'true' }}

      - name: Clean build tree
        if: ${{ steps.changes.outputs.files_cppcheck == 'true' }}
        run: ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/clean-builder ${GITHUB_WORKSPACE}

      - name: Add cppcheck matcher
        if: ${{ steps.changes.outputs.files_cppcheck == 'true' }}
        run: echo "::add-matcher::.github/matchers/cppcheck.json"

      - uses: ./.github/actions/cppcheck-build
        if: ${{ steps.changes.outputs.files_cppcheck == 'true' }}
        name: Run cppcheck

      - name: Remove cppcheck matcher
        if: ${{ always() && steps.changes.outputs.files_cppcheck == 'true' }}
        run: echo "::remove-matcher owner=cppcheck::"

      - name: Upload cppcheck SARIF report
        uses: actions/upload-artifact@v7
        if: ${{ always() && steps.changes.outputs.files_cppcheck == 'true' && hashFiles('build/cppcheck.sarif') != '' }}
        with:
          name: cppcheck_sarif_report
          if-no-files-found: warn
          path: ${{ github.workspace }}/build/cppcheck.sarif
