name: 'Stale old issues and prs'
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 365
          days-before-pr-stale: 90
          # number of days after it's set to stale
          days-before-close: 7
          exempt-issue-labels: 'Induction,Roadmap'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity in a year. It will be closed in 7 days if no further activity occurs.

            Allowing issues to close as stale helps us filter out issues which can wait
            for future development time. All issues closed by stale bot act like normal issues; they can be searched for, commented on or reopened at any point.

            If you'd like a closed stale issue to be considered,
            feel free to either re-open the issue directly or contact a developer.

            To extend the lifetime of an issue please comment below,
            it helps us see that this is still affecting you and you want
            it fixed in the near-future. Extending the lifetime of an issue
            may cause the development team to prioritise it over other issues,
            which may be closed as stale instead.
          close-issue-message: >
            This issue has been closed automatically. If this still affects you please
            re-open this issue with a comment or contact us so we can look into resolving it.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            activity in 3 months. It will be closed in 7 days if no further activity occurs.

            Allowing pull requests to close as stale helps us filter out old work that is no longer
            relevant and helps developers focus on reviewing current work.

            All pull requests closed by this bot act like normal pull requests;
            they can be searched for, commented on or reopened at any point.

            If these changes are still relevant then please comment and tag \@mantidproject/gatekeepers to highlight
            that it needs to have a reviewer assigned.
          close-pr-message: >
            This pull request has been closed automatically. If these changes are still relevant
            then please re-open this pull request with a comment and tag \@mantidproject/gatekeepers
            to highlight it needs to have a reviewer assigned.
