#ifndef MANTID_ICATTEST_PRECOMPILED_HEADER_H_
#define MANTID_ICATTEST_PRECOMPILED_HEADER_H_

#include <cxxTest/TestSuite.h>
#undef _CXXTEST_LONGLONG // Kill a warning

#endif //MANTID_ICATTEST_PRECOMPILED_HEADER_H_