#ifndef MANTIDPLOT_RELEASE_DATE
#define MANTIDPLOT_RELEASE_DATE "03 Jul 2009 (Version 1.0, SVN R2688M)"
#endif

#ifndef MANTIDPLOT_RELEASE_VERSION
#define MANTIDPLOT_RELEASE_VERSION "1.0.2688M"
#endif
