#ifndef MANTIDQT_MANTID_IMAGE_VIEWER_DLLOPTION_H_
#define MANTIDQT_MANTID_IMAGE_VIEWER_DLLOPTION_H_

#include <MantidKernel/System.h>

#ifdef IN_MANTIDQT_IMAGEVIEWER
#define EXPORT_OPT_MANTIDQT_IMAGEVIEWER DLLExport
#else
#define EXPORT_OPT_MANTIDQT_IMAGEVIEWER DLLImport
#endif

#endif //MANTIDQT_MANTID_IMAGE_VIEWER_DLLOPTION_H_
